### ISSUE TITLE
Warrior Flurry issues.

### ISSUE THREAD

**Issue by Aruze** [LightsHope/server#10]
Ive noticed that Warrior Cleave and Heroic strike are not removing a Flurry stack.
Also some whirlwind and cleave Crits are not proccing flurry every time they crit, They do procc off the main target when they do, but not off extra targets.
(Edit: ive noticed crits also dont procc flurry when using Retaliation)

This may also be an issue with sweeping strikes but i haven't tried that out as its not oftein warriors use sweeping with flurry unless they go 21/30/0 please if you could fix this asap as to not imbalance the class or make it less viable or abused in raids.

(please contact Monstermashx ingame on Elysium)

**Comment by semprevivo** [comment]
I thought Flurry was consumed only by auto-attacks.

**Comment by GuybrushGit** [comment]
The Flurry proc flag from the client files is set to only proc on white melee attacks. Do you have any source that contradicts this?

**Comment by Aruze** [comment]
Im a 2h Flurry warrior  20/31/0 Talents.

To sum it up: When flurry proccs u get 3 stacks of flurry, ""Theese 
stacks do not go away when you do Cleave or Heroic strike"", However 
they go away on white hits.  They should however tick 1 away for every 
swing made be it Cleave, Heroic strike or White hit (Shouldnt they?), 
weather it is a crit or not, it should remove 1 stack each time. This is 
a red flag and it can be abused very effectively.

How? if you do 1 white crit, and you get a Flurry (15 second 
attackspeed) buff, you can carefully choose not to spend your ticks by 
using Cleave or heroic strike, a Cleave vs 2 opponents would keep your 
rage up also, and would be used to procc an extra flurry, keeping the 
warrior basically in flurry mode the entire time by choice alone.

You might Charge > Autoattack > Bloodthirst > Berserker Stance > Auto 
Attack > Whirlwind > (if a Flurry proccs anywhere in this sequence) 
"Then" Berserker Stance > Autoattack... > Autoattack... (2 Ticks /3) > 
Cleave > Cleave > Cleave > Cleave > Whirlwind/Execute.  all While still 
having that last 1 stack of flurry up, helping your cleaves get faster 
attacks/hits even if you dont do a single crit, but you always do a few, 
However they dont give you fresh flurry stacks unless you hit a crit on 
a primary, be it Cleave, heroic strike, white hit or a whirlwind.

Ive noticed as im trying to get a Flurry to procc, im pulling in say 3-4 
mobs and im doing a Whirlwind, it will crit 1 maybe 2 times, but because 
it did not crit on my Primary target i get no Flurry. this is also true 
about Cleave, my secondary crits do not procc flurry.

im just a player who plays on Elysium/Anathema, i just felt like this 
could be abused and also that it wasnt proccing as oftein than it 
should, but i could be wrong on the latter, perhaps its only supposed to 
procc off white hits.

in my opinion, this should be looked at and studied ingame more closely 
by admins if possible.

The fact that flurry stacks are giving players this opportunity to abuse 
its system may be an indication that blizzard changed this to what im 
suggesting, that it would remove a stack on cleaves and heroic strikes, 
and procc off every single critical strike made be it off a whirlwind or 
a cleave.

I dont know, maybe im wrong, but it just feels like its different from 
the Elysium project, maybe its something that needs fixing?

**Comment by GuybrushGit** [comment]
This shouldn't be that hard to prove, there are plenty of warrior pvp videos from vanilla out there.

**Comment by Aruze** [comment]
It might be hard to find a warrior pvp video who's doing 2h Fury tho, although a video springs to mind, a nightelf grandmarshal who specced fury, dont recall his name.

**Comment by Aruze** [comment]
i found this video of a Nightelf using a 2h fury in Rank 14 gear, at  the mark  45-56 second mark it shows Heroic strike being used removing a Stack of flurry , on top of his Heroic strike he uses Bloodthirst which gives him a fresh flurry procc.

https://www.youtube.com/watch?v=Msp5nnrp0Gk

**Comment by GuybrushGit** [comment]
It appears that next-swing type attacks should PROC_FLAG_SUCCESSFUL_MELEE_HIT instead of PROC_FLAG_SUCCESSFUL_MELEE_SPELL_HIT like they currently do.
