### ISSUE TITLE
The Reins of the Winterspring Frostsaber sold by Rivern Frostwind in Winterspring suddenly cost 10 times what it should on Darrowshire (can't say about the other servers) but now it cost 1000g instead of the correct 100g or 900g instead of 90g with rep discount.

### ISSUE THREAD

**Issue by Ako999** [LightsHope/server#100]
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

- Search the issue tracker for open and closed issues before opening a new
  issue. You may be able to contribute additional facts by commenting on
  existing issues instead of adding extra noise in a separate issue.

- http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
  for quests, items etc., instead, please use archived versions of
  http://wow.allakhazam.com or http://www.thottbot.com through
  https://archive.org/.

- Validate the date and time of the archived sources to a certain patch. The
  patch release dates can be found on the corresponding WoWWiki article, as
  found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.

- Videos are valid if and only if the footage contains a timestamp or
  information that confirms the time it was recorded. Date of upload is NOT
  valid and does not confirm when it was shot.

- Read the Effective Bug Reporting article at
  https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md
  which covers these points and more.

Once you've read this message, delete it and write your report below.

--

Write your report here

**Comment by Ako999** [comment]
The Reins of the Winterspring Frostsaber sold by Rivern Frostwind in Winterspring suddenly cost 10 times what it should on Darrowshire (can't say about the other servers) but now it cost 1000g instead of the correct 100g or 900g instead of 90g with rep discount.

**Comment by GuybrushGit** [comment]
This is intentional. Reduced cost came in TBC.

**Comment by kcharles67** [comment]
In Vanilla it was 100gp (minus any rep discounts).  This was also the case on Nostalrius, Kronos and also on Darrowshire before the recent split.

**Comment by brotalnia** [comment]
Guybrush is correct, price was changed in TBC.

Snapshot of the item from August 2006.
https://web.archive.org/web/20060922071357/http://wow.allakhazam.com:80/db/item.html?witem=13086

The item history on Allakhazam.
https://web.archive.org/web/20071106011108/http://wow.allakhazam.com:80/db/itemhistory.html?witem=13086

> 2007-05-22 13:08:24 | sellprice changed from '10000000' to '1000000'

**Comment by kcharles67** [comment]
Well I see what you are saying however keeping at the lower price would also be true to Vanilla since

2006-11-30 11:48:34 | sellprice changed from '10000000' to '1000000'

Which was a month and a half before TBC release date.  That might also explain why it was a lower price on Darrowshire before the split and it was that price on Nost as well.

**Comment by brotalnia** [comment]
Patch 1.12.1 was released on 26 September 2006, so the change on 2006-11-30 must have been the TBC pre-patch. It does not matter what it was on Nost, that is a private server, it is not proof of what it was on retail vanilla.
