### ISSUE TITLE
Incorrect Dragonstalker Armor Graphic

### ISSUE THREAD

**Issue by thetower1** [LightsHope/server#1001]
![image](https://user-images.githubusercontent.com/34558321/34021036-80d4b0fc-e105-11e7-8996-72a778dfdfdf.png)

**Comment by Sabre142** [comment]
Working as update intended (will be reverted in 1.9)

**Comment by thetower1** [comment]
?

**Comment by Sabre142** [comment]
http://i.imgur.com/yVSTr.jpg

**Comment by QAkvastskaft** [comment]
The new graphics will arrive with 1.9
Delete your WDB folder to see current graphics and stats
