### ISSUE TITLE
Darrowshire: Shadowcraft Armor set have wrong set bonus.

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [LightsHope/server#1003]
[Shadowcraft Armor](http://db.vanillagaming.org/?itemset=184)
Stats and set bonus in patch 1.0-1.2
![1 0-1 2](https://user-images.githubusercontent.com/30354821/34027959-b3a73274-e192-11e7-89a6-b0b1376151dc.jpg)
Stats and set bonus in patch 1.3-1.9
![1 3-1 9](https://user-images.githubusercontent.com/30354821/34027971-c8f8a784-e192-11e7-9773-9209289f2894.jpg)
Stats and set bonus in patch 1.10-1.12
![1 10-1 12](https://user-images.githubusercontent.com/30354821/34027981-dc4478d6-e192-11e7-987d-549c50d4f7a5.jpg)
As we can see - in current patch on Darrowshire realm we have wrong set bonus. Anathema have right set bonus. Lightbringer also have wrong set bonus.

**Comment by Sabre142** [comment]
Set bonuses have been completely disregarded across the board. They would need to change every tier sets effects.

**Comment by Slicy** [comment]
Those spells or equivalent with the exact same end result do exist considering most of them are very very common spell effects.

3 pieces, +2 daggers : http://db.vanillagaming.org/?spell=7573
5 pieces,+1% dodge : http://db.vanillagaming.org/?spell=13669
6 pieces, +1% crit : http://db.vanillagaming.org/?spell=7597
7 pieces, +2% hit : http://db.vanillagaming.org/?spell=15465
8 pieces, +4% OH dmg : closest I could find is +5% which isn't too far off http://db.vanillagaming.org/?spell=23584
Didn't check on other db but perhaps a better/similar effect could be found for the 8 pieces set bonus.

**Comment by QAkvastskaft** [comment]
Anyone wanna make a complete list for all classes and all old spells (Same as Slicy comment)?

Would be most helpful

Thanks

**Comment by Bloodmoon-Darrowshire** [comment]
Battlegear of Valor ([patches 1.0-1.9](http://web.archive.org/web/20060215220220/http://wow.allakhazam.com:80/db/itemset.html?setid=189) [patches 1.10-1.12](http://web.archive.org/web/20060415054155/http://wow.allakhazam.com:80/db/itemset.html?setid=189 )) - WARRIOR
Old set bonus spell:
3 pieces: +50 Armor: http://db.vanillagaming.org/?spell=9764
5 pieces: +20 Attack Power: http://db.vanillagaming.org/?spell=9331
6 pieces: When struck in combat inflicts 2 Arcane damage to the attacker: http://db.vanillagaming.org/?spell=20887
7 pieces: Restores 5 health every 5 sec.: http://db.vanillagaming.org/?spell=20969
8 pieces: 1% chance to stun a victim struck in combat for 1 seconds.: http://db.vanillagaming.org/?spell=20884

Beaststalker Armor ([patches 1.0-1.9](http://web.archive.org/web/20060215183301/http://wow.allakhazam.com:80/db/itemset.html?setid=186) [patches 1.10-1.12](http://web.archive.org/web/20060415054113/http://wow.allakhazam.com:80/db/itemset.html?setid=186)) - HUNTER
Old set bonus spell:
3 pieces: Attack Power increased by 15 when fighting Beasts: http://db.vanillagaming.org/?spell=20877
5 pieces: Increased Bows +4: http://db.vanillagaming.org/?spell=7569
5 pieces: Increased Guns +4: http://db.vanillagaming.org/?spell=7581
5 pieces: Increased Crossbow +4: http://db.vanillagaming.org/?spell=22188
6 pieces: Improves your chance to get a critical strike by 1%: http://db.vanillagaming.org/?spell=7597
7 pieces: +20 Attack Power: http://db.vanillagaming.org/?spell=20987
8 pieces: +60 ranged Attack Power: http://db.vanillagaming.org/?spell=21013

Dreadmist Raiment ([patches 1.0-1.9](http://web.archive.org/web/20060302204240/http://wow.allakhazam.com/db/itemset.html?setid=183) [patches 1.10-1.12](http://web.archive.org/web/20060415054058/http://wow.allakhazam.com:80/db/itemset.html?setid=183)) -WARLOCK
Old set bonus spell:
3 pieces: +4 Fire Resistance: http://db.vanillagaming.org/?spell=14584
3 pieces: +4 Shadow Resistance: http://db.vanillagaming.org/?spell=14667
5 pieces: Increases damage done to Demons by magical spells and effects by up to 14: http://db.vanillagaming.org/?spell=21011
6 pieces: Increases damage done by Shadow spells and effects by up to 21: http://db.vanillagaming.org/?spell=9328
7 pieces: Restores 5 health every 5 sec.: http://db.vanillagaming.org/?spell=20969
8 pieces: Improves your chance to get a critical strike with Shadow spells by 2%: http://db.vanillagaming.org/?spell=23443

Lightforge Armor ([patches 1.0-1.9](http://web.archive.org/web/20060216131923/http://wow.allakhazam.com:80/db/itemset.html?setid=188) [patches 1.10-1.12](http://web.archive.org/web/20060415054134/http://wow.allakhazam.com:80/db/itemset.html?setid=188)) - PALADIN
Old set bonus spell:
3 pieces: Increases healing done by spells and effects by up to 11: http://db.vanillagaming.org/?spell=7679
5 pieces: +30 Attack Power when fighting Undead: http://db.vanillagaming.org/?spell=18074
5 pieces: +30 Attack Power when fighting Demons: http://db.vanillagaming.org/?spell=20858
6 pieces: +6 All Resistances: http://db.vanillagaming.org/?spell=18677
7 pieces: +10% chance to resist Fear spells and effects: http://db.vanillagaming.org/?spell=20710
8 pieces: When the victim of a critical hit in combat, 1% chance to be sheathed in a magical shield absorbing the next 500 damage: http://db.vanillagaming.org/?spell=20705

Magister's Regalia ([patches 1.0-1.9](http://web.archive.org/web/20060207191533/http://wow.allakhazam.com:80/db/itemset.html?setid=181) [patches 1.10-1.12](http://web.archive.org/web/20060415054029/http://wow.allakhazam.com:80/db/itemset.html?setid=181)) - MAGE
Old set bonus spell:
3 pieces: Increases damage done by Frost spells and effects by up to 7: http://db.vanillagaming.org/?spell=7701
5 pieces: +5 Arcane Resistance: http://db.vanillagaming.org/?spell=14707
5 pieces: +5 Fire Resistance: http://db.vanillagaming.org/?spell=14585
5 pieces: +5 Frost Resistance: http://db.vanillagaming.org/?spell=14546
6 pieces: Increases damage done by Arcane spells and effects by up to 21: http://db.vanillagaming.org/?spell=13605
7 pieces: Increases damage done by Fire spells and effects by up to 27: http://db.vanillagaming.org/?spell=17868
8 pieces: +10 Intellect: http://db.vanillagaming.org/?spell=9106
8 pieces: Restores 8 mana per 5 sec.: http://db.vanillagaming.org/?spell=18378

**Comment by brotalnia** [comment]
The set bonuses are in the client to my knowledge, its not possible to have the old ones without doing full client progression, same case as with spell changes. And we don't actually need to do any research on what the bonuses were if we wanted to implement them, just load the appropriate dbcs for this patch. Look at ItemSet.dbc. But since i don't think anyone here can tell us what all the changed packet structure was in every patch, client progression won't happen.

**Comment by thepparker** [comment]
As Brotalnia said, it's not really feasible to modify these or other set bonuses without a significant amount of work. Perhaps in the future someone may set the task for themselves.
