### ISSUE TITLE
Metzen the Reindeer (H)

### ISSUE THREAD

**Issue by Sabre142** [LightsHope/server#1008]
Can't seem to hand it in after completing the objectives.

http://db.vanillagaming.org/?quest=8746

**Comment by SoulSharer** [comment]
Same, but on Alli side

**Comment by bigfgeg** [comment]
Same, I did the standard protocol of abandoning and retaking quest and it didn't work then either (cause it resets the objective)

**Comment by ifyousayso** [comment]
Alliance: Doesn't work by freeing him in Tanaris either.

**Comment by staplerx300** [comment]
same

**Comment by staplerx300** [comment]
it still doesnt work

https://vgy.me/ZHyZNC.jpg

PLEASE FIX

JUST FINISHED THE QUEST FOR THE 3RD TIME

**Comment by Sabre142** [comment]
Worked for me horde side.
