### ISSUE TITLE
Druid - Dungeon Set 1 (Tier 0) Wildheart 6/8 and Dungeon Set 2 (Tier 0,5) Feralheart 4/8 not working

### ISSUE THREAD

**Issue by AliUDmov** [LightsHope/server#101]
Wildheart Raiment (itemset=185) and Feralheart Raiment (itemset=513) have a setbonus that reads "When struck in combat has a chance of returning 300 mana, 10 rage, or 40 energy to the wearer".

The proc (2% chance) can be identified by a visual effect that looks like the decurse spell animation. That is working correctly at Anathema.

The issue is, that the actual effect ("returning 300 mana, 10 rage, or 40 energy to the wearer") does not work. Therefore you see the animation but you don't receive mana in caster form, rage in bear form or energy in cat form.

The corresponding set bonus is called "Nature's Bounty" (spell=27781) and has an effect with the same name (spell=27798).

Thank you for your efforts!

**Comment by GuybrushGit** [comment]
Mana and energy regen work, rage doesn't.

**Comment by AliUDmov** [comment]
Thanks for your clarification! I tested it again and yeah, energy and mana do indeed work. I was confused because it is not shown in combat log nor as "energy gain" at your character, so that's another minor issue.

**Comment by AliUDmov** [comment]
Thank you for fixing the setbonus and for even fixing the combat log connection. You are the best! <3
