### ISSUE TITLE
[Lightbringer] Hardpacked Snowdrifts don't spawn, making Hardpacked Snowballs unobtainable

### ISSUE THREAD

**Issue by bigfgeg** [LightsHope/server#1014]
http://wowwiki.wikia.com/wiki/Hardpacked_Snowdrift

These are supposed to spawn in AV during winter veil. The Hardpacked Snowballs are supposed to knockback all players (only enemy players at some point, although I dont know which patch it was)

What's winterveil without snowballs?

**Comment by GuybrushGit** [comment]
These were introduced in the 2006 Winter's Veil during patch 2.0, but the spells exist already in the client.
