### ISSUE TITLE
Graphical Issues since New Patch

### ISSUE THREAD

**Issue by turetafr** [LightsHope/server#1015]
Ever since the new patch, I have been having graphical issues which are hard to explain but I will try:

I am a druid

Whenever I cast hurricane, the cloud does not disappear after I am done channeling. It stays there permanently until I re-log. If in an instance, reclogging does not remove the animation. Only leaving the instance does.  Eventually there are so many clouds it impedes gameplay, especially in battlegrounds. Same thing if I cast Tranq. Eventually there's tranq animations left all over the map wherever I cast it. 

I see leftover graphics from other classes abilities too, like hunter freezing trap. The ice part of the trap never disappears from my screen. Eventually they are all over my map and it impedes gameplay.

I am not sure what class ability leaves a green cloud, but eventually there are green clouds all over the map too.

I tried the following:

Exited game, deleted WDB, restarted game. No change.

Download Vanilla client from LightsHope forum, install without making any changes, log in, no difference. (no add-ons or any data transferred from other client folder). The problem still persists.

Seems that if the problem persists after doing the last step above, it must be a developer issue. There is nothing I can do. Please help!

**Comment by GuybrushGit** [comment]
Some other people reported this but could never reproduce, its probably an issue with your graphics card or drivers.

**Comment by QAkvastskaft** [comment]
Here is the other issue #50 which was similar. The fix was using older ATI drivers

**Comment by turetafr** [comment]
I was able to reproduce it as many times as you needed. I'm running on an I7-6700K with 32 GB ram M.2 SSD and GTX 1070 with the latest drivers. However, updating driver solved the problem. Mind blown. The problem was exactly as described in your referred ticket.
