### ISSUE TITLE
Undead Warlock/Devouring of Soul Quest

### ISSUE THREAD

**Issue by warlocktrouble** [LightsHope/server#1017]
I have put in a gm request and the suggestion that i was told to delete wtb and wtf folder did not work. The gm has asked that I come here to put in a request.   I am unable to do the level 20 quest for my undead warlock to get the succumbus...The quest quiver just has a grey exclamation and i just cant interact with the npc that gives the quest. i see there is a quest there but it is grey out. Please help.

thanks.

**Comment by brotalnia** [comment]
You must be too low level.

**Comment by GuybrushGit** [comment]
There are 2 seperate quest chains for Succubus. If you take one it will close off the other, check the NPCs in these chains: http://db.vanillagaming.org/?quest=1507 http://db.vanillagaming.org/?quest=1472
