### ISSUE TITLE
Rank 4 Battle Shout is giving more AP than intended.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1019]
http://vanillawowdb.com/?spell=11549
Possibly other lower ranks also do this.
It says it gives 85 AP in the spell book, but when you actually buff it, it says it gives 91, and when you remove it, you lose 91 AP. It gives more AP than intended.
No talents to improve Battle Shout.

**Comment by Phoosy** [comment]
What level are you compared to the level you learn the spell? Does the additional amount equal to the number of levels above the spell level you cast?

**Comment by Cabro** [comment]
My warrior was level 40~ish, i don't know where you are aiming at :-s

**Comment by Cabro** [comment]
At level 40 it's now giving 93 AP. This does indeed seem to vary with your level oO

**Comment by thepparker** [comment]
Battle Shout, like many other effects, scales a small amount with your level until a certain maximum (usually the level before you earn the next rank).
