### ISSUE TITLE
Subterranean Dimetrodon - Missing Ability

### ISSUE THREAD

**Issue by Groshar** [LightsHope/server#1028]
This bug was found on the Lightbringer server.

I couldn't find an entry for the Maraudon enemy known as Subterranean Dimetrodon on thottbot or allakhazam using the Wayback Machine, but there are a number of entries on various classic WoW databases, albeit some that were listed as "not being reliable."  This enemy, however, is simply missing an ability, its ONLY ability called Sonic Burst.  These enemies otherwise do nothing else.  If you've ran Maraudon enough back in the day, you would remember their Sonic Burst, which deals damage and has an AoE silence as well.

http://db.vanillagaming.org/?npc=13323#abilities

http://www.wowhead.com/npc=13323/subterranean-diemetradon#abilities (data mostly relevant to retail, but you can notice the enemy has Sonic Burst as well, as some dungeons use recycled mechanics of their old school counterparts)
**-written December 14th, 2006** "Subterranean Diemetradon often does an area of effect silence attack so keep your casters and healers at a distance when fighting these."

**Comment by sipertruk** [comment]
This is confirmed by the last revision from 2006 of this guide:
wow-pro.com/node/594/revisions/925/view
This guide also states that Theradrim Guardian (rock elemental) should split in 4 smaller rocks at death.
