### ISSUE TITLE
Captain Hecklebury Smotts offers horde quest for alliance as followup to a quest.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#103]
http://db.vanillagaming.org/?npc=2500#starts

I just remembered this bug after #102, and the NPC tried to give me horde quest as follow up to either http://db.vanillagaming.org/?quest=8552 or http://db.vanillagaming.org/?quest=614 , i'm not entirely sure which one it was.

**Comment by ejt1** [comment]
8552 is for both factions and 614 is for alliance only. Seems to be working as intended, no?

**Comment by GuybrushGit** [comment]
Neither of these quests have a defined followup quest.

**Comment by Cabro** [comment]
I found the error. It wasn't this NPC, but the one next to him.
