### ISSUE TITLE
[Lightbringer] Miss rate on level 60 and below seems to have changed

### ISSUE THREAD

**Issue by bigfgeg** [LightsHope/server#1031]
I am consistently missing level 59 and level 60 mobs (Twilight cultists in silithus) with 5% hit, which used to give me zero misses on 60 and below. All my hit comes from gear (warrior) so broken talent not a possibility. Not dualwielding, obviously.  

Possibly a bug? Or a change to the hit formula? I see no changes announced so I assume the former. 

Since I only have one melee class at 60 on lightbringer I can only do limited testing. 6% hit seems to be capped although I didn't do extensive testing yet.

**Comment by Dalleren** [comment]
Weaponskill?

**Comment by phillipnavarro** [comment]
I got a glancing blow on a 60 at 305 weaponskill so something has changed.

**Comment by Kittnz** [comment]
https://github.com/LightsHope/server/commit/3b382aba87c234a17134a465702c3bfdc8726618

**Comment by thepparker** [comment]
Due to a previous change, the cap at equal weapon/defense skill is currently 5.6% rather than the intended 5%. See #844
