### ISSUE TITLE
Quillshooter is missing the chance on hit.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1040]
http://wowwiki.wikia.com/wiki/Quillshooter
http://vanillawowdb.com/?item=10567

**Comment by QAkvastskaft** [comment]
![image](https://user-images.githubusercontent.com/26366996/34168027-aeeab4a0-e4e3-11e7-834c-43ddc872a4d9.png)

**Comment by druidish** [comment]
http://web.archive.org/web/20060909225053/http://www.thottbot.com:80/?i=16392

**Comment by Cabro** [comment]
Cool.
