### ISSUE TITLE
Local:BWL kills all boss.. But the next time I enter, boos refreshes again.

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#1043]
BWL kills all boss.. But the next time I enter (CD time unreset), boos refreshes again.
Test account: GM level 6
I don't know if the other copies are the same.

![wtf](https://user-images.githubusercontent.com/21149808/34217187-ce000ae0-e5e5-11e7-8427-5d6986d7cd08.png)

**Comment by stesve** [comment]
You forgot to clear the eggs before killing the boss :) Thats the requirement for a registered razorgore kill.

Don't expect every script to take weird gm interactions into account.
