### ISSUE TITLE
Quest: The Zhevra - hooves not dropping

### ISSUE THREAD

**Issue by fier11** [LightsHope/server#1046]
For the Horde quest "The Zhevra" the hooves are not dropping. I've killed nearly 15 and not gotten a single one. My addon (ShaguDB) says that it should be an 80% drop rate. I've tried abandoning and picking up the quest again a few times and nothing seems to work.

**Comment by Cabro** [comment]
This quest was supper annoying on retail, i can wholeheartedly say the drop chance WASN'T 80% on retail. Once it took me about 3-4 hours to complete this quest alone.

**Comment by fier11** [comment]
I've done this quest dozens of times even in  retail vanilla, retail TBC, retail wrath, and even other private servers and even this very server, I've done it multiple times. and I almost always get all 4 hooves in 5-8 kills.

**Comment by DarkmoonRabbit** [comment]
In the language of China: "人品问题". {Bad luck...}
^o^

**Comment by thepparker** [comment]
It is currently rather high and is actually wrong according to https://web.archive.org/web/20050220094957/http://wow.allakhazam.com:80/db/item.html?witem=5086 ;) It seems like you got pretty unlucky.
