### ISSUE TITLE
Exorcism (holy damage) partially resisted?

### ISSUE THREAD

**Issue by ifyousayso** [LightsHope/server#1059]
"Your Exorcism hits Undead Ravager for 86 Holy damage. (86 resisted)"

http://vanilla-wow.wikia.com/wiki/Resistance : "There is no resistance stat for Holy, and as such no players nor NPCs can resist Holy spells."
http://wowwiki.wikia.com/wiki/Resistance: "There was no resistance stat for Holy, and as such no players nor NPCs could resist Holy spells."

The way I understand it, in vanilla, Holy spells can only "miss" (unless the target is immune/evades): There shouldn't be any partial resists.

Oh, Judgement of Command holy damage is also partially resisted.

Seal of Command (holy damage) is also partially resisted. It should be able to miss/parried/dodged (like a physical attack), but once it hits, do full damage.
http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)?oldid=327126 : "Unlike other spells, Seal of Command and Judgement of Command are considered physical hits, that does Holy damage. They both use melee crit and hit stats instead of spell crit or hit, and when they crit the damage will be multiplied by two. However like other physical attacks, Seal of Command can miss, or be dodged, parried, or blocked. Judgement of Command can only be resisted."

Update: The partial resists only seem to happen on NPCs that have higher level than my character.

**Comment by knasen88** [comment]
The level based resistances includes holy, dont think your goddamn school of magic ignores all the laws of this game

**Comment by thepparker** [comment]
^

**Comment by ifyousayso** [comment]
I still suspect something is messed up. About 25% of holy damage is resisted by mobs that are 3 levels higher. According to this, raid bosses should resist 25% of all spell damage..

The only information about this that I've been able to find is here:
http://wowwiki.wikia.com/wiki/Resistance
"Note that this formula rendered level 83 bosses as having 15 magical resistance against level 80 player attacks."
.. and according to Damage reduction percentage = 100% * effective resistance rating / ( K + effective resistance rating ), the average damage reduction should be 7.14%. Perhaps I was just unlucky on 30 mobs in a row.
