### ISSUE TITLE
Missing NPC : Dashel Stonefist

### ISSUE THREAD

**Issue by syenna123** [LightsHope/server#106]
Hi,

Missing NPC : Dashel Stonefist
Quest name : The Missing Diplomat

I tried to use allakhazam.com along with archive.org but it didn't work.

Anyway, here is a video that shows where the NPC should be : https://youtu.be/LxBllhqRkvg?t=23m10s or https://youtu.be/W65GDUOfnS8?t=10m21s

Regards

**Comment by Lictoria** [comment]
Dashel Stonefist has been temporarily removed from the game as he was causing problems.

AFAIK, you will just have to wait for him to be returned, there is no work-around.

**Comment by syenna123** [comment]
Alright, thanks for the heads up!
