### ISSUE TITLE
Bloody bone necklace

### ISSUE THREAD

**Issue by Runass** [LightsHope/server#1062]
Bloody bone necklace in STV should have an 80% drop rate according to vanillawowdb:

http://db.vanillagaming.org/?item=3915

but in the server I think it's very low compared to this,I hope that if that's a bug it get solved.
Ty.

**Comment by stesve** [comment]
It has 17% droprate.

The droprates you see on vanillagaming is the droprates they have on their servers. The numbers can't be trusted as how high or low the droprate was on retail vanilla.

But if you look at the comments:

> low rating of drop , took me some time to get 25

> too True,Too true. the drop rate is not that good. 
> The Rates for the top four are (Rates From Wowhead.com and are Rounded up.)(Necklace/Bloodscalps Killed)
> 
> Bloodscalp Warrior: Necklace acquired 17%of the time with a rate of 1/6 or 1/5.8
> 
> Bloodscalp Shaman: Necklace acquired 17% of the time with a rate of 1/6 of 1/5.9
> 
> Bloodscalp Axe Thrower: Necklace acquired 17% of the time with a rate of 1/6 or 1/5.9
> 
> Bloodscalp Scavenger: Necklace acquired 13% of the time with a rate of 1/8 or 1/7.8
> 
> These Results were acqured from information from Wowhead and may not be the most acurate if caompared to other sites.
> 
> Overall it is best to Loot the bloodscalp Warriors,Shamans and Axe throwers if using the result rounded to the nearest whole spot (for ex. 1/6 is rounded to the nearest whole spot not 1/5.8, that is rounded to the nearest tenth spot), But if you are using the results from the tenth spot rounded then the Bloodscalp warriors will give you a 0.1 higher chance of looting the necklace rather than the enemies in spots 2 and 3.

**Comment by QAkvastskaft** [comment]
http://vanillawowdb.com/?item=3915
