### ISSUE TITLE
Item:1168 does not exist in creature_loot_template

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#1073]
Item:1168 does not exist in creature_loot_template

**Comment by druidish** [comment]
This is a world drop item.

**Comment by thepparker** [comment]
It probably exists in a reference template shared by many creatures

**Comment by druidish** [comment]
It does, it's in the world drop reference loot tables. This issue is invalid.

**Comment by QAkvastskaft** [comment]
http://vanillawowdb.com/?item=1168
