### ISSUE TITLE
Ironfoe proc rate is inncorrect

### ISSUE THREAD

**Issue by watchtheworldburn** [LightsHope/server#1077]
Below is a list posted from thottbot forums

Demonfork = 10%; ppm = 2,1428 (2,1)
Ironfoe = 10%; ppm = 2,5
Quel'Serrar = 12%; ppm = 3,6 (author: only %)
Gutgore Ripper = 4%; ppm = 1,3333 (1,3)
Shadowstrike/Thunderstrike = 8%; ppm = 1,5483 (1,55)
Bonereaver's Edge = 15%; ppm = 2,6470 (2,6) (author: only proc because can perma up)
Perdition's Blade = 4%; ppm = 1,3333 (1,3)
Sulfuras, Hand of Ragnaros = 10%; ppm = 1,6216 (1,6)
Thunderfury = 18%; ppm = 5,6842 (5,7) (author: only proc chance(till end bc best tank weapon in threat))

Barovian Family Sword = 10%; ppm = 2,8571 (2,9)
Frightskull Shaft = 8%; ppm = 1,4117 (1,4)
The Cruel Hand of Timmy = 10%; ppm = 3,3333 (3,3)
Demonshear = 6%; ppm = 0,9473 (0,9)
Gargoyle Shredder Talons = 8%; ppm = 2,6666 (2,7)
Hammer of the Titans = 10%; ppm = 1,5789 (1,6) (author: lower there was another Hammer of the Titans with 8% chance)
Skullforge Reaver = 8%; ppm = 1,92 (1,9)
Vis'kag the Bloodletter = 6%; ppm = 1,3846 (1,4)
Deathbringer = 8%; ppm = 1,6551 (1,7)
Eskhandar's Right Claw = 8%; ppm = 3,2
Eshkandar's Left Claw = 8%; ppm = 3,2
Empyrean Demolisher = 8%; ppm = 1,7142 (1,7)
Nightfall = 20%; ppm = 3,4285 (3,4) (author: only proc chance(weapon got nerfed in bc))
Ebon Hand = 8%; ppm = 2,0869 (2,1)
Sulfuron Hammer = 6%; ppm = 0,9729 (1)
Arcanite Champion = 10%; ppm = 2
Jeklik's Crusher = 6%; ppm = 1
Halberd of Smiting = 4%; ppm = 0,6857 (0,7)
Arlokk's Grasp = 8%; ppm = 3,2
Ancient Hakkari Manslayer = 6%; ppm = 1,8
The Untamed Blade = 10%; ppm = 1,7647 (1,8)
Drake Talon Cleaver = 6%; ppm = 1,0588 (1,1)

Source: forum thottbot wow-wikki for the information of the %

http://forums.elitistjerks.com/topic/8503-weapon-proc-rates-database/

https://xpoff.com/threads/weapon-proc-rates.60492/

**Comment by watchtheworldburn** [comment]
Steppen can dif for trying to nerf a weapon he is too lazy to farm

**Comment by thepparker** [comment]
See the other issue reports.
