### ISSUE TITLE
Both Elixirs of Intellect don't stack with buffs

### ISSUE THREAD

**Issue by AutisticDwarf** [LightsHope/server#1078]
Not so long ago I've noticed that Greater Elixir of Intellect and Elixir of Wisdom both stopped giving me mana whenever I use em in party and raid groups. After some autistic digging I realized that they just don't stack with mage buffs. Happened around AV water patch, so I think it's the one to blame.

**Comment by thepparker** [comment]
They have never stacked with Arcane Intellect, and this is working as intended.
