### ISSUE TITLE
Hunter pet bugs 

### ISSUE THREAD

**Issue by Anderslarsson1337** [LightsHope/server#109]
Hunter pets who uses cower and growl are bugged It will auto matic use both at same time even 1 of them are off. 
https://www.youtube.com/watch?v=USxFNNYYkL8
I tried it on my Boar (learnt) the cower spell and it happens the same as it does for the cat on video.

**Comment by GuybrushGit** [comment]
That's just the global cooldown, its not using Cower.

**Comment by Anderslarsson1337** [comment]
Thats not global cooldown ... it litterally uses it.

**Comment by QAkvastskaft** [comment]
Growl and Cower share cooldown

https://www.gamefaqs.com/boards/534914-world-of-warcraft/46008516
