### ISSUE TITLE
witch doctor unbagwa in STV is bugged. Needs reset

### ISSUE THREAD

**Issue by mikelish** [LightsHope/server#1097]
witch doctor unbagwa in STV is bugged. Please reset him. I have the Stranglethorn Fever quest from Booty Bay and I walked up to witch doctor unbagwa  and he wont even talk to me. Others experiencing same problem.

Thanks

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
