### ISSUE TITLE
30%-50% disconnection rate at login attempt

### ISSUE THREAD

**Issue by ifyousayso** [LightsHope/server#1099]
"Disconnected from server"

This started recently (today?). I enter the password, enter, and get instantly disconnected. It's not a connection issue because I'm still logged on another computer, same account, and it's not the wrong password either.

Even now when the server is down, every other attempt is "Disconnected from server", every other actually attempt to connect: "Connecting".

**Comment by QAkvastskaft** [comment]
Likely due to these attacks: https://twitter.com/i/web/status/946854119989481472

**Comment by ifyousayso** [comment]
It's very valid. Also, just got banned for attempting to log on and getting disconnected.

**Comment by berillis** [comment]
It started to do that for me also after Christmas. Everytime I login it disconnects me first and on the second try I can get in.
