### ISSUE TITLE
AV: Stormpike Mine layer and Frostwolf Mine layer

### ISSUE THREAD

**Issue by Hatredshit** [LightsHope/server#11]
Mine layers should no longer respawn when killed:
https://wow.gamepedia.com/Patch_1.5.0#Patch_1.5_Supplemental_Changes

NPC ID:
Horde: http://db.vanillagaming.org/?npc=13357
Alliance: http://db.vanillagaming.org/?npc=13356

Also these mine layers are stronger than Galvangar, Balinda, Drek'thar, Vanndar and the Ultimate Units; Lokh'alar and Ivus.

**Comment by GuybrushGit** [comment]
AV is intentionally left in its pre-nerf state.

**Comment by Hatredshit** [comment]
Is this the patch 1.5 state?

**Comment by Hatredshit** [comment]
Not sure where to post feedback, so i will use this thread.

Stormpike Mine Layer has just respawned.

Tested after maintaince/honor update.
