### ISSUE TITLE
Never got reward for Korrak the Bloodrager

### ISSUE THREAD

**Issue by KoalaNinjas** [LightsHope/server#1102]
Back on the original Elysium server i completed the Alterac Valley quest for Korrak the Bloodrager and I never recieved my weapon the Ice Barbed Spear I transfered my characters when Light's Hope came online I just haven't played since then but I can't redo the quest. Is there any way I can actually get my weapon?

**Comment by Questida** [comment]
Make an in-game ticket. The system records the reward selected and the absence of one, I would imagine.

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
