### ISSUE TITLE
Empyrean Demolisher proc chance should be higher

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#111]
Empyrean Demolisher currently only has 1 PPM, making it considerably weaker than Ironfoe, which is a similar weapon.

There's very hard to find concrete evidence for this, since this was an uncommon weapon back in retail.

**Reasoning and Proof**

- https://xpoff.com/threads/weapon-proc-rates.60492/ lists Empyrean demolisher as 1.7 PPM. I think it should be either 1.5 or 2 PPM, since Blizzard almost always used 1, 1.5 or 2 PPM for weapons.
- Empyrean Demolisher is a similar weapon to the hammersmith maces (Dragonstrike) in TBC, which had 1.5 PPM.
- Empyrean Demolisher timewalking version in retail WoW has a 1.5 PPM http://www.wowhead.com/spell=243994/empyrean-demolisher I think its likely that this value was either tuned down or kept the same for balance sake.
- http://runeclad.com/viewtopic.php?f=2&t=3221&view=previous "Empyrean demolisher - Kazzak (supposedly, this thing procs A LOT, which makes this one of the best fury weps you can get, if i was an alt fury warr, i'd be all over this)"
- http://webcache.googleusercontent.com/search?q=cache:hxsiAsKxOMAJ:z13.invisionfree.com/Fire_and_Blood/index.php%3Fact%3DST%26f%3D17%26t%3D182%26view%3Dgetnewpost+&cd=26&hl=et&ct=clnk&gl=ee "Empyrean Demolisher - In my opinion this is BY FAR the best main hand for a fury warrior. Its nice and slow and the proc is a god send. It stacks with flurry and seems to go off all the time. I'd say the proc rate is 1/15 swings. A few people I know actually try to kite me when this thing goes off because of the DPS it can produce. It not only increases the speed of your main hand but your off hand as well. Its a little weak in the DPS compared to Vis'Kag and Deathbringer but the proc makes up for all of that. Should this thing go off with deathwish its just good game." 1/15 swings means 6,66% proc chance which is pretty much 1.5 PPM (7% proc chance)
- http://www.tribalwar.com/forums/archive/index.php?t-441927.html "I don't have this yet but a buddy does and he tells me this thing procs like crazy. Add +hit gear and "Flurry" and, well, I imagine you can imagine ..."

I think it would be best to change it to either 1.5 PPM or 2 PPM, making it's power more in line with how hard it is to obtain.

**Comment by GuybrushGit** [comment]
https://vanilla-twinhead.twinstar.cz/?issue=10452

**Comment by ohganot** [comment]
The general consensus in that thread also seems to be 1.5 PPM, so I guess that would be the best number.

**Comment by ohganot** [comment]
Further Research:

Empyrean Demolisher's proc was reused in TBC, in fact Dragonstrike uses the EXACT same proc. (Same spell id). Therefore the PPM for Dragonstrike should also be accurate for Empyrean.
http://web.archive.org/web/20070819152024/http://wow.allakhazam.com:80/item.html?witem=17112
http://web.archive.org/web/20071020024703/http://wow.allakhazam.com:80/item.html?witem=28439

http://www.overclockers.com/forums/archive/index.php/t-511357-p-3.html
"Dragonstrike [375] MH Mace (184-344) 97.6 dps, Spd 2.7, +19 Sta, 1.5 ppm Proc: +212 Haste for 10 sec., (Epic, BoP)" (1.5 PPM)
https://www.engadget.com/2007/09/21/encrypted-text-most-valuable-procs/
Lists Dragonstrike as 1.4 PPM, but most likely its because they didn't do 10k swing test. 1.5 PPM is more likely since blizzard usually used 1 PPM, 1.5 PPM and 2 PPM.

**Comment by GuybrushGit** [comment]
I agree that it should be 1.5 but I removed the confirmed tag since it was misleading, this sort of thing is impossible to confirm. A decision needs to be made to change this or not.

**Comment by ohganot** [comment]
Alright, got it. I just think it should be changed if there's more evidence for 1.5 PPM than 1 PPM. If anyone has evidence that it should be 1 PPM, please share that info.
