### ISSUE TITLE
Young Forest Bear (Elwynn)

### ISSUE THREAD

**Issue by sabana66** [LightsHope/server#1110]
Hello, when I tamed Young Forest Bear he actually had 2.70 attack speed. I don't know how he has now 2.50 attack speed. My pet hasn't got any buff/talent to increase his attack speed and I tryed to delete WDB, WTF and Addons folders but still 2.50 attack speed. 

Could you please fix this bugg? Thanks you in advance.

**Comment by Niceguyone** [comment]
He is supposed to have 2.50 attack speed, which is also the slowest one in the game. See https://web.archive.org/web/20061023195244/http://tkasomething.com:80/attackspeeds.php.

> Attack Speed: 2.50
Young Forest Bear, level range 8-9 (Elwynn Forest)
