### ISSUE TITLE
Flurry stacks are only being consumed by succesful melee hits

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#1114]
**Issue**
Flurry stacks are only consumed if the melee swing hits the target (only crit, hit or glancing blows)

**How it should be**
Flurry stacks are consumed on every melee swing, no matter if dodge, miss, parry, block, crit, hit or glancing blow

**Proof**
https://www.youtube.com/watch?v=fnu24GvWuWA
https://www.youtube.com/watch?v=VNbEcXikcvA

If you analyze those videos you can see that flurry stacks are spent by all swings. Note that they are spent and refreshed by a slight delay, so don't get confused by that.

**Comment by Cabro** [comment]
Add immune to those.
