### ISSUE TITLE
Divine Shield bug

### ISSUE THREAD

**Issue by VVarbandit** [LightsHope/server#1115]
Immunity of Divine Shield is broken.
Alot of CC goes trough it like seductions, fears and so on.
This is done in a similiar fashion with ppl crowd controlling each other at the same time.
I think the issue causing for these problems is bad netcoding/lagg.
Like this is a gamebreaking issue for pvp, so please fix it.

Proof of described bug: https://imgur.com/8DPIxYL.

**Comment by Nyatsuelysium** [comment]
This could be related:
https://github.com/LightsHope/server/issues/179

Succubus keep seduction even though succubus is blinded.
