### ISSUE TITLE
Rogue combo points shouldn't be removed upon target deselect.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1119]
Title. They should only be removed on new target selection.
[Patch 1.4.0](http://wowwiki.wikia.com/wiki/Patch_1.4.0): "Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected. "

**Comment by QAkvastskaft** [comment]
Works as intended for me

**Comment by Cabro** [comment]
Oh ok then, rogues were telling me the opposite.
