### ISSUE TITLE
Warchief's blessing should not have a CD

### ISSUE THREAD

**Issue by knasen88** [LightsHope/server#112]
Currently the cooldown is supposed to be 6 hours, but that's not true either because it's bugged aswell. The timer of the script does not count unless someone is close to thrall for him to be "loaded in" so for the 6 hour timer to be accurate there has to be someone in throne room the entire duration.
Now the real problem.

> http://wow.allakhazam.com/forum.html?forum=21&mid=113690196285182144

There is no source of WCB ever having a CD other than "it didn't pop often on my 200 pop realm" back in 2006 where the same player think onyxia buff lasted 1 hour. Or that killing whole of mc under 2 hours was IMPOSSIBLE so the caliber of that player can be disregarded.

and on that note, if that is proof for CD on WCB, i have proof from PATCHNOTES that even onyxia/nef buff have "6" hour cooldown.

Patch 1.7 also mentions it briefly that to buff, there can be no (same) head hanging.

https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html

http://alt.games.warcraft.narkive.com/nbkesSJ1/turing-in-onyxia-head-turnin-city-buffs

> When I have handed-in Onyxia's head, nobody was buffed,
    because a head already dangled from a stone ridge on the
    entrance to Stormwind (valley of heroes). I don't know
    how often it is removed, but I've heard that only one head
    can be handed-in per week.

> Not at all! It's a couple of hours normally (or is that 24h? can't
    remember), check the guards to see what buff they have, this will let
    you know if your head will buff everyone around.
    
> AFAIK* you can get the buff only every six hours. But the buff (and the
    head itself) are only two hours. But I think Nefarians head is on a
    different counter; but you can't receive the buff more than once.

Remove WCB cd or both should have cd.

**Comment by druidish** [comment]
Some comments on Allakhazam and Thottbot suggest it had some sort of cooldown on it. I agree with your trailing comment. They should fix Ony/Nef buff so that it only gets cast if the corresponding head isn't hanging/on a pike.

https://web.archive.org/web/20071118115501/http://wow.allakhazam.com:80/db/quest.html?wquest=4974
http://web.archive.org/web/20050830183740/http://www.thottbot.com:80/?q=4575

**Comment by Tunesisback** [comment]
Thanks @knasen88 for not giving up on this.

**Comment by knasen88** [comment]
when is this getting added to live server?

@Tunesisback ofc, its every hordes duty

**Comment by knasen88** [comment]
24 days and counting

**Comment by Omarthegreatone** [comment]
Any response?
