### ISSUE TITLE
Enchanting items should make them soulbound.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1120]
[Patch 1.7.0](http://wowwiki.wikia.com/wiki/Patch_1.7.0):
>Enchanting an item with an enchantment that will cause the item to become soulbound will now prompt the enchanter with a warning message before the enchantment is cast. 

Or what exactly are the enchantments that cause items to become soulbound?

**Comment by QAkvastskaft** [comment]
The class specific ones from ZG no doubt

**Comment by Cabro** [comment]
Oh that actually makes sense. Thanks.
