### ISSUE TITLE
[Core] NPCs in combat that are CCed don't make threat on players in combat.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1132]
I've had so many times a sheep go for me (Tank) after 30s fights in which i received a lot of heals, and the only damage towards it was a bow shot and eventually threat from shield block and 1 demo shout.
Same for banished NPCs. They don't upgrade the threat table while CCed. This is not how it was on retail. They are still in combat and they should update the table.

I guess the CC types are sheep/banish/sleep etc. This should really be checked.

**Comment by knasen88** [comment]
as always, find some SOURCE

**Comment by Cabro** [comment]
They are in combat, while CCed. Threat is applied to all mobs that are in combat with you. INCLUDING THE CCED ONES. Common logic.

**Comment by Cabro** [comment]
I guess it is working as it should.
