### ISSUE TITLE
[Lightbringer] can't summon Winter Veil companions

### ISSUE THREAD

**Issue by ibarazaki** [LightsHope/server#1134]
All Winter Veil companions got bugged after trying to summon one while already having summoned another companion. After using e.g. Green Helper Box, the old companion disappeared and new companion hasn't showed up. Now every attempt to summon Winter Veil companion ends with 'Item is not ready yet' message despite no cooldown shown on the item icon.

**Comment by Cabro** [comment]
You need snowballs.

**Comment by ibarazaki** [comment]
Lol, my bad. I thought snowballs are needed only for Snowman Kit, lol.
