### ISSUE TITLE
About druid's shapeshifting and movement impairing effects. Lightbringer server.

### ISSUE THREAD

**Issue by Speranskiy** [LightsHope/server#1143]
Hello. Found out, that druid's shapeshifting deosn't break the "Daze" debuff, which, for example, you can get from mobs while running away from them. Other movement impairing effects, like immobilize from spider web, are still breakable. 
Thought it could be a game mechanic, so checked it on Kronos server - there it works ok.
Thx in advance and happy new year :*

**Comment by AskeH** [comment]
While it slows movement speed, daze is not considered a movement impairing effect. Thus it cannot (and shouldnt) be removed by the usual means such as druid shapeshifting, Vanish, Faction Insignia, or Hand of Freedom.

The scripting on Kronos is, sorry to say, utterly shit.

Happy new year :)

**Comment by QAkvastskaft** [comment]
We need sources, e.g a video from vanilla, to take any action.

**Comment by stesve** [comment]
http://wowwiki.wikia.com/wiki/Mechanic?oldid=30364
Revision as of 18:27, September 20, 2005 

> A Blizzard post to the official forums indicated that it is intentionally impossible to remove a Daze other than waiting it out. There was once a bug (appeared in patch 1.6; fixed in patch 1.7) that allowed Paladins' Blessing of Freedom and Druids' Shapeshifting to remove Daze, but this was a mistake.

**Comment by stesve** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.7.0

> Fixed a bug where the Dazed ability used by creatures when attacking targets from behind was countered/dispelled by some spells (e.g. Blessing of Freedom).
