### ISSUE TITLE
unlearning a professional speciality

### ISSUE THREAD

**Issue by Popejackson** [LightsHope/server#1150]
When talking to the trainer of the professionspeciality one has chosen (in my case master axesmith), there is an option to unlearn the profession speciality. pressing that option leads to a new chat with a sort of "are you sure you want to unlearn...", when pressing this new option, a red text tells me that its not possible. i have deleted WDB/WTF files, though its still not working.

**Comment by Haiwuu** [comment]
I believe swapping specialization is from TBC and the menu shouldn't be there.

http://wowwiki.wikia.com/wiki/Patch_2.0.3
