### ISSUE TITLE
Manual of Eviscerate IX

### ISSUE THREAD

**Issue by Vanillaforprez** [LightsHope/server#1151]
**Manual of Eviscerate IX should be added in 1.9**
There are multiple sources all quoting different patches which is common with alot of items, however it was originally added with all the other class books in 1.9 

here is one source claiming **1.12** http://wowwiki.wikia.com/wiki/Manual_of_Eviscerate_IX
and one source claiming **1.11.1.5462** -- http://www.wowhead.com/item=24102/manual-of-eviscerate-ix

Here are two sources confirming **1.9**-
https://forum.nostalrius.org/viewtopic.php?f=45&t=5945
https://wow.gamepedia.com/Manual_of_Eviscerate_IX

**Comment by brotalnia** [comment]
Wrong. Both the display id 36765 and the spell id 31017 used by the item do not exist in the client prior to 1.12.

You can get dbc files from all vanilla wow versions converted to sql here so you don't have to speculate -> https://github.com/brotalnia/ely-database/blob/master/new_progression/old_versions_data.7z

**Comment by Sylvestersnr** [comment]
In the patch notes of 1.12.0:
'' Eviscerate: Manual of Eviscerate (Rank 9) now drops off Blackhand Assassins in Blackrock Spire. In addition, Eviscerate now increases in potency with greater attack power.''
