### ISSUE TITLE
MoveMapGen fail

### ISSUE THREAD

**Issue by Jinsheng-Peng** [LightsHope/server#1157]
HI，I git the release  version，and compile pass . （windows7 X86 ，Visual Studio 2017，CMAKE3.8.1  ，ACE6.4，TBB2017_0919）
（wow1.12.1 5875）ad、vmapextractor、vmap_assembler runs OK，but the MoveMapGen  has error while runing to half。

Error message  ：

```
Building map 000, tile [27,28]
Building map 000, tile [27,29]
___________________________________________________
Assertion Failure - MoveMapGen.exe
Debug assertion failure
Expression: direction.isUnit()
C:\lighthope\server\dep\src\g3dlite\Ray.cpp:21

Choose an option by number:
  (0) Debug   (1) Ignore   (2) Exit
>
```

**Comment by brotalnia** [comment]
You need to use the Giperion branch to compile the extractors, not development branch.

These are compiled extractor binaries for Windows:
https://github.com/elysium-project/server/files/852498/Elysium.Extractors.18.March.zip

**Comment by Jinsheng-Peng** [comment]
think you!
