### ISSUE TITLE
Insanely short cooldown on Transmute: Elemental Fire

### ISSUE THREAD

**Issue by budaletina** [LightsHope/server#1165]
While this may not be a bug at all, as it is hard to find any concrete and reliable source on items such as these, Transmute: Elemental Fire added in 1.9 and bough from the Thorium Brotherhood NPC has an insanely short cooldown of only 10 minutes. This is totally out of line with the other Alchemy transmutes, which have much longer cooldowns, 1 or 2 days. I am not able to provide any evidence what the duration should be, but it seems totally out of place and is most likely bugged.

**Comment by bjornenalfa** [comment]
10 min cooldown is correct. https://web.archive.org/web/20060216192805/http://wow.allakhazam.com:80/db/item.html?witem=20761
