### ISSUE TITLE
Varimathras not spawned in Undercity Royal Quarter. Can't turn in "The Power to Destroy..." quest.

### ISSUE THREAD

**Issue by aenemike** [LightsHope/server#117]
Darrowshire server:
Varimathras is not spawned in the Undercity Royal Quarter.
I am attempting to turn in the quest "The Power to Destroy..." but Varimathras is not here.
Other NPC's in the room pop in and out as I run around the room, but Verimathras never spawns in

**Comment by Lictoria** [comment]
Varimathras, like other city-bosses, can take **many** hours to respawn.

**Comment by GuybrushGit** [comment]
Let us know if he doesn't respawn.

**Comment by aenemike** [comment]
He shows up now. The other characters in the room have also stopped popping in and out as I move around the room.
Thanks!
