### ISSUE TITLE
What is the unfreeze command?

### ISSUE THREAD

**Issue by Locario** [LightsHope/server#1179]
Hi there.

I have used .freez command, now selected player cannot move, how i can unfreeze him?

Thanks!

**Comment by Haplotaxida** [comment]
Goggle suggests  .unfreeze

**Comment by Locario** [comment]
There is no such command

**Comment by GuybrushGit** [comment]
.unaura 29826

**Comment by Locario** [comment]
YES!!!! MANY THANKS
