### ISSUE TITLE
Hunter's Aimed Shot (Rank 1) no where to be found

### ISSUE THREAD

**Issue by kroman123** [LightsHope/server#118]
My level 30 hunter that should have (Rank 2) Aimed Shot is unable to buy the (Rank 2) spell from any hunter trainer because I do not have (Rank 1) Aimed Shot and am incapable of purchasing the (Rank 1) spell from any hunter trainer in result of it not showing up ANYWHERE. I have already closed out of all WoW programs, then deleted my WTF/WDB folders from the WoW directory, then reopened WoW and relogged into my character while disabling all Addons. Still no correction to missing spell (Rank 1) Aimed Shot from my spellbook and/or any hunter trainers.

**Comment by ejt1** [comment]
Aimed shot is a tier 3 talent in the marksmanship tree.
