### ISSUE TITLE
LightsHope/Server/20180106024716_world.sql

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#1183]
LightsHope/Server/20180106024716_world.sql
Why not put it in server/sql/migrations/ ?

**Comment by brotalnia** [comment]
@ohganot lol, migrations are supposed to go in sql/migrations

**Comment by Kittnz** [comment]
https://github.com/LightsHope/server/commit/389b9ad27204cda63211fb645358793d087e06d6
