### ISSUE TITLE
Spirestone Battle Lord <rare spawn>

### ISSUE THREAD

**Issue by kkruusi** [LightsHope/server#1187]
We killed him and he dropped nothing. Possibly a bug.

**Comment by Kittnz** [comment]
invalid, drops 12219, 13284, 13285, 14047, 21982 and 22528.
https://woehead.way-of-elendil.fr/?npc=9218#drops

**Comment by Cabro** [comment]
Why are you linking private server as proof?

**Comment by Kittnz** [comment]
I'm just linking the dropped items, and these are in the db. Easier to see. It's a wowhead like website..

**Comment by Cabro** [comment]
Well the bug is that it didn't drop anything. Not that it has no items in the loot table. Please think.

**Comment by Kittnz** [comment]
prolly tagged?

**Comment by Kittnz** [comment]
works on dev eitherway

**Comment by Cabro** [comment]
So it's working as it should? Not dropping items from loot table when killed? Source?

**Comment by kkruusi** [comment]
He spawned in after after we had killed Wyrmthalak. He wasn't initially in the ogre area when we started the instance.

**Comment by kevin-kruusi** [comment]
It was on Darrowshire if that helps.
