### ISSUE TITLE
Multiboxing report

### ISSUE THREAD

**Issue by maoqixiao** [LightsHope/server#1188]
Dear GM , I am now reporting some guy Multiboxing to boost his low level charater in Ruins of Alterac.Their names are horde 60lvl warrior Stancee and horde 38lvl warlock Fpuckyou.They already violated Light's Hope Lightbringer game rules , please check and ban them for fair play, thank you very much .I am pleased to be a law-abiding person and help decontaminating our game environment.

**Comment by Kittnz** [comment]
no gm support here, make a ingame ticket
