### ISSUE TITLE
PvP Set update

### ISSUE THREAD

**Issue by alp84** [LightsHope/server#1191]
Hi,
Since a few weeks, the blue rank 10 pvp set was new updated, but the blue rank 10 pvp set, which already purchased wasn’t patched and are still with old stats, however , they must be patched because the people cannot rank again and again because of the update of the server- - and when people don’t have rank 10 anymore, they cannot buy them too, althrough they have reached it before.

**Comment by thepparker** [comment]
The level 60 and level 58 Blue PvP sets are two different sets of equipment, and hence are not automatically upgraded. The ruleset on Lightbringer is such that your current rank must be sufficient to purchase the items, it does not use your lifetime rank. Whether you choose to participate in PVP once more to acquire the new items or not is up to you.
