### ISSUE TITLE
The following error occurred at compile time, please fix it.

### ISSUE THREAD

**Issue by bluehelp1989** [LightsHope/server#1193]
I was the windows10 64 - bit system compiled in the following errors, the development branch and release will have such a mistake, request repair!

3>C:\Users\baidupc\Desktop\server\src\shared\Database\Database.cpp (560): warning C4018: ">": signed / unsigned mismatch
3>C:\Users\baidupc\Desktop\server\src\shared\Database\Database.cpp (570): warning C4018: "<": signed / unsigned mismatch

7>C:\Users\baidupc\Desktop\server\src\game\Handlers\PetitionsHandler.cpp (288): warning C4101: "fields": a local variable that is not referenced

7>C:\Users\baidupc\Desktop\server\src\game\Maps\MapManager.cpp (858): the conversion of warning C4838: from "double" to "const float" requires contraction conversion
7>C:\Users\baidupc\Desktop\server\src\game\Maps\MapManager.cpp (858): warning C4305: "initialization": from "double" to "const float" truncation

7>C:\Users\baidupc\Desktop\server\src\game\Objects\Pet.cpp (734): warning C4018: "<": signed / unsigned mismatch
7>C:\Users\baidupc\Desktop\server\src\game\Spells\SpellAuras.cpp (501): warning C4018: ">": signed / unsigned mismatch
7>C:\Users\baidupc\Desktop\server\src\game\Spells\SpellEffects.cpp (4469): the conversion of warning C4838: from "int" to "uint32" requires contraction and conversion

10>C:\Users\baidupc\Desktop\server\src\scripts\custom\custom_creatures.cpp (1018): warning C4018: "<": signed / unsigned mismatch
10>C:\Users\baidupc\Desktop\server\src\scripts\custom\custom_creatures.cpp (1027): warning C4018: "<": signed / unsigned mismatch
10>C:\Users\baidupc\Desktop\server\src\scripts\world\world_event_wareffort.cpp (94): warning C4101: "info": a local variable that is not referenced

Thank you very much.

**Comment by stesve** [comment]
The following **warnings** occurred at compile time.

**Comment by bluehelp1989** [comment]
Do these errors have an impact on the game?

**Comment by bluehelp1989** [comment]
Thank you very much for your answer. Thank you.
