### ISSUE TITLE
Emperor Vek'nilash is missing Double Attack ability

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#1200]
**Issue**
Emperor Vek'nilash should be able to do double attacks.
There's a separate ability called Double Attack, which causes 2x attacks, while Thrash causes 3x attacks.

**Proof**
https://www.youtube.com/watch?v=Qm6tsnot_1c&feature=youtu.be&t=290

**Comment by Dalleren** [comment]
Video is from 2013, could possible be from another private server? It is also the only source that implying that Emperor Vek'nilash should do double attacks.

Also, why do you not post the research you did yourself on the matter of bosses that should or should **NOT** have double attacks:
https://vanilla-twinhead.twinstar.cz/?issue=10896
This is also the origin of the video you posted.

**Comment by ohganot** [comment]
His channel also has a Naxxramas video from the same guild, at the start of the video it says Arak-Arahm, which was an EU server.

That issue was for a different bug, which doesn't exist on Lightbringer. So I don't see how is that relevant.

The Double Attack doesn't show up in combat log since it seems to be an aura that grants the boss % chance to get extra attack, which will just register as a normal AA.

**Comment by Zarant** [comment]
This youtube channel have a Thaddius video uploaded in 2013 (https://www.youtube.com/watch?v=EpfLqcmIqJI) and then the same video is uploaded somewhere else (https://www.youtube.com/watch?v=f7zB9OfyMTQ) from 2009, which strongly suggests that his videos were from retail. If you compare his ui from both videos, you can assume that this is either from retail vanilla or this guy went out of his way to make the video look like it.

**Comment by Aklol** [comment]
http://warcraftrealms.com/charsheet/5603684

This is confirmed from retail
