### ISSUE TITLE
pet spells lead to Server crash!

### ISSUE THREAD

**Issue by Jinsheng-Peng** [LightsHope/server#1202]
Area ： Elwynn Forest （艾尔文森林）
in the Blackwell's pumpkin field （布莱克威尔南瓜田）  
There's a pig called a princess （有一只叫作公主的猪）
If the hunter grabs the pig as a pet, （如果猎人抓这个猪作为宠物）
logout the game ！（退出游戏）
once when the character login the game again， the game server will be crashing（然后在角色退出再进入游戏时候会导致服务器崩溃）

![qq 20180110222721](https://user-images.githubusercontent.com/16498476/34726281-851373d6-f58e-11e7-9e7c-8e68a1c02de1.png)
![qq 20180110222511](https://user-images.githubusercontent.com/16498476/34726282-854fb10c-f58e-11e7-8d4f-5ad6eae203e9.png)

**mangosd server crash Log:**
2018-01-09 21:26:59 D:\lightsHope\server\src\game\Spells\SpellAuras.cpp:268: Error: Assertion in Aura::Aura failed: spellproto->EffectApplyAuraName[eff]
2018-01-09 21:26:59 Aura::ComputeExclusive()+0xc0 [0x0]
Pet::_LoadAuras()+0x217 [0x0]
Pet::LoadPetFromDB()+0x7c6 [0x0]
Player::LoadPet()+0x6c [0x0]
WorldSession::HandlePlayerLogin()+0xc5a [0x0]
WorldSession::HandlePlayerLogin()+0x1033 [0x0]
Player::CanSwim()+0x1a2e0 [0x0]
CreatureAI::SwitchAiAtControl()+0xa8f [0x0]
Object::GetPackGUID()+0x332e [0x0]
BarGoLink::step()+0xbe7 [0x0]
ACE_OS_Thread_Adapter::invoke()+0xc2 [0x0]
crt_at_quick_exit()+0x104 [0x0]
BaseThreadInitThunk()+0x12 [0x0]
RtlInitializeExceptionChain()+0x63 [0x0]
RtlInitializeExceptionChain()+0x36 [0x0]

**windows server log**
错误应用程序名称: mangosd.exe，版本: 0.0.0.0，时间戳: 0x5a4eded7
错误模块名称: ucrtbase.DLL，版本: 10.0.10586.788，时间戳: 0x5879aa7b
异常代码: 0x40000015
错误偏移量: 0x0008469a
错误进程 ID: 0xb80
错误应用程序启动时间: 0x01d389505a08c3e2
错误应用程序路径: E:\ftp\mangosd.exe
错误模块路径: C:\Windows\system32\ucrtbase.DLL
报告 ID: c01789c2-f543-11e7-af9a-ee5dd4fb31fb

**Comment by brotalnia** [comment]
I tamed her but it's not crashing for me.

**Comment by DarkmoonRabbit** [comment]
I tamed her but it's not crashing for me
(你客户端问题么？老铁)
