### ISSUE TITLE
Combat Healing Potion and Combat Mana Potion require rank 6 to buy.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1209]
I've been looking for it for some time, and i cannot find a single internet reference that mentions this. Why do they require rank 6 to buy?

**Comment by stesve** [comment]
http://www.wowhead.com/item=18841/combat-mana-potion#comments

First comment from 2006/10/28 - "They are sold by the PvP officer supplier at rank 6, costs 11s each and has an unlimited supply. They are a very cheap alternative to purchasing potions off the auction house.".

Vendor located in pvp hall that requires rank 6 to enter until patch 2.0.1.

**Comment by Cabro** [comment]
I must be blind. Thank you!
