### ISSUE TITLE
Elixir of Greater Firepower should not be in the game until patch 1.10

### ISSUE THREAD

**Issue by someotherplayer** [LightsHope/server#1213]
There are people selling Elixir of Greater Firepower on the auctionhouse on Light's Hope which current state is patch 1.9
According to http://wowwiki.wikia.com/wiki/Patch_1.10 the recipe has been added in patch 1.10

I quote: "There is now an Elixir of Greater Firepower recipe in the world. The Dark Iron Dwarves of the Searing Gorge hold the secret."

I talked to a seller and he told me the recipe has been available when Zul Gurub launched and he bought it off the auctionhouse.
The recipe is no longer available on Light's Hope as far as I can tell. Linking the item in chat will result in an unclickable link.
People are still able to make the elixirs and they are selling them on the auctionhouse.

I did not test if the elixirs work correctly.

**Comment by LHGemt** [comment]
A staff member tested it, and it is not usable ingame. The elixir itself has the correct min-patch in the DB, so while the existing elixirs may not be removed, it won't be usable until the correct patch.

If someone, for some reason, is still able to use it, feel free to re-open the issue.
