### ISSUE TITLE
Bug regarding rogues sap mechanic.

### ISSUE THREAD

**Issue by snokthe1** [LightsHope/server#1216]
Hello
Found a bug regarding rogues sap mechanic.
If they sap you just as you fly away from flight master, you are stuck on the flight mount. 
I tried to drown myself, didn't work, tried to relogg, didn't work.
Cant interact with anything, this is the dumbest and most broken bug ever.
I appreciate if you look into this.
Thanks for your time.

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.
Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.
Thank you
