### ISSUE TITLE
Issue with the Mailbox

### ISSUE THREAD

**Issue by viktornolander** [LightsHope/server#123]
I was told by a GM to post my problem here if it still existed after after deleting my WTF and WDB.

The problem is that i cant send any items from my alts to my main char. It says ive reached the limit.

When i go to my main it says (and have done this for several days/weeks) that i got a unread mail. I open the mailbox, but nothing is there.

i dont know what to do.

**Comment by GuybrushGit** [comment]
Some mailboxes are full with invisible expired mails.

**Comment by viktornolander** [comment]
So what should i do about it? :/
