### ISSUE TITLE
The Prophet Skeram raid markers shouldn't be cleared

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#1237]
**Current behaviour**
When Skeram splits, the raid markers are cleared.

**Correct behaviour**
When Skeram splits, the raid markers remain, letting you distinguish the boss from the illusions.

**Proof**
https://www.youtube.com/watch?v=YpQwYIr1wFY

http://wowwiki.wikia.com/wiki/The_Prophet_Skeram?oldid=388887
"Since the 1.11 patch you can place a Raid Target marker on The Prophet Skeram at the start and it will stay with him when he splits and teleports."

**Comment by LHGemt** [comment]
We try to keep raids in their "pre-nerf" state wherever possible. Blizzard may or may not have considered this a bug when changing it in 1.11, but I think it's a core mechanic to the fight to do a bit of "searching" before you find the correct image. We will be keeping it as-is.
