### ISSUE TITLE
The Quest "Mazzranache"

### ISSUE THREAD

**Issue by Alucard600** [LightsHope/server#1243]
The Drop rate for Swoop Gizzard is suppose to be 100% since all other items for the quest also have a drop rate of 100%

Swoop Gizzard does not drop until many, many kills so the droprate for it is bugged.

I used shaguquest  to determine the droprate of the items and it says each one is 100% including Swoop Gizzard. I do not think this is a problem on the addons end.

This is the quest
http://db.vanillagaming.org/?quest=766

Sorry for editing it so much. I was trying to make it clear.

**Comment by stesve** [comment]
ShaguQuest uses the mangos zero db afaik and isn't always correct. You should use his newer addon instead (pfQuest) which uses the lh db.

The Vanillagaming db belongs to a different private server community and you can't trust the information shown to be 100% correct of how it where on retail vanilla or on lh.

(06-01-2006) https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/871-mulgore-quest-guide.html

> You may have to kill quite a few of these before they will drop the quest item.

**Comment by Alucard600** [comment]
I see, thank you
