### ISSUE TITLE
Fused Wiring

### ISSUE THREAD

**Issue by smrt1** [LightsHope/server#1247]
So today ive killed over 100 of venture co. shredders. The reason is because im looking for Fused Wiring, mat that i would need for my engineering. Yesterday i got 2 by killing 50 shredders, but today - 0 (and apperantly they have a drop chance of 6%). I would like to know if it is bugged or im really unlucky with the loot today. Ty

**Comment by Phatcat** [comment]
2 from 50 is a roughly 4% chance, which is not very off from 6% - you may indeed just be unlucky. 6% doesn't mean you get 6 per 100 kills, it means you STATISTICALLY get 6 per 100, but those numbers can be heavily influenced by people who have gone in and just killed a couple before it dropped for them.
