### ISSUE TITLE
Warlock Succubus questline strangely bugged.

### ISSUE THREAD

**Issue by Holteman** [LightsHope/server#126]
My bugg was in regards to the quests : http://db.vanillagaming.org/?quest=1476 and also http://db.vanillagaming.org/?quest=1472
I am an UD warlock at currently lvl 34.

I did not have any relating quest in my Qlog. I was unable to talk to any of the NPCs Godrick Farsan or Carendin Halgar. Neither NPC were "clickable" at all. 

GM Stodola assisted me, killed off Carending and maybe that did something, because I was then able to talk to Godrick and also finish the quest Devourer of Souls and then continue with Hearts of the Pure.

**Comment by GuybrushGit** [comment]
Quest is working fine in dev. Can't reproduce.
