### ISSUE TITLE
When loading mangosd.exe produces a lot of errors

### ISSUE THREAD

**Issue by OlegVintage88** [LightsHope/server#1263]
When loading mangosd.exe produces a lot of errors

Revision of the core https://github.com/LightsHope/server/commit/1e79aa124f037e9a378d94d4b1a023b364a50afc
Base https://github.com/LightsHope/database/blob/master/world_partial_15_january-2018.7z

Logs mangosd https://gist.github.com/OlegVintage88/2e6d338921ef98c405d9b2132f9f43b1

**Comment by brotalnia** [comment]
Do not download the database from the LightsHope repo! It is missing important data.

Here is the full database.
https://github.com/brotalnia/database/blob/master/world_full_15_january_2018.7z
