### ISSUE TITLE
Hunter pet normalization for 1.9

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1268]
[Patch 1.9](http://wowwiki.wikia.com/wiki/Patch_1.9.0):
- All hunter pets will now always deal Physical damage for their base attack. ( -translation: Lupos should stop doing shadow damage.)

**Comment by VeryRare** [comment]
Lupos should be changed now. Do you have any evidence that he wasn't?

I see you submit a lot of bug reports and some good ones for sure but it's going to make the dev's job impossible if you don't provide any evidence that you are reporting an actual bug.  If your trying to make the server better then think about the dev's that have to respond to these bug works and try and make their job a little easier.

**Comment by Cabro** [comment]
True, need to delete WDB once in a while.Thank you!
