### ISSUE TITLE
Twilight Cultist set doesnt drop

### ISSUE THREAD

**Issue by Elysis** [LightsHope/server#127]
Hi,

Ive been grinding for over two days to get my hands on the Twilight Cultist set and Encrypted Twilight Text from

**-Twilight Avenger
-Twilight Geolord
-Twilight Stonecaller
-Twilight Master
-Twilight Marauder
Twilight Marauder Morna
-Twilight Prophet
-Twilight Flamereaver
-Twilight Lord Everun**

But it doesnt seem to drop at all, and should according to vanilla databases have a 8% drop chance on 
-Twilight Cultist Mantle
-Twilight Cultist Robe
-Twilight Cultist Cowl
and a 25% drop chance on

**-Encrypted Twilight Text**

Could you please have a look at this? there are many people whom this would benefit, including every new player.

Regards Elysis

**Comment by GuybrushGit** [comment]
Same as https://github.com/LightsHope/server/issues/14
