### ISSUE TITLE
error loading dbghelp.dll

### ISSUE THREAD

**Issue by Jinsheng-Peng** [LightsHope/server#1272]
I  use the Giperion branch to compile the extractors,  and the  release branch  run steady with the maps. 

but today  i compile  the development branch   to  test(with the same maps). it  runs  error.
need  dbghelp ? i had copy from server\dep\lib\win32_release\dbghelp.dll
or ths maps error?
i am so puzzled

![qq 20180119094016](https://user-images.githubusercontent.com/16498476/35130990-9a7dd7ee-fcfe-11e7-97d0-ec309c8bc7b1.jpg)

**Comment by brotalnia** [comment]
Did you compile for x86 or x64 and Debug or Release? If you are using x86 make sure preloading of mmaps is disabled.

**Comment by Jinsheng-Peng** [comment]
@brotalnia 
yes  I compile for x86  and Release ,and set
Terrain.Preload.Continents = 1
Terrain.Preload.Instances  = 1
