### ISSUE TITLE
Still about the database unification issue, everyone please come in to discuss!

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#1274]
I think it is necessary to unify the development branch and release branch database, if the development and release database database is not coordinated, later will bring more trouble!

**Comment by brotalnia** [comment]
Release branch is always behind development, that branch is managed solely by thepparker and it is used only for the Light's Hope live servers. He manually picks and chooses commits from development and merges them into release. Do not use that branch, you will not get support, it does not concern you what works and doesn't on it, only report problems about development branch. And stop opening issues about the same thing.
