### ISSUE TITLE
Unable to accept the quest "A Vengful Fate"

### ISSUE THREAD

**Issue by golers** [LightsHope/server#1279]
This quest is given by Auld Stonespire in Thunder Bluff. According to everything I could find this quest has no pre-requisites and should be acceptable at level 22 for the Horde. It currently is sitting there with a grey question mark and can not be accepted. My character is currently a level 28 UD Mage.

**Comment by QAkvastskaft** [comment]
The minimum level for this quest has been changed to 29 in #843

**Comment by brotalnia** [comment]
Level 29 is the correct requirement https://web.archive.org/web/20060521235550/http://wow.allakhazam.com:80/db/quest.html?wquest=1102
