### ISSUE TITLE
Wintersaber Trainers Mount Price

### ISSUE THREAD

**Issue by kelila** [LightsHope/server#1289]
This was a previous issue, fixed, and then closed however I think the issue has come back up with the AQ patches.  

The price of the mount is showing 1000g (value 10000000). According to the information in the previous issue (linked below again) the change from value 1000000->10000000 wasn't made until the pre-tbc patch (which I do not believe we are at yet).

**Expected solution: change item cost of Reins of the Wintersaber to value: 1000000**

https://github.com/LightsHope/server/issues/767

https://web.archive.org/web/20071106011108/http://wow.allakhazam.com:80/db/itemhistory.html?witem=13086
https://web.archive.org/web/20060922071357/http://wow.allakhazam.com:80/db/item.html?witem=13086

**Comment by brotalnia** [comment]
You misunderstand, it was 1000g for the entirety of vanilla and was changed to 100g in the TBC preparation patch.

**Comment by kelila** [comment]
Oh, thanks for the quick response
