### ISSUE TITLE
Demonfork is not scaling at 100%

### ISSUE THREAD

**Issue by supasteed** [LightsHope/server#129]
Demonfork is scaling at 3.3% per tick but there are 25 seconds instead of 30 seconds.

This means it should be 4% per tick

**Comment by supasteed** [comment]
@GuybrushGit Not 200%
Score 0.52     Vote: [-] [+] by Asmodues, 1.0 year ago
That's not actually a 200% bonus- the damage portion, which is the lifesteal, gets 100%; the damage dealt by the lifesteal is what you gain back. 

Vanilla comment
http://web.archive.org/web/20071031064747/http://thottbot.com:80/i12621

**Comment by Mostprovidedlinks** [comment]
@guybrushgit since that says 100% shouldnt the need source be removed?

**Comment by Mostprovidedlinks** [comment]
Demonfork would be 20% coefficient meaning 4% each 5 second tick.

**Comment by GuybrushGit** [comment]
That post is referring to Skullflame Shield.
