### ISSUE TITLE
Blade Flurry aura removal

### ISSUE THREAD

**Issue by Slicy** [LightsHope/server#1294]
Blade Flurry (spell=13877) is occasionally getting removed from rogues before the end of its duration.

Common situations it has been noticed : 

- While fighting the waves of trash during the General Rajaxx encounter (possibly due to the friendly NPC's aura ?). This is the best situation to try reproduce the bug. It happens consistently.
- Sometimes on Grobbulus and Heigan.
- Fighting a hostile mob/NPC/player and a player of the opposite faction that is not flagged for PvP enters your attack range.

Could be the same source of issue as the SF bug (https://github.com/LightsHope/server/pull/1288) ?

**Comment by Sylvestersnr** [comment]
Blade Flurry also gets removed when:

- Fighting a hostile mob/NPC/player and a player of the opposite faction that is not flagged for PvP enters your attack range.

This was probably put in as a measure to prevent rogues from killing non-pvp flagged players, implemented while Nostalrius was still up, as you were able to kill non-pvp flagged players with the ability if they were close enough to you and the target you were attacking.
