### ISSUE TITLE
Elixir of Poison Resistance no longer shares a 2 minute cooldown with potions - implementation not functioning.

### ISSUE THREAD

**Issue by groeterud** [LightsHope/server#1311]
Ref: https://forum.lightshope.org/viewtopic.php?f=5&t=9138 

Quote: 

> Elixir of Poison Resistance no longer shares a 2 minute cooldown with potions

First thing I did was to go and test this (today jan 24th), my result: https://gyazo.com/0819ec217b165bd7cbe41d15f9747d27

Obviously this has yet to be implemented, and the 3s cd is not in effect.

**Comment by groeterud** [comment]
cba siting sources as you have already commited to the change, I'm simply stating that change is yet to be implemented correctly.

**Comment by Haiwuu** [comment]
Have you deleted your cache before testing?

**Comment by groeterud** [comment]
Yeah I didn't delete cache - closing issue.
