### ISSUE TITLE
Darrowshire - Dark Iron Deposits should spawn in world with 1.7.0 patch

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#135]
Original report by: Ripper007

Dark Iron Deposits ( id 165658) should spawn in Burning Stepps and Searing Gorge with patch 1.7.0.

Source : http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by GuybrushGit** [comment]
How many and in which locations?

**Comment by Memnok1** [comment]
The only thing i can find is this partial shot of BS/SG which has quite a few nodes listed 
http://mapwow.com/blog/2006/03/dark-iron-ore-locations-added.html

If it's legit is hard to tell and the map feature doesn't seem to work anymore.

**Comment by GuybrushGit** [comment]
Does Gatherer or other similar addons from later patches have any data for this?

**Comment by GuybrushGit** [comment]
http://web.archive.org/web/20100617084346/http://thottbot.com:80/o165658/z46
http://web.archive.org/web/20100721133623/http://thottbot.com:80/o165658/z51

**Comment by Memnok1** [comment]
I actually found some info in a gatherer addon from 2008
https://pastebin.com/zLKyZRV7 Here's a list of node ID's DI has 165658
https://pastebin.com/kj6L6VJ9 This is the locations of all deposits in BS and SG, from a file called DB_Wowheaddata.lua.
https://legacy-wow.com/tbc-addons/Gatherer/ Here's where i found the addon.

I hope those location numbers will help you somewhat i'm not sure what kind of coordinate system they use, and it probably doesn't show if it's above or below ground.

**Comment by Pisshead** [comment]
Proposal for respawn timers: It should act like it was the equivalent to mithril and truesilver. I'm not sure if I remember that correctl, but normal mining nodes have a respawn time of 30 minutes and rare ones like gold and truesilver had 2hs if I'm correct.
