### ISSUE TITLE
TWILIGHT TEXTS AND SETS DON'T DROP ON ANATHEMA

### ISSUE THREAD

**Issue by Ausser** [LightsHope/server#14]
It is fucking ABSURD that this issue has been broken and ignored for so long .

**Comment by mircontenti** [comment]
+1

**Comment by Elysis** [comment]
Yeah, we need this up and running asap. All the reputation we are losing due to the sets non existence is ridiculous.. making the grind so much harder for everyone..

**Comment by GuybrushGit** [comment]
Today's patch should have fixed this can you confirm?
