### ISSUE TITLE
QUEST Hidden Enemies - Part 2 of quest line NPC Gossip Glitch

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#142]
Original issue by: jestersson

On the second part of the quest Hidden Enemies, which requires you to take the Lieutenant's Insignia then speak with Neeru Fireblade and gauge his response, there seemed to be a glitch in the NPC's gossip text. Once on the quest I can click on the "You may speak frankly Neeru..." gossip bubble, however the next gossip bubble only says "[PH]..." ?
The correct text that should follow is:
Ahh, one of our own. It is good to see our numbers are growing so rapidly that I can no longer keep track of the faces of our members .

That fool Thrall thinks I am working hard to cleans the image of warlocks and prove we are his servants. Idiot! The Burning Legion will make ash of this entire world after it drains it completely.

"It is good to see the Burning Blade is taking over where the Shadow Council once failed."

Naive fool. The Burning Blade IS the Shadow Council! There are many cults and organizations under the Council's rule, but all of them are just extensions of their will. I may lead the Burning Blade, but I am still just as much a pawn to the Council as you are to me!

Look at the Searing Blade--most of them think they are becoming the next rising group of powerful warlocks that they will replace the Shadow Council.

"So the Searing Blade is expendable?"

Haha! Save for their leaders--the satyr, Bazzalan, and the warlock Jergosh--yes, all of them. That is why I constantly send Thrall's worshippers at them. It gives Thrall the impression that I am weeding out the evil in the bowels of his great city. The victory is in reality two-fold: kill Thrall's faithful and test the strength of those in the Searing Blade to see if they are truly worthy of joining me.

"If there is anything you would have of me..."

I will make it known to you. You are obviously already proving yourself in our ranks to become a lieutenant so quickly. Perhaps you can return to me later and I will have tasks for you. The council adores those skilled in the arcane, but servants of all kinds are always welcome, no matter their profession.

Comment by QAkvastskaft:
Here is a source for the gossip text from 2009: http://www.wowhead.com/quest=5727/hidden-enemies

Correct behavior should be to complete quest once all gossip has been clicked through

**Comment by henkethebenke** [comment]
The text "[PH] ..." seems to come from here: https://github.com/LightsHope/server/blob/development/src/scripts/kalimdor/orgrimmar/orgrimmar.cpp#L55

**Comment by brotalnia** [comment]
Fixed in https://github.com/LightsHope/server/commit/49727ee8135109efe492d3d20fe42dcc7cbb806d.
