### ISSUE TITLE
Dragon's Call dropprate off 

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#146]
Current drop rate is actually too high.
Drop rate for item 10847 should be set to 0.2% according to both

"
Looks like 0.2%
https://web.archive.org/web/20060719013203/http://wow.allakhazam.com:80/db/item.html?witem=10847

0.2% On Thottbot as well
http://web.archive.org/web/20061116052924/http://thottbot.com/?n=394701
"

**Comment by GuybrushGit** [comment]
Pretty small sample size, chance increases to 0.3 - 0.4 on later dates when the sample is larger.
