### ISSUE TITLE
Alterac Valley "Not Enough Players"

### ISSUE THREAD

**Issue by groovytulip** [LightsHope/server#15]
Server: Elysium
Battleground: Alterac Valley
Bug: Closes regardless of player count.

AV currently shuts down due to "Not Enough Players" after 5 minutes.  This is regardless of how many players are in the Battleground.  I was just in a match with 30H and 30A and the match shut down, granting 1 mark, and 300 rep to all players.

This occured @ 2:25PM PST on 10/19/2017.

Some player comments from discord:

Floyd - Today at 2:33 PM
@Ian I havent a github account. I just want to play Alterac Valley and I cant because the game closes in 5 minutse every time we get in , even with 30 people on both sides, and then people get free 300 rep when the game closes. People are going to get exalted in one day doing nothing but queueing up and then the game closing automatically.

**Comment by knasen88** [comment]
just joined AV and its been going for 35 mins. i dont think so

**Comment by ejt1** [comment]
@Floyd reported it only happens if either team falls below 30 people.

**Comment by groovytulip** [comment]
This is correct, the minimum required is 30A/30H for the game to remain active.  I am unaware if this was a change Blizzard made in 1.7, but it makes it nearly impossible for 1 AV game to take place outside of AV weekend.  Seems reasonable to have 20A/20H to make a game possible.  

But I suppose it depends on Vanilla intent, battlegroups were added for a reason.

**Comment by brotalnia** [comment]
It was changed to 20 per side minimum in patch 1.8.0.

**Comment by GuybrushGit** [comment]
Same as https://github.com/LightsHope/server/issues/63
