### ISSUE TITLE
There is no faction-wide notification whenever BGs start.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#16]
Title? :)

**Comment by knasen88** [comment]
that sounds like a funserver

**Comment by Sabre142** [comment]
Not blizzlike.

**Comment by Cabro** [comment]
I could swear i remember these from retail, not other fun server. Am I wrong?

**Comment by jsb** [comment]
I remember this feature only from emulated servers, never from retail Vanilla.

**Comment by Cabro** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.4.0

Weapon enchants are now shown at the character selection screen.

**Comment by brotalnia** [comment]
This is a private server feature, it was never on retail to my knowledge. You can enable it on your own server from the config.

> Battleground.QueueAnnouncer.Join
>     Enable queue announcer posting to chat at join
>     Default: 0 (not send)
>              1 (send to joined player only)
>              2 (send to all players)
> 
> Battleground.QueueAnnouncer.Start
>     Enable queue announcer posting to chat at BG start
>     Default: 0 (disable)
>              1 (enable)
