### ISSUE TITLE
Seal of Ascendance (part 2)

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#167]
Using Emberstrife to breathe on the unforged seal of ascendance doesn't turn it into forged seal. Quest can't be completed, UBRS key can't be obtained anymore.

**Comment by GuybrushGit** [comment]
Works in dev.

**Comment by Cabro** [comment]
Huh, gonna try it again on live servers tomorrow.

**Comment by Cabro** [comment]
Tried it again with WDB cleared and it worked.
