### ISSUE TITLE
Innkeepers selling wrong items.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#173]
Bear with me, I am aware that not all innkeepers have the same loottable, and that some may sell these items and some may not.
The correct way is that none of the following items should be sellable by ANY innkeeper.
- Hearthstone (you should get one each time you set a new home location)
- Love Token (this should be available only during Valentine's festival)
- Perfume Bottle (this should be available only during Valentine's festival)
- Cologne Bottle (this should be available only during Valentine's festival).

Related: #170

**Comment by wormrunner** [comment]
If I recall correctly the innkeepers in Vanilla did offer hearthstones for "sale" and you could pick one up without changing your hearth if you had deleted yours to make an extra slot (or by mistake).  Perhaps it is just the fogginess of the years, but that is what I recall.
