### ISSUE TITLE
Oozeling adds dropping large quantities of ore vein contents

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#175]
Original issue by: lotharboys

Currently on Darrowshire (1.8), the monster "Oozeling" (no DB entry available for this particular "Oozeling") is dropping incorrect items. The monster is spawned by "Devouring Ooze" (http://db.vanillagaming.org/?npc=1808), which are found in the "Weeping Cave" in the Western Plaguelands (coords to entrance around 65,68).

They are dropping large quantities of items that seem to have ore veins as their correct source. Killing 6 Devouring oozes and their Oozeling adds yielded 43 thorium ore, 13 truesilver ore, 2 aquamarines and 25 dense stones.

In the DB, the similarly named Oozeling monster in Sunken Temple (http://db.vanillagaming.org/?npc=8257) has its drops listed as similar: including thorium, stones and gems. It should be noted that databases are notorious for listing false drops on things like adds and containers and that the server drop tables are probably derived from them which could explain these incorrect drops.

Earlier, at some point, these oozelings dropped nothing, which is likely the intended behavior. The current items dropping can also be attributed to a mistake by common sense. One could grind these monsters (whose respawn time is also not long) and get much more thorium and stones than a character with 300 mining skill. This goes against the design of the game where the vast majority of materials that can be harvested from tradeskill nodes originate from said nodes, and these huge drop rates from unrelated monsters greatly reduce the exclusivity of the materials.

I don't have any high level characters on other servers to presently I can only confirm that this happens on Darrowshire.

**Comment by QAkvastskaft** [comment]
No loot should drop from mob id: 8257

Source top comment: https://web.archive.org/web/20060520164811/http://wow.allakhazam.com:80/db/mob.html?wmob=8257

**Comment by merlsti** [comment]
A friend of mine was in a party of 4 and killed these oozes for a couple of hours. All of them got their account perm banned from Lights Hope / Lightbringer WITHOUT any warning. So please fix this bug, and to other players I advice you to not take advantage of this stupid bug.
