### ISSUE TITLE
Leper Gnome wrong language

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#176]
Original issue by: borisy91

Leper Gnomes in Gnomeregan are speaking Trollish, instead of Gnomish/Common.

Comment by QAkvastskaft:
Both mob id 1211 and id 8503 should be speaking Gnomish or Gnomish binary

http://db.vanillagaming.org/?npc=8503#wh-comments

**Comment by GuybrushGit** [comment]
Gibblewilt should say a bunch of lines: http://www.bubblesofmischief.com/2012/03/28/gibblewilt/
