### ISSUE TITLE
Summoners Tomb/7D loot is dropping from fire elementals on the lava run path

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#177]
Original issue by: Pre-Elysium 

Doing regular lava runs hopping the lava path, we killed the 3 lava elementals on the bridge after 7D and Deathdealers Breastplate dropped. Here's a screenshot of the loot screen from the fire elemental:

https://i.imgur.com/untWPbp.jpg

Don't think theres much else to report about this bug? We didn't start summoners tomb event, it was a normal lava run. Sorry for the hastily submitted report, I'm mid lava run

Comment by QAkvastskaft:
Item id 11926 should be removed from all creature loottables
it should only drop from Chest of The Seven

https://web.archive.org/web/20061116093741/http://wow.allakhazam.com:80/db/item.html?witem=11926

**Comment by ohganot** [comment]
This doesn't only apply for the fire elementals. Hammer of Grace also has a 2% drop chance from Watchman Doomgrip, while it should only be looted from the 7D chest. http://db.vanillagaming.org/?item=11923

Alot of loot tables are bugged, it seems most loot tables are identical to db.vanillagaming.com which has alot of incorrect stuff.
