### ISSUE TITLE
Swiftdart Battleboots are green quality instead of blue.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#181]
http://db.vanillagaming.org/?item=13284
http://wowwiki.wikia.com/wiki/Swiftdart_Battleboots?oldid=560449

**Comment by druidish** [comment]
Depending on what server you're on these will have different stats.

Prior to 1.10 this was green. It got buffed and promoted to rare quality in 1.10

Pre 1.10
https://web.archive.org/web/20060207081042/http://wow.allakhazam.com:80/dyn/items/iname8.html

1.10
https://web.archive.org/web/20060527073350/http://wow.allakhazam.com:80/db/item.html?witem=13284

**Comment by Cabro** [comment]
Anathema.

**Comment by GuybrushGit** [comment]
Will be fixed once Anathema gets the progression patch.
