### ISSUE TITLE
Magus Ring is green quality instead of blue.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#182]
http://db.vanillagaming.org/?item=13283
http://wowwiki.wikia.com/wiki/Magus_Ring?oldid=560448

**Comment by druidish** [comment]
Depending on what server you're on these will have different stats.

Prior to 1.10 this was green. It got buffed and promoted to rare quality in 1.10

Pre 1.10
https://web.archive.org/web/20060208033741/http://wow.allakhazam.com:80/dyn/items/iname11.html

1.10
https://web.archive.org/web/20060410015604/http://wow.allakhazam.com:80/dyn/items/iname11.html

**Comment by Cabro** [comment]
Anathema.

**Comment by brotalnia** [comment]
Should be fixed when Anathema is updated to use the new progression system. There are two entries for the item in the database. It gets updated in 1.10.

**Comment by Cabro** [comment]
Isn't Anathema beyond 1.10?
