### ISSUE TITLE
Trueaim Gauntlets are green quality instead of blue.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#183]
http://db.vanillagaming.org/?item=13255
http://wowwiki.wikia.com/wiki/Trueaim_Gauntlets?oldid=560428

**Comment by druidish** [comment]
Depending on what server you're on these will have different stats.

Prior to 1.10 they were green. They got buffed and promoted to rare quality in 1.10

Pre 1.10
https://web.archive.org/web/20060307184715/http://wow.allakhazam.com:80/db/mob.html?wmob=9236

1.10
https://web.archive.org/web/20060516085040/http://wow.allakhazam.com:80/db/item.html?witem=13255

**Comment by Cabro** [comment]
Anathema.

**Comment by GuybrushGit** [comment]
Will be fixed once Anathema gets the progression patch.
