### ISSUE TITLE
Darrowshire - Missing warrior quest.

### ISSUE THREAD

**Issue by CykaBlyatIdiNahui** [LightsHope/server#186]
Horde warrior trainers Krang Stonehoof in Mulgore, Tarshaw Jaggedscar & 
Sorek in Orgrimmar don't appear to have the level 10 class quest "Veteran Uzzek".

**Comment by GuybrushGit** [comment]
They do have the quest, most likely you took the quest "Speak with Deathguard Dillinger" which closes off "Veteran Uzzek".
