### ISSUE TITLE
Hunter pets not attaining trained traits

### ISSUE THREAD

**Issue by Bulvaui** [LightsHope/server#192]
Hello, my hunter on Darrowshire  Snipeabul, is having problems when I train a trait like stamina, armor, resistances, growl, anything they don't add to pets stats/skills, and don't show up or anything, other hunters I have talked to recently have noticed the same thing. 
Thank you.

**Comment by GuybrushGit** [comment]
You need to open your spellbook and use the skill "Beast Training" to train pet skills.
