### ISSUE TITLE
Shimmering Gloves with no random stats when bought at vendor

### ISSUE THREAD

**Issue by Haldian** [LightsHope/server#195]
I just bought Shimmering Gloves (Level 17 BOE <Random enchantment> Cloth gloves) from Zizzek (Fishing Supplies vendor in Ratchet). The gloves have no stat on them other than just armor. After taking a look on the AH I can see that there are several versions of the "enchanted" glove available, which leads me to believe it may be an issue with purchasing it from a vendor rather than obtaining it as a drop.

Could not find any information on these gloves or Zizzek in any of the old databases for whatever reason, probably due to the somewhat insignificant nature of the npc and item. The item number on vanillagaming seems to be #6565 for whatever its worth.
![shimmering gloves bug](https://user-images.githubusercontent.com/33012725/31869545-c1d9dfc2-b776-11e7-9460-74665f3c0933.png)

**Comment by GuybrushGit** [comment]
Zizzek shouldn't sell this.
