### ISSUE TITLE
Black Dragonflight Molt not inside Hoard of the Dragonflight

### ISSUE THREAD

**Issue by bhgur84** [LightsHope/server#196]
I finished the entire quest chain for Kalaran Windblade in Searing Gorge, I opened my lootbox (Hoard of the Dragonflight), there was only 2 iron ore and 2 healing potions inside (i think), I need the Black Dragonflight Molt to get the quest Taste of Flame in Burning Steppes, which is the BRD quest, please help! Player name: Hildegunn

**Comment by bhgur84** [comment]
Quest done on Elysium

**Comment by Cabro** [comment]
The same happened to me on Anathema. It seems the drop chance is not 100%.
Or if someone else does the quest, but only loots the mold, the next one will not get one?

**Comment by Lictoria** [comment]
There are supposed to be other NPCs that drop the moot, but, AFAIK, they are not in game. GM in-game ticket.

**Comment by bhgur84** [comment]
@Cabro @Lictoria Found a work around for this issue, if you go back to the dragon quest giver who gives the quest for A Taste of Flame, he has an alternative quest where he summons a level 54 elite Frenzied Black Drake and you kill it and get the molt. Managed the work around, but still disappointed I did the whole chain in Searing Gorge for nothing

**Comment by Lictoria** [comment]
Are you sure that the alternative was offered originally? It sounds like it may be available for this kind of situation only?

**Comment by bhgur84** [comment]
@Lictoria I honestly am not sure... I'm pretty new to the game, but I did notice that the quest giver in the cave did have 2 "Taste of the Flame" pickup, one of them asked you to show proof from Kalaran Windblade (which I could not do) but then there was another Taste of the Flame which just summons the frenzied drake. It is also mentioned in 2nd comment on http://www.wowhead.com/item=10575/black-dragonflight-molt#comments

**Comment by GuybrushGit** [comment]
Chance to get it from the chest is set at 89% for some reason.
Should be 100%. 
https://web.archive.org/web/20070320203321/http://www.thottbot.com:80/i10575

**Comment by gabryatfendor** [comment]
The alternative was always in place in game, since you could accidentally destroy the mold. But the chance from the chest should be indeed 100%.
