### ISSUE TITLE
Hunter Tier2 pants data bug

### ISSUE THREAD

**Issue by ghostly001** [LightsHope/server#197]
![image](https://user-images.githubusercontent.com/33016216/31873160-0fa90bd8-b7f4-11e7-9a5c-bf213e70e301.png)
the pants are 2%hit now but i know this is 1%hit&1%crt on the database on the network 

also the dragonstalker`s shoulder. 1%hit is disappeared

**Comment by lovemonkeyz** [comment]
On Elysium this is the correct item stats. T2 stats were changed in 1.8

**Comment by ghostly001** [comment]
ok,thanks.
