### ISSUE TITLE
Sniper Scope(+7) is only adding +4 damage

### ISSUE THREAD

**Issue by LEGAZIZ** [LightsHope/server#200]
The +7 sniper scope is only adding +4 damage every auto shot instead of +7. Tested with this item http://db.vanillagaming.org/?item=15808 .

As you can see in the video below I'm shooting the Owl for 94 damage every autoshot without the scope and for 98 with the scope.

https://vimeo.com/239403839

**Comment by kallith** [comment]
These owl's have armor.

**Comment by LEGAZIZ** [comment]
yea im actually retarded
