### ISSUE TITLE
Reputation with frostwolf clan rolled back

### ISSUE THREAD

**Issue by vsarrg** [LightsHope/server#205]
After  a painful week of doing nothing but AV premades I finaly achieved got to exalted with AV. 
Minutes later the Elysium project R.I.P. 
After server got online again my reputation with frostwolf clan rolled back just enough to get me off exalted. I am not asking for beneficial favour. I am asking for justice. Gm jethri told me was to busy atm and I should report it with ticket later. I did it 3 days later and another gm get rid of me sending me here DON'T FOOLING ME pls!

**Comment by vsarrg** [comment]
My character name is Psoli.

**Comment by Hatredshit** [comment]
its the 1 hour Rollback we all got.

**Comment by vsarrg** [comment]
@Hatredshit OMG YOU ARE FUCKING GENIUS! Einstein is that you?

**Comment by Kolmarwow** [comment]
and lots of my guildies lost items from ZG, and i bet other people lost tons of items/rep too. it's simply too much work for the GMs to sort out everything that got rolled back in those 1-2 hours so it's basically tough luck, my guildies will simply have to get their items back from ZG and you will simply have to get your reputation back to exalted.

**Comment by QAkvastskaft** [comment]
Please see this link section III. Character/Currency/Item restoration for our policy regarding these types of issues

https://forum.lightshope.org/viewtopic.php?f=4&t=9
