### ISSUE TITLE
call to water shaman quest

### ISSUE THREAD

**Issue by stavish123** [LightsHope/server#208]
had competed up to quest 7 call to water and forgot to talk to water elemental quest to reget sapta islen will not give sapta and i have traveled back and forth droping quest regetting to try and fix with no avail

screenshots i have cant be uploaded becuase they are tga files? not sure how to convert 
account is kenan3213 shaman name stavish lvl 23

**Comment by Lictoria** [comment]
There are tga converters available, google.

This is probably an occasion that an in-game ticket for a GM to provide you with the item is needed

**Comment by GuybrushGit** [comment]
Can someone translate?

**Comment by Lictoria** [comment]
He asked about .tga files. They are available. Google.

You need to ask a GM to give you the item. 

Sentences can become obscure... and that one disappeared up its own rear end.

**Comment by brotalnia** [comment]
You can convert TGA to JPG or another format with Paint .Net, it's free.

**Comment by Cabro** [comment]
Wait for another shaman to do the quest and talk to the water elemental then, until it gets fixed :)))
