### ISSUE TITLE
Suntara Stones followup

### ISSUE THREAD

**Issue by Drraze** [LightsHope/server#209]
I had done the Suntara Stones escort quest in Searing Gorge, and it ends with the NPC dying and dropping an object on the ground that starts a followup. At the time I was not high level enough to start the followup, so I couldn't use it. Now when I came back with the right level, the letter is still on the ground, but I can't interact with it. Nor can I do the escort quest again from the NPC.
So this quest line bugged for me and I can't continue it. Some help would be appreciated.

**Comment by Lictoria** [comment]
In-game ticket.

**Comment by GuybrushGit** [comment]
Ask the GM to remove quest 3367 from your char (the escort).
