### ISSUE TITLE
Double Questgivers in Cernerionhold

### ISSUE THREAD

**Issue by griner1991** [LightsHope/server#210]
Seem like alot of questgivers for AQ items is double one lvl 56 and one 57, both have the q

**Comment by GuybrushGit** [comment]
Server name please.

**Comment by griner1991** [comment]
Anathema

**Comment by GuybrushGit** [comment]
Will most likely be fixed once Anathema gets the new database.

**Comment by GuybrushGit** [comment]
Today's patch should have fixed this can you confirm?

**Comment by griner1991** [comment]
I can confirm that there now only one of each :)
