### ISSUE TITLE
Darrowshire: Smoked Desert Dumplings suddenly "Not Available"

### ISSUE THREAD

**Issue by Colovion** [LightsHope/server#213]
Before switching over to Lights Hope these were implemented and working fine, but since the switch they give the "Not Available" error when you go to eat.

**Comment by brotalnia** [comment]
It was disabled in custom https://github.com/LightsHope/server/blob/development/sql/custom/elysium_disabled_spells.sql#L4.

**Comment by fgsfdss** [comment]
https://web.archive.org/web/20070303212027/http://www.thottbot.com:80/?it=20452
Comment describing the quest dating "1.4 years ago" at capture time of March 2007 (December 2005) suggests Dumplings should be available in 1.8, as 1.9 was released in January 2006.

Allakhazam comments and date added point in the same direction.
https://web.archive.org/web/20070114112202/http://wow.allakhazam.com:80/db/quest.html?wquest=8307

**Comment by Colovion** [comment]
Should be 1.8, yep. This old Nostalrius thread also: https://forum.nostalrius.org/viewtopic.php?f=6&t=16774 or http://wowwiki.wikia.com/wiki/Smoked_Desert_Dumplings
