### ISSUE TITLE
Missing animation for Atiesh staves and Brimstone Staff.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#220]
Brimstone Staff is missing the wing flap animation.
Atiesh is missing the crows animation.

**Comment by GuybrushGit** [comment]
Don't think this is a thing in vanilla.

**Comment by Cabro** [comment]
Yes it was, let me find video with animation for Atiesh

**Comment by Cabro** [comment]
https://www.youtube.com/watch?v=5Mr_ZbI8A34 however this is TBC
https://www.youtube.com/watch?v=QSgTWlyWMSI same...
https://www.youtube.com/watch?v=ZNHCkd5AvKI so hard to find movie frapsed in vanilla, dafuq

https://www.youtube.com/watch?v=DjIXawP-Mz4 - and here is the unicorn.

**Comment by brotalnia** [comment]
The spell id for the crows animation is 31796 but it does not exist in the vanilla client.

**Comment by Cabro** [comment]
It can be possible that they replaced some spells in TBC?
The last movie i posted was uploaded in November 2006, while TBC was launched in January 15, 2007.
Something doesn't add up.

**Comment by GuybrushGit** [comment]
2.0 came earlier and this could be from the PTR. I couldn't find any spell for this in vanilla so its impossible to implement.

**Comment by Cabro** [comment]
Fair enough.
