### ISSUE TITLE
Enrage/ Reckoning triggered by sitting

### ISSUE THREAD

**Issue by testear** [LightsHope/server#225]
Enrage and Reckoning can be triggered by recieving an Autohit-Crit through sitting. They should not.

http://blue.cardplace.com/cache/wow-paladin/1069149.htm

> Can I sit down to force a crit and gain a charge?
Charges will not generate off auto attacks or npc attacks by trying to sit down and force a crit. However, ability crits from physical abilities such as Sinister Strike, Hamstring, Auto-shot, Aimed shot, etc will generate a charge if you're sitting

it was implemented in 2.3.0 that Enrage can be triggered while Sitting.

http://wowwiki.wikia.com/wiki/Patch_2.3.0

> Enrage: This talent can now trigger while the Warrior is sitting.

> Blood Craze: This talent can now trigger while the Warrior is sitting.

**Comment by supasteed** [comment]
I cant find enrage on the blue.cardplace

**Comment by testear** [comment]
I answer to this cause i now have the time to waste it on this. Not that it matters anymore since Blizzard announced VanillaWoW and then we finally get Blizzlike and not just a speculation of it.

The Date when the Video you posted was made is unclear as the uploader clearly writes below it. The possibility exists that the Video has been made way earlier than my post.
Btw i find it hard to see anything of viable use in this Video and as far as i know the Spiders dont only do autoattacks.

On the most Servers i played on the Spells, Bloodcraze, Enrage, Reckoning and Redoubt have the same Proc-Flag so i guess they should all work the same way. 

Now i would like to watch at 2.0.1
http://eu.battle.net/wow/en/game/patch-notes/2-0-1
Fixed an issue where spells that proc while a player was standing would not proc if they were sitting or lying down. 

Now we move to 2.2.0
http://wowwiki.wikia.com/wiki/Patch_2.2.0
Reckoning: This ability can now trigger while the Paladin is sitting.
