### ISSUE TITLE
[Elysium] List of Paladin Bugs

### ISSUE THREAD

**Issue by supasteed** [LightsHope/server#227]
Old paladin bugtracker from elysium which never was entirely fixed
https://webcache.googleusercontent.com/search?q=cache:W9YDyUVqXesJ:https://github.com/elysium-project/server/issues/1976+&cd=1&hl=en&ct=clnk&gl=au

Hey guys, so there's a growing list of issues with Paladins that have both been on the server from the beginning and have been showing up in the last couple of patches. So here it goes:
1.Berserker buff in BGs is dropping off you when you Divine Shield or Blessing of Protection and it should not. If you are already bubbled and you pick it up, you still get it which is working correctly.
2.Lawbringer Set should be healing everyone in your raid in the current patch.
3.I believe Unstoppable Force had a knockback at this point of the game instead of a stun. Not exactly a paladin bug, but it triggers DR for Hammer of Justice if it's a stun.
4.Occasionally a Warlock Succubus Pet can Seduce you through Divine Shield.
5.If you already have Blessing of Freedom cast on you and you use a Gnomish Engineering Net, and backfires you will still net yourself even though you should be immune to the root.

EDIT: Added a few more I forgot about
 6. Mind Control sometimes affects you through Divine Shield and it shouldn't.
 7. Blessing of Sacrifice Damage still hits you through Divine Shield and it shouldn't.
 8. Gnomish Deathray's return damage hits you through Diving Shield and it shouldn't.

EDIT 2: September 15th, removed some of the above that have been fixed.
 9. Seal of Command has been stated to be scaling at 20% Spellpower and 29% Holy Power, this should not be the case. It should be 29% from all sources.
 10. I believe that Seal of Command is also not receiving any from Power Infusion which should increase all spell damage by 20%.

Phoosy wrote
If you already have Blessing of Freedom cast on you and you use a Gnomish Engineering Net, and backfires you will still net yourself even though you should be immune to the root.

#1815
#1167

All blessings are randomly bugging out on certain characters, I don't know what triggers it. But you just can't target them and use a blessing on them. This has happened to me with Divine Intervention as well.

#1937

Esfand
Reply: I haven't noticed anything like #1815Failed to load issue title suggests, but what #1167 is talking about citing 8:20 in the video actually happens to me all the time, and then I freedom out of the net. But if I already have freedom active it will throw me to them, but then it keeps me rooted even though I have freedom active.

gearelysium

Berserking Buff Issue: #2477
 

Unstoppable Force Issue: #2478Failed to load issue title

According to Spells.dbc, Repentance is flagged to interrupt auto attack. Do we have any evidence that this should be overridden?

**Comment by GuybrushGit** [comment]
Don't copy over the bad bug reports, otherwise they'll just remain open forever like on ely.
Some of these issues are invalid / been fixed / need sources / etc. 

Test them out and resubmit the valid ones on seperate issues, with the proper research if needed.
