### ISSUE TITLE
Anvilrage mobs stats and abilities

### ISSUE THREAD

**Issue by Mondota** [LightsHope/server#230]
There are several enemies that are bugged on Blackrock depths starting with the soldier's, and officers neaar Bael'Gar, Soldiers have an ability that traps you with a net for 4 seconds, but as they are right now they use the ability twice instantly traping you for 8 seconds, that is for each cast of each soldier on the group, now the officers when sheeped they keep attacking and using their abilitys while in sheep form.
Lastly the respawn time on the enemies of the room before magmus, where you have to get 2 torches to open the doors, well those enemies are respawning waaay too quickly, we had a party with 2 mages and a lock and we were barely able to clear a path to the braziers, they were taking about 8-10 seconds to respawn.

**Comment by GuybrushGit** [comment]
- Anvilrage mobs are using the wrong abilities: https://i.imgur.com/5QcKRjO.jpg
- Can't reproduce sheep bug
- Reservist respawn timers are set at 30 secs.

**Comment by ohganot** [comment]
https://www.youtube.com/watch?v=6NPg20GdNxk 1:20 You can see a mage getting netted by Anvilrage Warden. So Anvilrage Wardens should use a net and not the soldiers.

**Comment by dimefox** [comment]
Abilities are wrong for many of these guys, here's how they are set currently
```
+-------+---------------------+--------+--------------+--------+-------------------+--------+------------+
| entry | name                | spell1 | SpellName1   | spell2 | SpellName2        | spell3 | SpellName3 |
+-------+---------------------+--------+--------------+--------+-------------------+--------+------------+
|  8903 | Anvilrage Captain   |      0 | NULL         |      0 | NULL              |      0 | NULL       |
|  8892 | Anvilrage Footman   |      0 | NULL         |  19644 | Strike            |      0 | NULL       |
|  8891 | Anvilrage Guardsman |      0 | NULL         |  27581 | Disarm            |      0 | NULL       |
|  8898 | Anvilrage Marshal   |  17143 | Holy Strike  |  10293 | Devotion Aura     |  25292 | Holy Light |
|  8894 | Anvilrage Medic     |   8812 | Heal         |  10961 | Prayer of Healing |  10947 | Mind Blast |
|  8895 | Anvilrage Officer   |  25292 | Holy Light   |   1020 | Divine Shield     |      0 | NULL       |
|  8889 | Anvilrage Overseer  |      0 | NULL         |      0 | NULL              |      0 | NULL       |
|  8901 | Anvilrage Reservist |      0 | NULL         |      0 | NULL              |      0 | NULL       |
|  8893 | Anvilrage Soldier   |  14030 | Hooked Net   |  27991 | Sunder Armor      |      0 | NULL       |
|  8890 | Anvilrage Warden    |  24317 | Sunder Armor |  19644 | Strike            |      0 | NULL       |
+-------+---------------------+--------+--------------+--------+-------------------+--------+------------+
```
You can ignore Officer and Reservist because they are using EventAI and seem to have the right abilities there.


Damage values look wrong for a few too as mentioned in the other thread.
```
+-------+---------------------+----------+----------+--------+--------+-------------+
| entry | name                | minlevel | maxlevel | mindmg | maxdmg | attackpower |
+-------+---------------------+----------+----------+--------+--------+-------------+
|  8903 | Anvilrage Captain   |       54 |       56 |    372 |    479 |         254 |
|  8892 | Anvilrage Footman   |       51 |       52 |    375 |    462 |         234 |
|  8891 | Anvilrage Guardsman |       50 |       51 |    344 |    444 |         230 |
|  8898 | Anvilrage Marshal   |       54 |       55 |    800 |    854 |         248 |
|  8894 | Anvilrage Medic     |       51 |       53 |    441 |    534 |         238 |
|  8895 | Anvilrage Officer   |       53 |       54 |    689 |    760 |         244 |
|  8889 | Anvilrage Overseer  |       47 |       49 |    269 |    346 |         220 |
|  8901 | Anvilrage Reservist |       54 |       55 |     89 |    111 |         248 |
|  8893 | Anvilrage Soldier   |       52 |       53 |   1000 |   1100 |         238 |
|  8890 | Anvilrage Warden    |       49 |       50 |    276 |    356 |         226 |
+-------+---------------------+----------+----------+--------+--------+-------------+
```
Captains should have the highest damage range. Soldier looks like someone was messing around and forgot to change it back. Officer, Marshal and Medic also look high. Makes sense to scale those back to be in line with the rest.

Working on a PR now with some changes.
