### ISSUE TITLE
Seal of Wrynn stats bug

### ISSUE THREAD

**Issue by BorisOner** [LightsHope/server#231]
Hello
I am aware that this is may be a character specific bug (as far as I know), but the GM who answered my ticket, asked me to report the issue here.

I was completing the alliance quest chain that leads to the rare quality ring "Seal of Wrynn"(quest "An Audience with the King").
But when i turned in the second to last quest in the chain ("Brotherhoods End") to npc "Baros Alexston", he gave me an uncommon quality ring called "Seal of Wrynn" with +2 stamina and +6 spirit, and when I turned in "An Audience with the King" at npc "Lady Katrana Prestor", I did not get any item or upgrade.

I am aware that you are very busy, and I understand if this is not a priority compared to other bugs.
Thank you for all the hard work on this great project! We are enjoying it immensely!

Character:
"Cheesyho"
"Elysium PVP"
"Alliance"

**Comment by GuybrushGit** [comment]
This ring is only blue after patch 1.9. Elysium is on 1.7.
