### ISSUE TITLE
ZG Bugs

### ISSUE THREAD

**Issue by femdead** [LightsHope/server#232]
Just some questionable interactions noticed from running the place:

>Bloodlord Mandokir: places his "Threatening Gaze" (spell ID 24314) debuff on pets, then murders the pet's owner for acting while the pet is debuffed (even if the pet is phase shifted or set to "stay").
Correct behaviour: Only the debuffed character needs to cease action. Unsure if pets should be valid targets for him in the first place.

>Gurabashi Berserker: Drops aggro after using his AoE fear effect (spell ID 16508), even if the tank is immune to fear through fear ward or berserker rage.
Correct behaviour: resisted fears should not drop aggro. Only aggro drop should be his "Knock Away" ability.

>High Priestess Mar'li: Her aggro drop and web ability seem to be independant (NOT related to any potential aggro drop attached to changing forms similar to bat/snake bosses)
Correct Behaviour: Her "Enveloping Webs" ability (spell ID 24110) should wipe aggro on all affected targets.

**Comment by GuybrushGit** [comment]
- Bloodlord Mandokir: fixed already.
- Gurabashi Berserker: the AoE fear still goes out if the main target is immune
- Threat is properly dropping on players that get webbed and charged.

**Comment by marchelzo** [comment]
@GuybrushGit indeed the AoE still goes out if the main target is immune, but that doesn't seem to be OP's concern. Is it correct for the main target's threat to be reset even when they're immune to the fear portion of the spell?

**Comment by GuybrushGit** [comment]
Its a full threat reset, not just on those hit by the fear. This can be changed with evidence.

**Comment by marchelzo** [comment]
Well for example you take no damage from Razorgore's War Stomp if you have Free Action, which seems inconsistent with how this works. I don't have evidence though, I was just wondering if you're sure the current behavior is correct.

**Comment by Cabro** [comment]
It seems to me that the threat reset happens by default when the NPC casts fear, but it should not be that? Like, reset threat (even here i'm not sure, shouldnt it be just a threat drop for the duration of the fear?) for those that are actually feared.
