### ISSUE TITLE
Zul'gurub Tier Sets

### ISSUE THREAD

**Issue by kolokotrolis** [LightsHope/server#236]
Hello,this is a major issue.Until patch 1.11  some Zg tier pieces(not all of them) should have inferior stats and be of blue quality.Example:
https://web.archive.org/web/20060416011948/http://wow.allakhazam.com:80/db/item.html?witem=19845
https://web.archive.org/web/20060827062133/http://wow.allakhazam.com:80/db/item.html?witem=19845

Please fix it.

**Comment by QAkvastskaft** [comment]
Here are the sets before and after patch 1.11


Class | Before 1.11 | After 1.11
------------ | ------------- | -------------
Druid | [Before](https://web.archive.org/web/20051214023921/http://wow.allakhazam.com:80/db/itemset.html?setid=479)| [After](https://web.archive.org/web/20060722043424/http://wow.allakhazam.com:80/db/itemset.html?setid=479)
Hunter | [Before](http://web.archive.org/web/20060407103727/http://www.thottbot.com:80/?set=477)| [After](http://web.archive.org/web/20060902115651/http://thottbot.com:80/?set=477)
Mage | [Before](http://web.archive.org/web/20060416084148/http://www.thottbot.com:80/?set=482)| [After](http://web.archive.org/web/20061116205638/http://www.thottbot.com:80/?set=482)
Paladin | [Before](http://web.archive.org/web/20060128131038/http://www.thottbot.com:80/?set=475)| [After](http://web.archive.org/web/20060822110524/http://www.thottbot.com:80/?set=475)
Priest | [Before](https://web.archive.org/web/20051214052938/http://wow.allakhazam.com:80/db/itemset.html?setid=480)| [After](https://web.archive.org/web/20060721062830/http://wow.allakhazam.com:80/db/itemset.html?setid=480)
Rogue | [Before](http://web.archive.org/web/20060606232622/http://thottbot.com/?set=478)| [After](http://web.archive.org/web/20060908172639/http://www.thottbot.com:80/?set=478)
Shaman | [Before](http://web.archive.org/web/20060621075117/http://www.thottbot.com:80/?set=476)| [After](http://web.archive.org/web/20060822110536/http://www.thottbot.com:80/?set=476)
Warlock | [Before](http://web.archive.org/web/20060109075353/http://www.thottbot.com/?set=481)| [After](http://web.archive.org/web/20061116205626/http://www.thottbot.com:80/?set=481)
Warrior | [Before](http://web.archive.org/web/20060428102951/http://www.thottbot.com:80/?set=474)| [After](http://web.archive.org/web/20060716151524/http://www.thottbot.com:80/?set=474)

**Comment by GuybrushGit** [comment]
Fixed with https://github.com/LightsHope/server/commit/0f7d18e12a1dce3d66a41d3ff64437d51117941a
