### ISSUE TITLE
Gift wrapping presents for well deserved guildies:

### ISSUE THREAD

**Issue by Gandalf41265** [LightsHope/server#237]
Cannot gift wrap rare and epic items. Says you cannot wrap an already wrapped item- I guess its a skin issue? I believe all vanilla items were wrapable if they were not soulbound.

**Comment by GuybrushGit** [comment]
Wrapping epic items works. You're doing something different.

**Comment by Gandalf41265** [comment]
I personally tried it on a Blue item. It didnt work. My raid officer said she tried on a epic. I myself have not tried a epic yet.
