### ISSUE TITLE
Wrong Maraudon Zone-Out portal: Orange instead of Purple one

### ISSUE THREAD

**Issue by FireReaver** [LightsHope/server#238]
as stated in the title, after zoning out from mara (reset instance+/camp), you get teleported outisde the Orange Portal, instead of the correct one (Purple).
That hinders the farming of the instance since the path towards the scepter portal zone has become longer to reach now.

**Comment by GuybrushGit** [comment]
The fix for https://github.com/LightsHope/server/issues/9 applies to this as well.

**Comment by FireReaver** [comment]
Still not fixed
