### ISSUE TITLE
Druid t3 2 set bonus bugged

### ISSUE THREAD

**Issue by Tyraine** [LightsHope/server#239]
Druid t3 2 set bonus not working on full health targets, still not fixed on Anathema

**Comment by GuybrushGit** [comment]
Should be fixed with https://github.com/LightsHope/server/commit/608f27bff75d4ba3d4b10b24d5287786b206715a

**Comment by Niceguyone** [comment]
I think the fix was only applied on Elysium (where no one has T3) before the project change. I hope we will soon get in on Anathema as well.

https://forum.elysium-project.org/topic/56778-development-update-14102017/

**Comment by Tyraine** [comment]
"This patch is currently only live on Elysium"
, so yea it didnt get applied on Anathema
