### ISSUE TITLE
AQ 20 sets incorrect

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#241]
The AQ20 sets were updated to their final state in 1.11

Here are the sets before and after patch 1.11

Class | Before 1.11 | After 1.11
------------ | ------------- | -------------
Druid | [Before](https://web.archive.org/web/20060216193505/http://wow.allakhazam.com:80/db/itemset.html?setid=494)| [After](https://web.archive.org/web/20061128165359/http://wow.allakhazam.com:80/db/itemset.html?setid=494)
Hunter | [Before](https://web.archive.org/web/20060221181159/http://wow.allakhazam.com:80/db/itemset.html?setid=510)| [After](https://web.archive.org/web/20061129153924/http://wow.allakhazam.com:80/db/itemset.html?setid=510)
Mage  | [Before](http://web.archive.org/web/20060606232815/http://thottbot.com/?set=504)| [After](http://web.archive.org/web/20060922091516/http://www.thottbot.com:80/?set=504)
Paladin  | [Before](http://web.archive.org/web/20060407103909/http://www.thottbot.com:80/?set=506)| [After](http://web.archive.org/web/20060621075759/http://www.thottbot.com:80/?set=506)
Priest  | [Before](https://web.archive.org/web/20060415063840/http://wow.allakhazam.com:80/db/itemset.html?setid=508)| [After](https://web.archive.org/web/20060722043636/http://wow.allakhazam.com:80/db/itemset.html?setid=508)
Rogue  | [Before](https://web.archive.org/web/20060415055155/http://wow.allakhazam.com:80/db/itemset.html?setid=498)| [After](https://web.archive.org/web/20061129170111/http://wow.allakhazam.com:80/db/itemset.html?setid=498)
Shaman | [Before](http://web.archive.org/web/20060621075656/http://www.thottbot.com:80/?set=502)| [After](http://web.archive.org/web/20060920152113/http://www.thottbot.com:80/?set=502)
Warlock | [Before](https://web.archive.org/web/20060415055209/http://wow.allakhazam.com:80/db/itemset.html?setid=500)| [After](https://web.archive.org/web/20060720211252/http://wow.allakhazam.com:80/db/itemset.html?setid=500)
Warrior | [Before](http://web.archive.org/web/20060427174010/http://www.thottbot.com:80/?set=495)| [After](http://web.archive.org/web/20060716151550/http://www.thottbot.com:80/?set=495)

**Comment by brotalnia** [comment]
Resolved in https://github.com/LightsHope/server/commit/fb8030abddbdc7cf27e8d25d522c0264de860aa4.
