### ISSUE TITLE
Suggestion: Dynamic Blood of Heroes Spawn

### ISSUE THREAD

**Issue by lploom** [LightsHope/server#243]
During the lifetime of the server there's sometimes been dynamic spawns implemented for mobs/herbs/quest-items etc. This should also be applied to Blood of Heroes. 
As a player trying to get Blood of Heroes currently is almost impossible. Say there's roughly ~20 spawns with 2h respawn timer, that's 10 blood per hour. How many new players join every day that also need it? To illustrate my point: https://imgur.com/FftLlF2 (this was taken at the time of this writing)
Please make the spawn dynamic or faster.

**Comment by martinjlowm** [comment]
Coming: db72f82ffedab255b77c7ed43197f4ce826c5ca3

**Comment by lploom** [comment]
Nice!
What does "spawnFlags=12" mean?

**Comment by martinjlowm** [comment]
It's a bit mask of `1100` with the 3rd bit being random timer (respawn with a window) and the 4th bit which introduces the dynamic timer based on population.

https://github.com/LightsHope/server/blob/d357fff1cfd6a340d3660bf585cb2150d4d0477f/src/game/Objects/Object.h#L135-L143

**Comment by rickharrison** [comment]
@martinjlowm Shouldn't Blood of Heroes just have `0x08` applied for dynamic respawns? The way the code works in `GameObject` if the random flag is set it always uses that respawn timer if my understanding of the code is correct.
