### ISSUE TITLE
Zandalarian Hero Charm - Incorrect values (Elysium PvP)

### ISSUE THREAD

**Issue by Javelja** [LightsHope/server#245]
The Zandalarian Hero Charm on Elysium is currently the nerfed post 1.10 version with 25 damage / 50 healing per charge. Prior to 1.10, each charge held 35 damage / 70 healing.
Proof can be found in [this video](https://youtu.be/3VgtyF0r_OI?t=1m45s), which was filmed "shortly after AQ came out."
The [1.10 patch notes](http://wowwiki.wikia.com/wiki/Patch_1.11.0) tells the same story:
>Zandalarian Hero Charm: The damage and healing on this item have been reduced by 30%. Instead of granting 35 damage and 70 healing per charge, it now grants 25 damage and 50 healing per charge. Several Paladin spells, Starshards, and Lightning Shield were not consuming charges of this trinket. All those spells have been fixed. In addition, totems which now benefit from increased damage and healing will also consume charges (Healing Stream Totem, Searing Totem, Magma Totem, and Fire Nova Totem)

From the video:
![zhc](https://user-images.githubusercontent.com/30442901/31972971-b1710a8a-b923-11e7-80fb-42fcbade38cb.PNG)

Ingame screenshot (my WDB folder has been deleted):
![zhc ely](https://user-images.githubusercontent.com/30442901/31972916-77e06806-b923-11e7-9098-a2ce4c647c64.png)

**Comment by GuybrushGit** [comment]
This is not possible without modifying the spell and we don't do spell progression.

**Comment by Sabre142** [comment]
sadly not fixable
