### ISSUE TITLE
Dm East spawnpoint

### ISSUE THREAD

**Issue by Bajsmackan** [LightsHope/server#247]
Hey,

The spawnpoint when you come out from DM east in the tunnel is abusable by people standing in a group killing people as they spawn from DM east. Since it´s in the tunnel there is no way to reach your corpse, forcing people to use resssickness. You should change it back to where it was before (outside of DM West). 

Best regards,

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/9
