### ISSUE TITLE
Peter Galen not training Blue Dragonscale Leggings nor Green Dragonscale Gauntlets

### ISSUE THREAD

**Issue by ezmonyezlife** [LightsHope/server#249]
Hello, 

Peter Galen in Azshara is not training Blue Dragonscale Leggings nor Green Dragonscale Gauntlets

http://db.vanillagaming.org/?npc=7866#teaches-ability

Thank you

**Comment by GuybrushGit** [comment]
Works in dev.

**Comment by brotalnia** [comment]
Most likely the items don't exist in the current patch.
