### ISSUE TITLE
Demonic Rune shouldn't have class restrictions.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#258]
http://wowwiki.wikia.com/wiki/Demonic_Rune
http://db.vanillagaming.org/?item=12662

The other one, Dark Rune, is scripted good, with no class restrictions.

**Comment by Sabre142** [comment]
It was made so because warriors and rogues could use them.

**Comment by Cabro** [comment]
In what patch was that changed made? I can't find anything mentioning this.

**Comment by vindruvor** [comment]
from what ive heard, Rogues got energy from using Dark Runes on this server. So I get that was one of the reasons they decided to just disable them completely for rogues (idk about warriors)

**Comment by Cabro** [comment]
The that custom server has to be reverted and fixed so they don't get rage/energy.
It is a bug that they have a class restriction.

**Comment by supasteed** [comment]
Cabro is right
