### ISSUE TITLE
Missing events in combat log on opening doors.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#259]
https://youtu.be/kRXGQpMeKi0?t=1m03s
"You perform Opening on Shadowforge Gate." - at the end of the opening cast.

**Comment by GuybrushGit** [comment]
Every single opening spell in the client has the SPELL_ATTR_HIDE_IN_COMBAT_LOG attribute. No idea how that video was possible, maybe a bug from an earlier patch.

**Comment by Cabro** [comment]
Fair enough.
