### ISSUE TITLE
Detect Magic resisting puts you in combat.

### ISSUE THREAD

**Issue by dcish** [LightsHope/server#260]
If you case Detect Magic on a mob while out of combat, it normally will leave you out of combat if it doesn't resist. If it is resisted, the mob will aggro.

**Comment by Cabro** [comment]
Isn't this how it was? Along with Mind Soothe/Mind Vision resists?

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/23 fixes this.
