### ISSUE TITLE
Hallow's End quest(s) missing

### ISSUE THREAD

**Issue by Sabre142** [LightsHope/server#261]
http://web.archive.org/web/20060428142527/http://wow.allakhazam.com:80/db/quest.html?wquest=8312

This is not available currently, and most likely there are other Hallow's End quests that are missing.

Some of those quests can be found [here](http://web.archive.org/web/20060516054042/http://wow.allakhazam.com:80/db/item.html?witem=20557).

**Comment by brotalnia** [comment]
Nothing is wrong on development branch. The quest template exists, and so do the relations. You are most likely playing on Elysium, which is on patch 1.7, and Hallow's End was added in 1.8, which is why the quests are not available.

**Comment by Sabre142** [comment]
Ah, well I thought this discord post from a community manager also meant that quests would be included

![image](https://user-images.githubusercontent.com/26516348/32029206-c3751908-ba3e-11e7-928e-2cc346f9881b.png)
