### ISSUE TITLE
Hunter Pet issues

### ISSUE THREAD

**Issue by Asmindia** [LightsHope/server#265]
I have issues with my pet. I was only lvl 10 so I deleted the character and started over and still had the same problem. 

While doing the lvl 10 hunter quests my pet disappears and I cant revive it or get a new pet. When I hit dismiss it says I don't have a pet, call pet does nothing and when I try to tame a new pet it says that I have one already.

Anathema server

**Comment by Lictoria** [comment]
When you start the hunter level 10 quests, as soon as the quest says completed i.e. you have tamed the animal, dismiss it at that time. If you fail to do so, logging off for about 10 minutes after turning the quest in usually works.

**Comment by twatllama** [comment]
I have a similar issue, but I have long dismissed the Lvl 10 quest pets and caught two unrelated ones. I now cannot use pets, cannot summon existing one, cannot tame a new one, or swap to a new pet in my stable.

**Comment by Asmindia** [comment]
I found that if you abandon the quest and redo it, then as soon as you tame the pet dismiss it it works.

**Comment by twatllama** [comment]
There is no quest to "abandon", I have completed all parts of it. These pets are completely unrelated to the quest. They are new pets I attained after completing the quest using the Tame skill, not the taming rod. 

    On Tuesday, October 31, 2017 5:18 PM, Asmindia <notifications@github.com> wrote:
 

 I found that if you abandon the quest and redo it, then as soon as you tame the pet dismiss it it works.—
