### ISSUE TITLE
Hakkar disappear

### ISSUE THREAD

**Issue by Ragmach** [LightsHope/server#271]
Hi everyone.
We havent killed Hakkar the day before and today we entered the dungeon with the same group and what a surprice we have. NO Hakkar on the top of a pyramid. So can u please check what was it? It very sad for everyone to clear the bosses for the Hakkar to finally kill it and he is not at his place. Thanks.

**Comment by thepparker** [comment]
Did you do this with any PUGs? I believe someone may have stolen your raid lockout.

**Comment by Ragmach** [comment]
It is a guild-raid run. It cant be. Earlier i wrote to Gms on th server and i think they can check it, so they advice me to go here with our problem.

**Comment by LHGemt** [comment]
Was the trash before him alive?
How long did you wait for him? If you reset him by running down the pyramid he will respawn again after 5 minutes. Is there a chance someone pulled and reset the boss?

**Comment by Ragmach** [comment]
We came to his place, trash was alive but no Hakkar. Afrer this we went to alive Mandokir and killed him. Than we went to check Hakkar place again and still there is no Hakkar. RO
