### ISSUE TITLE
Candy Corn, Candy Bar and Lollipop not restoring said HP value.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#273]
They all are supposed to restore 75% HP in 25s, but what you get from them is far from it.

http://db.vanillagaming.org/?item=20388
http://db.vanillagaming.org/?item=20389
http://db.vanillagaming.org/?item=20390

**Comment by GuybrushGit** [comment]
Works in dev.

**Comment by Cabro** [comment]
Is it restoring on dev 75% of base HP or 75% of all HP? Because it should be the last one.

**Comment by GuybrushGit** [comment]
Tested with flask of titans on, restored 75% of all.

**Comment by Cabro** [comment]
Ok then, i must be imagining things :(
