### ISSUE TITLE
More Hallow's End bugs

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/server#276]
* Apple bob: There seem to be multiple instances of the tub on top of one another, and it gives an error of "That is already being used" when clicked. When I finally managed to get an opening, there was no loot window and I could not click it again. Tested twice with the same result.

* Trick or Treat: The dialogue option is now there, I had an animation of getting tricked (the overhead skeleton) but did not receive any (de)buff nor a candy bag.

Both of these tested on a level 10, might be a possible cause.

**Comment by GuybrushGit** [comment]
Which innkeeper?

**Comment by fgsfdss** [comment]
Orgrimmar.

**Comment by GuybrushGit** [comment]
I think the stacked Apple barrels are intentional, so when you loot you don't see it despawning and instantly respawning.
