### ISSUE TITLE
 /camp is broken

### ISSUE THREAD

**Issue by Alucard600** [LightsHope/server#280]
/camp no longer moves player to the front of the instance's entrance

**Comment by brotalnia** [comment]
I thought /camp is the logout command?

**Comment by Alucard600** [comment]
Did just logging out move players to an entrances instance?
Regardless /camp or logging out used to move players to the instance's entrance. Was it not suppose to?

**Comment by Cabro** [comment]
I don't remember this from retail. Only move to entrance if there was a soft reset meantime.

**Comment by vindruvor** [comment]
Were you alone in the instance?

**Comment by Fiskehatt** [comment]
I used `/camp` yesterday while in a group inside an instance: it worked fine and I got teleported to the entrance. When you are not in a group, I think you have to reset the instance first to get to the entrance:

```
/script ResetInstances();
/camp
```

**Comment by Alucard600** [comment]
Back on Elysium /camp was all I needed while solo grinding RFD but that appears to have changed. Maybe logging was bugged and caused everyone to port back to the instance entrance and it got fixed.

Fiskehatt it worked like a charm thank you. Problem resolved. sorta.

**Comment by vindruvor** [comment]
ive always had to reset instance before I camp when solo, or invite some1 to group and then camp
