### ISSUE TITLE
Frostmane Hold "Fully Explore Frostmane Hold" not working 

### ISSUE THREAD

**Issue by turnerj22** [LightsHope/server#281]
Explore Frostmane Hold quest not currently working. You can run though entire cave without it popping

**Comment by Lictoria** [comment]
it does work, the trigger point is far from obvious.

**Comment by Cabro** [comment]
What @Lictoria said, the trigger point is beyond the middle of the cave. Just clear everything there :)

**Comment by turnerj22** [comment]
I cleared the entire cave with a friend and walked all over the cave. I'll take your word for it, got  some good xp by grinding the trolls in there anyway :) Thanks for the quick response I appreciate the hard work.

**Comment by Cabro** [comment]
I completed this quest like last week. It works, just not where you usually get it on other private servers.
