### ISSUE TITLE
Raid ID bug

### ISSUE THREAD

**Issue by NotoriousMac** [LightsHope/server#282]
Was given a Raid ID upon entering raid instance. Having not killed any bosses I should not have received a raid ID. Tried to join my guilds run and was not able to because I had the wrong ID. One should not be locked to a Raid till after you kill a boss.

**Comment by GuybrushGit** [comment]
You don't need to kill any bosses yourself to get saved. If you enter an instance with bosses already dead you will get saved to it, all it takes is grouping with another saved person.

**Comment by brotalnia** [comment]
Shouldn't there be a warning message where you have to click accept or leave the dungeon? Or was that added later?

**Comment by Cabro** [comment]
That was added in wotlk @brotalnia
