### ISSUE TITLE
Paladin cant 'Divine Shield' and pick herbs

### ISSUE THREAD

**Issue by alfredSss** [LightsHope/server#283]
Hi, since the swap over from elysium to lights hope paladins can no longer cast divine shield / protection and pick herbs, while using blessing of protection does allow it. I was told in game by a gm to research whether they could do this in retail vanilla and I have been told by people that played then that this was possible (was also told that they could bubble and open chests too, something that didn't work on elysium either). 
Thank you

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/228

**Comment by alfredSss** [comment]
Hi the post you reference is a different issue, this is relating to divine shield, not blessing of protection. Divine shield is a self cast immunity to physical and magical damage, and we should be able to pick herbs while it is up. This worked fine up until the move to lights hope. Currently get an error message saying 'you can't do that while immune'
