### ISSUE TITLE
The quest "Kitchen Assistance" can't be done.

### ISSUE THREAD

**Issue by SubbyDK** [LightsHope/server#292]
The quest "Kitchen Assistance" you get fra innkeeper "Calandrath" in "Cenarion Hold" can't be done.
Every time I try to make the 10 x "Smoked Desert Dumplings" for her, I get this message "The spell is not available to you"

If it have somthing to do with this:
https://github.com/LightsHope/server/issues/213

Then the quest was added in patch 1.11.1.10958
http://www.wowhead.com/quest=8317/kitchen-assistance

Regards,
Subby - Darrowshire

**Comment by samercyn** [comment]
Do not use wowhead for patch information. Wowhead did not exist until June 2006 when patch 1.11 had just come out.

Kitchen assistance came in with patch 1.8
http://wowwiki.wikia.com/wiki/Quest%3AKitchen_Assistance

**Comment by SubbyDK** [comment]
Will remember that samercyn, thanks ;)

But it's still patch 1.8 we are running now right ?
So the quest is supposed to be in the game and you are supposed  to make the "Smoked Desert Dumplings"
