### ISSUE TITLE
Weapons of Choice

### ISSUE THREAD

**Issue by Sunlancer** [LightsHope/server#295]
The quest titled Weapons of Choice, for horde, given by Tatternack Steelforge, with the objective to obtain Razormane Backstabber, Charred Razormane Wand, and Razormane War Shield, is unable to be completed regardless of whether or not you have obtained each of these items. 

I have attempted moving the items to the first backpack slots, relogging, disabling addons, and deleting the folders WDB and WTF, and none of these were the problem, so I can only assume that this issue is in fact server-sided

**Comment by Sabre142** [comment]
Put them in your bank, log out, delete WDB, log in, withdraw, see if that works.

**Comment by Sunlancer** [comment]
I can confirm that performing this sequence of tasks is a sufficient fix, thank you.
