### ISSUE TITLE
Arena Grand Master

### ISSUE THREAD

**Issue by Gandalf41265** [LightsHope/server#3]
After completing the Arena Grandmaster quest in STV (Gurubashi), and then looting the chest in an attempt to get a second Arena grand master trinket, all the chest items are visible except for the trinket. And the chest cannot be emptied. This has been a known issue on private servers.

**Comment by Sabre142** [comment]
Yeah, in order to complete it currently you need to save up 24 chest trinkets and hand them in at one time.

**Comment by Gandalf41265** [comment]
That's great! But, that means it isn't working like it is suppose to, there fore it is a bug and therefore the reason for my post..... : /

**Comment by GuybrushGit** [comment]
Any source from vanilla?

**Comment by GuybrushGit** [comment]
>It does share a cooldown...however wearing 2 gives you +2% dodge which is why they would wear two.
>http://web.archive.org/web/20070228153421/http://wow.allakhazam.com:80/db/item.html?witem=19024
