### ISSUE TITLE
[Gnomeregan] Dark Iron Ambassador doesn't seem to spawn.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#308]
I did quite a lot of this instance and i've never seen this rare. Am i that unlucky?

**Comment by Ripper007** [comment]
I've farmed Gnomer on Nostalrius, Old Elysium PVP and  Darrowshire - never saw the NPC in more than 100 instances.

**Comment by QAkvastskaft** [comment]
People has items from this rare spawn on all realms
https://legacy-logs.com/Vanilla/Armory/Items/Anathema/9457
https://legacy-logs.com/Vanilla/Armory/Items/Darrowshire/9457
https://legacy-logs.com/Vanilla/Armory/Items/Elysium/9457

However the spawn chance should be double checked and if found to low set to 15% as most other instance rare spawns

**Comment by gabryatfendor** [comment]
Confirmed that he spawn: we defeated him yesterday

**Comment by QAkvastskaft** [comment]
Spawn should be 30%

**Comment by Cabro** [comment]
Ye i also saw it spawn. Elite though, not rare elite. that's another bug :)
