### ISSUE TITLE
Slow Movement Effects Not Applying on Fleeing Mobs

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#331]
When an NPC Humanoid attempts to flee due to low health, any form of movement slowing effect does not hamper the speed at which they flee - they completely disregard the effect, regardless of strength. This is occurring across all 3 servers (and given no core changes related to this type of movement, presuming probably PTR too). Hamstring, Crippling Poison, Frostbolt slow, etc. all do not slow down mob fleeing speed.

I'm working on getting specific examples of this being a Blizzlike function in general for Vanilla, so for now here's what I've got handy without watching videos -

Comments Section:

    Mobs that run away before they die are a lot easier to catch and kill
    if they're Hamstrung. This also prevents them from bringing in adds.
    Try to hit them with Hamstring when they're near the flee point so it
    wont time out before you can kill them. Hamstring is a waste on a mob
    that wont run away. Of course, another use for Hamstring is if you
    realize that you aren't going to win a battle and you want to run
    away, or want time to use a bandage.
    Yes one of the uses is to stop people running away and bringing back 3
    or 4 adds. not a bad skill but only usable in a couple of places
    Remove it at your peril. There are many places in the game where
    controlling the 'runaway' speed of mobs is a life or death matter, par-
    ticularly in instances of all kinds. Many wipes in instances could have
    been prevented if the tank-warrior had been bright enough to cast a
    hamstring on their mob before it ran off to get 5 more elite nasties
    and bring them back to the party.

    I've taken a warrior up to level 52, and use hamstring all the time.
    You learn quickly which mobs will stay and fight to the death, and
    which ones will bolt when their life gets low. Life is just so much
    easier when you slow them down with hamstring before they go
    walkabout on you.

Source: http://www.computergamesforum.info/c754/Hamstring_1_jVlZ.html

    Intensely irritating due to their speed. They're liable to sprint into any fight at any time from considerable distance, and they're difficult to anticipate and thus avoid/pull.
    Like most murlocs they also flee below 20% (?) hp, but their speed makes them impossible to keep up with - so if you can, slow them down when their health gets low (hamstring, frostbolt, etc.)

Source: http://db.vanillagaming.org/?npc=126#wh-comments (TBC era patch)

    The Entire Article on Hamstring

Source: http://vanilla-wow.wikia.com/wiki/Hamstring
(Yes, yes, I know, more for my reference than anything)

For my reference: it appears a lot of PServers do not have this functionality working properly.
This was noticed at least as far back as February, no clue why this hasn't been mentioned yet.
https://elysium-project.org/bugtracker/issue/2423
https://www.reddit.com/r/ElysiumProject/comments/682elu/snare_effects/
https://www.reddit.com/r/ElysiumProject/comments/5w1z24/other_rogues_notice_riposte_not_lowering_dmg_from/de740is/ (Specifically about Crippling Poison)

**Comment by jsb** [comment]
A fix for this would be really appreciated. This bug makes Crippling Poison significantly less useful in solo PvE.

**Comment by berillis** [comment]
Also when a slow is applied to a fleeing monster, it should change direction.

**Comment by Cabro** [comment]
I noticed that the mobs don't regain their normal flee speed once the slowing debuff is over. It's stuck on slow even without debuffs. :)
