### ISSUE TITLE
Quest Egg Collection is made trivial

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#335]
http://db.vanillagaming.org/?quest=4735#wh-comments

Several bugs:
1 - you can use the collectronic from very far away from eggs, and you collect them and get quest completion. You should have to freeze them first, so they don't spawn whelps. Solution: make the range for collectronic smaller.
2 - the eggs don't disappear when you collect them. They should.

The combo of these 2 bugs make the quest super easy, stay in door and use collectronic 8 times and presto, quest completed!

**Comment by brotalnia** [comment]
Fixed in https://github.com/LightsHope/server/commit/ec69f0102c2333ef2af217f7a66899c647f51d03.
