### ISSUE TITLE
Eunice Burch bugged trainer.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#336]
Porting over from the other tracker, sorry if it's already fixed.

This is a cooking trainer in UC. It's bugged in the way that it offers to teach you Basic Campfire, without having cooking skill in the first place. If you do train Basic Campfire, the other recpies turn green but you can't actually train them, because no cooking skill.
It shouldn't have the option to teach Basic Campfire by itself, it should be automatically learned when you train Apprentice Cooking as far as i know.

https://i.imgur.com/HHmbJy9.png basic campfire should not be in this list

**Comment by brotalnia** [comment]
It was already fixed.
https://github.com/LightsHope/server/blob/119dac1e342226556168b0cf73945ee0b405b961/sql/migrations/20171011223552_world.sql
