### ISSUE TITLE
Can't resummon Mor after a wipe.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#341]
Was in LBRS earlier. Pulled Mor too early and players were not ready, so we wiped. After we came back, the brazier was placed but the boss was a no-show.
Probably all other D2 summon bosses have this same bug.

**Comment by GuybrushGit** [comment]
Its normal that you can't resummon but the despawn timer should be longer than 60 seconds.

**Comment by Cabro** [comment]
Great, despawn timer should be really long in this case.
