### ISSUE TITLE
Masterwork Target Dummy has no effect on spawn or in time.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#343]
Just porting over from other tracker, sorry if it's already fixed.

1 - Unlike Target Dummy and Advanced Target Dummy, which have a taunt on spawn, this one doesn't.
2 - Also from the spells i see in database, it should have a 3 second periodical of giving threat to mobs. This doesn't work either.

At this point this craft is 100% useless.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/37
