### ISSUE TITLE
[Database] There are mobs that actively CAST Dazed.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#345]
Dazed should be a result of being attacked from behind only or getting attacked with hunter's speed aspects.
This spell should never be cast actively by a mob.
You can get dazed from mobs that you are facing.
Example: http://db.vanillagaming.org/?npc=6233
http://wowwiki.wikia.com/wiki/Daze

**Comment by Fiskehatt** [comment]
Duplicate #307 :)
