### ISSUE TITLE
An Imp's Request

### ISSUE THREAD

**Issue by zebromil** [LightsHope/server#347]
As a level 52 Warlock, i still cannot pick up warlock class quest named An Imp's Request (which should be now available for me at my class trainers in both Stormwind and Ironforge), nor the quest Hot and Itchy (from NPC Impsy in Felwood), which serve the same purpose and both lead to continuation with final quest of the chain being warlock dungeon quest to Sunken Temple. Level required posted on reliable sources online is said to be 52 for the first quest of the chain (An Imp's Request/Hot and Itchy) and 50 for the later steps of the chain (The Wrong Stuff ->Trolls of a Feather)

(was sent here by GM tellin me i encountered a bug)

http://db.vanillagaming.org/?quest=8419 - An Imp's Request
http://db.vanillagaming.org/?quest=8420 - Hot and Itchy

**Comment by GuybrushGit** [comment]
Server name.

**Comment by zebromil** [comment]
Elysium (PVP)

**Comment by GuybrushGit** [comment]
Elysium is on 1.7. This quest is added on 1.8.
