### ISSUE TITLE
Divine Shield should not prevent Maexxna's Web Spray

### ISSUE THREAD

**Issue by fidbugs** [LightsHope/server#348]
Copying discussion. TLDR - precasting "bubble" should not prevent you from being consumed by Web Spray.

 webdkpthroaway commented 12 days ago

Paladins can prevent Maexxna's web spray by using Divine Shield, allowing them to heal throughout the raidwide stun. The wiki mentions that the only ways around Web Spray are Flask of Petrification and Divine Intervention. I have watched several Maexxna vids and there's no paladins bubbling to prevent Web Spray.

Being able to circumvent the most important mechanic of the fight so easily makes little sense.

Wiki text

Web Spray: Cast every 40 seconds incapacitating everyone for 8 seconds, and dealing 1750-2250 Nature damage. This ability cannot be resisted, and the only way to avoid it is to be dead, have Flask of Petrification, have Divine Intervention, or be already incapacitated by Web Wrap.

fidbugs commented 12 days ago

I am unable to find any video that shows paladin preemptively using bubble(Divine Shield), to avoid Web Spray.

On contrary i found a video of mage trying to do the same thing, but Web Spray goes thru.

https://youtu.be/LDEP14-uCAs?t=191

One more indicative thing is that it uses same flags as Digestive Acid from C'Thun, which also cant be avoided by buble.

http://www.wowhead.com/spell=29484/web-spray

http://www.wowhead.com/spell=26476/digestive-acid#changelog

Also having buble as counter to Web Spray would completely null this game mechanic, and whole fight as a "tank test". Not to mention shift the balance highly in favor of Alliance compared to Horde.

Its quite reasonable to assume that if Divine Shield could counter Web Spray, it would have been common knowledge and elaborated in Naxx guides(as is it mentioned almost everywhere when this ability counters boss game mechanic).

On the other hand, it is mentioned in same page on wow wikia that "For the second Web Spray have a healer with SS or Divine Shield ready. Shamans with Reincarnation also do. " - it dosent make much sense since there is no mention of bubble when talking in general about Web Spray and how to counter it.

http://wowwiki.wikia.com/wiki/Maexxna_(original)

Also i found one reference, which states that you can bubble the Web Spray from the time of WotLk, but at same time, statements like that were in declared as not true. There is space for interpretation since it states "You cant bubble out from spray while in it." - ergo, there is possibility of precasting it to avoid. But IMHO that is highly unlikely since there is again no video material of it, no other mentions in guides/tactics, and obvious counter to game mechanic(which should by the time of WotLK be well known).

http://www.mmo-champion.com/threads/634562-Problems-in-10man-Naxxramas-Is-it-too-hard-Need-help!

http://www.dslreports.com/forum/r21661220-Archivis-Guide-to-Naxx-10-man

Just my 2 cents on topic.

**Comment by Krotux** [comment]
why are you talking about game balance? Of course divine shield protects the paladin from everything, as it should.
