### ISSUE TITLE
nefarian corrupted totems

### ISSUE THREAD

**Issue by grimmochov** [LightsHope/server#350]
reposting from elysium github.

currently, you are able to hit shaman totems with any aoe. whirlwinds, hellfire, arcane explosion etc. they should be immune to it forcing people to deal with them individually and currently makes it very simple to just have the shamans stand together with a warlock handling it on his own. every old strategy post that can be found via google mentions having single target dps handle them. a wowwiki link for good measure
http://wowwiki.wikia.com/wiki/Nefarian_(tactics)#Phase_2

and a few timestamped videos showing the melee coming out to deal with them
https://youtu.be/G8LZU9l6mtM?t=550

https://youtu.be/z22sbP9n1TU?t=598

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/36
