### ISSUE TITLE
Improved Ambush (tooltip?) bug

### ISSUE THREAD

**Issue by nydokade** [LightsHope/server#351]
the additional critchance is not showed in the tooltip. its still the base critchance (for example 29% instead of that + 45% from talents)

im not sure if its only tooltip bug or it doesnt work completly. i tested it in duels and it doesn feel like 75% crit.

**Comment by GuybrushGit** [comment]
Tooltips are client side. Nothing we can do about them.

**Comment by nydokade** [comment]
and what about the issue that out of 20 ambush only 5 critted? i will do later a test with 100 ambushes to get a more accurate testing, please dont close this yet.

**Comment by gotmilk0112** [comment]
Even with things like Improved Overpower giving the ability a total of around 72% crit for me, it still frequently doesn't crit. 75% =/= 100%.
