### ISSUE TITLE
Wrong amount of Agent Dawn reputation.

### ISSUE THREAD

**Issue by SubbyDK** [LightsHope/server#352]
The quest "Felstone Field Cauldron" in "Western Plaguelands" is supposed to give 25 reputation with Agent Dawn when you complet it.
Source:
http://db.vanillagaming.org/?quest=5218
But it only give 9 reputation.
Proof:
![skaermbillede 2017-10-27 21 07 50](https://user-images.githubusercontent.com/31448358/32121186-d9c986e4-bb5b-11e7-8335-4145a4a32904.png)
![skaermbillede 2017-10-27 21 08 10](https://user-images.githubusercontent.com/31448358/32121194-e3e1de7e-bb5b-11e7-8806-a2c719e31cbe.png)

Regards, 
Subby - Darrowshire

**Comment by SubbyDK** [comment]
Dalson's Tears Cauldron
http://db.vanillagaming.org/?quest=5221
That quest gives 15 reputation, was supposed to give 25 reputation.
![skaermbillede 2017-10-27 21 50 22](https://user-images.githubusercontent.com/31448358/32122665-6e6c4994-bb61-11e7-9af0-ca95e11348a1.png)

Writhing Haunt Cauldron
http://db.vanillagaming.org/?quest=5224
That quest gives 15 reputation, was supposed to give 25 reputation.
![skaermbillede 2017-10-27 21 57 42](https://user-images.githubusercontent.com/31448358/32122830-217342e0-bb62-11e7-8539-34c637e86052.png)

Gahrron's Withering Cauldron
http://db.vanillagaming.org/?quest=5227
That quest gives 15 reputation, was supposed to give 25 reputation.
![skaermbillede 2017-10-27 22 07 58](https://user-images.githubusercontent.com/31448358/32123211-a94b0dbe-bb63-11e7-9a1a-7cae85523e0d.png)

**Comment by GuybrushGit** [comment]
Reputation gains scale with level. You won't get the full gain from a 55 quest on a level 60.

**Comment by QAkvastskaft** [comment]
Source confirming 25 rep is the correct one (http://db.vanillagaming.org is not a valid source): 

https://web.archive.org/web/20060516063542/http://wow.allakhazam.com:80/db/quest.html?wquest=5218
https://web.archive.org/web/20060524215846/http://wow.allakhazam.com:80/db/quest.html?wquest=5221
https://web.archive.org/web/20060111114713/http://wow.allakhazam.com:80/db/quest.html?wquest=5224
https://web.archive.org/web/20060111124111/http://wow.allakhazam.com:80/db/quest.html?wquest=5227

**Comment by Sabre142** [comment]
It's because you're level 60

**Comment by henkethebenke** [comment]
Fixed in #404
