### ISSUE TITLE
High level players are not being properly credited the right amount of faction reputation

### ISSUE THREAD

**Issue by Nelythia** [LightsHope/server#354]
If you are above the level range for a quest that you complete, you do not get the full reputation reward.

For example if you complete a quest that gives you +75 reputation during its level range, you get +75 reputation.
If you in fact complete it outside of the level range, lets say as level 60, you don't get +75, you get around 10 or 20 reputation.

This is a blizzard confirmed issue which was patched with the release of TBC
http://wowwiki.wikia.com/wiki/Patch_2.0.1

'Fixed an issue where high level players were not being properly credited the right amount of faction reputation.'

**Comment by averes2** [comment]
I don't believe this is an issue, and even the TBC fix did not remove reputation penalties: http://wow.allakhazam.com/wiki/Reputation_Guide_%28WoW%29#What_is_Reputation_Reduction? this looks like it was written pre 2.4.3

**Comment by GuybrushGit** [comment]
Reputation penalties for high levels are a thing. See this 1.9 patch note for example:
>All versions of the quests "A Donation of Wool," "A Donation of Silk," and "A Donation of Mageweave" have had the level of the quest raised so that higher level characters performing them will be able to receive the full reputation gain.
