### ISSUE TITLE
Nekrum's Medallion] quest

### ISSUE THREAD

**Issue by mole1505** [LightsHope/server#358]
[Nekrum's Medallion] do not drop from  Nekrum Gutchewer so i cant do the quest  [Nekrum's Medallion]  ( stair boss in zf ) 👍 

Write your report here

**Comment by GuybrushGit** [comment]
Item drops, you need to be on the quest to get it.

**Comment by mole1505** [comment]
Y i found IT out i just delete the item folder in my fils and i Washington
able to pick it up runned after :)

Den 30. okt. 2017 3.39 AM skrev "GuybrushGit" <notifications@github.com>:
