### ISSUE TITLE
We slain Nefarian at about 6pm ST 27/10 and did not distribute the loots yet!

### ISSUE THREAD

**Issue by kakusegu** [LightsHope/server#361]
Hi there, we slain Nefarian at about 6pm ST 27/10 and did not distribute the loots yet, then the server broke down for a while, so we lost all the loots when we get back on, could we have a restore of the items or the boss ,ty instance ID 175 .(Darrow-PVE Server)

**Comment by Lictoria** [comment]
In-game ticket with the [required evidence](https://forum.lightshope.org/viewtopic.php?f=8&t=486). Without that, they will not help.
