### ISSUE TITLE
No Flimsy Masks from the Halloween Event [Treat Bag]

### ISSUE THREAD

**Issue by Manlet** [LightsHope/server#362]
Currently, when you trick of treat an innkeeper and get a [Treat Bag](ID:20393) you only get the wands/food, no masks. The following masks should have a chance to 'drop' in the Treat Bags;

Flimsy Female Dwarf Mask 20562
Flimsy Female Gnome Mask 20392
Flimsy Female Human Mask 20565
Flimsy Female Nightelf Mask 20563
Flimsy Female Orc Mask 20569
Flimsy Female Tauren Mask 20571
Flimsy Female Troll Mask 20567
Flimsy Female Undead Mask 20574
Flimsy Male Dwarf Mask 20561
Flimsy Male Gnome Mask 20391
Flimsy Male Human Mask 20566
Flimsy Male Nightelf Mask 20564
Flimsy Male Orc Mask 20570
Flimsy Male Tauren Mask 20572
Flimsy Male Troll Mask 20568
Flimsy Male Undead Mask 20573

The masks are the best part of the Hallow's end event, a fix would be appreciated.

**Comment by Cabro** [comment]
I had the tauren mask drop. However only 1 mask in god knows how many treat bags :(

**Comment by SubbyDK** [comment]
I just got [Flimsy Female Dwarf Mask] in Org.

**Comment by Manlet** [comment]
OK good to know, possibly way too low of a drop chance then, have yet to see a mask in Ironforge.

**Comment by GuybrushGit** [comment]
A fix for this was applied 3 or 4 days ago, does it still continue?
