### ISSUE TITLE
t3 druid set bonuses (2set - 6 set) not functioning properly on Anathema

### ISSUE THREAD

**Issue by sapylla** [LightsHope/server#365]
Take a look here please https://github.com/elysium-project/server/pull/3149 

The proc effect should proc even when the target is at full hp ,
it was reported on the old bug tracker and before it got implemented the whole drama happened :( 

Please love us bears a little

**Comment by GuybrushGit** [comment]
This was fixed already on the pull request you linked, wait for the fix to go live.
