### ISSUE TITLE
You can use scrolls when you have a more powerfull buff than the one they give.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#366]
You should get the error "a more powerufl spell is present"

**Comment by Fiskehatt** [comment]
Might be fixed already by https://github.com/LightsHope/server/commit/925aa164bee6d1e8377802433cab96b40ef6df00.

**Comment by Cabro** [comment]
I opened it since i didnt see any bug reports on this tracker and on live i wasted scrolls. It could be fixed, but it's not live yet.

**Comment by Fiskehatt** [comment]
Ye, it's a not problem that you opened the issue, just letting you know that a fix might be incoming :)

**Comment by GuybrushGit** [comment]
Fixed already.
