### ISSUE TITLE
Warlock Sucubus quest bug

### ISSUE THREAD

**Issue by smokeotzarow** [LightsHope/server#367]
simple . I am a lvl 60 , I ain't have the quest (lvl 20 ) called Devourer of souls ( Sucubus starting quest chain ) please do fix this .

**Comment by GuybrushGit** [comment]
You must have started the chain and never finished it, check any of the npcs in these chains:
http://db.vanillagaming.org/?quest=1472
http://db.vanillagaming.org/?quest=1507
http://db.vanillagaming.org/?quest=1717

**Comment by smokeotzarow** [comment]
no mob indicated by you has any quest for me. if I picked up when I was lvl 30 quest line for sucubbus and now I can't get it anymore . is that normal?  is my warlock having a handicap now ?not being able to summon a sucubbus ?

**Comment by smokeotzarow** [comment]
I made an in game ticket regarding this and they said that indeed is a bug and I should lost it here. so if I abandoned the quest at lvl 30, now I can't get it ?

**Comment by QAkvastskaft** [comment]
Have you checked all parts of all 3 chains mentioned above?
