### ISSUE TITLE
Head of Onyxia has race requirements, and it shouldn't.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#370]
http://db.vanillagaming.org/?item=18423
http://www.wowhead.com/item=18423/head-of-onyxia
http://wowwiki.wikia.com/wiki/Head_of_Onyxia_(Alliance,_original)

It has race requirements. It shouldn't. Probably horde side one has the same bug.

**Comment by knasen88** [comment]
There is 2 different heads for the two factions? I dont even see how this is an issue other than clogging up developers time
