### ISSUE TITLE
There's a Winterspring Owl in Silithus @ 44.63

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#376]
This is a Winterspring mob, it shouldn't be in Silithus.

**Comment by Fiskehatt** [comment]
It's actually a blizzlike bug: the owl was there in vanilla and the devs here have said that they won't remove it :)

**Comment by fgsfdss** [comment]
#ProtectTheOwl

**Comment by Nelythia** [comment]
Staden approved bug that will stay, it has to stay.

**Comment by Sabre142** [comment]
Blizzlike. Working as intended.

**Comment by Cabro** [comment]
=)))
