### ISSUE TITLE
AB Reputation not correct

### ISSUE THREAD

**Issue by Ruathaz** [LightsHope/server#380]
Resource: http://vanilla-wow.wikia.com/wiki/Arathi_Basin

On the Battlegrounds Holiday weekend for Arathi Basin, the Reputation rewards are:
Collecting multiples of 150 resources (at 150, 300, 450, ...) = 10 rep (total 130 rep if you win)

Reputation rewards
Collecting multiples of 200 resources (at 200, 400, 600, ...) = 10 rep (total 100 rep if you win)
Control Four Bases Quest = 800 rep
Win an AB Quest = 50 rep
Turn in For Great Honor (Horde) / Concerted Efforts (Alliance) = 100 rep

**Comment by GuybrushGit** [comment]
Confirmed on the actual wiki: http://wowwiki.wikia.com/wiki/Arathi_Basin?oldid=193604
