### ISSUE TITLE
Jin'dos Judgement Resist Rate

### ISSUE THREAD

**Issue by rezzidue** [LightsHope/server#382]
Can you please check Jin'do's Judgement is behaving as it is supposed to in regard to it's +spell hit?

Ever since using it I have been getting resists in every area of the game. From triple resists on players to 6 resists on the first pack in DM North.. And switching back to another weapon I no longer have these issues.

I do not believe it is perception bias, can you check it is behaving as supposed to?

Thankyou

**Comment by GuybrushGit** [comment]
Nothing out of the ordinary with this weapon. Miss chance is properly reduced by 2.
