### ISSUE TITLE
Crystal of Zin-Malor does too little damage.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#386]
http://db.vanillagaming.org/?spell=19307
http://www.wowhead.com/item=13347/crystal-of-zin-malor#comments:id=672
http://wowwiki.wikia.com/wiki/Crystal_of_Zin-Malor

It should do between 100 and 500 damage, and between 100 and 500 mana drain.
Note that each tick should be a random value between those limits. Right now you get the same damage from each tick. Whether the mana drain and damage should have the same value on the same tick is unknown to me.

**Comment by Cabro** [comment]
Nvm i was wrong.

**Comment by ifyousayso** [comment]
Yeah, well, it still does too little damage, but in a more.. direct way. I've gotten 90 per tick and never above 400 in more than 30 attempts.

**Comment by Cabro** [comment]
It is affected by armor, it's physical damage.

**Comment by ifyousayso** [comment]
Seems like a bleed effect that should ignore armor..
