### ISSUE TITLE
Character can't receive mails. Elysium 1.07

### ISSUE THREAD

**Issue by Grinel** [LightsHope/server#391]
One of the characters on the account can't receive mails from other characters, as any attempt to sent mail to him results in error:"You have reached in-game cap of unique in-game recipients." This issue was observed as by myself from other characters on the account, so by other people that tried sent mail to that character. The character could send mails to other characters and receive mails from AH. Other characters on the account could sent and receive mails without problem.
GM redirected issue here,

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
