### ISSUE TITLE
[Crash] FlightMasters can cause the client to crash

### ISSUE THREAD

**Issue by Marcelo20XX** [LightsHope/server#396]
I am experiencing a crash when talking to a Flightmaster and ask him to show the FPs, step to reproduce:

1) Have all horde FPs
2) Talk to Michael Garrett in Undercity and made him shows the FP
3) Or do the same with the Burning Steppes FlightMaster

either of them will trigger a crash on the client...

Maybe the packet change commit caused this?

**Comment by brotalnia** [comment]
I didn't touch any packets related to flight masters.

**Comment by Marcelo20XX** [comment]
Fair though, I reverted to an earlier commit and didn't experience this, the latest commit that I tested without this bug is:
https://github.com/LightsHope/server/commit/608f27bff75d4ba3d4b10b24d5287786b206715a

**Comment by GuybrushGit** [comment]
Tested on current dev. No crash.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/commit/be9e70a8fa1d04263b5770c3c37711386362cfd8

**Comment by Marcelo20XX** [comment]
Fixed thank you!
