### ISSUE TITLE
Druid Combo Point Bug

### ISSUE THREAD

**Issue by Dontegi** [LightsHope/server#397]
Report for Elysium PvP Druid/Female/Tauren
 1.12.1

When fighting a target 1v1 and beyond a single battle if I swap forms and want to heal myself the combo points I generated on a single target will fall off. Whether or not I keep focus on a target my points will usually just dissipate forcing me to lose all generated progress via usage of energy and skills to build. If I am kiting a target and happen to drop "Focus" or "Target" the energy from "Claw" will be used and apply damage to target, but then the point it should have applied will not actually stack. It will just register damage done and nothing else. 

Started noticing this earlier this morning. Have been testing it for two hours. Have looked over former "Blue" posts from games retail versions and this has never been a problem.

Thank you for taking the time to look this over. My character is named "Highstick" On Elysium PvP.

**Comment by ItsmeAga** [comment]
likely caused by an addon, try without

**Comment by Fiskehatt** [comment]
Yep, I've heard that especially the addon "enemyframes" causes this problem. Try disabling it.

**Comment by Dontegi** [comment]
Disabled Questie and it still occurs. It is the only add-on I use. This was a glitch/Bug from Beta days and it seems to have leaked through in to this build of their game. I've asked about it in Elysium PvP /1 on both sides and others have reported the same issue even after disabling add-ons.

**Comment by GuybrushGit** [comment]
Can't reproduce. Did claw -> feral off -> healed -> feral on. Combo points never dropped.

**Comment by berillis** [comment]
@GuybrushGit If you change target to any other target (friendly or enemy) than the one you have your combopoints on, you lose all combopoints. Happens with rogues and feral druids. So I'm guessing he targeted himself to heal.

**Comment by GuybrushGit** [comment]
That is intentional, its how combo points work.
