### ISSUE TITLE
PvP ranks can't drop to 0

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/server#40]
With Dishonorable Kills (killing NPCs tagged as civilian) it should be possible to drop your rank all the way to 0. Currently you remain at 0% in rank 1.

Patch 1.5 notes: http://wowwiki.wikia.com/wiki/Patch_1.5.0

>Enough dishonorable kills will reduce a player's rank all the way to zero.

**Comment by GuybrushGit** [comment]
On the week you did the DKs did you also get the mininum 15 HKs to be included in the standings?

**Comment by fgsfdss** [comment]
I don't think so as I don't actively PvP on the character I tried it with most recently, but I will try again this week. However it is possible to derank from 2 to 1 as the rank progress gets updated after each DK, until you reach 0% in rank 1, then it just stops. I don't see why it would be different for rank 1 to 0.
This change was made early on on Elysium, it worked fine on Nostalrius and even in the first few weeks on Elysium.
