### ISSUE TITLE
Curroptor´s scourge Stone.

### ISSUE THREAD

**Issue by RealZarkom** [LightsHope/server#401]
Hello,
i dont actually know if the following is really bug:
Did another Scholomance run and was the only one with the argent dawn thingy equipped. Could not roll for the curroptor´s scourge stones. Someone told me there have to be atleast two people wearing the trinket. It was a waste because all those nice little reputation boosts were just going to rot there forever.
I could not even roll on the thing despite the message "That Item is still being rolled for"

![wowscrnshot_103017_113406](https://user-images.githubusercontent.com/31869461/32168651-c6043708-bd6d-11e7-8ac8-38f269fc72a2.jpg)

**Comment by Cabro** [comment]
Yes this is one of the cases from #178

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/28

**Comment by Cabro** [comment]
http://wowwiki.wikia.com/wiki/Quest to confirm the quest loot system
