### ISSUE TITLE
General DB issues part I

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#406]
Issues found with the database - part I: Misc.

1. Water barrel
Current:		http://vanillawowdb.com/?object=3658	
Should not drop anything but Refreshing Spring Water
Indirect motivation
http://vanillawowdb.com/?item=852#contained-in-object		
Should not be in water barrel
Source:			https://web.archive.org/web/20060515231422/http://wow.allakhazam.com:80/db/item.html?witem=852

2. Dirt-stained Map
Current:		http://vanillawowdb.com/?object=3076	
Object should not drop anything but item 4851
Source:			https://web.archive.org/web/20071112014710/http://wow.allakhazam.com:80/db/object.html?wobject=303

3. The following items should be removed from object loot tables, they should only be sold at NPCs

Name | item id  | Source |
------------ | ------------- | ------------- | 
Thick Cloth Belt	|3597	| [Link](https://web.archive.org/web/20050118042558/http://wow.allakhazam.com:80/db/item.html?witem=3597) |
Thick Cloth Bracers	|3598|	 [Link](https://web.archive.org/web/20060216035649/http://wow.allakhazam.com:80/db/item.html?witem=3598)|
Thick Cloth Gloves	|203	| [Link](https://web.archive.org/web/20060527183024/http://wow.allakhazam.com:80/db/item.html?witem=203)
Thick Cloth Shoes	|202	| [Link](https://web.archive.org/web/20060527183012/http://wow.allakhazam.com:80/db/item.html?witem=202)
Thick Cloth Pants	|201	| [Link](https://web.archive.org/web/20060728033736/http://wow.allakhazam.com:80/db/item.html?witem=201)
Thick Cloth Vest	|200	| [Link](https://web.archive.org/web/20060523222925/http://wow.allakhazam.com:80/db/item.html?witem=200)

Should be removed from objects

4.
The following items should be removed from object loot tables, they should only be sold at NPCs

Name | item id  | Source |
------------ | ------------- | ------------- | 
Padded Armor	|	2160	|	[Link](https://web.archive.org/web/20050224105708/http://wow.allakhazam.com:80/db/item.html?witem=2160)
Padded Belt	|	3591	|	[Link](https://web.archive.org/web/20050118042536/http://wow.allakhazam.com:80/db/item.html?witem=3591)
Padded Boots	|	2156	|	[Link](https://web.archive.org/web/20050117180737/http://wow.allakhazam.com:80/db/item.html?witem=2156)
Padded Bracers	|	3592	|	[Link](https://web.archive.org/web/20060726024627/http://wow.allakhazam.com:80/db/item.html?witem=3592)
Padded Gloves	|	2158	|	[Link](https://web.archive.org/web/20060307172401/http://wow.allakhazam.com:80/db/item.html?witem=2158)
Padded Pants	|	2159	|	[Link](https://web.archive.org/web/20060726024530/http://wow.allakhazam.com:80/db/item.html?witem=2159)

Should be removed from objects

**Comment by henkethebenke** [comment]
Fixed Water Barrel and Dirt-stained Map, but not sure how to add "level appropriate uncommon/rare" in #412

**Comment by QAkvastskaft** [comment]
I removed the last issue here, it will come back in a few days with similar issues in a separate post

**Comment by QAkvastskaft** [comment]
Added a new 3rd issue for maximum confusion

**Comment by henkethebenke** [comment]
Fixed 3rd issue in #415. This issue is now fully done.

**Comment by QAkvastskaft** [comment]
Added a 4th issue

**Comment by henkethebenke** [comment]
Fixed in #416. Please don't add anything else to this issue now so that it can be closed. Should probably save up to a new issue or add to your issue #407 which hasn't received any pull requests yet. Keep up the good work ☺️
