### ISSUE TITLE
Xp bug for pets

### ISSUE THREAD

**Issue by kuseboi** [LightsHope/server#410]
These are bugs i've only noticed when attempting to level a pet that is a much lower lvl than my character. The pet im leveling is Lupos, and i started leveling him on the 30th of October  2017. 

When trying to level up a low level pet, i tried some different methods to see what was the most efficient way to do so. I discovered that it seems like any mobkill, regardless of the mobs level yields the same amount of XP for your pet, as long as the mob is not "gray lvl" for your pet. If the mob is, say 10 levels lower than your pet, it does not yield any experience. 

This kind of forces me to grind low-lvl mobs that do not yield any XP for my character, as trying to level my pet while questing will constantly keep my pet at a much lower lvl than my self. 

It also seems that when in a party, no matter what mobs you're killing, the pet does not get any experience at all. I haven't tried this with too many different mobs, so it could be that it just happens in some cases. It did atleast not yield any XP when killing mobs outside BFD, but when i left the party, it did. 

Im only assuming that it SHOULD yield more experience for the pet when killing a high lvl mob (20lvls-ish higher than the pet) so that if you tame a new low leveled pet, it will catch up to your own level fairly quick.

**Comment by kuseboi** [comment]
I've done some more testing. My pet is currently lvl 29. When killing lvl 28-35 mobs, it yields the pet 222 xp. When killing 41-50lvl mobs it yields the pet 228 xp.

**Comment by GuybrushGit** [comment]
Level difference > 4 will not grant any aditional experience. Pets are no exception.

**Comment by kuseboi** [comment]
What about xp while in a party?

**Comment by GuybrushGit** [comment]
Works as well.

**Comment by GuybrushGit** [comment]
You have to be within a certain range to get xp, you won't get any if you're at like 100 yd.
