### ISSUE TITLE
BoP Tailoring Recipes not lootable

### ISSUE THREAD

**Issue by Kyndros** [LightsHope/server#411]
Hi,

I've encountered this issue in the past and thought it was mob exclusive but has happened again. There is an issue where if a BoP tailoring recipe which drops off a mob (Which only tailors can see) it will bring up an "This item is being rolled for" when trying to loot it but there is no greed/need box pop up.

![image](https://user-images.githubusercontent.com/32825770/32205490-676036fa-bde7-11e7-8746-03cb348f7cc0.png)

![image](https://user-images.githubusercontent.com/32825770/32205496-75e6e836-bde7-11e7-8644-10d2a4204f0f.png)

**Comment by Cabro** [comment]
#178

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/28
