### ISSUE TITLE
Neutral mobs are hostile

### ISSUE THREAD

**Issue by Gleamypal** [LightsHope/server#413]
Hi there,

It happens on Elysium server v 1.12.1 (5875) as it shown at login screen (i dont know  what current patch number exatly are). Login name is Gleamy and characters: Gleamy and Gnimsh. 

The problem is some neutral mobs like guardians, for example are shown neutral (with yellow health bar), but they are like hostile for me.

It is ok, when this are just an ordinary guards cos the only thing that bothering me is unavailability to ask them a question.

But sometime it is a problem, because i can't deliver a quest, for example.

So what should i do in this case? 
![wowscrnshot_103117_111811](https://user-images.githubusercontent.com/33172314/32215089-fecd81ba-be31-11e7-8ede-a3d29fdcaa67.png)
![wowscrnshot_103017_191110](https://user-images.githubusercontent.com/33172314/32215090-feeeea08-be31-11e7-9b59-89f5570ce896.png)

**Comment by Cabro** [comment]
#171
