### ISSUE TITLE
Hallow's End bugs

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/server#42]
- Innkeepers do not have the "Trick or Treat" gossip option
- Bobbing Apples do not give a Well Fed buff after being eaten for 15 seconds as stated in the tooltip.
- Pumpkin Treat's 'Hallow's End Fright' debuff gets applied to self, but has no effect. Should be a chance on hit when you have the growth buff to reduce movement speed by 30% and attack speed by 25% as per http://db.vanillagaming.org/?spell=25022. (see comments on https://web.archive.org/web/20071020040441/http://www.thottbot.com/?i=52265)
- Pumpkin Treat's Pirate transformation only has the male variant. It should randomly have a female variant, even if your character is a male. (http://db.vanillagaming.org/?item=20557#screenshots:id=101786)
- Traveler's Backpacks don't drop as Pumpkin Bags.

http://wowwiki.wikia.com/wiki/Hallow%27s_End?oldid=345906

**Comment by GuybrushGit** [comment]
Pumpkin Treat's female pirates were introduced in a later patch, spell id is 44742. Too high for vanilla.

**Comment by GuybrushGit** [comment]
Unsure of the mechanics behind the Fright effect. Is it something that always happens when you're shapeshifted or only rarely?

**Comment by Cabro** [comment]
Rarely, low chance to proc as i remember it.

**Comment by GuybrushGit** [comment]
Nevermind, the Fright is currently working. Only happens when you have the big and orange buff.

**Comment by fgsfdss** [comment]
I guess I must've been unlucky with the proc in that case, does it only proc off melee attacks or also ranged and spells?
Though surely the 'Hallow's End Fright' buff that gets applied when getting the orange growth and stays at 0 seconds until you die (can't click it off) shouldn't be there.
