### ISSUE TITLE
General DB issues part III

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#421]
Issues found with the database - Part III: Shields

Small Shield
Current:	http://vanillawowdb.com/?item=17184	
Should be removed from creature loot tables
Source:		https://web.archive.org/web/20051129072616/http://wow.allakhazam.com:80/db/item.html?witem=17184

Large Round Shield
Current:	http://vanillawowdb.com/?item=2129	
Should be removed from creature loot tables
Source:		https://web.archive.org/web/20060527155907/http://wow.allakhazam.com:80/db/item.html?witem=2129

Dust Bowl
Current:	http://vanillawowdb.com/?item=4290	
Should only drop from mob id: 832 at 2%
Soruce:		https://web.archive.org/web/20060527043945/http://wow.allakhazam.com:80/db/item.html?witem=4290

Green Carapace Shield
Current:	http://vanillawowdb.com/?item=2021	
Should only drop from mob id: 569 at 1.5%
Source:		https://web.archive.org/web/20050912104410/http://wow.allakhazam.com:80/db/item.html?witem=2021

**Comment by henkethebenke** [comment]
Fixed in #429
