### ISSUE TITLE
Guild master appears guildless, no permissions in newly formed guild

### ISSUE THREAD

**Issue by Burreido** [LightsHope/server#425]
I created a guild yesterday called "Fly Boys". I'm still in that guild (I can see guild chat), but every other part of the interface says I am guildless. I can't /ginvite, can't /gquit or /gdisband, or even talk in guild chat. It just says "You are not in a guild." When people shift-click my name it also says that I am not in a guild. It's a real pain. 

I hope you can resolve this. Until then, is there any chance you could delete the guild so that I could remake it? Thanks for your assistance.

Cheers. (In-game name same as here)

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you

**Comment by Burreido** [comment]
I did this repeatedly. Was told repeatedly to make a bug report and that they couldn't help.
