### ISSUE TITLE
Overlord Saurfang missing scripted pathing when turning in Head of Nefarian

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/server#43]
**Bugged Behavior**

Overlord Saurfang doesn't move when turning in the Horde version of Head of Nefarian (id 19002) for the quest The Lord of Blackrock (id 7784).

**Correct Behavior**

He should walk up to the pillar spawn point, spawn the pillar, do his yell script and cast the 'Rallying Cry of the Dragonslayer' buff, similar to Overlord Runthak with the Head of Onyxia.

**Sources**

https://www.youtube.com/watch?v=szm0tKJIzqg
You can clearly see Overlord Saurfang standing next to the pillar yelling out.
Even though this video was uploaded in 2008, the gear people have equipped clearly indicates this is Vanilla.
Also comment from the uploader: "escobari 8 years ago // hhhm, late fall 2005﻿"
He also mentions in the description that this is recorded on Stormreaver EU, which is an official server.

**Comment by GuybrushGit** [comment]
Better video https://www.youtube.com/watch?v=VfkwV2dgjjY
