### ISSUE TITLE
Enemies always flee towards their closest ally

### ISSUE THREAD

**Issue by jsb** [LightsHope/server#431]
Currently, enemies that "try to run away in fear" will *always* try to run towards a nearby ally, if there is one.

From what I remember and from the sources I've looked at, this behavior was *not* there in Vanilla WoW: Fleeing enemies would just run off in a random direction, regardless of nearby allies. This would randomly result in mobs running towards ally NPCs but not necessarily.

Some video evidence from Vanilla servers (Patch 1.10) showing fleeing enemies **not** running towards their allies:

* [Wastewander Thief runs away from group of allies](https://youtu.be/x9M61jaHFVM?t=19m24s)
* [Wastewander Rogue on the left runs away from the second one on the right](https://youtu.be/x9M61jaHFVM?t=1h46m35s)
* [Bael'dun Rifleman running away from other dwarves in the garrison gate](https://youtu.be/9n_V6xmHhMs?t=18m26s)
* [Southsea Privateer runs past enemy next to her](https://youtu.be/x9M61jaHFVM?t=55m53s)
* [Galak Mauler flees towards player instead of allies behind him](https://youtu.be/BObxNsbRWsc?t=1h44m31s)

I think the fix shouldn't be too difficult since the random direction fleeing behavior is already implemented. Currently it's only used when there are no nearby allies. To fix this issue, the random direction fleeing should always be used.

**Comment by Cabro** [comment]
Nicely spotted. Also gonna open another bug for NPC aggro too early by fleeing mobs on servers.

**Comment by berillis** [comment]
Also using slowing effects on a fleeing monster should change its fleeing direction

**Comment by GuybrushGit** [comment]
Works this way in dungeons as well: https://youtu.be/y0f3aCoPx84?t=173

**Comment by Phoosy** [comment]
This is probably in the same behavior scripting, but slowing effects do NOT impact mobs fleeing in any way. They completely ignore movement impairing effects when their flee behavior is triggered, no matter the source.

**Comment by jsb** [comment]
@Phoosy That is a separate issue and also handled differently, I think. See #331.
