### ISSUE TITLE
Hurricane (Bow) is missing proc

### ISSUE THREAD

**Issue by Char2D2** [LightsHope/server#435]
https://forum.nostalrius.org/viewtopic.php?f=38&t=12943

"Ranged Elemental Damage: Our ranged combat system does not allow a ranged weapon to do a mix of Elemental (Fire, Frost, Arcane, etc.) and Physical damage. Many ranged weapons existed which were listed as doing Elemental damage and did not function properly (the damage was dealt, but was treated as Physical). All of those weapons have been changed to deliver the Elemental damage as a chance on hit effect. Hurricane was previously changed this way in 1.11. The following ranged weapons are also fixed in 1.12: Bow of Searing Arrows, Dwarven Hand Cannon, Heartseeking Crossbow, Dark Iron Rifle, Galgann's Fireblaster, Quillshooter, Shell Launcher Shotgun, Venomstrike, and Verdant Keeper's Aim."

As per this forum thread and 1.12 patch note- Hurricane is missing its proc entirely. It was presumably removed for itemization reasons, but it's an absolute waste to keep it how it is presently and leave all these other ranged weapons mentioned in their fixed 1.12 state. The change to a proc is not increasing the weapons damage, it's simply allowing it to give the same damage it was always supposed to (albeit a bit spikier). The current state of this weapon never existed at any point during retail.

Relevant links:
http://db.vanillagaming.org/?item=2824

And its proc:
http://db.vanillagaming.org/?spell=29501

This issue was found on the Elysium Git Hub, and copied from there. It looks as though the issue was resolved on October 15th, 2017 on Elysium, which was the day before the server switch. The code may have been pulled for Lights Hope before this fix was in place, leading to the loss of this fix.

**Comment by GuybrushGit** [comment]
Just checked Anathema and it has the proc. Clear your WDB.

**Comment by Char2D2** [comment]
Thank you! Just curious, should I clear WDB often?

**Comment by GuybrushGit** [comment]
Whenever theres a patch yes.

**Comment by Char2D2** [comment]
Sorry to comment on a closed ticket, but after clearing WDB I see 1-5 frost damage on it, and most people in my guild see nothing at all. Did you mean the frost damage is there, or the frost arrow proc?

**Comment by GuybrushGit** [comment]
What server are you on?

**Comment by Char2D2** [comment]
LH Elysium PVP

**Comment by GuybrushGit** [comment]
Elysium is on 1.7, you're supposed to see it with the 1-5 frost damage.

**Comment by Char2D2** [comment]
Awesome, that works for me. Thanks again!

**Comment by Char2D2** [comment]
I hate to be annoying, but I believe this bow still may not be functioning correctly. If I start WoW as admin, this bow shows 1-5 frost damage. If I start as I normally would, it does not. Additionally I don't see any evidence of frost damage in the combat log. I have cleared WDB while testing both methods.

I am not sure if there is any way I can confirm what I am seeing at any given time is the correct information, or if there is any way I can properly test it. Does the + 1-5 frost damage currently apply on the Elysium PvP realm in your tests?

**Comment by brotalnia** [comment]
There is no version of the item with nothing on it. The original version has the 1-5 dmg, while the updated version from 1.11 has the spell effect.

**Comment by Char2D2** [comment]
That is what I thought as well. I am concerned that the Hurricane I am using now has nothing on it. It shows nothing in most circumstances, and I have no method of testing whether the frost damage is occurring. There is no frost damage in my combat log while shooting.

**Comment by GuybrushGit** [comment]
You need to clear your WDB folder, if you cleared the one in your WoW folder and it still happens its because your WoW folder is somewhere that requires admin permissions so the real WDB folder was placed somewhere else.
