### ISSUE TITLE
Intoxicating venom debuff in ZG is not behaving correctly

### ISSUE THREAD

**Issue by Zarant** [LightsHope/server#437]
Intoxicating venom debuff is supposed to randomly knock you down or disarm you at random intervals.
Currently, the debuff only disarms you and the disarm debuff bypass any disarm immunity mechanics from weapon chains, stronghold gauntlets or death grips.

https://imgur.com/JWKQX5Q
The tooltip states that you have a chance of falling down and a chance of dropping your weapon.

http://web.archive.org/web/20051219144928/http://www.gamersliving.com:80/wowblog/category/places/instances/zulgurub/
This source loosely indicates that both effects should trigger separately.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/226
