### ISSUE TITLE
Elysium: Mallow's slam strength proc 

### ISSUE THREAD

**Issue by Krotux** [LightsHope/server#439]
Strength proc still not working on live despite this change:

https://github.com/LightsHope/server/pull/286/commits/93302b29283f95278b0c7f66ff362bae9075aeeb

**Comment by brotalnia** [comment]
The pull request that fixed this has not been merged yet.
https://github.com/LightsHope/server/pull/286

**Comment by Krotux** [comment]
oh thanks for the clarification
