### ISSUE TITLE
Captain Sander's Hidden Treasure quest (bugged for Horde)

### ISSUE THREAD

**Issue by jiegema** [LightsHope/server#444]
Captain Sander's Treasure Map can now be accepted and the Captain Sander's Hidden Treasure just can be started, for the horde!~

But.  The world objects cannot be "interacted" with.  The footlocker shows no "gear cursor", to which you can finish the quest.  I assume all of the interactable objects are this way... for all 3-4 of the quests.

I was very happy to be able to accept the quest and I thought I could finish it.  My thoughts were quickly thwarted.  Don't get your hopes up, I guess.

A fast fix would be great, some of us have been waiting a month for this issue to resolve.

**Comment by GuybrushGit** [comment]
My bad.

**Comment by jiegema** [comment]
My bad also GuybrushGit.  I was a lil sad and depressed when I made this post.  I apologize and I appreciate everything you do to give us this great experience.

**Comment by Lictoria** [comment]
[Se also](https://github.com/LightsHope/server/issues/248)
