### ISSUE TITLE
Hunter: VIPER STING

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/server#446]
Dear staff/devs/players and every one else who enjoy to read this,

I don't know if any one notice it yet. While viper sting is on an enemy, it s supposed to "drain" the mana from the target TO the hunter.
The first part, burning the mana of the enemy is working quite well.
The second part, DRAINING the mana to the hunter is not effective.
Please feel free to do the test, i will be glad to show you that on screenshots if requiered.

Best regards to readers

**Comment by GuybrushGit** [comment]
This is not a thing.

**Comment by SuperHeroesAlwaysdie** [comment]
Dear @GuybrushGit ,

I don't understand what is not a thing.

Best regards

**Comment by SuperHeroesAlwaysdie** [comment]
Observations:
![0](https://user-images.githubusercontent.com/33297493/32325862-fcc37a32-bfd0-11e7-8ae3-92a337c861ec.png)
first picture, you can see the target at 2000 mp, hunt at 136.

![1](https://user-images.githubusercontent.com/33297493/32325863-fcef8492-bfd0-11e7-82b0-ffa530384788.png)
second picture, you can see the target at 1896 mp, the hunt at 136.

Interpretation:
 Viper sting  rank 1 is not working correctly. This is not a thing but a fact.
Perhaps rank 2 and 3 too?

references: 
http://db.vanillagaming.org/?spell=3034
http://db.vanillagaming.org/?spell=2898

Conclusion: Invalid? (#error)

Kindly regards

**Comment by Fiskehatt** [comment]
Viper sting did not return any mana in vanilla, that was added sometime in Wrath. Just look at this video 3:07 forward:

https://www.youtube.com/watch?v=qaKUhhSrfa8

**Comment by SuperHeroesAlwaysdie** [comment]
Thank you a lot fiskehatt
