### ISSUE TITLE
ignore list, LONGER?

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/server#449]
Dear readers,

First, thank you for the server.

Second: the ignored player list:
I would like to remind that, in the ignored list there are:
-people with bad behaviors (mean stealing you mobs or other ressources or what ever)
-people with really really bad behaviors (you'r in dungeon and THE LOOT for you class is looted, let s take the exemple i m thinking about, specials weapons for hunters, and a FU/LANGUAGE/ ng warrior pick it, while at the next boss, another weapons drop, but for warrior, which is better in cac than the previous one and he takes so them both...)
-people you know who are playing in horde and alliance (chose you'r side, stop beeing... i let you imagine the followings words)
-a lot of other people but the list will be too long and it s better for an article to be as short as possible)

-AND finally, the numerous, uncredible numbers of people lvl 10 or a little more spamming you:
"golds and lvl up on victoria.Iwillstillyourmoney.com" (a lot ... each 8sec a human personne die in the world, but those... they do better each 10min they contact you to propose you to pay some money, you could give as a donation to the server for keeping him beeing well, and to lose your account/be banned or else)

So here is the main question of this article, how are we supposed to ignore a 100 people like those
when the maximum ignored list is... i didnt count but let's say 15 or 20?

(all of this for just this? OMG ! ;-) )

Thank you for your intention.
Best regards

**Comment by Lictoria** [comment]
There is no point in using the ignore list for gold spammers. Mostly they are banned within a short period. But they do not delete their characters so your list fills with names that will never seen again. Use an add-on like spamthrottle for gold spammers. Save your ignore list for real players.

**Comment by GoBAtech** [comment]
The function of the ignore list is to stop people from messaging you. It doesn't hinder ninja looting, group participation or cross-faction douchebaggery. Use the ignore list for people you don't want messaging you, and another list (notepad.exe is great for this) as a personal hate list.

**Comment by SuperHeroesAlwaysdie** [comment]
Thank you both for your answers.

**Comment by GuybrushGit** [comment]
Ignore list is client side we can't change it.

**Comment by Fiskehatt** [comment]
You can use some addon to make your ignore list longer, for example:

https://github.com/EinBaum/SuperIgnore
