### ISSUE TITLE
compile error debian 9

### ISSUE THREAD

**Issue by chybber** [LightsHope/server#451]
root@wow:/home/wow/server/build# cmake -DDEBUG=0 ..cmake -DDEBUG=0 ..
-- Detected 64-bit platform.
--
This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    PREFIX: Path where the server should be installed to
    PCH: Use precompiled headers
    DEBUG: Debug mode
  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  For example: cmake .. -DDEBUG=1 -DPREFIX=/opt/mangos

-- Found ACE library: /usr/local/lib/libACE.so
-- Found ACE headers: /usr/local/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadbclient.so
-- Found MySQL headers: /usr/include/mysql
--
-- Core revision: a0cc98a941b6f6bd85b3 2017-10-27 04:26:47 +0300
-- Install server to: /home/wow/server
--
-- Use PCH               : No
-- PGO profile           : Disabled
-- Memory allocation     : TBB/Release /usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbb.so
-- Detected compiler     : GNU
-- Build in debug-mode   : No  (default)
-- Use anticheat    : No  (default)
-- Build scripts    : Yes (default)
-- Debug symbols         : Disabled
-- Build flags (RELEASE) : -O3 -DNDEBUG  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -O3 -pipe
-- Build flags (DEBUG)   : -g  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -O3 -pipe
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wow/server/build
root@wow:/home/wow/server/build# make
[  7%] Built target g3dlite
[  8%] Built target gsoap
[  9%] Built target detour
[ 14%] Built target shared
[ 15%] Built target framework
Scanning dependencies of target realmd
[ 15%] Building CXX object src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o
In file included from /home/wow/server/src/realmd/AuthSocket.cpp:27:0:
/home/wow/server/src/shared/Auth/Hmac.h:43:18: error: field ‘m_ctx’ has incomplete type ‘HMAC_CTX {aka hmac_ctx_st}’
         HMAC_CTX m_ctx;
                  ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /usr/include/openssl/hmac.h:15,
                 from /home/wow/server/src/shared/Auth/Hmac.h:23,
                 from /home/wow/server/src/realmd/AuthSocket.cpp:27:
/usr/include/openssl/ossl_typ.h:102:16: note: forward declaration of ‘HMAC_CTX {aka struct hmac_ctx_st}’
 typedef struct hmac_ctx_st HMAC_CTX;
                ^~~~~~~~~~~
src/realmd/CMakeFiles/realmd.dir/build.make:62: recipe for target 'src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o' failed
make[2]: *** [src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o] Error 1
CMakeFiles/Makefile2:504: recipe for target 'src/realmd/CMakeFiles/realmd.dir/all' failed
make[1]: *** [src/realmd/CMakeFiles/realmd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by keaarori** [comment]
What ace lib's are you using? and which version of cmake?

**Comment by Daylien** [comment]
I think its not an issue with ace or cmake. Looks like OpenSSL 1.1 is installed. As far as i know Debian 9 comes with OpenSSL 1.1 (correct me if i wrong).
For the server you need OpenSSL 1.0.2 and not 1.1.

Please check your openssl version and post it here.

Run `openssl version` in your terminal

**Comment by chybber** [comment]
ACE-6.0.3
cmake version 3.7.2

root@wow:/usr/local/ssl/bin# ./openssl
OpenSSL> version
OpenSSL 1.0.2l  25 May 2017
OpenSSL> exit

**Comment by Daylien** [comment]
Mh that's strange. I will install later this day a new fresh debian 9 machine. I will report back.

**Comment by chybber** [comment]
now i've installed the openssl correct get this now:
CMakeFiles/realmd.dir/Main.cpp.o: In function `main':
Main.cpp:(.text.startup+0x2fd): undefined reference to `SSLeay_version'
Main.cpp:(.text.startup+0x325): undefined reference to `SSLeay'
../shared/libshared.a(Hmac.cpp.o): In function `HmacHash::HmacHash(unsigned char const*, int)':
Hmac.cpp:(.text+0xe): undefined reference to `HMAC_CTX_init'
../shared/libshared.a(Hmac.cpp.o): In function `HmacHash::~HmacHash()':
Hmac.cpp:(.text+0x31): undefined reference to `HMAC_CTX_cleanup'
collect2: error: ld returned 1 exit status
src/realmd/CMakeFiles/realmd.dir/build.make:206: recipe for target 'src/realmd/realmd' failed
make[2]: *** [src/realmd/realmd] Error 1
CMakeFiles/Makefile2:504: recipe for target 'src/realmd/CMakeFiles/realmd.dir/all' failed
make[1]: *** [src/realmd/CMakeFiles/realmd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@wow:/home/wow/server/build#

**Comment by chybber** [comment]
Now i get some other errors :/

root@wow:/home/wow/server/build# make
[  7%] Built target g3dlite
[  8%] Built target gsoap
[  9%] Built target detour
[ 14%] Built target shared
[ 15%] Built target framework
[ 15%] Linking CXX executable realmd
/usr/bin/ld: /usr/local/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/realmd/CMakeFiles/realmd.dir/build.make:206: recipe for target 'src/realmd/realmd' failed
make[2]: *** [src/realmd/realmd] Error 1
CMakeFiles/Makefile2:504: recipe for target 'src/realmd/CMakeFiles/realmd.dir/all' failed
make[1]: *** [src/realmd/CMakeFiles/realmd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Daylien** [comment]
So i can confirm you're issue. But I didn't found any solution yet. Problem is that CMake points automatically to the default OpenSSL directory, which is in our case `/usr/include/openssl/`. 
But we want to point to `/usr/include/openssl-1.0.2l/` (or similar). I tried different options in CMake but one of them works atm.
I will look deeper into this. BTW is isn't an Debian 9 problem, all distro with OpenSSL 1.1 have this issue.

**Comment by chybber** [comment]
Yes got it working now by install debian 8 instead, thx anyway.
