### ISSUE TITLE
Bow of Searing Arrows

### ISSUE THREAD

**Issue by cerealwalrus** [LightsHope/server#455]
This ticket pertains to the level 37 bow titled "Bow of searing arrows" on the Elysium realm under Lightshope on November 1st 2017.

With the patch currently on Elysium the item is suppose to be adding + 1 -5  fire dmg with every auto shot.
With the way it is currently working it is not adding any fire dmg at all.
Below is a screenshot highlighting a combat log while having the bow equipped.
https://ibb.co/h0oLSb

Item id: 2825
Item link on vanilladb: http://db.vanillagaming.org/?item=2825

**Comment by Cabro** [comment]
The 1-5 damage should be included in the normal damage of the bow. It shouldn't have a separate combat log event. Now, if it is added into the normal damage or not, you have to ask the devs.
