### ISSUE TITLE
Raid Roll system not work in Alterac Valley bg

### ISSUE THREAD

**Issue by Mag24** [LightsHope/server#457]
When I was playing on AV and help killing "Ivus the Forest Lord", hes rares loot got to the one who the first will steal his loot, becaus the system of automatic roll on rares item not work on this battleground. (We have group loot with Uncommon filter).

Today his ring with int was ninjed by rogue and yesterday his rare cloth helm with +40 cold damage - by druid.

Can you fix the roll system?

**Comment by kakysha** [comment]
Isn't it blizzlike? But even if you make it being rolled, how do you prevent from ninjaing?

**Comment by GuybrushGit** [comment]
> Unfortunately for the mage, a priest won it because he accidentally rolled on the hat and passed on the ring instead of the other way around.
>http://web.archive.org/web/20060216104350/http://wow.allakhazam.com:80/db/item.html?witem=19109
