### ISSUE TITLE
AV: Battle Standards

### ISSUE THREAD

**Issue by Hatredshit** [LightsHope/server#459]
Item ID:
Horde: http://db.vanillagaming.org/?item=19046
Alliance: http://db.vanillagaming.org/?item=19045

These are currently one-time use. Should be re-usable.

Dont think evidence is needed but a few things i found:
http://www.wowhead.com/item=19045/stormpike-battle-standard#comments:id=82571
http://www.wowhead.com/item=19046/frostwolf-battle-standard#comments:id=81705

**Comment by GuybrushGit** [comment]
http://web.archive.org/web/20080603235534/http://wow.allakhazam.com:80/db/item.html?witem=19045

15 min CD
