### ISSUE TITLE
Mmaps misssing? craches

### ISSUE THREAD

**Issue by chybber** [LightsHope/server#466]
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001433.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001533.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001633.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001733.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001833.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0001933.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0002033.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0002133.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0002233.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0002333.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/wow/run/bin/mmaps/0002433.mmtile'
Killed
 can't seem to get the server started it craches with the same errors.

**Comment by brotalnia** [comment]
Either disable preloading of mmaps, or recompile for x64. It's not possible to allocate enough memory to preload all mmaps on a 32-bit process.

**Comment by chybber** [comment]
Ok now I might appear dumb though I did compile it as x64.
But apparently not,
How do I compile it as x64?
Or disable preloading? And what may not preloading cause for issues?
