### ISSUE TITLE
Bonereaver's Edge is stacking to 3 again

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#47]
Prior to patch 1.10, this item should apply a debuff on the target for -300 armor. Currently this weapon gives you a buff of 700 armor penetration which stacks up to 3.

On Elysium this was nerfed to only stack to one.

Is this maximum 3 stacks intentional?

**Comment by GuybrushGit** [comment]
Setting to 1 stack doesn't seem like a good solution. The pre 1.10 spell is only 300 and 60 seconds long.
Since we're not doing spell progression this spell should be left on its post 1.10 state IMO.

**Comment by ohganot** [comment]
I'm not opposed to that, but having 3 stacks on this weapon makes it very very powerful compared to other weapons in both PvP and PvE. R14 weapons will still probably beat it in PvE, given that you use all armor debuffs. But I tend to agree that no spell progression is best.

That means you should also buff thunderfury to 20% proc chance, which is the Naxxramas value.

**Comment by Cbabya** [comment]
>Setting to 1 stack doesn't seem like a good solution. The pre 1.10 spell is only 300 and 60 seconds long.
Since we're not doing spell progression this spell should be left on its post 1.10 state IMO.
With all due respect, what happened to keeping things "not blizzlike, but a blizzlike experience?"

This is a step in the complete wrong direction

**Comment by GuybrushGit** [comment]
I just gave my opinion, its not final in any way don't know why OP closed the issue.

This was not intentionally reverted, its simply a side effect of implementing the progression database.
If you think it should be changed you can submit your modifications as a custom change and the lead team will decide to apply it or not.

**Comment by ohganot** [comment]
For PvE, it is still the best 2h weapon no matter if 1 stack or 3 stacks. You can reduce armor to 696 which means only 1 BRE stack will be effective.
For PvP, thats where the biggest difference is.

**Comment by Cephel** [comment]
Please see where I have listed more sources: https://github.com/LightsHope/server/issues/394

BRE is by far and wide the best 2h PVE weapon in the game, bar none, nothing comes even close with the 3 stacks. Not AQ loot, not even Naxx loot, ignoring KT loot. The 3 stacks **utterly** destroy the gearing progression. Dualwield DPS can only catch up with full best-in-slot AQ gear at the very earliest.

**Comment by ohganot** [comment]
Incorrect. If your guild is properly using all armor debuffs, you will benefit from maximum 2 stacks. (1 stack if using annihilator). Yes, it is the best 2h weapon for dps, but dual wield will still beat it.

**Comment by Cephel** [comment]
Nope. The 1600~ or so armor you get from 2 stacks alone account for 10% extra damage, even if you layer everything. Armor pen becomes progressively better the closer you get to 0. With the exception of some special bosses with an unusually low armor value, BRE will outperform any DPS combo in the BWL patch period.

It gets especially bad on bosses like Magmadar and Chromaggus which have increased armor over regular bosses, so your full 3 stacks are used to their full effect.

**Comment by ohganot** [comment]
Please do your theorycraft properly before stating as a fact.

First off, most bosses have 4691 armor. The few exceptions to this are the Flamewaker bosses in MC (3795-3840 armor) and Ragnaros, who has 5691 armor.

That means if your guild uses full armor debuffs, the Flamewaker bosses will have 0 armor and the bosses with 4691 armor will have 696 armor.

Magmadar and Chromaggus don't have increased armor, they both have the standard 4691 armor value.

A BWL BiS geared dual-wield fury warrior will outdps a BWL BiS geared BRE warrior. The reason why BRE seems so strong is because you need less gear for it to perform to high levels. You get full benefit from world buffs since you aren't crit capped and only need 9% hit chance to never miss yellows.

Out of the top 10 horde warriors on Elysium, only 3 of them use BRE.

Yes, it is a very strong weapon, but vanilla itemization was never linear. Some items were overly strong and some were useless. For example Ironfoe being one of the best weapons in-game even though it drops from BRD.

Nerfing it to 1 stack will have very little effect on the hardcore guilds who already minmax their debuffs. It will have a bigger effect on casual guilds, who don't really care about minmaxing and won't do high dps because of that anyways.

**Comment by Cephel** [comment]
Please list the armor debuffs you're using to reduce a boss by 4000 armor. Because you're most likely adding things that either don't stack or don't work.

Your Ironfoe comment leads me to believe you're just following hearsay from other private server and either haven't played Vanilla yourself in retail or basing your knowledge of it from badly scripted servers, or both.
