### ISSUE TITLE
A list of minor issues

### ISSUE THREAD

**Issue by Wayfahrer** [LightsHope/server#471]
I want to list some minor issues that are not really important but can be quickly fixed to make the server look more professional. I noticed most of them as I leveled in Teldrassil. This concerns patch 1.7 on Elisium.

- The quest mobs for the "Taming The Beast" hunter quests are very conveniently placed close to Dolanaar. There is one Nightsaber Stalker with a very fast respawn timer just outside the inn and several Strigid Screechers to the east of the tall tree-building. These mobs are higher lvl and totally out of place as they make the hunter quest much faster and easier to complete.
- You are not able to swap a full bag with an empty one from your inventory. Currently you have to empty the bag first before you can swap it.
- Mount trainers in Darnassus have an incorrect dialog box. They tell you what they are supposed to tell outsiders who do not have exalted reputation with Darnassus - namely that they do not provide training (even though you are a night elf and they provide training for you).
- Great Stamina (lvl1) and Natural Armor (lvl1) (hunter pet skills) have a written requirement of pet lvl 1 yet you can not train them to your pet until it is lvl 10. Either the text description is wrong or the requirement is bugged.
- The main Blacksmithing trainer in Ironforge (I do not have his name but he is the main trainer who has the most recipes out of the three) can teach you Journeyman Blacksmithing before you reach the required skill level in Blacksmithing and he misses a recipe - silver skeleton key (it was either him or the main trainer in Stormwind that misses the recipe, it is hard for me to test these things but they are fresh from memory).
- At Raven Hill Cemetery in Duskwood at thr house where Morbent Fel is there is a purple aura that should thicken as you approach the house. Currently the thickness of the aura depends on your camera position and not on your character position which completely breaks the effect as you look around. There is purple mist when you look away from the house and no mist when you look at the house. This is my favorite  place in the game because of its atmosphere and the finalizing of Morbent Fel's storiline and it is completely ruined.

I believe these will be quite easy to track down and fix and if all such minor issues are addressed the server will get a nice polish and a more authentic feel.

**Comment by GuybrushGit** [comment]
Please submit only one issue per thread, with the proper sources if required.

Bag swap was already submitted, Journeyman Blacksmithing was already fixed, atmospheric effects are client side we cannot change them.
