### ISSUE TITLE
Two-Handed Weapon Specialization Effecting One-Handed Weapons

### ISSUE THREAD

**Issue by AssObliterator** [LightsHope/server#472]
I did a search of the existing issues and could not find one related to Two-Handed Weapon Specialization for the Warrior class.

I'm not sure if this is just an interface bug, but when I equip a one-handed weapon it says I still receive +1/2/3/4/5% increased damage. I'm pretty sure Two-Handed Weapon Specialization should not increase the damage of one-handed weapons.

**Comment by Sceto234** [comment]
It is just a tooltip bug. According to my own testings it doesn't apply to 1h weapons!

**Comment by GuybrushGit** [comment]
Client bug.
