### ISSUE TITLE
The mobs in Tiragarde Keep are missing the alliance mark next to their icon and they can't be healed nor buffed.

### ISSUE THREAD

**Issue by OrmanAbloReborn** [LightsHope/server#478]
If I remember correctly, back in retail vanilla this was an implementation that wasn't removed until BC or WoTLK. If you could look into this issue further I would really appreciate it.

**Comment by GuybrushGit** [comment]
This is intentional: https://github.com/LightsHope/server/issues/62

**Comment by OrmanAbloReborn** [comment]
But it was a blizzlike implementation. The people who get killed in tiragarde get killed once and move onto the next zone, meanwhile the twinks that spent over 100g on their char/s have to suffer.

**Comment by OrmanAbloReborn** [comment]
It was blizzlike and if you want a blizzlike server you will implement this back.

**Comment by GuybrushGit** [comment]
Video evidence shows otherwise.

**Comment by OrmanAbloReborn** [comment]
![maxresdefault_1](https://user-images.githubusercontent.com/33352199/32388891-72db0fc0-c0c9-11e7-9716-6306eed8c772.jpg)

**Comment by OrmanAbloReborn** [comment]
Evidence ^

**Comment by brotalnia** [comment]
That is not evidence, that's a random screenshot with unknown source.
