### ISSUE TITLE
Web server sharing

### ISSUE THREAD

**Issue by Lapov** [LightsHope/server#479]
Hello guys, 

I have a question about web server. New lightshope.com just have been launched, but it is completely simple and I know that you guys work on it. So, may be it will be a good idea to share the web server as well that anyone can contribute in developing web portal. I think there are a lot of guys who can help in design part and the server landing page can be updated by contributes for different event or celebrations (Christmas for example), add additional statistics or at least just make it in modern good-looking design. 

What do you think guys? What do you, @LHGemt, think about it, is it possible?

**Comment by LHGemt** [comment]
No decision has been made on whether or not we will open source the web stuff yet. but it's not impossible that it will be. Atm there are internal developers working on it, and as of now it won't be. you have experience and interest in contributing

**Comment by Lapov** [comment]
@LHGemt yes, I am interesting in contributing but it depends on which technology stack do you use. Who can I ask to get any details about it?

**Comment by LHGemt** [comment]
Whitekidney
