### ISSUE TITLE
Thunderfury: One-Hand Issue

### ISSUE THREAD

**Issue by Ordnac** [LightsHope/server#481]
On Anathema PVP, Thunderfury was mistakenly reverted back to main-hand on the 11/1 update.  This item should be one-hand as of patch 1.12.  See original patch notes below, an extensive Nost thread detailing changes made to this item, and an 11 year old PvP video showing this item equipped in the off-hand post patch 1.9.  

Sources:
http://wowwiki.wikia.com/wiki/Patch_1.12.0
http://forum.nostalrius.org/viewtopic.php?f=24&t=703
https://www.youtube.com/watch?v=FFr4iOTPcg8

**Comment by Zarant** [comment]
I also tested with about 2000 swings, it does have a ~17% proc rate, which is consistent with the 1.9 version of the sword.

**Comment by StadenElysium** [comment]
Anathema is not on patch 1.12.
