### ISSUE TITLE
Rotgrip - Fatal Bite hitting way too hard

### ISSUE THREAD

**Issue by Derferter** [LightsHope/server#483]
Elysium Server
creature: Rotgrip - Maraudon
issue: FATAL BITE lifetap ability is hitting for 804 spell damage

(note the damage in PURPLE in the combat window)
https://i.imgur.com/tQe2566.png
https://i.imgur.com/8ZnfIZK.png

correct behavior: Fatal Bite should be hitting for 100 damage, healing the creature for twice that amount
http://vanillawowdb.com/?npc=13596#abilities
http://vanillawowdb.com/?spell=16495

**Comment by GuybrushGit** [comment]
Fatal Bite scales with level.
>BasePoints = 100 + Level * 16.00, Multiple = 2.00
