### ISSUE TITLE
Quest NPC doesn't spawn. Elysium 1.7

### ISSUE THREAD

**Issue by Grinel** [LightsHope/server#485]
NPC Lakota Windsong, that  starts the quest Free at Last in Thousand Needles, doesn't spawn near quest mob Arnak Grimtotem. The issue wasn't encountered by me on Elysium patch 1.6.

**Comment by brotalnia** [comment]
She is spawning on dev branch. Most likely somebody had killed her.
![lakota](https://user-images.githubusercontent.com/6519171/32412586-22d3b6fc-c205-11e7-8288-020d0a585616.jpg)

**Comment by Grinel** [comment]
Today she again started to spawn. Still, even if the reason was in her being killed, is she supposed to disappear on the whole day in that case?
