### ISSUE TITLE
Unable to get the quest : The legend of korrak

### ISSUE THREAD

**Issue by Hulemand123** [LightsHope/server#489]
Unable to get the quest : The legend of korrak (horde side)
tried to take the quest on my newest lv 60 toon

Checked on one of my other characters, which already had the quest in his quest logs, i went and abandoned it and then he also wasn't able to repick the quest again
questgiver: Warmaster Laggrond from Alterac Mountains

Server: Darrowshire

**Comment by GuybrushGit** [comment]
This quest is disabled patch 1.8 and above.
