### ISSUE TITLE
Hammer Of Wrath Multiple Bugs

### ISSUE THREAD

**Issue by Hsekr** [LightsHope/server#49]
Currently paladin's spell Hammer of Wrath is not working as it should:

- A paladin should be able to use How when target is 20 or less percent of health. Currently it only works when the target is bellow 20 percent ( execute had this issue but was fixed )

- How should not reset weapon swing timer Currently it resets swing timer witch pretty much makes it worthless in raids  ( it was working correctly about 3 weeks ago so its a recent bug )

- How critical chance should be based off melee critical chance. Currently it is hard to determine what critical chance it uses. ( I did a medium test ~70 min while grinding mobs and it only amounted to How critical chance being 21% while my melee critical chance was 33% and spell 14% )

- How should be able to trigger weapon/trinket procs ( it was working correctly a few weeks ago )

- How is being treated as a spell and therefore is applied spell damage reductions on certain BWL trash mobs ( How is a melee special attack that does holy damage just like seal of command and should be treated the same )

If you need any additional info or tests please note and ill try to get it.

**Comment by GuybrushGit** [comment]
>A paladin should be able to use How when target is 20 or less percent of health. Currently it only works when the target is bellow 20 percent ( execute had this issue but was fixed )

Back on the old tracker we determined that this and execute should not be usable at 20%.

>How should not reset weapon swing timer Currently it resets swing timer witch pretty much makes it worthless in raids ( it was working correctly about 3 weeks ago so its a recent bug )

This is related to the spellcasting resetting the swing timer fix a few weeks ago and it afects shamans as well. Its not clear what should happen to the swing timer after casting a spell: nothing, delayed timer or reset timer. You should make a seperate issue for this with the proper research.

>How critical chance should be based off melee critical chance. Currently it is hard to determine what critical chance it uses. ( I did a medium test ~70 min while grinding mobs and it only amounted to How critical chance being 21% while my melee critical chance was 33% and spell 14% )

Its using ranged crit. Bugged.

>How should be able to trigger weapon/trinket procs ( it was working correctly a few weeks ago )

Which procs? How can it proc weapons when its not a melee spell?

>How is being treated as a spell and therefore is applied spell damage reductions on certain BWL trash mobs ( How is a melee special attack that does holy damage just like seal of command and should be treated the same )

Why? HoW is not a melee spell but even if it was the damage reductions should apply to it.

**Comment by Hsekr** [comment]
Thanks for input.

> Back on the old tracker we determined that this and execute should not be usable at 20%.

Unfortunately old bug tracker is down so I can`t look up that discussion My clues/reason on why it should work at 20% are:

- Game spell description http://prntscr.com/h09len
- The spell on wow client action bars becomes active at 20%
- Original vanilla addons also give out notice about How being usable once the target hits 20%

> This is related to the spell casting resetting the swing timer fix a few weeks ago and it afects shamans as well. Its not clear what should happen to the swing timer after casting a spell: nothing, delayed timer or reset timer. You should make a seperate issue for this with the proper research.

That probably may be the fix that changed it. Maybe my previous explanation was not clear enough or misleading hopefully this will add to understanding the issue:

- How is not a spell but a melee/range physical ability that is castable and does holy damage HoW should not affect swing timer unless the swing timer finishes while how is still casting witch should put swing timer on hold and execute swing after how cast finish and then start the next swing. The aim / skillcap for paladin to cast HOW between swings to maximize dps witch currently is impossible due to HoW resetting/holding swing timer regardless when its casted. 

> Its using ranged crit. Probably a bug.

That might be it.

> Which procs? How can it proc weapons when its not a melee spell?

My way of thinking/idea behind this was based on judgement ability witch is similar and it beeing an ability rather than spell but i understand that you probably want an in-depth research on this so ill try my best and look through web archives old videos.

> Why? HoW is not a melee spell but even if it was the damage reductions should apply to it.

lets take Death Talon in bwl as our example ... seal of command does full damage on him  judgement / consecration damage is almost nonexistent due to them being spells so what about How since its not a spell should it hit for almost no damage like spells or full damage like seal of command ?

As for splitting this up to creating separate issues..... I rather not. I would like to get to the most correct behavior of this ability so that it might fixed in one go if anyone has any input / suggestions please add them.

**Comment by supasteed** [comment]
@guybrushgit I think you are right. Here I can see his execute becomes avaiblable at 19%

https://www.youtube.com/watch?v=y3tsv0Y0QKw&t=5m12s

**Comment by theloras** [comment]
Its not clear what should happen to the swing timer after casting a spell: nothing, delayed timer or reset timer._

This took me all of 2 minutes to find...

**paladin dps golemagg**
https://youtu.be/ovhRqAxnXqg?t=204
Published on Nov 19, 2006

**Comment by fidbugs** [comment]
Regarding HoW resetting swing timer - and making it bad in PvE - well that's how it was, even thru TBC.

Quick google research should show you that:

http://vanilla-wow.wikia.com/wiki/Paladins_as_DPS

http://www.arenajunkies.com/topic/18240-how-to-ret/

http://www.wowhead.com/forums&topic=12409&p=108746

To be more precise, lets take a look at this video:

https://www.youtube.com/watch?v=y_-u0B4vLJg

If you analyze situation around 3:10-3:20 you will see that casting HoW resets swing timer.

@3:12 - melee hit
@3:14 - he changes target, and instantly casts HoW
As HoW lands(3:16) he changes back target and next melee strike occurs 3:20, which is fits the attack speed of his weapon(GM wpn).

That proves the resetting of swing timer. 

HoW never triggered item/enchant procs, analogy with Judgement is not correct. But yea, it should use your melee crit rating so that's a bug.

**Comment by dpopovics** [comment]
http://paladin-guide.blogspot.com/2005/12/other-abilities.html

Seems to indicate that below 20% is needed but also that this counts as a melee strike and should hit the same way SoC does.

**Comment by GuybrushGit** [comment]
Sources for melee crit:

>Which abilities are melee crit? SoC, JoC, HoW. 
>http://web.archive.org/web/20060323081244/http://forums-en.wow-europe.com/thread.aspx?fn=wow-paladin-en&t=95120&p=1&tmp=1#post95120

>Crit chance (and damage) are based upon the melee crit chance
>http://www.wowhead.com/spell=24275/hammer-of-wrath#comments

**Comment by GuybrushGit** [comment]
From the videos and comments it seems that HoW should reset swing on cast, fixed swing reset on landing here: https://github.com/LightsHope/server/pull/427
Fixed melee crit here https://github.com/LightsHope/server/pull/428

**Comment by Hsekr** [comment]
Looks Good what about activation on 20% since client makes spell active + tool tip states 20% or bellow ?

**Comment by GuybrushGit** [comment]
That's not a bug, video evidence shows this type of spells only being usable 19 and under.

**Comment by Hsekr** [comment]
Could the issue lie in how the numbers are interpreted by client / addon / server say addon goes by exact number while client/server by ceiled number resulting in seeing 19% activation on addon while client/server would think its 20%

The issue:

Looking at the videos from retail once the how/execute becomes active on client its immediately usable while currently on LH it is not.

Should probably dig deeper on this What is your option ?
