### ISSUE TITLE
Warlock Felhunter quest issue

### ISSUE THREAD

**Issue by discory** [LightsHope/server#491]
Character name: Aywinia - Alliance
Server : Elysium

Summary: Felhunter quest not handed out.

Issue: The quest to obtain the felhound was never handed out by the quest-giver.

The pets i can summon are : Imp, Voidwalker, Succubus.
I am a level 60 warlock and its a bit frustrating to do pvp without the Felhound.    

If there are other pets i am now missing, I've never received those quests. 
Gm told me to post the question here as he could not help me in-game

**Comment by Qirel** [comment]
Most likely you are just missing a part of the chain, that you started sometime before. Depends a little on what race you are, there are different questlines, but they should end up in the same place.

Please see http://wowwiki.wikia.com/wiki/Quest:The_Binding_(Felhunter) and check all questgivers.

**Comment by GuybrushGit** [comment]
You need to go to all the npcs in http://db.vanillagaming.org/?quest=1798 and check what step you're on.
