### ISSUE TITLE
Shaman: call of water disappeared from quest list

### ISSUE THREAD

**Issue by kromosomi** [LightsHope/server#492]
so... i was doing my call of water class quest (part 6) and i log offline for awhile, when i came back in the quest was gone from my questlist, and my quest items also from bag. i cant find the quest to pick up anywhere.... i want my damn water totem :s

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
