### ISSUE TITLE
Group of NPC's not working properly. Behaviour broken after recent changes

### ISSUE THREAD

**Issue by JuJuBam** [LightsHope/server#493]
Greetings,
After recent changes the NPC's in Durotar - Tiragarde keep, became non affiliated with Alliance which is wrong because in retail Vanilla and up to probably WOTLK they were like Alliance guards with all the consequences coming with it. Thats why they had that status in old Nostalrius which by the way is the same for dwarves in the Barrens also, the dwarves in Bael'Dun.

Here is a video from year 2015 from Nostalrius showing the Bael'dun Dwarves being PVP
https://youtu.be/aV2Lhg0H0t8?t=171

As for the Tiragarde NPC's its clearly visible that they are also Alliance NPCs from thottbot archive -
http://web.archive.org/web/20071015101125/http://thottbot.com:80/c3129
http://web.archive.org/web/20071023070922/http://thottbot.com:80/c3128
FACTION - STORMWIND

They are connected with Stormwind and have the same status as City Guards, as like the same status have the Razor Hill Grunts too for example - 
http://web.archive.org/web/20071022041723/http://thottbot.com:80/c5953
FACTION - ORGRIMMAR

I know that some people are mad because they got killed there, but thats vanilla and they have to accept it like it is, thats why Nostalrius kept these NPC's the way they were.

**Comment by Cabro** [comment]
Linking another private servers is not proof...

**Comment by JuJuBam** [comment]
But linking thottbot from vanilla is proof.

Also Nostalrius is not some random private server but the server that gave the data to Elysium and thus to Lightshope, and they kept those NPCs that way for a reason. Because they were Blizzlike with all pros and cons comming with it. Lightshope is too a Blizzlike server.
Some people really want LFG system for Vanilla, should it be added because they dont like spamming trade channel looking for group? No.

**Comment by OrmanAbloReborn** [comment]
Well their evidence is from a 2013 private server (probably feenix), so this one is approvable.

**Comment by brotalnia** [comment]
Video proof from retail vanilla they were not marked as PvP.
https://youtu.be/FaV6oAteJGI?t=2m16s

**Comment by OrmanAbloReborn** [comment]
Brotalnia that is not retail vanilla.

**Comment by brotalnia** [comment]
Oh really? Joana's leveling videos are not retail vanilla? That's a nice joke you just made. I know you didn't spend 1 second verifying that btw, you just blurted it out cause you WANT it to be true, but i shall indulge you.

First look at the description of the video:
> This is part of a full Unedited 1-60 vanilla WoW speed run done by the speed runner FuriousPaul, who played the character Joana in this run. This was done back in 2006 (Patch 1.10). FuriousPaul did 1-60 in 4 days 20 hours /played time and first to level 60 on this server. No rested XP was used, no twinking, no help from other players. This is part of Joana's WoW Leveling Guide. 

The realm name.
https://youtu.be/FaV6oAteJGI?t=1s
Jubei'Thos is a retail Oceanic realm.

The realm selection menu.
https://youtu.be/SwLjJH8LXfc?t=52m5s
Are you telling me that there is a vanilla private server out there that has realms separated by region, and it has 18 realms in the United States, and 3 Oceanic realms? Please name me that private server.

The message of the day.
https://youtu.be/FaV6oAteJGI?t=2h16m4s
No heavily populated private server i have ever seen has ever left their motd at "Welcome to World of Warcraft". 

Joana's website from 2006.
http://web.archive.org/web/20061108103226/http://www.joanasworld.com/
Exact same character in the screenshots as in the videos, talking about her leveling strategies.

The flawless scripting and the fact that not even one quest in this whole playthrough is even missing a single emote. Everything is perfect, just like retail, cause it is retail. Go watch it. Sit down on your ass in front of your computer and play the whole thing and find me a private server bug.

Now to address the most idiotic question i know you are going to ask.
"Well then why is it uploaded in 2013 and not 2006, derp!"

- Youtube was nowhere as popular in 2006 as it is now. It had just launched.
- Everyone had shit internet, uploading 53 videos that are 1 to 5 hours in length EACH with 2006 internet is not realistic. And he is Australian, as you can see he plays on an Oceanic realm. Australian internet is garbage in 2017, think about what it was like in 2006.
- Youtube had a maximum length of 10 minutes per video until 2010. I'll let you do the math on that and figure out into how many parts the 1-60 leveling series would have to be split to be uploaded. It's close to a thousand.

This is the whole playlist.
https://www.youtube.com/playlist?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n

You can even see a trailer of the leveling series that was uploaded in 2007, but uploading the whole thing unedited was simply not possible then.
https://www.youtube.com/watch?v=MHuAb0s16hk

Thank you for wasting my time and making me explain that water is wet. Shame on you.

**Comment by OrmanAbloReborn** [comment]
But did you even consider the fact that this was an issue from previous patches? Like idk, 1.7 for ex?

**Comment by OrmanAbloReborn** [comment]
Or that it could have been fixed only on that  server?
