### ISSUE TITLE
Weird aggro bounce in raids.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#495]
Went in BWL earlier. Someone aggroed some adds, realized his mistake and then ran out of the instance. However the adds (@ vael) instead of resetting, they aggroed the rest of the raid which was @ Nefarian.... How is this even remotely possible?

**Comment by knasen88** [comment]
instance wide combat pulses so healers cant ress people OOC 40 yards away.

**Comment by Cabro** [comment]
..for trash? Oo

**Comment by Cabro** [comment]
Any feedback on this bug? If it is due to combat pulse, then how can the trash be skipped by kiting them with a hunter and using FD? They all reset instead of going for the rest of the raid.

**Comment by GuybrushGit** [comment]
Could also be agro from something like Blessing of Wisdom.

**Comment by Cabro** [comment]
Ooo.... then that's another bug. BoW/GBoW/Mana Totem/Enamored mana totem give threat on their ticks?

**Comment by GuybrushGit** [comment]
It doesn't do threat but puts the Pala in combat.

**Comment by Cabro** [comment]
Should it?

**Comment by GuybrushGit** [comment]
Just tested BoW doesnt do anything after all. You most likely agroed mobs with raidwide combat.

**Comment by Cabro** [comment]
Ok then this has to be rechecked, because currently you can skip those exact mobs that caused the wipe in my report with simple FD and they reset without aggroing the rest of the raid.

**Comment by GuybrushGit** [comment]
You dont even say what mobs they are...

**Comment by Cabro** [comment]
The 2 packs of drakonids after Vaelastrasz and before the suppresion room.

**Comment by GuybrushGit** [comment]
Those dont cause raidwide combat it was something else.

**Comment by Cabro** [comment]
Can you confirm that if the player that is currently in combat with some mobs in raid leaves the instance via portal, the mobs do actually reset and not aggro the rest of the players inside the instance?
