### ISSUE TITLE
Quest Timbermaw Ally is not available.

### ISSUE THREAD

**Issue by pitykov** [LightsHope/server#496]
Tried to pick up the quest Timbermaw Ally in Felwood, but I was unable to do it, since quest NPC is not offering it. Lvl 60, and already done the Timbermaw related quests in Winterspring. I'm not sure if it's a bug or just introduced in a later patch.

**Comment by Zarant** [comment]
This quest is supposed to be introduced with patch 1.9 iirc

**Comment by pitykov** [comment]
thanks for the info... should I just delete this post then?
