### ISSUE TITLE
Taerar Splits at ~1-2% and regains full Health and Deaggros

### ISSUE THREAD

**Issue by grifon1** [LightsHope/server#497]
Anathema - PVP

World dragon Taerar becomes banished / splits again at ~ 1-2% and then becomes whole again, regains full health and de-aggros to players.

Occurred ~00:45 on Anathema 5 November 2017.

Video: 
https://streamable.com/m4jy2

**Comment by GuybrushGit** [comment]
Did any of the other 3 splits not happen?

**Comment by GuybrushGit** [comment]
What probably happened: Taerer moves from Dream Bough to Jademir Lake, area change makes it enter evade mode and resets m_uiEventCounter, a well timed hit cancels the evade but the event counter is still reset so he splits.
