### ISSUE TITLE
Where is Varian Wrynn?

### ISSUE THREAD

**Issue by Tsaav** [LightsHope/server#498]
Where the heck is Varian Wrynn?

I was doing some research on my king, and noticed that Varian Wrynn was actually in vanilla one point. Pulling a quote form WowWiki:

> Until patch 1.9.0, players could witness the king in his captivity in the sewer dungeons of Alcaz Island just north of Theramore, though he was not involved in any quests at the time. With patch 1.10, Varian was replaced with an elite level 62 myrmidon named Tidelord Rrurgaz and a sewer full of elite naga, and Alcaz Island became home to Doctor Weavil, a major part of the Gates of Ahn'Qiraj world event. 

So until 1.9, Alcaz Island **SHOULD** house Varian, but it doesn't. If you go there on the Elysium server, you'll see the island is overrun with naga, and where Varian should be is the level 62 boss Tidelord Rrurgaz. 

Proof:
Old post form WowWiki in 2005:
>http://wowwiki.wikia.com/wiki/Varian_Wrynn?oldid=39190

Current WowWiki page:
>http://wowwiki.wikia.com/wiki/Varian_Wrynn#In_World_of_Warcraft

A video from from vanilla:
>https://www.youtube.com/watch?v=kSL4lsMsdHs

Attached image of Tidelord Rrurgaz (who replaces Varian in a future patch)

Unfortunately, I do not have much proof to back this up, but I hope what I *do* have is enough. Thanks for taking the time to read through this. 
![wowscrnshot_110417_214523_1](https://user-images.githubusercontent.com/33384632/32411275-22cfc5c2-c1ad-11e7-8312-568f97a8d05b.jpg)

**Comment by brotalnia** [comment]
Fixed in https://github.com/LightsHope/server/commit/39856fb30727ef976c7af048ef8d2c455a027cad.
