### ISSUE TITLE
Renewing the issue of "Prevent proc spells from breaking CC"

### ISSUE THREAD

**Issue by vindruvor** [LightsHope/server#5]
I am not sure if you guys managed to store the fix for this, since it was not on live servers as far as I remember (for example Blazefury Medallion still instantly interrupts Gouge).

This: https://github.com/elysium-project/server/pull/2506

"The fire damage from the Blazefury Medallion and the Gutgore Ripper's effect should no longer immediately break Gouge.
Stormshroud Set: The Lightning effect from this set will no longer break your Gouge.
http://shadowpanther.net/roguechanges.htm
Maelstrom will proc on a gouge but does not break the gouge.
http://web.archive.org/web/20070515083410/http://www.thottbot.com/i19289

Seems like the default behaviour for these triggered proc spells is not to break the CC that triggered them.
Made it so spells caused by SPELL_AURA_PROC_TRIGGER_SPELL dont remove auras with SPELL_ATTR_EX_UNK18 (stun, polymorph, daze, sleep)"

fix: https://github.com/elysium-project/server/pull/2506/commits/c6bf175e7b3596bc739c850c29957eab4ae420cc

**Comment by Harkonnen13** [comment]
Darkmoon card never break gouge for me. They fixed this. idk about lifesteal , or something else, but seems they solve this issue

**Comment by GuybrushGit** [comment]
Can you be more specific, what proc is breaking what CC for you?

**Comment by vindruvor** [comment]
ah well sorry, I just copy pasted the whole bug report from Elysium Project github. 

The only thing I have tested was Gouge + Blazefury Medallion. The +2 fire damage instantly interrupts Gouge.

**Comment by GuybrushGit** [comment]
How long ago was that? It doesnt happen after the fix.

**Comment by vindruvor** [comment]
I tested it just some minutes after servers went live again at Light's hope (Anathema server)

**Comment by vindruvor** [comment]
I mean When Light's Hope went live for the first time after they detached from elysium Project

**Comment by GuybrushGit** [comment]
Anathema doesn't have the fix yet.
