### ISSUE TITLE
Dust Stormer's are creating two cloud animations; 1 of which do not disappear

### ISSUE THREAD

**Issue by yeahmate** [LightsHope/server#50]
The Dust Stormer (npc-id: 11744) mobs in Silithus are creating Storm clouds which do not disappear. 
When they cast Lightning Cloud (spell-id: 19513) it summons two clouds and only 1 disapears when the spell ends.

Two clouds are summoned when Lightning Cloud is cast: https://i.imgur.com/utOwrtR.jpg
One cloud persists: https://i.imgur.com/nt2laiP.jpg

core revision: cbc44def559d708de1b0 on Darrowshire 2017-10-20

**Edit**: Further testing shows that other players cannot see the additional clouds and restarting my client gets rid of them. However they do continue to double spawn when ever the spell is cast. This might be a driver/graphics issue (ATI).

**Comment by GuybrushGit** [comment]
Can't reproduce.

**Comment by yeahmate** [comment]
Independent reports suggest that this issue also effects Druid Hurricane spell and is not limited to ATI cards.

**Comment by yeahmate** [comment]
this has been reproduced by Agrillos 2017-11-08 14:04

**Comment by GuybrushGit** [comment]
Most likely related to the client, nothing we can do about it.

**Comment by Shokar** [comment]
i got this recently too, using ATI card, but i cant figure out how to solve the problem, really want to get rid of it.
