### ISSUE TITLE
The Great Masquerade permanently despawned Bolvar!

### ISSUE THREAD

**Issue by ciorex** [LightsHope/server#507]
Started the quest "The Great Masquerade" yesterday november 4 without knowing Bolvar was already dead. 

November 5, he is still dead and despawned, Stormwind Royal Guards are still transformed into Onyxia's Elite Guard.

**Comment by ciorex** [comment]
So Bolvar finally respawned after 3 days and everything is back to normal. Except now every time I start the quest, Reginald Windsor bugs out at the entrance of Stormwind.

He gets of his mount and just stands there until he despawns.

**Comment by GuybrushGit** [comment]
Most likely horde killed him. He has a long respawn timer.
