### ISSUE TITLE
Green Whelp Armor works against enemies over level 50.

### ISSUE THREAD

**Issue by Fiskehatt** [LightsHope/server#509]
I have seen some players successfully use the [Green Whelp Armor](http://db.vanillagaming.org/?item=7375) several times in BGs against level 60 players, when it clearly should not happen:

> Equip: When struck by a melee attacker, that attacker has a 5% chance of being put to sleep for 10 sec. **Only affects enemies level 50 and below.** (cooldown 10 sec)

(Anathema)

**Comment by ItsmeAga** [comment]
Level restriction was added in Patch 1.10.0, so its one of those progression changes. Should not proc on anathema, but on the other servers.
