### ISSUE TITLE
Guards don't attack within Alchemist's hut in Everlook

### ISSUE THREAD

**Issue by transportertest1** [LightsHope/server#51]
Location: Everlook, building of Evie Whirlbrew <Alchemy Supplies>

Expected Behaviour on PvP server: If someone attacks another faction's character the guards should attack the person

Actual Behaviour: There are a lot of areas (especially behind the NPC) that people can attack each other without the intervention of the guards. It's even possible to "fire" out of the building (saw Hunter, Druid, Shaman, Warlock doing it) to characters outside without guards intervening.

**Comment by GuybrushGit** [comment]
Guards like any other mob are affected by agro ranges and line of sight. They won't attack people fighting out of their range / LoS.
