### ISSUE TITLE
Amulet (and Orb) of the Darkmoon not updated with 1.7

### ISSUE THREAD

**Issue by Bobross23** [LightsHope/server#512]
In patch 1.7 these items were supposed to be upgraded to their epic versions.  As of now they are still rare on Elysium server.  I know the issue was addressed already on the other servers so I guess Elysium just needs its update.  But for completeness some meh sources...

http://wowwiki.wikia.com/wiki/Amulet_of_the_Darkmoon

http://wowwiki.wikia.com/wiki/Orb_of_the_Darkmoon

**Comment by brotalnia** [comment]
Actually, only the buffed version was in the database until now, so you probably forgot to delete your cache. I have added the 1.6 versions in https://github.com/LightsHope/server/commit/a9a0cfce16955be1cc469e08f034e2ec7b2f55f0.

**Comment by Bobross23** [comment]
Thanks.  Fixed.  I completely forgot about the good old days of deleting cache.  For anyone else that doesn't know, delete wdb folder to fix.
