### ISSUE TITLE
Warlock's Soulstone bug

### ISSUE THREAD

**Issue by mpfans** [LightsHope/server#515]
When a warlock binds a player to a Soulstone and  login again ,then can use different LV Soulstone, binding other player..

**Comment by mpfans** [comment]
a 60LV warlock can bind SoulstoneS to 5 players in half an hour

**Comment by mpfans** [comment]
A bind Minor Soulstone ,login again,
B bind Lesser Soulstone ,login again,
C bind Greater Soulstone ,login again,
D bind Major Soulstone.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/31

**Comment by mpfans** [comment]
Closed #515 via #31
