### ISSUE TITLE
Wrong stats on certain items since 1.7 (elysium)

### ISSUE THREAD

**Issue by Maef95** [LightsHope/server#517]
Some of my item's stats changed after 1.7 hit.
For example T2 hunter shoulders lost 1% hit and T2 hunter pants gained 1% hit and lost 1% crit.

I didn't find anything in any patchnotes that confirm a change of these items.

The odd thing is that half of the hunters I spoke to still have the old pre 1.7 stats on their items even after deleting WDB folder and the other half got the 'new' stats.

I opened certain tickets and GMs verify as well that this is a bug.

normal stats:
![t2 pants normal stats](https://user-images.githubusercontent.com/33423281/32445000-b6ea3136-c304-11e7-9cd8-4b2ac612569b.JPG)

my display:
![t2 pants with 2 hit my display](https://user-images.githubusercontent.com/33423281/32445001-b7104c40-c304-11e7-8b86-28e317eeaed4.JPG)

normal stats:
![t2 shoulders normal stats](https://user-images.githubusercontent.com/33423281/32445002-b7382148-c304-11e7-8660-df49c66076d0.JPG)

my display:
![t2 shoulders without hit my display](https://user-images.githubusercontent.com/33423281/32445003-b75caee6-c304-11e7-883f-a60662764be6.JPG)

**Comment by GuybrushGit** [comment]
This is not a bug.
