### ISSUE TITLE
[ZG] Tranquilizing Poison cast by Razzashi Serpent is not triggering a sleep when it ends (if not removed).

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#52]
http://db.vanillagaming.org/?spell=24002
http://db.vanillagaming.org/?npc=11371

At the end of the poison it should cast a Sleep, which was unremovable. Which is why you had to remove the Tranquilizing Poison. This makes the trash 10x times easier if the tank is not taken out of battle.

LE: found the Sleep id: http://db.vanillagaming.org/?spell=24004

**Comment by supasteed** [comment]
hey cabro I found some of your issues here

Hallow's End's Treat Bag is mostly empty.
#3206 opened 5 days ago by Cabro
Stun/root while charging teleports you to your target.
#3205 opened 5 days ago by Cabro
can't train leatherworking
#3204 opened 5 days ago by Davidspencer1982
Charge/Intercept scripts movement.
#3203 opened 5 days ago by Cabro
Nefarian warrior call is removing stances.
#3202 opened 5 days ago by Cabro


https://webcache.googleusercontent.com/search?q=cache:qwo7MuCRNWcJ:https://github.com/elysium-project/server/issues+&cd=2&hl=en&ct=clnk&gl=au%20bfgghfbhhg

https://webcache.googleusercontent.com/search?q=cache:17FlVTIln9gJ:https://elysium-project.org/bugtracker/%3Fnpc%3D311%26page%3D2+&cd=5&hl=en&ct=clnk&gl=au&client=firefox-b-ab

**Comment by Cabro** [comment]
Oh no, they killed the old bug tracker? fml, so many bugs opened.

**Comment by Cabro** [comment]
Not doing this on Lightbringer.
