### ISSUE TITLE
AV: Honor rewards

### ISSUE THREAD

**Issue by Hatredshit** [LightsHope/server#525]
Honor rewards are incorrect. Some may be correct, havent seen all of it.
For example, i gained 43 Honor for killing Galvangar and destroying Iceblood Tower.

http://vanilla-wow.wikia.com/wiki/Honor_System#Alterac_Valley

http://web.archive.org/web/20051031100234/http://worldofwarcraft.com/pvp/battlegrounds/info-alteracvalley.html
1 Bonus Kill = 198 Bonus Honor

A few mentions of Honor gains: 
http://beta.mortalken.com/reputation/alterac/
http://www.wtfman.com/jov/oldguildnews/nov02-oct06.htm

https://youtu.be/6wSXnyVZz_A?t=43s
Video shows 1584 of Bonus Honor. Most likely from AV Weekend.
(Maximum Honor someone on that Scoreboard got is 5742)

The following table is from the above links, just so it is handy/ready.

### Non-Weekend Honor gains:
    Killing the enemy General = 792 Bonus Honor
    Killing the enemy Captain = 198 Bonus Honor
    Killing enemy Lieutenants/Commanders = 198 Bonus Honor
    Destroying an enemy tower = 198 Bonus Honor
    Keeping your captain alive (until game end) = 198 Bonus Honor
    Owning an intact tower (at game end) = 198 Bonus Honor per Tower 
    Owning a graveyard (at game end) = 198 Bonus Honor per Graveyard
    Owning a Mine (at game end) = 198 Bonus Honor per Mine

### Additional Honor gains during AV Weekend:
    Winning the match = 396 Bonus Honor
    Winning or Loosing = 1584 Bonus Honor

**Comment by berillis** [comment]
Should also check if the reputation gains are correct. I remember getting around 10-30 reputation for a destroyed bunker, which seems very underwhelming.
