### ISSUE TITLE
Redemption

### ISSUE THREAD

**Issue by Paladinski** [LightsHope/server#528]
Quest Redemption is bugged, 

quest giver tirion fordring

no dialog opens or anything happens when u accept quest

**Comment by berillis** [comment]
Read the quest text and don't rely on addons.

**Comment by Paladinski** [comment]
quest redemption from eastern plaguelands where u need to talk to tirion fordring, and i cant talk to him



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Kolmarwow** [comment]
type /sit when speaking to him to activate dialogue options

**Comment by Paladinski** [comment]
*facepalm*



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
