### ISSUE TITLE
GET IT RIGHT!!!! improved shadowbolt debuff

### ISSUE THREAD

**Issue by Aliveprogress** [LightsHope/server#529]
This report is about the "improved shadowbolt" debuff from the destruction tree of the warlock talents. The talent reads as follows (5/5) 
"Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec."
I'd like to emphasize the portion that says NON-PERIODIC DAMAGE SOURCES. 

CURRENT BUG: periodic damage sources such as dots and channeled shadow spells are consuming 1 stack of the debuff when they are first applied. example: 4 stacks are up, shadow word pain is applied, and 1 stack is consumes. this is the same case for any shadow DoT, or any channel such as drain soul or Mind flay. 

This is NOT working as intended and is a significant decrease in all Warlock damage on the whole server. this is a CRUCIAL debuff that makes warlock damage competitive. 
I know that "on nostalrius" and here, dots are doing 20% more damage each tick when improved shadowbolt is on the boss. This is also a common bug between private servers that, to my knowledge, had never been able to be fixed. However, having dot applications and channel spell application take off a stack is unacceptable and far from what is intended. The talent is very clear in what is intended here and what is actually happening on the server is not what the talent entails.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/57
