### ISSUE TITLE
you reached the ingame cap of the unique mail recipients

### ISSUE THREAD

**Issue by ploughmeister** [LightsHope/server#535]
When someone wants to send me an ingame mail, this person gets the error "you reached the ingame cap of the unique mail recipients". it occured when elysium devs removed the unexpiring Battleground marks in the mailbox.

**Comment by Ripper007** [comment]
Means you reached the cap of items that you can hold in mail and no one can send anything until you clear some of the items.

**Comment by ploughmeister** [comment]
I know but i have an empty mailbox since weeks and cant recieve anything

**Comment by Wippeno** [comment]
Bump

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
