### ISSUE TITLE
Missing mail COD past 30 days

### ISSUE THREAD

**Issue by Nyatsuelysium** [LightsHope/server#536]
Hi, I sent 7 grilled squid in a COD to someone over 30 days ago and it has not returned.. Was told by GM to post it here. My character name is Nyatsu.

thx

**Comment by Nyatsuelysium** [comment]
bump

**Comment by Wippeno** [comment]
Bump

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123

**Comment by Nyatsuelysium** [comment]
My missing items have returned! Took more than 30 days though!
