### ISSUE TITLE
Alliance has no graveyard in Tirisfal.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#541]
Alliance should have graveyard@ Bulwark, close to the border with WPL, not all the way in WPL base.

**Comment by GuybrushGit** [comment]
>Patch 1.6.0 (12-Jul-2005):
>The Ruins of Lordaeron above Undercity now has a Horde-only graveyard. Horde characters dying inside the Undercity will use this new graveyard. Alliance characters will continue to solely use the Faol's Rest graveyard.

**Comment by Cabro** [comment]
Ooooh, it must be they changed it to bulwark GY sometime in TBC. That other GY is also good.
