### ISSUE TITLE
Hunter Spells

### ISSUE THREAD

**Issue by Asmindia** [LightsHope/server#542]
My hunter spells are not working. they are grayed out like im out of mana. Any solutions? Ive deleted cache and restarted without addons. Im lvl 12 nelf. Raptor strike and hunters mark is the only spells available.

**Comment by Asmindia** [comment]
forgot to add that its on Anathema server and its 122 MST

**Comment by vindruvor** [comment]
Have you equipped arrows/bullets?

**Comment by Asmindia** [comment]
I did, but it still didnt work. Im on #3 hunter and have made it past 12 so
hopfully I wont have to reroll again
