### ISSUE TITLE
warlock succubus quest

### ISSUE THREAD

**Issue by Cronopia** [LightsHope/server#549]
Elysium, 1.12.1 (5875)

i take the succubus quest (http://www.wowhead.com/quest=1476/hearts-of-the-pure) and then drop it because my log was close to be full and now i cant take it again, the npc's dont show the quest, only see a gray mark i think is for felhunter quest. same issue in orgrimar and undercity.

![lock1](https://user-images.githubusercontent.com/33502336/32582539-1b732f02-c4ce-11e7-8a54-ad85d7dbce07.jpg)
![lock2](https://user-images.githubusercontent.com/33502336/32582540-1ba6f2f6-c4ce-11e7-8c00-e41b46ea2917.jpg)

thank you! sorry for my english!

**Comment by GuybrushGit** [comment]
You most likely completed some of the quests but not all, talk to any of the npcs in these chains:
http://vanillawowdb.com/?quest=1472
http://vanillawowdb.com/?quest=1507

**Comment by Cronopia** [comment]
you're rigth sorry for the post !
