### ISSUE TITLE
[Anathema] Bonereaver's Edge still stacking to 3

### ISSUE THREAD

**Issue by Waveridge** [LightsHope/server#555]
It was fixed when Elysium launched but broken in AQ patch.

https://web.archive.org/web/20060629120704/http://wow.allakhazam.com:80/item.html?witem=17076

Shouldn't stack to 3 until TBC, afaik. Trying to find more info.

https://github.com/elysium-project/server/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20bonereaver%27s%20edge

https://github.com/LightsHope/server/issues/47 Seems it was closed before.

**Comment by tyrachnydia** [comment]
shhhhttt
