### ISSUE TITLE
Lost COD item

### ISSUE THREAD

**Issue by Aithys** [LightsHope/server#563]
I submitted a gm ticket in game and I was referred here to the bug tracker. 

I am Aithys on the Elysium PvP server. I sent a pair of Bloodvine Leggings to another user "Adalberta" for 120g COD on the 3rd of November. It is now the 10th of November and I have not received any gold or the item returned in the mail. It was my understanding that COD items were returned after 3 or 4 days. Also I have not seen Adalberta logged in so I have not been able to ask them if they received my COD or sent the gold back or anything so I don't know the case there whether its sitting in their mailbox still or lost in the mail or what. If this could please be looked into and the item returned to me I would much appreciate it. 

Thanks.

**Comment by Nyatsuelysium** [comment]
CODs are supposed to return after 30 days. I've opened a ticket about lost items too, however in my case it's been over 30 days.

**Comment by Cabro** [comment]
On "another" private servers there was a bug where the CoD wasn't returning to the sender after 30 days, but it was returned to the recipient. Maybe this is the same case here?

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
