### ISSUE TITLE
AV : unable to loot and missing commander

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/server#566]
Dear support,

1) this character
http://db.vanillagaming.org/?npc=13179
is unfoundable, so may be i miss it , or may be she is not here

2) Loot in alterac
2.1)I saw people looting ivius
http://db.vanillagaming.org/?quest=6881
i have a screen shot if required, but i dont want to pointed those players, i m just wondering, why there was no rand
2.2)my character can loot the body of players and most of the npc (like the alliance guards..)
BUt not the npc in the mine when i solo it, not the frostwolf when i kill them alone
So after doing a request to a game master, it seems required to post this here.

Thanks for your attention

**Comment by GuybrushGit** [comment]
1. NPC is there
2.1 Duplicate
2.2 Can't reproduce
