### ISSUE TITLE
quest : another message to the wildhammer

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/server#568]
hi
my character took the quest "another message to the wildhammer"
i accepted it 
but
 idkw i dont see it in my quest log,
and there is still a "!" on the quest giver Otho Moji'ko

BUT when i m talking to him, he doesnt propose the quest or any discussion linked to the quest, only the "i want to browse ur goods..." is avalable

BR

**Comment by cnzjs** [comment]
no avaible at this patch I guess.

**Comment by GuybrushGit** [comment]
Quest is not acceptable for levels over 48 due to pvp flag. Its a bug.

**Comment by brotalnia** [comment]
@GuybrushGit I think we should add a MaxLevel column to quest_template to solve this. We can just set the max level for the PvP quests that should have one, and this would let us get rid of the current logic it uses which is wrong.
