### ISSUE TITLE
DoT spells taking charges from Shadow Vulnerability Warlock Debuff

### ISSUE THREAD

**Issue by kevmodrome** [LightsHope/server#57]
DoT spells like Corruption, Curse of Agony and Shadow Word: Pain are removing charges from the warlock talent debuff "Shadow Vulnerability". This is not the correct behaviour. Only non-periodic sources of damage should remove charges. This actually has a huge impact on DPS, especially if one is running with a Shadow Priest in the raid (basically eating up to 25% of the charges generated by the warlocks, depending on how many you have in the raid).

I am not certain if Drain Life and Mind Flay should take charges as well but I would assume not, since they are periodic. More research might be needed though.

**Comment by Imbaslap** [comment]
i thought Guybrush fixed this already?
bah humbug.

**Comment by kevmodrome** [comment]
Pretty sure he only fixed Curse of Shadow when I reported the bug happening on that spell.

**Comment by volkain5** [comment]
this needs to be reopened

**Comment by Aliveprogress** [comment]
please fix this. I made a post as well "GET IT RIGHT!!!! improved shadowbolt debuff #529 " but nothing is being done about it. we are just being ignored

there WAS a bug on the server where stacks were never consumed, but even that is closer to "correct" than what this current state is
