### ISSUE TITLE
safespotting abuse

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/server#573]
CF title & GM request:

![1](https://user-images.githubusercontent.com/33297493/32668141-0fb18bb2-c63d-11e7-9c96-f08a4d4c332b.PNG)
![2](https://user-images.githubusercontent.com/33297493/32668142-0fcdbc06-c63d-11e7-9fe5-506fab54d77c.PNG)
![3](https://user-images.githubusercontent.com/33297493/32668143-0fe9f01a-c63d-11e7-879c-7ec7696524e9.PNG)

I think this issue doesnt need any explanation right?

BR

**Comment by GuybrushGit** [comment]
Make a GM ticket.

**Comment by SuperHeroesAlwaysdie** [comment]
done, and the gm answered me post it on github.
