### ISSUE TITLE
Tier 3 Bonescythe - 6 set bonus doesnt work.

### ISSUE THREAD

**Issue by AskeH** [LightsHope/server#576]
The 6 set bonus is supposed to reduce the threat of some of the rogue abilities:
[http://db.vanillagaming.org/?item=22479](url)

However it doesnt work. I have tried to look for sources to see how much the threat reduction should be, but I havent found any sources. 

I did 3 test samples:
I tried 2 samples with 6 piece of tier 3 on me, which gave me the following results:
20512 yellow dmg from sinister strike were turned into 14564 threat
20429 yellow dmg from sinister strike were turned into 14505 threat

After this I did 1 sample with only 5 piece of tier 3 on me, which gave me the following result:
20575 yellow dmg from sinister strike were turned into 14608

With or without the set bonus, the threat factor from dmg vs. threat was the same. 
I was using KTM 17.35 for the testing.

Best regards.

**Comment by Cabro** [comment]
Are you sure KTM even has the T6 bonus in its formula? Oo
The only way to properly threat is on PTR, or with GM commands.

**Comment by AskeH** [comment]
I did it on PTR though, however not with GM commands to check things. Only used KTM, so that might be the issue. How can I check it so that Im 100 % sure?

**Comment by Cabro** [comment]
Btw the link you gave in the first comment is .... meh.
You need GM commands to see the threat.

**Comment by AskeH** [comment]
Dunno why the link doesnt work. I know that DB vanilla isnt an official source, but since its the same set bonus in game as well as on db vanilla, I didnt really find another link since it was just to show the:"6 pieces: Reduces the threat from your Backstab, Sinister Strike, Hemorrhage, and Eviscerate abilities."

I wasnt sure if I had worn 6 or 7 pieces, but I tried again with 6 pieces, and the result were the same. The threat factor was a 0,71*dmg done (With yellow attacks as well as for white hits)

Appreciate your time doing this!

**Comment by GuybrushGit** [comment]
Tested with debugger. Threat is being reduced.
