### ISSUE TITLE
Gear being disenchanted that wasn't clicked

### ISSUE THREAD

**Issue by CalonnHumanPriest** [LightsHope/server#577]
Hi!

I am hoping to get some help. I believe I found a unique bug when disenchanting. I received new t1 bracers and enchanted it. After equipping it, I disenchanted my old pair of bracers and POOF my new bracers that were equipped went missing.

Can anyone help here? It happened last night around 2am ET.

Thank you

-Calonn

**Comment by GuybrushGit** [comment]
Can't reproduce.

**Comment by CalonnHumanPriest** [comment]
Hmmm - what do you guys even do if you can't help with in game bugs?

**Comment by berillis** [comment]
Pretty sure you misclicked.
