### ISSUE TITLE
Can't select/activate some ground selection spells while moving (i.e. Blizzard)

### ISSUE THREAD

**Issue by semprevivo** [LightsHope/server#58]
I've only tested this on the Mage. While moving you are unable to select spells like Blizzard or Flame Strike. You have to stop moving, select/activate the spell, then begin moving  again to keep the ground selector on your cursor while waiting for the right time to *click* and actually cast the spell.

**Comment by lovemonkeyz** [comment]
Can confirm this occurs with Hunter Volley as well, and it causes a lot of issues because you need to actually fully stop to get the targeting circle.

**Comment by brotalnia** [comment]
I think that's a client issue.

**Comment by thepparker** [comment]
Client side limitation, resolved in a later expansion
