### ISSUE TITLE
Possible Ivus and Lokholar missing items from their loot tables.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#582]
http://web.archive.org/web/20060524200137/http://wow.allakhazam.com:80/db/mob.html?wmob=13256
http://web.archive.org/web/20060526204612/http://wow.allakhazam.com:80/db/mob.html?wmob=13419

They are missing the head and swords from their loot tables from what i see on the database.
http://db.vanillagaming.org/?item=19105
http://db.vanillagaming.org/?item=19110

Also please recheck their drop chance % because it also looks off on the database.

**Comment by Aklol** [comment]
http://realmplayers.com/ItemUsageInfo.aspx?realm=Ely&item=19105
http://realmplayers.com/ItemUsageInfo.aspx?realm=Ely&item=19110

?

**Comment by Cabro** [comment]
The website with the database could use some updating tbh.
