### ISSUE TITLE
My world proccess gives all time info

### ISSUE THREAD

**Issue by Locario** [LightsHope/server#583]
Hi there,

I have compiled the release core under trusty ubuntu linux, i have no tools to extract maps (i have used an old ones), also, when i run mangos all the time gives output info, if i press enter i can see "mangos>" prompt but it dissapear in seconds because too much output info,

can i remove all that info to see "mangos>" prompt quiet? how i can compile extractors?

Thanks all and sorry my english

**Comment by brotalnia** [comment]
Use the Giperion branch to compile extractors. Change the LogLevel in mangosd.conf to 0 so it does not spam in the console.

**Comment by Locario** [comment]
Tnx for the response Brotalnia,

I have this errors compiling Giperion branch:

cc: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [dep/src/zlib/CMakeFiles/zlib.dir/adler32.c.o] Error 1
make[1]: *** [dep/src/zlib/CMakeFiles/zlib.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[  6%] Built target g3dlite
make: *** [all] Error 2

What can be the problem?

**Comment by brotalnia** [comment]
Yes, that doesn't matter.

**Comment by Locario** [comment]
Thanks for all Brotalnia!
