### ISSUE TITLE
"Valik" not working

### ISSUE THREAD

**Issue by Laivoriz** [LightsHope/server#584]
On the Elysium server, the questgiver Henchman Valik in the Alterac Mountains cannot be spoken to and thus he can't give the quest "Valik", he is just attackable.

**Comment by GuybrushGit** [comment]
Are you alliance? NPC is only friendly to horde.

**Comment by Laivoriz** [comment]
I thought he was neutral since his quest is not marked as a faction one, thanks for the help.
