### ISSUE TITLE
Mail box  problem  please help!!

### ISSUE THREAD

**Issue by qqjydeng** [LightsHope/server#585]
--
Dear GM 
My  mail box gots a problem . there is a icon beside the minimap.  But i cant see the mails in mailbox.
And im sure they are the mats i bought  from AH  beforelong. I didnt have many bags so I kept them in mailbox.
But now  I cant see them.  Please help  and fix .
server: Elysium  alliance
account   : qqjydenged   
char: lvl48  elf  druid    : Diviciacus
Already delete all WDB WTF  INTERFACE ADDONS!!!!  DOESNT WORK!!

**Comment by Wippeno** [comment]
Bump

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
