### ISSUE TITLE
[Anathema] Warlock - Improved Shadow Bolt Talent

### ISSUE THREAD

**Issue by mnoser** [LightsHope/server#59]
https://github.com/elysium-project/server/issues/3157

Moving over to this repository

Improved Shadow Bolt is consuming charges when dots are applied.

Examples: Corruption, Curse of Agony, Siphon Life all consumed a charge when applied.
Edit: Also noticed warlock pets consuming charges when using a pet ability.

Curse of Shadow, Elements etc. did not - this was fixed previously.
See - #920

Thanks

Edit: https://elysium-project.org/updates/2017-09-08
This update may have something to do with it.

Abilities
Reworked when some spell procs are performed
Periodic spells should now properly trigger on cast rather than being delayed to the first tick
Abilities that are triggered on periodic damage will still only proc on periodic damage
Re-added a previous change for channeled spells that prevents ticks being lost
Unique spell cast speed modifiers will now stack properly
Spells that are affected by heartbeat resists are now properly affected by Diminishing Returns
Spells that cast on the next melee swing should now be more consistent with triggering extra auto attacks
Spells which are being casted on players that release their corpse, or accept a resurrection, are now cancelled
Dispel abilities will now trigger other effects properly

**Comment by GuybrushGit** [comment]
Same as https://github.com/LightsHope/server/issues/57

**Comment by mnoser** [comment]
Whoops, did not see this was already posted sorry!
