### ISSUE TITLE
"Pirate Hats Ahoy!" and "Southsea Shakedown" not working

### ISSUE THREAD

**Issue by Laivoriz** [LightsHope/server#594]
On the Elysium server, the questgivers Haughty Modiste and Security Chief Bilgewhizzle in Tanaris cannot be spoken to and thus they can't give the quests "Pirate Hats Ahoy!" and "Southsea Shakedown", they cannot be interacted.

**Comment by Nelythia** [comment]
Working as intended, they weren't in the game until patch 1.8 and Ely is on 1.7
