### ISSUE TITLE
Invisible BG mark mails not expiring and filling mailbox

### ISSUE THREAD

**Issue by Manlet** [LightsHope/server#599]
A little over a month ago, an unannounced change went live which aimed to correct the BG mark mails not expiring after 24h (prior to this they lasted 30days then expired and deleted).

Instead what seems to have happened is that these mail (BG marks) are now hidden, invisible, and NEVER expire.

This means that many people have permanently full mailboxes, long after the 30day period where they would have been deleted before this change. I am still unable to receive any mail at all from players or my bank alts, and when I look at my mailbox it appears empty. Whenever I log in it says I have unread mail, still empty.

**Comment by Wippeno** [comment]
Bump

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
