### ISSUE TITLE
extractor tool problems (mmap)

### ISSUE THREAD

**Issue by lduguid** [LightsHope/server#6]
Is there clear documentation anywhere on the voodoo required to successfully produce working vmaps (producing all necessary extracted WMO's) and mmaps with the current **development** build?

With some adjustments, I have  been successful in creating both 32 and 64 builds of the **server** on Ubuntu 17.4 (32-bit), Debian Jessie (64-bit) and Windows (32bit).  I can typically get the **extractors** to build as well but there does seem to be missing bits in their various cmake files.  

I have tried creating extractors on all the platforms above with various branches, including Gipperion, development, release etc. with each having different outcomes.  Some crashing when producing mmaps, some producing incomplete wmo's in  the buildings folder, some creating all the mmaps but crashing the development server at start up. etc.  

Any suggestions appreciated.

**Comment by GuybrushGit** [comment]
You can generate mmaps using this branch: https://github.com/elysium-project/server/tree/Giperion

**Comment by lduguid** [comment]
Thank you for the quick reply.

I believe I tried that branch as well without luck.  Using the Giperion branch, should i build the extractor tools 32bit or 64bit or it does not matter?  

Should I be using all the extractor  tools from Giperion i.e. (ad, vmap_extractor, vmap_assembler, MoveMapGen) or just MoveMapGen for the mmaps and the rest from development?

**Comment by Road-block** [comment]
> Should i build the extractor tools 32bit or 64bit or it does not matter?

> Should I be using all the extractor tools from Giperion i.e. (ad, vmap_extractor, vmap_assembler, MoveMapGen) or just MoveMapGen for the mmaps and the rest from development?

I built 64bit release versions personally and I went the latter way.
- Used the tools aside MoveMapGen from dev branch.
- Used MoveMapGen from Giperion branch for mmaps. (took all night to generate)

_On windows using the Win10 sdk as a platform._

**Comment by brotalnia** [comment]
Here are compiled extractors for windows -> https://github.com/elysium-project/server/files/852498/Elysium.Extractors.18.March.zip

**Comment by lduguid** [comment]
Update: To potentially save someone else some time in the future, after much mucking about and returning to this after a break, for windows platform, was only able to get it to build and work fully with server using 64 bit release and Giperion branch MoveMapGen,  and other extractor tools from development branch. (as mentioned above by Road-block).
