### ISSUE TITLE
PACKS NOT CONNECTED

### ISSUE THREAD

**Issue by Nyatsuelysium** [LightsHope/server#600]
A lot of packs in the game are not connected properly so you can often pull some mobs solo even though they are supposed to be linked - For example you can pull Araj in WPL alone without the surrounding mobs.

This is really basic so I'm surprised it's an issue - Could it be like this in raids too?

**Comment by GuybrushGit** [comment]
https://www.youtube.com/watch?v=mf5A6JFVcCY
