### ISSUE TITLE
Paladin cant 'Divine Shield' and pick herbs 

### ISSUE THREAD

**Issue by alfredSss** [LightsHope/server#601]
Hi, I have already posted this issue (#283) but it was closed for an incorrect reason. The person who closed it linked #228 however that issue was relating to 'blessing of protection' and not 'divine shield'

https://github.com/LightsHope/server/issues/283
https://github.com/LightsHope/server/issues/228

So the issue is that paladins can't currently use divine shield and pick herbs. This used to work just fine on the elysium realms but since the move to Lights hope we can no longer do it and receive the message: 'you can't do that while immune' .

**Comment by knasen88** [comment]
pretty sure it was patched so that you can't bubble and uncontested pick a herb/box

**Comment by alfredSss** [comment]
Patched by who? lights hope or bliz? 

I've been told by many people that casting bubble and picking a herb was possible in retail vanilla

**Comment by knasen88** [comment]
https://wow.gamepedia.com/Patch_0.6

Players can no longer loot or use items while invulnerable.

**Comment by Cabro** [comment]
Just a side note, if you receive the bubble while you are already casting, it should finish the cast and get a big "failed" at the end of the cast.

**Comment by knasen88** [comment]
use items as in AB flags, not items in bags

**Comment by Cabro** [comment]
Oh i dont know where my mind was. You are correct.

**Comment by QAkvastskaft** [comment]
http://wowwiki.wikia.com/wiki/Patch_0.6?oldid=26360

**Comment by knasen88** [comment]
also i wanna add, @QAkvastskaft u can at this moment pick herbs with LIP up

**Comment by Cabro** [comment]
LIP is not immunity, it only affects physical. Spells go through.
