### ISSUE TITLE
Unable to recall character.md

### ISSUE THREAD

**Issue by ecolization** [LightsHope/server#606]
Write your report here... Player 'Ecolization' is no longer accessible on Elysium server. New characters can me made successfully.

WoWBuild: 5875
Local Zone: Dun Morogh
Local Player: Unknown, 0000000000AAC9E9, (-6016.61,-270.158,418.165)

=========================================================
Assertion Failed!

 App:         /Users/ericcollins/Downloads/WoW-1.12.1-enUS-Mac/World of Warcraft.app
 File:        ../../../Engine/Source/Tempest/cmath.h
 Line:        447
 Time:        2017-11-12 15.49.51 EST

 Assertion:   "x >= .0f", x = nan

---------------------------------------------------------

Thread 0 (Crashed)
  0 0x001cd145 
  1 0x00027c71 
  2 0x00027fde 
  3 0x00005050 
  4 0x0000571e 
  5 0x0027b3b1 
  6 0x00226804 
  7 0x00050f9c 
  8 0x00051e0a 
  9 0x000568e2 
 10 0x00056be8 
 11 0x00056c97 
 12 0x001d50bd 
 13 0x001d9340 
 14 0x001da47a 
 15 0x001da6f6 
 16 0x0000f1ed 
 17 0x00004085 
 18 0x936275a4  InvokeEventHandlerUPP(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*, long (*)(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*))+0024
 19 0x93465681  DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)+08f3
 20 0x9346465c  SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)+0192
 21 0x934644c3  SendEventToEventTargetWithOptions+005f
 22 0x9349e59a  ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)+0778
 23 0x93465a4b  DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)+0cbd
 24 0x9346465c  SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)+0192
 25 0x93478f25  SendEventToEventTarget+0058
 26 0x93626d25  ToolboxEventDispatcher+0052
 27 0x93626be9  RunApplicationEventLoop+00f0
 28 0x000041b6 
 29 0x00003172 
 30 0x0000308d 
 31          

Thread 1 
  0 0x95bcb8ce  kevent64+000a
  1 0x90217ce3  dispatch_mgr_invoke+00f5
  2 0x902178c6  dispatch_mgr_init+0000
  3          

Thread 2 
  0 0x95bcae6a  workq_kernreturn+000a
  1 0x94ca872a  pthread_wqthread+03ab
  2 0x94ca5e0e  start_wqthread+001e
  3          

Thread 3 
  0 0x95bcae6a  workq_kernreturn+000a
  1 0x94ca872a  pthread_wqthread+03ab
  2 0x94ca5e0e  start_wqthread+001e
  3          

Thread 4 
  0 0x95bcae6a  workq_kernreturn+000a
  1 0x94ca872a  pthread_wqthread+03ab
  2 0x94ca5e0e  start_wqthread+001e
  3          

Thread 5 
  0 0x95bcae6a  workq_kernreturn+000a
  1 0x94ca872a  pthread_wqthread+03ab
  2 0x94ca5e0e  start_wqthread+001e
  3          

Thread 6 
  0 0x95bc49ce  mach_msg_trap+000a
  1 0x95bc3a70  mach_msg+0044
  2 0x9656996c  glcDebugListener+01cc
  3 0x94ca8c25  pthread_body+008a
  4 0x94ca8b9b  pthread_body+0000
  5 0x94ca5e32  thread_start+0022
  6          

Thread 7 
  0 0x0047c44a 
  1 0x00382e17 
  2 0x001e201b 
  3 0x001e1d65 
  4 0x001ce651 
  5 0x001d1011 
  6 0x001252bd 
  7 0x0008926f 
  8 0x000b3809 
  9 0x000b39f6 
 10 0x9737db6d  -[NSThread main]+002d
 11 0x9737d916  NSThread__main__+0602
 12 0x94ca8c25  pthread_body+008a
 13 0x94ca8b9b  pthread_body+0000
 14 0x94ca5e32  thread_start+0022
 15          

Thread 8 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94ca8e88  pthread_cond_wait+0030
  3 0x0019f2cb 
  4 0x0003287d 
  5 0x000b3809 
  6 0x000b39f6 
  7 0x9737db6d  -[NSThread main]+002d
  8 0x9737d916  NSThread__main__+0602
  9 0x94ca8c25  pthread_body+008a
 10 0x94ca8b9b  pthread_body+0000
 11 0x94ca5e32  thread_start+0022
 12          

Thread 9 
  0 0x95bc49ce  mach_msg_trap+000a
  1 0x95bc3a70  mach_msg+0044
  2 0x94705b80  HALB_MachPort:+008e
  3 0x946fe6d0  HALB_MachPort:+0048
  4 0x946fcbf0  HALC_ProxyIOContext:+052e
  5 0x946fc59a  HALC_ProxyIOContext:+009c
  6 0x94708cd9  invocation function for block in HALC_ProxyIOContext:+0014
  7 0x946fc4b1  HALB_IOThread:+00ad
  8 0x94ca8c25  pthread_body+008a
  9 0x94ca8b9b  pthread_body+0000
 10 0x94ca5e32  thread_start+0022
 11          

Thread 10 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94caa197  pthread_cond_timedwait+002f
  3 0x0019f1c5 
  4 0x00432c95 
  5 0x000b3809 
  6 0x000b39f6 
  7 0x9737db6d  -[NSThread main]+002d
  8 0x9737d916  NSThread__main__+0602
  9 0x94ca8c25  pthread_body+008a
 10 0x94ca8b9b  pthread_body+0000
 11 0x94ca5e32  thread_start+0022
 12          

Thread 11 
  0 0x95bca86a  select_nocancel+000a
  1 0x95bc7a4d  select+005c
  2 0x00378a81 
  3 0x000b3809 
  4 0x000b39f6 
  5 0x9737db6d  -[NSThread main]+002d
  6 0x9737d916  NSThread__main__+0602
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 12 
  0 0x95bca86a  select_nocancel+000a
  1 0x95bc7a4d  select+005c
  2 0x00378a81 
  3 0x000b3809 
  4 0x000b39f6 
  5 0x9737db6d  -[NSThread main]+002d
  6 0x9737d916  NSThread__main__+0602
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 13 
  0 0x95bca86a  select_nocancel+000a
  1 0x95bc7a4d  select+005c
  2 0x00378a81 
  3 0x000b3809 
  4 0x000b39f6 
  5 0x9737db6d  -[NSThread main]+002d
  6 0x9737d916  NSThread__main__+0602
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 14 
  0 0x95bca86a  select_nocancel+000a
  1 0x95bc7a4d  select+005c
  2 0x00378a81 
  3 0x000b3809 
  4 0x000b39f6 
  5 0x9737db6d  -[NSThread main]+002d
  6 0x9737d916  NSThread__main__+0602
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 15 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94caa197  pthread_cond_timedwait+002f
  3 0x0019f1c5 
  4 0x001cabe6 
  5 0x001cac56 
  6 0x000b3809 
  7 0x000b39f6 
  8 0x9737db6d  -[NSThread main]+002d
  9 0x9737d916  NSThread__main__+0602
 10 0x94ca8c25  pthread_body+008a
 11 0x94ca8b9b  pthread_body+0000
 12 0x94ca5e32  thread_start+0022
 13          

Thread 16 
  0 0x95bca86a  select_nocancel+000a
  1 0x95bc7a4d  select+005c
  2 0x001ca042 
  3 0x001cb00a 
  4 0x000b3809 
  5 0x000b39f6 
  6 0x9737db6d  -[NSThread main]+002d
  7 0x9737d916  NSThread__main__+0602
  8 0x94ca8c25  pthread_body+008a
  9 0x94ca8b9b  pthread_body+0000
 10 0x94ca5e32  thread_start+0022
 11          

Thread 17 
  0 0x95bc49ce  mach_msg_trap+000a
  1 0x95bc3a70  mach_msg+0044
  2 0x92c78d96  CFRunLoopServiceMachPort+00d6
  3 0x92c781a9  CFRunLoopRun+05f9
  4 0x92c77946  CFRunLoopRunSpecific+0186
  5 0x92c777ab  CFRunLoopRunInMode+007b
  6 0x95f17dbf  +[NSURLConnection(Loader) _resourceLoadLoop:]+02cd
  7 0x9737db6d  -[NSThread main]+002d
  8 0x9737d916  NSThread__main__+0602
  9 0x94ca8c25  pthread_body+008a
 10 0x94ca8b9b  pthread_body+0000
 11 0x94ca5e32  thread_start+0022
 12          

Thread 18 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94ca9e68  pthread_cond_timedwait_relative_np+002f
  3 0x94017811  TSWaitOnConditionTimedRelative+00a7
  4 0x94017370  TSWaitOnSemaphoreCommon+01f3
  5 0x9401756b  TSWaitOnSemaphoreRelative+0018
  6 0x91a58282  SDH_ComponentDispatch+4bea
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 19 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94ca9e68  pthread_cond_timedwait_relative_np+002f
  3 0x94017811  TSWaitOnConditionTimedRelative+00a7
  4 0x94017370  TSWaitOnSemaphoreCommon+01f3
  5 0x9401756b  TSWaitOnSemaphoreRelative+0018
  6 0x93fba950  AIOFileThread(void*)+0392
  7 0x94ca8c25  pthread_body+008a
  8 0x94ca8b9b  pthread_body+0000
  9 0x94ca5e32  thread_start+0022
 10          

Thread 20 
  0 0x95bc4a0a  semaphore_wait_trap+000a
  1 0x91f2e42c  SGSoundComponentDispatch+6791
  2 0x91ac9fdc  Sound3ComponentDispatch+10b08
  3 0x91f2e1b6  SGSoundComponentDispatch+651b
  4 0x94ca8c25  pthread_body+008a
  5 0x94ca8b9b  pthread_body+0000
  6 0x94ca5e32  thread_start+0022
  7          

Thread 21 
  0 0x95bca84e  select+000a
  1 0x92cc8a3a  CFSocketManager+038a
  2 0x94ca8c25  pthread_body+008a
  3 0x94ca8b9b  pthread_body+0000
  4 0x94ca5e32  thread_start+0022
  5          

Thread 22 
  0 0x95bca512  psynch_cvwait+000a
  1 0x94ca91d7  pthread_cond_wait+034a
  2 0x94caa197  pthread_cond_timedwait+002f
  3 0x0019f1c5 
  4 0x0037afe6 
  5 0x000b3809 
  6 0x000b39f6 
  7 0x9737db6d  -[NSThread main]+002d
  8 0x9737d916  NSThread__main__+0602
  9 0x94ca8c25  pthread_body+008a
 10 0x94ca8b9b  pthread_body+0000
 11 0x94ca5e32  thread_start+0022
 12          
=========================================================

**Comment by jelgh** [comment]
Why was this closed? I have the exact same issue.

**Comment by jelgh** [comment]
https://forum.lightshope.org/viewtopic.php?f=9&t=8503
