### ISSUE TITLE
Warsong Gulch 10-19 unable to queue

### ISSUE THREAD

**Issue by stoutman1** [LightsHope/server#61]
Hello, 
Since launch it is impossible for any lvl 10-19 players (including mainly twinks) to queue or enter Warsong Gulch, simply by not receiving the option to queue from ANY battlemaster or even Emissary's from weekend battleground holiday.

I have posted this screenshot from my character displaying the character pane showing my level (13) and the emissary interaction box, which displays the correct text but no option to queue. In addition I have added the screenshot of the battlemaster in Orgrimmar on the right showing again, the correct text but no queue option.

Hopefully it is a simple fix that I'm sure alot of twinks and many low levels wanting early ranks would appreciate. :)

Thank you!
![warsong19](https://user-images.githubusercontent.com/32962287/31828400-07116cc0-b5b2-11e7-8b48-15e443562f88.png)

**Comment by stoutman1** [comment]
Strangely though, I tried my lvl 19 twink on Anathema and found you could queue just fine with no problems there.

**Comment by Cabro** [comment]
Probably the minimum level is not 10 as it should be.

**Comment by Sabre142** [comment]
Added in Patch 1.8 for 10-19.

**Comment by brotalnia** [comment]
This has been resolved with a custom patch and WSG is now available on Elysium realm.
