### ISSUE TITLE
Herb respawn rates

### ISSUE THREAD

**Issue by ninjalootah** [LightsHope/server#611]
Hello I am some random mass herb farmer and these spawn rates are awful currently.  Ever since a herb fix was done near the end of elysium, all herbs or at least the important ones (dreamfoil, silversage, etc). Had their respawn rates significantly reduced.  This is on the light ringer server.

You can see this in the over 100% increase in ah value of the herbs.  Black lotus is fine and working well.  The others since they are in a separate pool or w/e you call it are not working fine.

Lotus has a shorter respawn than any other herb in the game currently.  The rates of spawning are very close to the original blizzlike rates which sucks with the population.

Hope you increase them again!

Your friend,
    Neenjaaaa

**Comment by ninjalootah** [comment]
Unsure if it's been posted before but yeah, it's not correct at all.  It's been like this since launch due to a coding error during the last few days of elysium reign

**Comment by QAkvastskaft** [comment]
See #635
