### ISSUE TITLE
Seal Fate is (sometimes) not generating an extra combo point on CP builder crits. [Input/testing welcomed]

### ISSUE THREAD

**Issue by Slicy** [LightsHope/server#613]
http://db.vanillagaming.org/?spell=14189

5/5 is not always generating an extra combo point on crits from abilities initially generating one.

It remains unclear how/why is this happening. The bug is around since some years (https://forum.nostalrius.org/viewtopic.php?f=37&t=5817).

Has been noticed on Ambush and Sinister Strike. Possibly happening for any CP generating ability.

Usually gets fixed by relogging and/or after some time.

Possible interactions causing the bug to help trying to reproduce it :

    Cold Blood bugging out and remaining active even though an ability crit off it already happened.
    Remorless attacks talent interaction with Seal Fate.
    Mind control effect on the rogue.

**Comment by GuybrushGit** [comment]
Can't reproduce. Are you wearing any item sets that could affect this?

**Comment by Slicy** [comment]
No, item sets do no affect it. Which you can see just by looking at the picture posted in the forum thread, linked above.

**Comment by thepparker** [comment]
This might not be dissimilar to the impact bug where it was being removed by Ice Block. BoP or some other invuln may be removing the Seal Fate aura

**Comment by GuybrushGit** [comment]
@thepparker that was exactly it
