### ISSUE TITLE
Start-zone mobs PVP-flag players

### ISSUE THREAD

**Issue by Greyzore** [LightsHope/server#62]
On the Elysium realm, mobs at Tiragarde Keep near Razor Hill will PVP-flag players.

**Comment by Hsekr** [comment]
Its not a bug attacking opposite faction npcs/guards will flag you

**Comment by Greyzore** [comment]
I would assume the original blizz system had numerous factions, some which are friendly to H/A by default that behaved just as you say, some others being reputation based and maybe ... a couple factions being H/A aligned that would "not" auto-flag opposition.

**Comment by Cabro** [comment]
Those mobs weren't flagging you for PVP on retail. They were not Guards or alliance NPCs.

**Comment by GuybrushGit** [comment]
https://youtu.be/YcEqpVfrE7U?t=181
