### ISSUE TITLE
Mara Sceptre Quest

### ISSUE THREAD

**Issue by MitchellSQL** [LightsHope/server#620]
I spent about two hours getting two required pieces for the sceptre to Mara. I turned them into the NPC inside the instance. He walked over to the stone where he was supposed to perform some ritual and then he stood there and did nothing. After a long period of time he disappeared and I lost my two items for quest. Apparently nothing GMs can do to help so I am just making you aware of this issue.

Thanks.

**Comment by dimefox** [comment]
Did some testing on 7046: The Scepter of Celebras and looks only the original player to accept the quest is able to complete it. And he doesn't respawn after completion so other party members can't even restart the event.

Also looks like Celebras is supposed to offer a new scepter to people who destroyed theirs but he doesn't.

**Comment by berillis** [comment]
The Quest worked fine before Light's Hope.

**Comment by GuybrushGit** [comment]
Just tested and it works fine. After 1 player gets the scepter another can take the quest again.

**Comment by dimefox** [comment]
Yeah, i see that the quest has party flag so other party members will have to drop it, but then it works fine.

I also see the menu texts for offering the new scepter are now in broadcast text so i'll look into adding that menu for him.
