### ISSUE TITLE
Linken's Adventure 12th quest in 13 part chain.

### ISSUE THREAD

**Issue by tmfpena** [LightsHope/server#630]
Let me start by thanking you guys for taking the time to review and for a wonderful server that you have provided.

Level 51 Dwarf Paladin, Vurduinn, Elysium Server.

Link to quest http://db.vanillagaming.org/?quest=3961

Cannot acquire #12 (Linken's Adventure) in Un'Goro which leads to the #13 part (It's Dangerous to Go Alone). I have completed the quest before (#11 Aquementas) which gave me the ability to accept the next quest #12(Linken's Adventure) but upon clicking accept nothing happened. I eventually exited out of the accept or decline quest option and the quest disappeared. 

Tried to contact the GM but they contacted me when I was afk and left me a note telling me to "Report this to bugtracker". If I cannot get this resolved here then I will have to contact the GM's again and ask them to reset the quest for me.

-------------------------------------
Item-Silver Totem of Aquementas
Take the Silver Totem of Aquementas to Linken in Marshal's Refuge. 

To think all this time that the reason Linken came here was to rid us of Blazerunner... He seems like such an ordinary guy, but I did notice that he's not at all interested in any of my experiments or gadgets like most gnomes would be. He must be a true warrior at heart.

Bring the totem to him. See if that helps him remember why he came here.

**Comment by Cabro** [comment]
Most likely incorrect level requirement for the quest you seek :)

**Comment by tmfpena** [comment]
The quest on the info says level 48 required.

**Comment by Cabro** [comment]
I see "Requires level: 54". Most likely a random value added by someoen that didnt check blizzlike numbers. This is the bug.

**Comment by tmfpena** [comment]
Alright well I will mark this as resolved in the mean time until I hit 54, 53 now.

**Comment by Cabro** [comment]
It is bugged, it requires level 54 instead of 48. Why don't you reopen this report? :)

**Comment by tmfpena** [comment]
Because I haven't checked yet as to it being level 54. I will be checking soon.

**Comment by tmfpena** [comment]
Ok so I picked up the quest just at level 54. I'm a little confused as to whether or not I should reopen this.
