### ISSUE TITLE
Quest #566 minimum level

### ISSUE THREAD

**Issue by msystems11** [LightsHope/server#633]
Edit:  This quest is not missing, but the prerequisite level is incorrect. 
The required level should be **17** instead of 35, as established by comments dating back to 2006-2007.

Link to quest on Vanilla DB:  http://db.vanillagaming.org/?quest=566
Another: https://web.archive.org/web/20071012234712/http://wow.allakhazam.com:80/db/quest.html?wquest=566

Mangos sql has incorrect min-level here:
`(566,2,267,35,40,0,0,178,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,'WANTED: Baron Vardus','By order of High Executor Darthalia, the human known as Baron Vardus is wanted for crimes against the Forsaken. Vardus is known to be a high-ranking member of the organization known as the Syndicate.$B$BHe was last spotted in the Uplands in the Alterac Mountains, north of Tarren Mill.$B$BHe is wanted dead. Bring evidence of his demise to High Executor Darthalia to claim the reward.','Kill Baron Vardus and deliver his head to High Executor Darthalia in Tarren Mill.','Productive work you do, $N. With Baron Vardus dead, the number of Syndicate leaders grows smaller. Their resistance and irritation will be short-lived.','Ah, $N. Perhaps you\'ve come to collect the bounty on the head of Baron Vardus?','','','','','',3626,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2231,0,0,0,1,0,0,0,68,0,0,0,0,250,0,0,0,0,0,2100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0)
`

**Comment by GuybrushGit** [comment]
All the comments about picking this up at 19 in both the quest pages and item pages are from TBC.
Vanilla master guide has this quest at 35.

**Comment by spiderbot22** [comment]
If inferno robe wasnt obtainable at 19 then why are 19 twinks running around with Glacial Stone maces, a quest labeled as level 30 on the same sites provided by msystems11 above. If level 19s are able to get Glacial Stone then there is no reason that inferno robe shouldnt be obtainable. Proof https://media.discordapp.net/attachments/314965587316965386/380035300744888320/glacial.png?width=832&height=468

**Comment by GuybrushGit** [comment]
Glacial Stone comes from another quest, with a min level of 18.

**Comment by spiderbot22** [comment]
Could you provide proof for that.

**Comment by msystems11** [comment]
spiderbot22:  This isn't about the fairness of what is or isn't available at level 19, we wouldn't even be able to scratch the surface of that topic here and so that has nothing to do with this report. This is about the quest level accuracy of this quest. You are free to do your own research on that other quest and make a report.

If GuybrushGit is correct regarding this quest, that would mean that this quest was was **initially** a level 35 requirement and then somehow dropped to level 17 with the release of TBC in Jan 2007 (since we have many confirmed comments from early 2007 showing it was 17 at that point in time). It doesn't really make sense why Blizzard would do that though, it's very strange.

Note that the pre-requirement quest is 17, here is that for reference:
https://web.archive.org/web/20071106014906/http://wow.allakhazam.com:80/db/quest.html?wquest=549

sql:
(549 | 2 | 267 | 17 | 22 | 0 | 0 | 178 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 8 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 'WANTED: Syndicate Personnel' | 'By the authority of Lady Sylvanas | all members of the organization known as the Syndicate are wanted dead. Those brought into custody or taken prisoner will be summarily executed. They are currently known to be amassing in the ruins of Durnholde Keep | to the southeast of Tarren Mill.$B$BA handsome reward is offered to all who bring proof of their deeds to High Executor Darthalia.' | 'Kill 10 Syndicate Rogues and 10 Syndicate Watchmen. Return to High Executor Darthalia in Tarren Mill for your reward.' | 'Excellent | $C. At this rate | the Syndicate pest will be rid from the land in no time.' | 'Do you have nothing better to do than stand here before me | $c? As High Executor | I have more pressing matters than to stare at your rotting visage.' | '' | '' | '' | '' | '' | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 2260 | 2261 | 0 | 0 | 10 | 10 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 68 | 0 | 0 | 0 | 0 | 250 | 0 | 0 | 0 | 0 | 1400 | 1050 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by msystems11** [comment]
Found Wowhead source stating 17 in sidebar:

http://www.wowhead.com/quest=566/deprecated-wanted-baron-vardus#comments

**Comment by Dippydoo1** [comment]
Feenix had the same issue years back, but it was fixed. This quest was available for levels before 35 to pickup in vanilla. Please fix :)

https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1872
