### ISSUE TITLE
Mail notification on minimap doesnt disappear even though mailbox is empty. Steps to reproduce

### ISSUE THREAD

**Issue by dogmax** [LightsHope/server#636]
The Issue: 
The Minimap Mail notification does not disappear even though the mailbox is empty. 

Character in question: 
Johnlars, 60 warlock, horde-side. Realm: Lightbringer/Elysium.

What I tried: 
Re-downloading client. Deleting WDB, WTF. Removing Addons. Logging on a different computer. Sending myself some mail from an alt and collecting it. Sending myself a C.O.D. item from an alt and buying it. Buying things from AH. Sending mail from the bugged character.

The problem persists.

Conclusion: 
Must be a server side issue. 

Steps to reproduce: 
1) Receive a mail with a C.O.D. item
2) Don't buy the item nor return it;  Let it sit in the mailbox until the timer runs out. 
2.1) For me the timer was 2 days
(I didn't buy the item because I was low on gold - don't know if that has anything to do with it.)
3) Be logged OUT while the timer runs out. 

You should now have a permanent mail notification.

Why is this an issue: 
It is impossible to be notified about receiving in-game mail in this state as the notification is now useless.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/409
