### ISSUE TITLE
Can't recieve any more mails from my alts on my rogue Meley.

### ISSUE THREAD

**Issue by Wippeno** [LightsHope/server#637]
A guildie said it was easy fixed by "resetting the variable to 0 on your character" I made a ticket about it and they just sent me a mail to go here(which worked to receive btw), I've seen a couple of threads with ppl having similar problems, I have written bump on all of them but they still hasn't been responded. The character I'd wish to fix is Meley, thanks.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/123
