### ISSUE TITLE
Quest bugged. Garments of the Moon

### ISSUE THREAD

**Issue by Zuiron** [LightsHope/server#64]
it will not recognize heal when using lesser heal rank 1. but i went to trainer and trained lesser heal ranked 2 and then it worked. 

i tried several times with rank 1. also cancel and retake quest. using rank 2 heal was only solution. probably misspelled spell somewhere in quest script ?

**Comment by QAkvastskaft** [comment]
Quest text says to use rank 2 so this is not a bug:
http://web.archive.org/web/20060504005014/http://www.thottbot.com:80/?qu=5621
