### ISSUE TITLE
BWL port problem

### ISSUE THREAD

**Issue by Zapiccz** [LightsHope/server#640]
Character: Zapic
Server: Lightbringer

i have problem with port in BWL... i have preQ and i can click on orb but if i click doesnt work and i still stay near orb
i was delete all addons and wdb, wtf folders
still no working
GM in game cant help me.

Thank you

**Comment by GuybrushGit** [comment]
You either don't have the quest completed or are not in a raid or the raid is in combat.

**Comment by Zapiccz** [comment]
Nope....i finish Q on elysium and first time ported in BWL after finish Q.... and i try enter with friend in raid group and still doesnt work....i try everything what i can...now i need check my character in game... if bugged or what  thank you.
