### ISSUE TITLE
Accepting BG quests turns on your PvP tag.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#642]
http://db.vanillagaming.org/?quest=8372
I accepted the quest linked above and my PvP turned on by itself.
Possibly the other BG quests also turns your PvP by itself.
Seems very buggy for me.
LE: the PvP tag hasn't turned off after 5 minute later. I never left Darnassus during this time.

**Comment by GuybrushGit** [comment]
PvP tagged quests flag you for PvP.

**Comment by Cabro** [comment]
Ok then, but how does this work? Do you have to /pvp after and wait 5 minute to be safe from ganking in your own city or does the pvp flag disable by itself after 5 minutes if you had no pvp tag when accepting the quest?

**Comment by GuybrushGit** [comment]
It should be 5 mins after this fix: https://github.com/LightsHope/server/pull/532
But I think what's blizzlike is for pvp to stay on while you have a pvp quest on your log.
