### ISSUE TITLE
Juju's should be HORDE ONLY until 1.10

### ISSUE THREAD

**Issue by knasen88** [LightsHope/server#643]
Hello, It's come to my attention that Juju buffs are supposed to be HORDE ONLY up until patch 1.10

This is a serious balance issue since alliance is inherently stronger than horde with blessings so this would help to even it out.

Sources:
>https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html

>https://web.archive.org/web/20060516092753/http://worldofwarcraft.com/patchnotes/patch1p10.html

>https://wow.gamepedia.com/Witch_Doctor_Mau%27ari

ps fix WCB

**Comment by Omarthegreatone** [comment]
If they do not want to fix wcb, I don't see why they would let alliance have extra buffs that should not be in game yet.

**Comment by Cabro** [comment]
Yes, because alliance totally has an equivalent to WCB....

**Comment by berillis** [comment]
Well considering how you can't really anticipate when WCB is coming at all, there's absolutely no way you can use it as a raiding buff in its current state.

**Comment by knasen88** [comment]
Are you kidding me @Cabro ? You have blessings, the most overpowered bullshit in the game.
ally having slight stat loss is not going to change anything lets be real here.

**Comment by Cabro** [comment]
You are the one turning this into a blessings vs world buff, not me. Alliance has no equivalent to WCB. Besides, horde melees will always choose windfury totem vs 10% stats. You argument is invalid.

**Comment by knasen88** [comment]
You still have 25str elixirs and winterfall firewater. It is really minor -5str and -6AP.
To say this fix would make the game unbalanced is wrong.
Besides, ally can just collaborate with hordes using mind control if they want WCB.

**Comment by Cabro** [comment]
"Besides, ally can just collaborate with hordes using mind control if they want WCB." Funny, hordes can MC paladins also.

**Comment by knasen88** [comment]
This is about jujus, please contain your WCB to other issues.

**Comment by LEGAZIZ** [comment]
What is this discussion about faction balance? I thought we are trying to replicate blizzlike progression here. Jujus are as shown by OP not available until 1.10 for alliance. If nobody can't find a source proving otherwise it should be pushed to live servers.

**Comment by Cabro** [comment]
I am not disputing that it should be horde only :) Also the NPC should be moved to OG from Everlook.

**Comment by thepparker** [comment]
Jujus were given to Alliance in a later patch for obvious balance reasons, please stop being naive and attempting to drag up other issues to support your WCB crusade.

**Comment by knasen88** [comment]
Ah yes, -6 AP and -5STR . The horror.
