### ISSUE TITLE
Internal Mail Database Error - Lightbringer

### ISSUE THREAD

**Issue by Richtor77** [LightsHope/server#644]
When I try to send mail from a bank alt to another character on my account, I get an error saying, "Internal Mail Database Error". I've reported it to GMs multiple times and they recommended posting it on the bug tracker. I have tried relogging, relaunching the client, disabling mods, and deleting WDB + WTF folders.

**Comment by GuybrushGit** [comment]
This is not a bug its the antispam check.

**Comment by Richtor77** [comment]
Yeah I have a level 5 bank alt that DEs stuff and does AH listings. So is
it flagged because he's sending money while being < level 10?
