### ISSUE TITLE
NPCs without shields can Block.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#649]
The tooltip specifies very clearly "Requires Shield".

A Moonstalker Runt blocked my attacks.
This leads me to believe all npcs can block.

**Comment by Oudeis1447** [comment]
Like parry, monster can block, without any equipment, if you attack them from the front. An other example of stuff mobs do that player cannot is dodge attack that come from behind them.

Some info there :http://wowwiki.wikia.com/wiki/Attack_table. It's not the good patch, it's wiki, but the rogue part was explaining that part very well.

**Comment by Cabro** [comment]
I watched Joana's movies on youtube, and while i saw that mobs can indeed parry, i didnt see anything about blocking, which is why i left this one open unlike #648

**Comment by GuybrushGit** [comment]
2007 / 2008:

>Note too, that unlike player characters, mobs sometimes block attacks even though they have no shield equipped.
>https://wow.gamepedia.com/index.php?title=Block&oldid=852206

>http://www.wowhead.com/forums&topic=61813.1#p654135

**Comment by Cabro** [comment]
Awesome, +1.
