### ISSUE TITLE
Glancing Blows don't always reduce damage of normal white hits.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#652]
<code>[1] = "11/16/17 11:16:56.969 Faerie Fire fades from you.",</code>
<code>[2] = "11/16/17 11:16:56.000 You fail to perform Heroic Strike: Not enough rage.",</code>
<code>[3] = "11/16/17 11:17:00.141 Your Shoot Bow hits Blackwood Windtalker for 12.",</code>
<code>[4] = "11/16/17 11:17:00.281 You enter combat.",</code>
<code>[5] = "11/16/17 11:17:03.422 You fail to perform Heroic Strike: Not enough rage.",</code>
<code>[6] = "11/16/17 11:17:03.797 Blackwood Windtalker hits you for 15.",</code>
<code>[7] = "11/16/17 11:17:03.797 Rabid Thistle Bear is afflicted by Concussive Shot.",</code>
<code>[8] = "11/16/17 11:17:03.906 You hit Blackwood Windtalker for 24.",</code>
<code>[9] = "11/16/17 11:17:04.469 Dragomartin casts Tame Beast on Rabid Thistle Bear.",</code>
<code>[10] = "11/16/17 11:17:04.578 Rabid Thistle Bear is afflicted by Tame Beast.",</code>
<code>[11] = "11/16/17 11:17:05.016 Dragomartin's Auto Shot hits Rabid Thistle Bear for 41.",</code>
<code>[12] = "11/16/17 11:17:05.828 Blackwood Windtalker crits you for 26.",</code>
<code>[13] = "11/16/17 11:17:06.016 You hit Blackwood Windtalker for 24. (glancing)",</code>
<code>[14] = "11/16/17 11:17:07.938 Concussive Shot fades from Rabid Thistle Bear.",</code>
<code>[15] = "11/16/17 11:17:07.938 Blackwood Windtalker hits you for 13.",</code>
<code>[16] = "11/16/17 11:17:08.156 You hit Blackwood Windtalker for 25.",</code>
<code>[17] = "11/16/17 11:17:08.500 Blackwood Windtalker begins to cast Gust of Wind.",</code>
<code>[18] = "11/16/17 11:17:10.500 You hit Blackwood Windtalker for 25.",</code>
<code>[19] = "11/16/17 11:17:10.641 You are afflicted by Gust of Wind.",</code>
<code>[20] = "11/16/17 11:17:12.735 Blackwood Windtalker hits you for 15.",</code>
<code>[21] = "11/16/17 11:17:14.531 Blackwood Windtalker attacks. You parry.",</code>
<code>[22] = "11/16/17 11:17:14.578 Gust of Wind fades from you.",</code>
<code>[23] = "11/16/17 11:17:14.578 You miss Blackwood Windtalker.",</code>
<code>[24] = "11/16/17 11:17:15.422 Your Sunder Armor missed Blackwood Windtalker.",</code>
<code>[25] = "11/16/17 11:17:16.906 Blackwood Windtalker attacks. You dodge.",</code>
<code>[26] = "11/16/17 11:17:16.906 You hit Blackwood Windtalker for 24.",</code>
<code>[27] = "11/16/17 11:17:19.125 Blackwood Windtalker hits you for 13.",</code>
<code>[28] = "11/16/17 11:17:19.141 You hit Blackwood Windtalker for 25.",</code>
<code>[29] = "11/16/17 11:17:20.078 Your Rend is parried by Blackwood Windtalker.",</code>
<code>[30] = "11/16/17 11:17:20.719 Blackwood Windtalker misses you.",</code>
<code>[31] = "11/16/17 11:17:20.969 You hit Blackwood Windtalker for 15. (7 blocked)",</code>
<code>[32] = "11/16/17 11:17:22.016 Blackwood Windtalker is afflicted by Rend.",</code>
<code>[33] = "11/16/17 11:17:22.750 Blackwood Windtalker hits you for 15.",</code>
<code>[34] = "11/16/17 11:17:23.156 You hit Blackwood Windtalker for 23. (glancing)",</code>
<code>[35] = "11/16/17 11:17:24.610 Tame Beast fades from Rabid Thistle Bear.",</code>
<code>[36] = "11/16/17 11:17:24.860 Blackwood Windtalker hits you for 14.",</code>
<code>[37] = "11/16/17 11:17:24.938 Blackwood Windtalker suffers 9 Physical damage from your Rend.",</code>
<code>[38] = "11/16/17 11:17:25.297 You hit Blackwood Windtalker for 23.",</code>
<code>[39] = "11/16/17 11:17:26.016 Blackwood Windtalker begins to cast Gust of Wind.",</code>
<code>[40] = "11/16/17 11:17:27.438 You hit Blackwood Windtalker for 18. (glancing)",</code>
<code>[41] = "11/16/17 11:17:27.969 Blackwood Windtalker suffers 9 Physical damage from your Rend.",</code>
<code>[42] = "11/16/17 11:17:28.172 You are afflicted by Gust of Wind.",</code>
<code>[43] = "11/16/17 11:17:29.922 Blackwood Windtalker hits you for 15.",</code>
<code>[44] = "11/16/17 11:17:30.047 Gust of Wind fades from you.",</code>
<code>[45] = "11/16/17 11:17:30.000 Blackwood Windtalker suffers 9 Physical damage from your Rend.",</code>
<code>[46] = "11/16/17 11:17:31.750 You hit Blackwood Windtalker for 21.",</code>
<code>[47] = "11/16/17 11:17:31.969 Blackwood Windtalker hits you for 14.",</code>
<code>[48] = "11/16/17 11:17:33.875 You hit Blackwood Windtalker for 22.",</code>
<code>[49] = "11/16/17 11:17:33.875 You have slain Blackwood Windtalker!",</code>
<code>[50] = "11/16/17 11:17:33.875 Blackwood Windtalker dies, you gain 115 experience.",</code>
<code>[51] = "11/16/17 11:17:33.953 You exit combat.",</code>

Above is a excerpt of my combat log. Three glancing blows against an NPC 2 levels below me (this is a bug itself), with damage of 24, 23 and 18. My highest hits were 25. I would understand the 18 glancing, but the 23 and 24 ones?

**Comment by stesve** [comment]
What race where you playing?
What weapon where you using?
What was your weaponskill?

Glancing blows vs lower level mobs is blizzlike afaik.

**Comment by Cabro** [comment]
Level 14 Night Elf warrior, sword, 67/70 skill. Target level 12.
