### ISSUE TITLE
Glancing Blows should only happen versus mobs of equal or higher level.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#653]
http://wowwiki.wikia.com/wiki/Glancing_blow?oldid=222055

**Comment by berillis** [comment]
Glancing blow chance is calculated from your weapon skill against the monsters defense skill. With 300 weapon skill against a level 60 monster with 300 defense skill you won't get any glancing blows. With 300 weapon skill against a level 63 monster with 315 defense skill your attacks are 65% glancing blows.

**Comment by Cabro** [comment]
Nowhere in what you wrote says something about target being lower level than the player.

**Comment by stesve** [comment]
> http://wowwiki.wikia.com/wiki/Glancing_blow?oldid=222055

From your source:

> Glancing blows are combat events that **can** occur when fighting a mob of equal or higher level. 

> There is still a debate on how to determine the chance of a glancing blow occuring, and it's severity

You should take a look here: http://wowwiki.wikia.com/wiki/Talk:Weapon_skill

> While fighting with my warlock, I encountered a glancing blow rate of almost 100% while fighting lower-level monsters. A 46th-level warlock with 219 sword skill fighting 43rd-level monsters. 

> have an even more interesting discovery: I got a glancing blow today on a mob 1 level lower than my rogue. I have a 44 rogue, using daggers, no +skill. I was fighting a 43 Vicious Owlbeast in the Hinterlands and out of 24 swings, 1 was a glancing blow.

**Comment by Cabro** [comment]
Man, i am talking about getting glancing blows on a mob that is 2 levels BELOW me. Come on, guys, read.

**Comment by stesve** [comment]
>Man, i am talking about getting glancing blows on a mob that is 2 levels BELOW me. Come on, guys, read. Casters have like double the chance for glancing blows, i was talking about playing a warrior at level 14 fighting a mob level 12. I was about 3 wep skill away from cap. No wonder leveling a melee on this server is a pita.

ye, glancing blows can happen while fighting a lower level mob. We have that already established. Unless you can supply information supporting that it shouldnt happen.

Do you have any source, that casters have double chance for glancing blows?

**Comment by Cabro** [comment]
http://wowwiki.wikia.com/wiki/Glancing_blow?oldid=631819
<quote>Non-melee classes level 30 and higher have a 60% chance to glancing blow.</quote>
