### ISSUE TITLE
all the Battlemaster no gossip_menu_option

### ISSUE THREAD

**Issue by mpfans** [LightsHope/server#655]
Update to https://github.com/LightsHope/server/commit/f99e40d8ddf10a2a2c1e0533ad16c4a4f8e6ea18

all the Battlemaster no gossip_menu_option

![qq 20171116204550](https://user-images.githubusercontent.com/18187177/32892158-405d20aa-cb10-11e7-880a-a1f17404481c.jpg)
![qq 20171116204628](https://user-images.githubusercontent.com/18187177/32892166-476eba3e-cb10-11e7-8697-31249e9b6046.jpg)

**Comment by GuybrushGit** [comment]
Yes we are aware of it.

**Comment by brotalnia** [comment]
You can fix it on your local server by reverting this commit https://github.com/thepparker/lightshope-mangos-server/commit/85270047c90da3e6fd01b8f34531552d54bf8d67.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/pull/668

**Comment by mpfans** [comment]
Closed #655 via #668 and #669
