### ISSUE TITLE
the-pledge-of-secrecy 

### ISSUE THREAD

**Issue by lisolove** [LightsHope/server#657]
I can`t start quest http://www.wowhead.com/quest=3640/the-pledge-of-secrecy
Lisolov, elf hunter 42 lvl, engeneering is 235 lvl. 

GM Totier have checked issue and said to put this here.

**Comment by GuybrushGit** [comment]
Maybe you already took the quest from Nixx Sprocketspring? Go to gadget and talk to him.

**Comment by lisolove** [comment]
No, when I started prequest on 30lvl I can't physically be at Gatgetzan))

**Comment by GuybrushGit** [comment]
Did you complete the quest Gnome Engineering? Did you recently come back after a long absence?
A couple of months ago it was possible for Alliance to get the Horde "Gnome Engineering" quest and get stuck. If that's the case you need to ask a GM to remove the quest 3637 from your character.

**Comment by lisolove** [comment]
I asked GM to remove prequest but he had denied.
