### ISSUE TITLE
The quest Escape Through Force should require level 15, not 18.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#659]
http://db.vanillagaming.org/?quest=994 requires level 18 on LH.
https://wow.gamepedia.com/index.php?title=Quest:Escape_Through_Force&oldid=815575 level 15 retail.

**Comment by brotalnia** [comment]
Actually the whole chain requires level 10 according to the Master's Guide.
![terenthis](https://user-images.githubusercontent.com/6519171/32942195-f8578bfc-cb90-11e7-8733-74f238d572bd.png)

**Comment by Cabro** [comment]
Where do you find those guides? Also, since I have developed a bit of OCD lately, is there any way i can help you guys with the quest levels and stuff?

**Comment by GuybrushGit** [comment]
Guide download link: https://mega.nz/#!e01X1DLa!AQF6RnA24ewfzo0IYvRRHdInNVFEuG2ZhVsp8bQZrFM

Changing quest levels is very simple, anyone with a basic understanding of SQL can do it. If you can feel free to submit a pull request with the fix.  
Alternatively you can create a spreadsheet with quest ids and respective levels, it would make it much easier for us to fix them.

**Comment by Cabro** [comment]
Can you tell me where i can find the data for the quests' level requirements? I feel like looking for a needle in the hay stack...

**Comment by GuybrushGit** [comment]
Pages 250+ theres tables with the quests and min level.

**Comment by GuybrushGit** [comment]
You need to setup an SQL server on your pc and apply the sql files or you can check on http://vanillawowdb.com/

**Comment by Cabro** [comment]
OK, gonna go with the spreadsheet option. :) Can you give me a blank template of how you want them to be? I will get on it this weekend.

**Comment by brotalnia** [comment]
`UPDATE `quest_template` SET `MinLevel`=number WHERE `entry`=number;`

**Comment by Cabro** [comment]
Any chance to bring that fix to live?
