### ISSUE TITLE
Quest Gyromast's Revenge should require level 14, not 18.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#661]
Edited for level 14 due to new proof.

**Comment by Cabro** [comment]
![gyromast revenge](https://user-images.githubusercontent.com/1155017/32973100-041cc172-cbf6-11e7-97e5-20b279cf62eb.jpg)

**Comment by GuybrushGit** [comment]
Better to create just 1 issue and list all quests and their min levels than creating 1 issue per quest.

**Comment by Cabro** [comment]
I'm working on it, done 7 zones so far.
