### ISSUE TITLE
Pathfinding 1/2 and 2/2 not adding 3%/6% extra speed

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#671]
Reports of Pathfinding hunter talent not working

Confirmed on the Elysium tracker

Investigation by Terranzin

I´ve reviewed your reported issue. I´ve ran a couple of marathons now with Aspect of the cheetah (id: 5118) and Aspect of the pack (id:13159) without the talents. I´ve attempted to do the exact same run pattern both with Pathfinding 1/2 (3%) and Pathfinding 2/2 (6%). The speed does not increase, the time it takes to go from one place to another is exact same with both aspects with or without the increased speed talent (Pathfinder).PS: Try report issues in English if possible, had to use a translator, thanks!

**Comment by GuybrushGit** [comment]
2/2 works 1/2 doesn't.
