### ISSUE TITLE
Bugged Quest: Sully Balloo's Letter

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#672]
~~Item id: 4433 incorrectly show level 25 required for quest
Quest can only be taken at level 26 which is correct~~

~~Change text on item id 4433 to level 26~~

Investigation by Terranzin

Edited:

Change min level requirement on quest id 637 to level 25

Source:
http://web.archive.org/web/20081008112857/http://thottbot.com:80/?qu=637

**Comment by Cabro** [comment]
This is 26 in the link you gave, but 25 in the master guide.

**Comment by QAkvastskaft** [comment]
Could you provide a picture or a link to the source?

**Comment by Cabro** [comment]
![balloo](https://user-images.githubusercontent.com/1155017/32968239-d695ed92-cbe0-11e7-815b-bc35ac06b7e3.jpg)
