### ISSUE TITLE
Wanted: Baron Vardus Not Available

### ISSUE THREAD

**Issue by Dippydoo1** [LightsHope/server#673]
The quest Wanted: Baron Vardus is unavailable to be picked up. The level requirement is 18 and is not available even at 19. The first quest in the chain to receive the item Inferno Robe is Wanted: Syndicate Personnel and that is available to be picked up correctly, just need the Wanted: Baron Vardus to be fixed. 

Thanks :)

**Comment by Cabro** [comment]
It is a level 40 quest, requires level 35, and it works blizzlike. Not a bug.

**Comment by QAkvastskaft** [comment]
See #633

**Comment by Dippydoo1** [comment]
The quest is a level 35, but from vanilla it was available as long as you could start the quest chain (Which is 17). It works the same way Glacial Stone does, that quest requires a level 30 to do it, but if you are available to pick up the first quest in the chain then the quest can be started.  This item was available to be obtained in retail vanilla, so this should be fixed. Thanks for replying :)

**Comment by Dippydoo1** [comment]
Link to Glacial Stone for example: it says requires level 30, but if you have done the pre-requisites before lvl 30; you can start the quest.

http://db.vanillagaming.org/?quest=1046

This should work the same for Wanted: Baron Vardus.

**Comment by spiderbot22** [comment]
https://media.discordapp.net/attachments/314965587316965386/380035300744888320/glacial.png?width=832&height=468 Proof that glacial stone is obtainable at level 19 on Lightbringer.

**Comment by Cabro** [comment]
I don't know, the comments come from TBC, notice the patch.

This is a few months before, it might be that they changed the minimum level - https://wow.gamepedia.com/index.php?title=Quest:Raene%27s_Cleansing_(11)&oldid=283806

**Comment by Dippydoo1** [comment]
https://wow.gamepedia.com/Quest:WANTED:_Baron_Vardus

Says it requires level 18.

**Comment by Cabro** [comment]
http://www.wowhead.com/quest=1046 i am very very confused atm, i see the level requirements for quest id 1046 (most likely a rename and rewards changed along the expansions), and it does indeed say minimum level 19. Comments also confirm this.

**Comment by Cabro** [comment]
Well yes, Raene's Cleansing can be done at 18, Baron Vergas at 35.
![wanted levels](https://user-images.githubusercontent.com/1155017/32972959-2ad89a4e-cbf5-11e7-80af-bbe774c8f4ad.jpg)

**Comment by spiderbot22** [comment]
Where is that table from and what does it say about the last quest of the Raene's Cleansing quest chain

**Comment by Cabro** [comment]
![raene](https://user-images.githubusercontent.com/1155017/32973181-6cd209a2-cbf6-11e7-9ce5-5282e4707f9f.jpg)

**Comment by spiderbot22** [comment]
What is this source

**Comment by Cabro** [comment]
World of Warcraft Master Guide

**Comment by spiderbot22** [comment]
Thank you
