### ISSUE TITLE
Wrong error on quest sharing of quest  you have already completed.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#676]
If someone shares or starts a quest that you have already finished, you get in chat log "You are already on that quest" instead of "You have completed that quest"

**Comment by GuybrushGit** [comment]
There is no "completed quest" error message.

**Comment by Cabro** [comment]
http://vanilla-wow.wikia.com/wiki/WoW_Constants/Errors

ERR_QUEST_PUSH_ALREADY_DONE_S 
     %s has completed that quest 

Or is it that you shouldn't get the error message in the first place? When you are being shared a quest you've already done?

**Comment by GuybrushGit** [comment]
Tested multiple ids with the SMSG_QUESTGIVER_QUEST_INVALID packet and none gave an already complete message. It probably needs to send quest data as well for that message to show, would need to figure out the exact structure of this packet.

**Comment by dimefox** [comment]
I rearranged the checks in `HandlePushQuestToParty()` and now get the "%s has completed that quest" message. Can someone verify if this is the right fix?

**Comment by GuybrushGit** [comment]
Yeah that will do it. 
OP said the message should show to the quest receiver not the sharer so I was looking in the wrong place.
That fix will make it correctly show only to the sharer.
