### ISSUE TITLE
Orc racial talent Blood Fury

### ISSUE THREAD

**Issue by zacharyzhang89** [LightsHope/server#679]
In the PTR server. I tested a Orc rogue. With T2 gears on the Blood Fury only gives about 18% of the AP, which should be 25% AP as described in the tooltips of Blood Fury.
With no gear on the character. The Blood Fury give 25% of the AP, which is correct. So there should be some AP from the gears or enchants are not being counted in the Blood Fury spell.
I propose to check whether the Blood Fury counts the agi, str, AP comes from the gears and enchants, including crusader.
Thank you

**Comment by GuybrushGit** [comment]
Blood Fury increases "base melee attack power".

**Comment by king-tuts** [comment]
blood fury only increases base attack power

**Comment by zacharyzhang89** [comment]
what is base attack power?

**Comment by king-tuts** [comment]
the attack power you gain from your character's base stats, not including any item bonuses, i.e. the attack power you gain from your base strength as a warrior

**Comment by zacharyzhang89** [comment]
You mean the gears that add ap is not included? Only str or agi for rogues? But the math still not work out. What is item bonuses, could you make some examples?

**Comment by king-tuts** [comment]
item bonuses = any stat you get from gear

**Comment by zacharyzhang89** [comment]
But it do includes some ap from the gear  it not all. Based on the
experiment I did on PTR

**Comment by zacharyzhang89** [comment]
You could try it in PTR to see.
