### ISSUE TITLE
My Tauren Druid is gone:(

### ISSUE THREAD

**Issue by JakeMoo** [LightsHope/server#68]
--

Write your report here
So since the shutdown of Elysium, I only realised that there was a servers called Lightshope. I was Excited.. Until my level 49 Tauren druid wasnt on the Elysium realm. my level 9 Orc is but not 49. He was Male had quest greens and blues from Scolamance and he had a Kodo mount, Skills and he was called Khondie. Listen please, he doesnt need to be the same but I just want near enough the same character back. I put a lot of time into him for end game PvP and Raids. Im honestly not trying to sound ungrateful, but I just want him back.

Character name: Khondie
He had Quest greens and blues from scolamance (dont know if I said correctly)
He was feral so he had agility and stamina armor
Kodo mount (took me ages to get)
Come on Elysium, I have faith in you understanding me. please I beg for help.

**Comment by brotalnia** [comment]
Have you ever played on the Test Realm? Some characters were deleted by mistake cause they were given access to the ITR realm. You should contact a GM and tell them your character and account name so they can forward it to the person working on restoring the deleted characters.

**Comment by JakeMoo** [comment]
I have never played the test realm. I just pm a gm on discord my char name and realm.
