### ISSUE TITLE
Uldaman Boss: Galgann Firehammer loot table

### ISSUE THREAD

**Issue by slawry00** [LightsHope/server#680]
I've been trying to farm Galgann Firehammer for the gun he drops, but it sure seems that his loot table is bugged. Out of 8 times, i got 5 cloth shoulders (~20% drop rate), and 3 1H maces (~20%  drop rate), and got 0 of the 40% drop rate cloak and 0 of the 20% drop rate gun. I know its not conclusive with this few of runs, but if you could look into it, that'd be great.

**Comment by GuybrushGit** [comment]
These are the current loot chances:
![image](https://user-images.githubusercontent.com/26495604/32975970-7b58515c-cc05-11e7-96d9-feab107296b2.png)
You got unlucky.

**Comment by slawry00** [comment]
ok thanks for responding... just wanted to make sure I wasn't entirely wasting my time.
