### ISSUE TITLE
 Battlegear of Eternal Justice 3/3 Set bonus does not work (Paladin AQ20 set)

### ISSUE THREAD

**Issue by theloras** [LightsHope/server#686]
Battlegear of Eternal Justice
Instant 
20% chance to regain 100 mana when you cast a Judgement.
http://db.vanillagaming.org/?spell=26135

Battlegear of Eternal Justice
100 yd range
Instant
Effect #1 | (30) Energize Value: 100
http://db.vanillagaming.org/?spell=26975

I had not seen this mana energize work for quite some time while AoE farming so earlier tonight I asked @brotalnia to check on his personal PTR if it was working and replied back to me that it was not even when manually setting the proc rate at 100%:

Theloras - Today at 6:06 PM
hey was wondering if you could check something on your PTR with 100% proc rate plz
was wondering if you could look at this
http://db.vanillagaming.org/?spell=26135
which does this
http://db.vanillagaming.org/?spell=26975
it's the 3/3 set bonus for Paladin AQ20
Battlegear of Eternal Justice
Instant
20% chance to regain 100 mana when you cast a Judgement.
doesnt seem to proc at all on live anathema for me

brotalnia - Today at 6:12 PM
doesnt seem to be working

Theloras - Today at 6:13 PM
ok i thought so
ill write up a report
it used to work
but not for a while now
thx for checking it out

**Comment by GuybrushGit** [comment]
Its proccing on spell hits when judgements are melee hits.
