### ISSUE TITLE
[Mage] Arcane Concentration is being procced by non-damaging spells as well as damaging spells not hitting any targets.

### ISSUE THREAD

**Issue by Coxis** [LightsHope/server#69]
Arcane Concentration talent description:
Gives you a 2% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%

On my mage, in Darrowshire, I'm getting AC procs when casting Ice Barrier which isn't a damaging spell, in the case of damaging spells which don't require a target, AC procs on Frost Nova even if it doesn't hit anything.

**Comment by thepparker** [comment]
Resolution is pending a merge of the current release branch with the public branches
