### ISSUE TITLE
Pets(Dunno if all pets, but warlock voidwalker) keeps targetting rogues even when stealthing.

### ISSUE THREAD

**Issue by zymtones** [LightsHope/server#7]
Noticed this today in PvP, a warlock sends his voidwalker on me, I enter stealth(far away, no way he could see me) but his pet still comes at me like a homing missle and white attacks me so my stealth drops. I'm pretty sure this isn't blizzlike.

**Comment by b82a** [comment]
Had the same happen to me with hunter pets. And no, I did not have hunter's mark on me.

**Comment by GuybrushGit** [comment]
This is blizzlike. Mechanic was changed in TBC.

**Comment by Rose-zk** [comment]
Blizzlike unfortunately, same with trees not being LOS in WSG

**Comment by zymtones** [comment]
Oh okay.. Sucks tho.

**Comment by thepparker** [comment]
Blizzlike
