### ISSUE TITLE
Issue in chain quest (Defias Bortherhood)

### ISSUE THREAD

**Issue by zensama** [LightsHope/server#706]
After killing the messenger in Westfall and delivering the message, no follow up quests were presented to me even though I was level 18.
Note: I tried to open a ticket and response was to submit a ticket here

**Comment by QAkvastskaft** [comment]
The next part is given by this npc: http://vanillawowdb.com/?npc=467#starts
He is sometimes absent when a group is escorting him. 
He will re-spawn later and offer the quest
