### ISSUE TITLE
The Defias Brotherhood quest does not open up

### ISSUE THREAD

**Issue by Violanti** [LightsHope/server#711]
Hello,

Questgiver Gryan Stoutmantle in Westfall does not give the 'The Defias Brotherhood' quest, which should become available at level 18 (I am now level 19). This appears to be only for my character, others can get the quest, I am not talking about the quest where you have to wait for the traitor, but the questline before that.

Help is much appreciated

**Comment by GuybrushGit** [comment]
Maybe you already completed it and forgot about it? Check the other NPCs in the chain.
