### ISSUE TITLE
Mailbox issue

### ISSUE THREAD

**Issue by Minotaurz** [LightsHope/server#714]
Hi guys,

I was instructed by a GM to post my issue here.. so I have the message indicating I have unread mail ingame but when I go check my mailbox it has nothing on it... I know its a minor issue but its bugging me.. can you look into it?

My character name is Fllokki lvl 21 Undead Rogue, Lightbringer PvP realm... theres another char in my account with the same issue.. name Terstein, lvl 25 Tauren Druid

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/server/issues/409
