### ISSUE TITLE
Unread Mail Notification Doesn't Go Away

### ISSUE THREAD

**Issue by mystictxe** [LightsHope/server#723]
Server: Elysium, Patch 1.7
Character: Txe

The unread mail notification doesn't go away on my character even when I have no mail. I have tried reloading my ui, disabling addons, and clearing my ignore list. This issue has persisted for weeks.

I issued a GM support ticket and they told me to post a bug report. I have searched old archives for a similar issue and it seems that this has happened before on Blizz servers and they had to manually turn it off for some people.

**Comment by heyda** [comment]
looks like this issue has already been identified/fixed has a pull request:
https://github.com/LightsHope/server/pull/608
