### ISSUE TITLE
Missing quest in Felwood.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#735]
The quest is missing completely from the database.
http://www.wowhead.com/quest=8460/deprecated-timbermaw-ally
Added in patch 1.11.1.10772

**Comment by QAkvastskaft** [comment]
That quest is replaced by the following, filling the same function
http://vanillawowdb.com/?quest=6131

**Comment by Cabro** [comment]
So they replaced quest with id 8460 with quest with id 6131? Smells fishy...
