### ISSUE TITLE
Ice Block delay 

### ISSUE THREAD

**Issue by bugbringer** [LightsHope/server#736]
The Problem: 

It takes about 0,5 seconds for Ice Block to be "up" or to cancel it after using it. This results in deaths while Ice Block is on cd, or not to be able to "Ice Block" incoming Spells right in time. 

The delay can be tracked better by trying to cast immediately a spell after canceling Ice Block. A error message appeares "You can't do that while frozen".

How it should work:

Both, using and canceling Ice Block should be instant without any delay. Many retail movies can prove this.

Source: 

Very good scene to show Ice Block's instant uptime: 

https://youtu.be/VuQ6Hq4n3I4?t=10m36s

Here you can see instant canceling of Ice Block (visual animation of Ice Block slightly showing up while being able to cast):

https://youtu.be/c4bgggKMvQU?t=3m30s

Fix this please.

**Comment by Cabro** [comment]
Hey, um is it only me or I noticed something that isn't scripted on this server?
https://youtu.be/VuQ6Hq4n3I4?t=11m57s
He had Ice Block up when the shadow bolt launched, removed ice block while it was flying and yet he was immune to the bolt. Is it scripted like this on this server?

**Comment by GuybrushGit** [comment]
@Cabro did you test this? Doesnt happen in dev.

**Comment by Cabro** [comment]
I didn't test, i don't have a mage.
