### ISSUE TITLE
All Lifedrains should be unaffected by healing reduction spells before 2.3

### ISSUE THREAD

**Issue by supasteed** [LightsHope/server#74]
Patch 2.3
http://wowwiki.wikia.com/wiki/Patch_2.3.0

Healing reduction effects will now affect all health drain spells and abilities (e.g. Mortal Strike will reduce health gained from Drain Life).

Problem: All lifedrains should not be affected by curse of deadwood, mortalstrike ,crippling poison, wounded poison

**Comment by GuybrushGit** [comment]
What life drains are being affected? Tested Death Coil and Life Drain both dont get affected.

**Comment by supasteed** [comment]
@GuybrushGit demonfork, demonforged breastplate

**Comment by GuybrushGit** [comment]
Tested demonfork. Not affected by mortal strike.

**Comment by supasteed** [comment]
@GuybrushGit I must be on an older repack, ill try the newer one and test
