### ISSUE TITLE
Mossflayer Scouts (EPL) way too scared

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/server#740]
Running away in fear seconds after engaging combat before even being attacked suggests extreme anxiety, they're due for a sit down with their local psychia-witch doctor.

**Comment by GuybrushGit** [comment]
Intentional: http://db.vanillagaming.org/?npc=8560#wh-comments

**Comment by fgsfdss** [comment]
Huh, well then.

Going by these comments, do they currently stop running when slowed as well?
If so, you can close this issue.
