### ISSUE TITLE
hunter aspect of the cheetah bug

### ISSUE THREAD

**Issue by oloun33** [LightsHope/server#745]
i found a bug with aspect of the cheetah where the penalty (daze) procs of dots.this shouldnt happen. you arent supposed to be dazed with aspect of the cheetah with just dot dmg and im not talking about immolate and moonfire the dots that have instant dmg aswell. im talking about pain corruption etc.and you are getting dazed even when someone put it on you and before it ticks. he just put it on you and you getting insta dazed like you do with moonfire for example. this should not happen and its pretty gamebreaking for pvp. can we expect fix pls?

**Comment by GuybrushGit** [comment]
Should be fixed with today's update.
