### ISSUE TITLE
Hyper-Radiant Flame Reflector and BWL

### ISSUE THREAD

**Issue by Ravyd** [LightsHope/server#747]
It is well known that the reflector provides immunity to fire-based spells while active, aoe, dot or otherwise (and reflects direct attacks). I made the item specifically for BWL to combat Vael and Firemaw specifically. To my disappointment, vael and firemaw's pulse go through this immunity. I have done a lot of research, and there is nothing saying that effects such as these should not be affected. There are certain extreme examples such as Onyxia's breath which are known to be unaffected, but that is an all encompasing onslaught of fire and makes sense (though even then I think the damage should be halved). Other things such as burning adrenaline are unique and I wouldn't expect them to be affected. However, the pulses put out by these dragons are not what I would consider worthy of ignoring a fire **immunity.** 

This item is rare and extremely expensive to make, and using it in a fight specifically, sacrificing one of your most important slots for it I think warrants this buff to stand. It is only 5 seconds, at best it allows 2 less ticks of firemaw's pulse , and lessens damage from vael long enough to get healed. 

If you want to consider lore-wise, a dragon pulsing fire would, in fact, be negated by an active reflector. It is not a direct breath.  Reflected mage spells can do more damage than either of these (not stopped, **reflected**).

I think engineers with it wholely deserve the short 5-second immunity. Now I am second guessing every PVE fight that i may want to use this in. I have yet to test it against technician packs, but I would half expect to be obliterated even though logic tells me I should be fine if I took a direct hit with it up. I shouldn't be doubting my gear, I should know it works on everything.

These attacks aren't mixed magic, they're pure fire.

Thank you for reading.

Reference:

https://web.archive.org/web/20060909225603/http://www.thottbot.com:80/?i=37473

**Comment by Ravyd** [comment]
I also have not tested this in MC.

If this is a common thing, please provide a list of all mobs and spells exempt from this immunity.

**Comment by GuybrushGit** [comment]
The spells used by Vael and Firemaw have the attributes SPELL_ATTR_EX_CANT_BE_REDIRECTED and SPELL_ATTR_EX_CANT_BE_REFLECTED.

**Comment by Ravyd** [comment]
Aye, but are they intended to be as such? Can you give any examples explicitly saying this was in vanilla?

**Comment by knasen88** [comment]
But vael is fireimmune, how does it even matter? I assume FIREmaw is the same

**Comment by thepparker** [comment]
The onus is on you to prove that it should be a mechanic that goes against traditional mechanic implementations.

**Comment by Ravyd** [comment]
@knasen88 What matters is the immunity, not that's it's reflected. While the flame reflector is active, the player is supposed to be immune to ALL fire spells. Example: Rain of Fire does no damage to a player with Flame Reflector up, but the rain of fire isn't "reflected" because it's not a direct damage spell.

**Comment by Ravyd** [comment]
@thepparker The mechanic of the flame reflector is that the player is immune to all fire spells while the reflector is active. This is a well-known and documented fact. So you should be proving to me why these two spells are exempt from this mechanic, considering all the research I've found only mentions Onyxia's deep breath, it says nothing regarding Firemaw or Vael

**Comment by Ravyd** [comment]
I do not think this thread should be closed until someone finds a solid mention in the archives. Until then, I contend that these two attacks should follow the mechanic that is documented.

Also, if this is a reoccurring thing, I would appreciate a list of all affected mobs.
