### ISSUE TITLE
Dazed immediately after charging

### ISSUE THREAD

**Issue by Ravyd** [LightsHope/server#749]
The current issue I've noticed on Warriors is that after initially charging a mob you are likely to get immediately dazed. In the past few days I've noticed it a little less, but that has probably more to do with the increased defense of my warrior, not the bug itself. It did happen today to me however. 99% of the time your back is not turned at any point to the Mob so being dazed should be impossible

**Comment by Ravyd** [comment]
This used to happen up to 50% of the time while leveling

**Comment by Ravyd** [comment]
It could possibly be related to #726 as my warrior is tauren

**Comment by Cabro** [comment]
#89

**Comment by Ravyd** [comment]
#317
