### ISSUE TITLE
Only humanoid mobs are capable of parrying, which is incorrect

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#752]
**Issue**

Only humanoid mobs are capable of parrying.
https://i.imgur.com/o8CFJ1N.jpg ~261 hits on beast type mobs

The issue is in Unit.cpp, which assigns the base 5% parry chance to only humanoids. https://github.com/LightsHope/server/blob/development/src/game/Objects/Unit.cpp#L3272-L3279

Currently none of the bosses in MC/BWL parry because none of them are humanoid, which is a gamebreaking issue.

**How it should be**

All mobs should be capable of parrying, possibly with a few exceptions, based on the fact that there is a NO_PARRY ExtraFlag in the mangos creature_template. I don't think that flag is ever used on Light's Hope though.

**Proof**

All vanilla sources tell dps to stay behind boss to avoid attacks being parried.
https://vanilla-twinhead.twinstar.cz/?issue=4987
https://vanilla-twinhead.twinstar.cz/?issue=3179
Bunch of sources and discussion posted in the two above bugreports.

All mobs are capable of blocking even though not all of them have shields. Therefore they should also be capable of parrying even though not all of them have weapons.

One of the example videos: https://www.youtube.com/watch?v=jTSyexUNN9E&t=26m16s

**Comment by brotalnia** [comment]
The NO_PARRY flag is implemented btw https://github.com/LightsHope/server/blob/development/src/game/Objects/Unit.cpp#L2585.
