### ISSUE TITLE
Divine Shield Issues

### ISSUE THREAD

**Issue by TimEsfandiari** [LightsHope/server#754]
Divine Shield still currently has these issues:

When you cast Divine Shield (or Blessing of Protection) while you have the Berserker buff active in a battlegrounds, it actually cancels the buff(debuff) from you. This shouldn't be the case. The buff should stay active on you... On the flip side of things, if you are already bubbled, and then you pick up the Berserking, you still have the buff applied to you while bubbled, so technically that part is working correctly.

Another issue with Divine Shield, is that if it is active, then you can't return the alliance flag in Warsong Gulch. My assumption is that there is a blanket fix added in to make it where you can't interact with the flag, because you're not supposed to be able to pick up the horde flag and carry it. But you should be allowed to return the alliance flag if the opposing team's flag carrier dies.

My last issue I can think of right now, is that Blessing of Sacrifice is still doing damage to you, even while you're bubbled. It should make you immune to thisdamage as well.

**Comment by GuybrushGit** [comment]
Make an issue for each bug please.
