### ISSUE TITLE
Divine Shield is cancelling Battlegrounds Berserker Buff

### ISSUE THREAD

**Issue by TimEsfandiari** [LightsHope/server#757]
When you cast Divine Shield (or Blessing of Protection) while you have the Berserker buff active in a battlegrounds, it actually cancels the buff(debuff) from you. This shouldn't be the case. The buff should stay active on you... On the flip side of things, if you are already bubbled, and then you pick up the Berserking, you still have the buff applied to you while bubbled, so technically that part is working correctly.

**Comment by GuybrushGit** [comment]
There are 2 Berserking buffs: 23505 and 24378.
They're identical except one is unaffected by invulns, WSG is using the other one for some reason.

**Comment by TimEsfandiari** [comment]
So this should be a simple fix of using the other Berserking Buff? I believe it's happening in AB as well

**Comment by GuybrushGit** [comment]
https://www.youtube.com/watch?v=mxUlBoTWtnQ&feature=youtu.be&t=48

**Comment by theloras** [comment]
@GuybrushGit - regarding https://www.youtube.com/watch?v=mxUlBoTWtnQ&feature=youtu.be&t=48 you mean to tell me that you don't know TBC Pre-Patch footage when you see it bro?!?!?

He even has CRUSADER STRIKE on his action bar beside Seal of Command...

why is this bug report still up? It's not blizzlike in Vanilla that zerker stays after using bubble:

https://youtu.be/wEcPkwsfLd4?t=193

https://youtu.be/wEcPkwsfLd4?t=364

https://youtu.be/2HMJNP1PbZM?t=196

This has all been shared with Esfand over a month ago and then lol @gearselysium weeks ago when he went off the rails in his epic forum post $hitshow in my thread...

**Comment by theloras** [comment]
since the original "Dernos - Spell Damage Paladin 2" link has been taken down on copyright grounds, thankfully I found another upload of it here:

https://youtu.be/C__rrJWqx6M?t=193

https://www.youtube.com/watch?v=C__rrJWqx6M&feature=youtu.be&t=364

**Comment by theloras** [comment]
In the off chance that the re-upload video gets taken down on copyright notice - here are screenshots:

https://cdn.discordapp.com/attachments/253446111753273354/396066381612843019/bubble_zerker1.jpg

https://cdn.discordapp.com/attachments/253446111753273354/396066400281559040/bubble_zerker2.jpg

https://cdn.discordapp.com/attachments/253446111753273354/396067139359866890/bubble_zerker3.jpg

https://cdn.discordapp.com/attachments/253446111753273354/396067161589678081/bubble_zerker4.jpg

**Comment by brotalnia** [comment]
So it actually SHOULD remove berserking when you bubble?

**Comment by theloras** [comment]
@brotalnia - yes in Vanilla, the evidence shows that Divine Shield did in fact remove Berzerker buff - come TBC it would appear that Blizzard changed it to no longer remove it.

The video that @GuybrushGit posted is one that I watched over a month ago as I was trying to find evidence over a weekend afternoon to help prove this bug report - but as you can clearly see, this is from 2.0.1 TBC Pre-Patch:

https://www.youtube.com/watch?v=mxUlBoTWtnQ&feature=youtu.be&t=48

1. Seal of Command cast Animation has been changed from Vanilla
2. Falling Hammer Animation when he casts Judgement
3. Crusader Strike is the 2nd icon shown in his Action Bar

No one would have liked to have been able to provide evidence to help prove this bug report by @TimEsfandiari but as I have always tried to do with everything either I report or chime in on, is follow the evidence no matter where it leads.
