### ISSUE TITLE
No Loot From Fishing Success during Nightfin/Sunscale exclusive time periods. [Anathema]

### ISSUE THREAD

**Issue by jeehive** [LightsHope/server#761]
I have fished extensively for Raw Nightfin Snapper in Feralas between the hours of 00:00-06:00 server time where Nightfin is to be fished to the exclusion of Raw Sunscale Salmon. During this period I experience many "wasted" casts due to no loot. I am not recieving the error that "No Fish Are Hooked" or indeed any error whatsoever. I click the bobber correctly after it bobs and my character simply stops fishing. I do not experience this bug while fishing between 06:00-12:00 or 18:00-24:00 for Nightfin.

If I had to speculate why this is, I believe the random number generated to determine fishing loot simply generates no loot when you roll a value corresponding to a Sunscale during Nightfin exclusive hours, and vice versa. Instead what should happen is that the value usually corresponding to a Sunscale should simply produce a Nightfin.

**Comment by bfedorov91** [comment]
I was just about to make a report for the same thing.  I am playing on Lightbringer and I was fishing in Azshara by the cave.  About 1 out of 5 loot windows were empty.  No errors and not at end of the cast timer.  I tried holding shift while clicking the bobber - no difference.  I've noticed this before in the past few months, but it was never this common.  

Today I was fishing at 3AM server time for 20 minutes and I caught 4 stonescale eels.  I probably got at least 20 empty loot windows.

**Comment by niknikk** [comment]
same thing today on Lightbringer. As soon as noon passed (and we entered only sunscale part of the day) i started getting empty loot windows

**Comment by Ravyd** [comment]
I can also confirm this fishing extensively on both LH and Ana. Lots of wrong fish at wrong times and blank windows.

In fact, according to FB, the most common time for catching nightfin is in the morning.

**Comment by druidish** [comment]
It appears they've done something. Now when sunscale/nightfin drops outside its window you get the error message "You can't loot right now." Still broken.

**Comment by Farticuno** [comment]
I have this bug but for me it also occurs with any sort of openable container (chests, lockboxes, clams, etc) though not as commonly as it does when fishing. Really hope it doesn't happen for a quest item or dungeon loot or anything.

**Comment by GuybrushGit** [comment]
Can we get some more details?
What specific spot did the bug occur? Was it fishing a school, wreckage or just water?

**Comment by GuybrushGit** [comment]
The only incomplete fishing loot tables I found were School of Tastyfish & these zones:

Zul'Gurub
Deadwind Pass
Dreadmaul Rock
Beggar's Haunt
Twilight Grove
The Noxious Glade
Plaguewood
The Veiled Sea
Dire Maul

**Comment by druidish** [comment]
Temple of Arkkoran, Hetaera's Clutch in Azshara is generally where I fish and get this issue.

I tried looking at the code and I don't think it's an incomplete fishing loot table from the database. I think it's a bug with how loot is generated and conditions are applied. I think loot is rolled then conditions are applied to it. So the when fishing 12AM to 6AM for example. If the fishing loot rolls Sunscale it will get removed from the loot due to the condition and then that empty loot gets forwarded to the player. We might need to add a special condition for fishing in this case to reroll the loot.

**Comment by Farticuno** [comment]
Happens to me a lot, like maybe 20% of catches, in Moonglade 12AM-6AM. Has
happened to me in the inner coast of Azshara 12AM-6AM as well but not
nearly as commonly.

**Comment by Farticuno** [comment]
Happens to me a lot in Moonglade 6AM-12AM, probably about 20% of my catches
are affected. Also has happened in the inner coast of Azshara (the area
that requires less fishing skill) 6AM-12AM but not nearly as commonly.
