### ISSUE TITLE
Can not learn Leatherworking profession

### ISSUE THREAD

**Issue by Hygnx** [LightsHope/server#765]
Patch 1.8: Dragons of Nightmare
Lightbringer
Andagus [A]

I currently have one profession, skinning. However I am unable to learn Leatherworking. When I visit a Leatherworking trainer in Darnassus, Ironforge, or Stormwind the trainer shows nothing available to learn. The filters for the trainer have 'available' and 'unavailable' selected. I am able to learn Herbalism as a second profession and then unlearn it. However, I still am unable to learn Leatherworking.

After renaming my WTF and WDB folders and disabling addons as advised by the GM I was still unable to learn Leatherworking.

Note: I believe I originally learned Leatherworking a couple months ago, and then unlearned it. I am not sure if this is part of the problem.

![wowscrnshot_112217_221509](https://user-images.githubusercontent.com/28201105/33159779-a3b69b3c-cfd3-11e7-906c-d1d101052f52.jpg)

**Comment by GuybrushGit** [comment]
That NPC doesn't teach Apprentice Leatherworking. Try one of these: http://db.vanillagaming.org/?spell=2155#taught-by-npc
