### ISSUE TITLE
Legend of Korrak No quest reward 11/22/17

### ISSUE THREAD

**Issue by arrowanLightshope** [LightsHope/server#766]
Simply put - I turned in "LEGEND OF KORRAK" quest as a horde Troll hunter named "Arrowan" on the Lightbringer realm on 11/22/17 at approximately 11 CST. It was patch 1.8 and it did not give me the option of an item to select - As the crossbow - Bloodseeker is extremely good for a hunter I am  hopeful that i will be able to receive the item per the original quest description. All I received was the Rune of Recall upon turning in the quest. I have never had an issue and therefore was not expecting nothing when I clicked on complete quest. When I submitted a ticket, I was told by the GM that they could not help me but that i had to submit the issue to the developer bug tracker. See attached file - screenshot 
![paint of legend of korrak - i didnt get the item](https://user-images.githubusercontent.com/33920668/33159775-9bbb3df2-cfd3-11e7-8359-d5bd551c45bd.png)

Thank you for your help.

**Comment by Oudeis1447** [comment]
In that patch, it's the Hero of Frostwolf/Stromspike "win a AV" that give you the weapon rewarding quest.

**Comment by arrowanLightshope** [comment]
thank you ! i will do that now.
