### ISSUE TITLE
Wintersaber Trainers  Faction

### ISSUE THREAD

**Issue by Lili422** [LightsHope/server#767]
Hello.
1. Server - Anathema = Patch 1.11: Shadow of the Necropolis
2. Bug :
Wintersaber Trainers Faction > for the Frostsaber Provisions quest, does not drop quest items from mobs the Chillwind Ravager (Chillwind Meat) and Elder Shardtooth (Shardtooth Meat) the chance of a meat drop should be 80%. 22.11.2017 non-stop killing that mobs around 30min - as result - 0 any meat
Rivern Frostwind sells Reins of the Winterspring Frostsaber for 900 gold is needed Exalted by this faction - the price for this mount should be 80-100 gold
Thanks for earlier, I hope for an early solution of the problem

**Comment by brotalnia** [comment]
The price was changed in the TBC pre-patch.

Snapshot of the item from August 2006.
https://web.archive.org/web/20060922071357/http://wow.allakhazam.com:80/db/item.html?witem=13086

The item history on Allakhazam.
https://web.archive.org/web/20071106011108/http://wow.allakhazam.com:80/db/itemhistory.html?witem=13086

> 2006-11-30 11:48:34 | sellprice changed from '10000000' to '1000000'

**Comment by Aklol** [comment]
The drop rate is definitely not 80% and should be looked in to

**Comment by Fiskehatt** [comment]
Allakhazam shows the following as drop rates in vanilla:

#### [Shardtooth meat](https://web.archive.org/web/20060519122503/http://wow.allakhazam.com:80/db/item.html?witem=12622):

**Azshara**
Rabid Shardtooth (57 - 60) 0.62% (46,884)

**Winterspring**
Elder Shardtooth (52 - 58) 12.99% (254,857)	Rabid Shardtooth (57 - 60) 0.62% (46,884)
Shardtooth Bear (51 - 54) 1.62% (53,311)	Shardtooth Mauler (50 - 56) 4.15% (157,921)

#### [Chillwind meat](https://web.archive.org/web/20060519122520/http://wow.allakhazam.com:80/db/item.html?witem=12623):

**Winterspring**
Chillwind Chimaera (51 - 57) 4.90% (119,479) | Chillwind Ravager (52 - 59) 15.40% (194,993)
Fledgling Chillwind (50 - 55) 1.37% (61,361)

 Based on the comments they also stop dropping after you have 5 of them. So if you forgot some e.g. in your bank, the mobs will not drop any:

> why stackable up to 10 pieces... when they just stop dropping after you get 5?

**Comment by QAkvastskaft** [comment]
You can use this site for more up to date droprates for the LH server
http://vanillawowdb.com/?item=12622
http://vanillawowdb.com/?item=12623

**Comment by Lili422** [comment]
Thanks for the quick response 
After 30 minutes of pharm - I checked the backpack and the bank - meat was nowhere to be found, I canceled the quest and start it again the meat still didn't dropped or I just most unlucky player...

**Comment by Lili422** [comment]
Its ok now, working/ meat dropped 
but chance is too low
can close it
