### ISSUE TITLE
Hunter Tier 2 is bugged

### ISSUE THREAD

**Issue by genericusername2** [LightsHope/server#77]
Hi everyone,

so after Patch 1.7.0 (ZG) the Hunter Tier 2 set got some stats wrong on the shoulders and pants. Before the patch the stats were fine but afterwards the shoulders lost their 1% hit and the pants changed from 1% hit and 1% crit to 2% hit. Unfortunately I couldn't find archived versions for this exact patch of these items but this is the closest I could get: 
Shoulders: http://web.archive.org/web/20060623213547/http://www.thottbot.com:80/?i=36293
Pants: http://web.archive.org/web/20060108190753/http://www.thottbot.com:80/?i=37611
This was also the case on the previous Elysium-Project Server Elysium (before Light's Hope was around) by the way.
It becomes more clear that something's wrong if you look at the Tier 1 shoulders in the current patch state which kept their 1% hit.   

Thanks for looking into this and I hope it gets resolved quickly :)

**Comment by GuybrushGit** [comment]
Stats changed in 1.8: 
http://web.archive.org/web/20051220114615/http://wow.allakhazam.com:80/db/item.html?witem=16938
http://web.archive.org/web/20051111234300/http://wow.allakhazam.com:80/db/item.html?witem=16937

**Comment by genericusername2** [comment]
God damnit that's so random... just look at this http://web.archive.org/web/20051030023914/http://wow.allakhazam.com:80/db/item.html?witem=16848
how can Tier 1 be so much better

**Comment by lovemonkeyz** [comment]
I believe they were using the incorrect stats because before the progressive database was implemented, the items had 1.12.1 itemisation.
