### ISSUE TITLE
Druid Class Quest

### ISSUE THREAD

**Issue by rotchie** [LightsHope/server#771]
As of patch 1.8 class quests were opened up. As a druid, I have been to Moonglade, TB, and even Feralas to seek out this quest. Though i have not received it, i have gone to the follow up (Torwa Pathstrider) in Un'goro and still unable to get or start a quest. Ive tried disabling add ons, deleteing WTF folder, and even relog. 
please advise.

**Comment by QAkvastskaft** [comment]
Druid class quest was added in 1.10
http://wowwiki.wikia.com/wiki/Patch_1.10.0

**Comment by rotchie** [comment]
Thank you. I was going off of information given by a GM in a previous ticket.
