### ISSUE TITLE
Warlock Talent Pyroclasm not working in PvP

### ISSUE THREAD

**Issue by vindruvor** [LightsHope/server#772]
I am reporting this issue for a guildy since he did not have a github account. Thus it is not me that has tested this.

Talent: 

Pyroclasm Rank 2 | Instant | 
"Gives your Rain of Fire, Hellfire, and Soul Fire spells a 26% chance to stun the target for 3 sec."

The warlock was specced Pyroclasm for a whole weekend PvPing, using a lot of hellfire and some rain of fire (however not many soul fire).

He did not stun anyone whatsoever in PvP. And he also tested in duels to spam r1 hellfire but did not cause any stun.

**Comment by GuybrushGit** [comment]
The proc works but I found a bug with it, its being affected by DR when the patch notes say:
>Patch 1.9.0 (2006-01-03): The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells

Also its coded so the chance to stun is 26% per spell not per tick, so the chance for each hellfire tick is 26% / 15. No idea if this is how it should work.
