### ISSUE TITLE
Lightning Shield not consuming Stormstrike charges (Lightbringer PvP)

### ISSUE THREAD

**Issue by vindruvor** [LightsHope/server#773]
As you can see in the video below the storm strike charges do not get consumed when I do damage with lightning shield. At the same time my lightning shield does 63 instead of 53 (approx 20% more dmg from stormstrike buff).

I am not too familiar on where to upload videos fast & easy so I just uploaded to this gif converter thingy:
https://ezgif.com/video-to-gif/ezgif-4-74ca5eb17f.mp4

**Comment by GuybrushGit** [comment]
The lightning shield spells have the SPELL_ATTR_EX3_CANT_TRIGGER_PROC flag.
