### ISSUE TITLE
[Hunter] Screech does not properly apply AoE aggro to units affected by Screech

### ISSUE THREAD

**Issue by Amanugai** [LightsHope/server#78]
Where applicable, provide relevant sources that show or describe the correct behaviour.
Source: http://wowwiki.wikia.com/wiki/Screech

    The server or game patch that your issue pertains to (e.g. Anathema, patch 1.10).
- Patch 1.7.0 technically, since that is when Screech was added, but I believe pet abilities (just like talents) have been pre-added in Light's Hope

    A clear, concise description of the current behaviour.
- Screech does NOT apply aggro/gain threat to targets affected by the bird hunter pet when applying its -100 AP debuff to enemies hit by it within its radius.  This was tested by having Screech auto-casted four times (theoretically 400 threat) before auto shooting a mob affected by the debuff four times but not attacked previously.  The attacked enemy immediately changed targets (acting like it had 0 threat on it) to me, the hunter.  This was also tested manually casting Screech four times, with the same result.  

    A description of the expected behaviour.
- Screech should apply roughly 100 threat to targets affected by its -100 AP debuff per application.  This is in addition to threat provided by the small amount of damage it does to its main target.  It should behave similarly to other AoE AP debuffing abilities like Demoralizing Shout which applies threat in addition to their AP debuff.  This has been a long-standing issue ignored in both Nostalrius and Elysium-project, and I hope that the devs in Light's Hope can shed some light on this issue, and make bird pets great again as threat management utility pets.

**Comment by GuybrushGit** [comment]
This is working properly.

**Comment by lovemonkeyz** [comment]
I use an owl to farm Maraudon, and if the aoe screech didn't work, I wouldn't be able to multishot and heal my pet on landslide during spawns.

Can confirm that it works properly.
