### ISSUE TITLE
Quest Twisted Hatred Enemy Npc wont spawn

### ISSUE THREAD

**Issue by asummers48423** [LightsHope/server#781]
We have been in the area Fel Rock where he is supposed to spawn and he hasn't for an hour now Just wanted to give you guys a heads up xD and thank you for keeping this amazing server going :D

**Comment by GuybrushGit** [comment]
Maybe you're in the wrong spot? Melenas is there.

**Comment by DoctorBak** [comment]
I waited for a while in Fel Rock. Lord Melenas should spawn in 51,51 but it's not there apparently.
server Darrowshire

**Comment by GuybrushGit** [comment]
We don't know if the spawn is bugged or you're just waiting in the wrong spot. Take a screenshot.

**Comment by DoctorBak** [comment]
Ok I found him on top of the ledge.
[Here](https://imgur.com/a/nSHI8)
