### ISSUE TITLE
Paladin: Judgement of the Crusader and Seal of Righteousness

### ISSUE THREAD

**Issue by jrobz23** [LightsHope/server#784]
When Judgement from the Seal of the Crusader (http://db.vanillagaming.org/?spell=21082) is used and active on the mob, the holy damage proc from Seal of Righteousness (http://db.vanillagaming.org/?spell=20154) does not increase in damage.

**Comment by jrobz23** [comment]
I tested this at low levels. An increase of up to 20 would be very obvious (when the proc is 2-4 usually), but the increase is 0, making the combo useless. Is this by design?

**Comment by GuybrushGit** [comment]
Its working, the increase is 2 (10% coefficient).

**Comment by jrobz23** [comment]
So just so low, it's hard to see unless you're tracking it due to some coefficient. Weird. Based on the spell description, I expected visible results. 

Sorry for the bunk bug file.
