### ISSUE TITLE
Missing thorium brotherhood rep

### ISSUE THREAD

**Issue by serkety** [LightsHope/server#792]
I have attempted to find out about this issue without any luck, I opened a ticket to speak to a GM but after a few hours I could not wait any longer so logged off only to come back today with mail saying report this as a bug so here goes.

I only noticed it today when I decided to carry on and rep up my thorium brotherhood rep and when I was about to start with turn in quests I noticed that all my previous rep that I had got with them has either gone completely or been scaled or something? I have completed almost all thorium brotherhood quests and currently sitting with 140/3000 Neutral.
Prior to Elysium -> LightsHope transfer I know I had more than 140 rep cannot say how much more but whatever all the quests in searing gorge give at the very least.
I am unsure if this can be looked at being fixed rep or quests being reset so I can get this rep back?
Please advise/help.

Cheers.

**Comment by serkety** [comment]
![wowscrnshot_112517_184153](https://user-images.githubusercontent.com/33974238/33227819-13753b60-d211-11e7-9826-aef6e5bd33bd.jpg)


As you can see this quest giver has three quests each of these quests is 100 rep and I have clearly completed these as there is no quest options available. You can also check the rep as being only 140/3000, does not add up?

**Comment by GuybrushGit** [comment]
Reputation rewarded depends on your level when you turned them in, for example at level 60 these quests will only give 20 rep.

**Comment by serkety** [comment]
This would have been at max level though.
