### ISSUE TITLE
Seal of Wisdom and Seal of Light proc rates

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#794]
They have a custom PPM of 20 listed in the spell_proc_event, even though the spell.dbc file has listed both of them as a constant 50% proc chance.

I'm pretty sure proc rates listed in dbc files are accurate.

**Comment by GuybrushGit** [comment]
Where are you seeing the 50% chance? My DBC files show 100%.

**Comment by ohganot** [comment]
My bad, I confused Judgement and Seal.
