### ISSUE TITLE
Leatherworking Trainer not working

### ISSUE THREAD

**Issue by josecrem** [LightsHope/server#797]
Trying to learn Expert Leatherworking, I go to meet Caryssia Moonhunter <Tribal Leatherworking Trainer>, Thalanaar, East Feralas.
When I Click on it, the dialog box open with only one option : "Train me".
When I click on it, the dialog box open blank, with no options. No Expert Leatherworking, no new recipes.
I have asked other players near the NPS to interact with her, and got the same response.
Thank for your work and forgive my poor english.

**Comment by GuybrushGit** [comment]
This NPC only trains Tribal Leatherworkers.

**Comment by Cabro** [comment]
Hm. Seems to me that the NPC shouldn't offer the "Train me" option if you're not tribal LW. I've seen to present to almost all trainers that train a branch.

**Comment by josecrem** [comment]
Thanks. I trained at Darnasus, did not know that there where one higher level trainer.
