### ISSUE TITLE
Missing quest id 8788 - A Gently Shaken Gift.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#805]
http://www.wowhead.com/quest=8788/a-gently-shaken-gift#comments:id=1787330

The quest reward should be item 21271.

**Comment by QAkvastskaft** [comment]
In the master guide there seems to be 2 versions of this quest, also in the old archives. 

quest id 8788 does not currently exist: http://vanillawowdb.com/?quest=8788
https://web.archive.org/web/20071104233747/http://wow.allakhazam.com:80/db/quest.html?wquest=8788

However quest id 8767 has the same name and exists: http://vanillawowdb.com/?quest=8767
https://web.archive.org/web/20071114123911/http://wow.allakhazam.com:80/db/quest.html?wquest=8767

The item 21271 should likely drop item id 21241: https://web.archive.org/web/20061026000705/http://wow.allakhazam.com/db/item.html?witem=21241.

(The other gently shaken gift 21270 drops the food equivalent item 21235)

![image](https://user-images.githubusercontent.com/26366996/33240612-02115bd0-d2b9-11e7-9d17-eaff96842763.png)

**Comment by GuybrushGit** [comment]
Added in https://github.com/LightsHope/server/pull/900
