### ISSUE TITLE
Missing quest id 8828 - Winter's Presents.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#806]
http://wowwiki.wikia.com/wiki/Quest:Winter%27s_Presents_(Horde)
http://www.wowhead.com/quest=8828/winters-presents

There is the alliance equivalent (8827), but not the horde one.

**Comment by QAkvastskaft** [comment]
https://web.archive.org/web/20071114193701/http://wow.allakhazam.com:80/db/quest.html?wquest=8828
With incorrect text however. 

"Added: Dec 25th, 2005"

**Comment by GuybrushGit** [comment]
Added in https://github.com/LightsHope/server/pull/900
