### ISSUE TITLE
[MISSING ITEM]RANIK-RATCHET

### ISSUE THREAD

**Issue by thejamesfork** [LightsHope/server#811]
The NPC Ranik at Ratchet is missing an item which was in classic wow, called Large Ruffled Feather, the id is 8426, which i found suprisingly on google nothing than a wrong wowhead ink.
Please fixx this.
Thanks. n, keep it up.

**Comment by thejamesfork** [comment]
http://www.wowhead.com/item=8426/large-ruffled-feather
the only thing i found, but i knowit from my memory.. i have to look on my old harddrives, maybe i can find some footage.
But im pretty sure it was in Ranik.

**Comment by brotalnia** [comment]
Are you saying he should be selling the item? I don't find this plausible, its a grey item, meaning its useless.

You can see what he sold on allakhazam:
https://web.archive.org/web/20060614004951/http://wow.allakhazam.com:80/db/mob.html?wmob=3499
