### ISSUE TITLE
Lost important questitem after servercrash/rollback!

### ISSUE THREAD

**Issue by ionized89** [LightsHope/server#813]
Hi!

I was hit by a sad issue today after the servercrash ~19:10, 2017-11-26.
I had recently done a run through "Sunken Temple, Temple of Atal'Hakkar", and defeated "Shade of Eranikus".
I got my questitem from him "Essence of Eranikus". 
Took it, started the quest. Pressed the altar behind "Shade of Eranikus", and recieved the "Chained Essence of Eranikus"

I then used [Oathstone of Ysera's Dragonflight], to earn the quest "The Essence of Eranikus".
Ran to Itharius in Swamp of Sorrows, and turned in the quest.(Wich requires you to have both the "Oathstone of Ysera's Dragonflight" and the "Chained Essence of Eranikus" Trinket/Questitem)

I got the followup-quest "In Eranikus' Own Words" and went on my way to continue questing.
I used Astrall Recall to Gadgetzan and started flying towards Thunder Bluff, and that is when the server crashed.

After the server got online again I had suffered a rollback. 
Back to the cave beside Itharius, in Swamp of Sorrows, again, right before when I handed in the quest to recieve the new quest "In Eranikus' Own Words".
But the server still "thinks" I turned in the "Chained Essence of Eranikus". 
Becuase it is nowhere to be found, and Itharius is standing in the cave with a yellow "?" above him, wating for me to turn in "Oathstone of Ysera's Dragonflight" and "Chained Essence of Eranikus" for the quest "The Essence of Eranikus".

I posted a ticket about the issue and I recieved an ingame mail that asked me to delete WTB+WTF folders and remove any addons I have installed.
Tried that and relogged.
The issue remains...

I recently tried to do another run in Sunken Temple, Temple of Atal'Hakkar.
Defeated "Shade of Eranikus" again, but was unable to loot another "Essence of Eranikus".

I really would like to have this issue resolved.

Thanks in advance!

ionized-

**Comment by GuybrushGit** [comment]
You need a GM to either give you the Chained Essence or remove quest 3373 from your char so you can get another.

**Comment by ionized89** [comment]
Hi!

Thanks for the reply!
Do I make an ingame-ticket referring to this issue#(#813) or how do I take it up with them?

KR

ionized-
