### ISSUE TITLE
Black & Blue Dragon Mail Setbonuses

### ISSUE THREAD

**Issue by thecrazyK** [LightsHope/server#820]
The Black and the Blue Dragon Mail Sets should have Setbonuses by Patch 1.8.

>  "The Blue, Green, and Black Dragonscale Leatherworking Armor pieces are now parts of sets and have set bonuses so they should be significantly more desirable"
> 
 Source: http://wowwiki.wikia.com/wiki/Patch_1.8.0

**Comment by brotalnia** [comment]
And they do.

![dragonscale items](https://user-images.githubusercontent.com/6519171/33277249-a6b30b24-d3a0-11e7-983d-39b27706c87c.jpg)
