### ISSUE TITLE
Release branch, is the most stable branch of the entire project?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#828]
I want to try to compile LightsHope.
Release branch, is the most stable branch of the entire project?

**Comment by DarkmoonRabbit** [comment]
@GuybrushGit help me- -

**Comment by brotalnia** [comment]
Release - what is currently live on the Light's Hope realms.
Development - ahead in term of fixes and features, but possibly has undiscovered issues.

**Comment by DarkmoonRabbit** [comment]
@brotalnia thank you my friend.
SQL/Custom/ What is the role of the document here?

**Comment by brotalnia** [comment]
Yes, release still uses the old database. Custom folder is for non-blizzlike changes.
