### ISSUE TITLE
Issue with PVP flagging while using the taxi service

### ISSUE THREAD

**Issue by Zarant** [LightsHope/server#833]
Whenever you use a flight master, PVP flag should be turned off for the whole duration of the flight and then the PVP flag should be applied again upon arrival depending if it's a contested zone or not.
Right now, if you fly from a contested zone to a major city you remain flagged for pvp upon arrival.

Source: https://www.youtube.com/watch?v=mA1vYEAbdgI&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=12
This is a recording from Joana's speedrun from retail WoW, and judging by the lack of linked flight paths this was recorded pre patch 1.10. At the 10 minute mark, Joana takes a FP from Stonetalon to Thunder Bluff and you can see the behavior I just described. There are many other examples in his speed run that corroborates that.

https://www.youtube.com/watch?v=t9-p76s-G5k&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=19
At the 3 hour, 5 minutes, 25 seconds mark you can see the behavior of a flight between Booty Bay and Grom'gol. The pvp flag is removed for the whole flight and then applied immediately upon arrival.

**Comment by Cabro** [comment]
Patch 1.6.0: The PvP flag is no longer cleared when you take a flight, if you have /pvp toggled on. Is this how it is currently? Or just pvp flag remove on FP takeoff no matter what?

**Comment by Zarant** [comment]
From the Joana's youtube channel and personal page (https://www.furiouspaul.com/pc/wow/) he says that the speed run was recorded in January 2006, in other words, after patch 1.9.

**Comment by Cabro** [comment]
Did he say if it was a pvp or pve server?
