### ISSUE TITLE
Unfinished Gordok Business quests.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#838]
http://vanillawowdb.com/?quest=1318
http://vanillawowdb.com/?quest=7703

Both quests are literally the same, with same rewards, and you get both. From what i read on patch notes there was a problem with this quest about priests not being able to get it, so i think they added another one to replace the bugged one. There is no reason whatsoever to have both quests active as it stands now.
Just disable one of them.

**Comment by GuybrushGit** [comment]
On dev he only offers the second one, how did you get both?

**Comment by Cabro** [comment]
I will have to level up to DM instance level, i cannot possibly remember how i got them both on Anathema.

**Comment by dimefox** [comment]
1318 has no quest relations or source item so I think it's unobtainable now.
