### ISSUE TITLE
Lvl 50 Warrior quest, A Troubled Spirit, not working properly. 

### ISSUE THREAD

**Issue by brandon6349** [LightsHope/server#84]
http://db.vanillagaming.org/?quest=8417#wh-comments <-- Accepted from Kelv Sternhammer

I traveled to this Dwarf in Ironforge, and he didn't have the level 50 Warrior quest I'm normally used to.
I also traveled to The Fallen Hero of the Horde, he didn't have anything either.

The quest definitely doesn't work properly, the minimum level for the quest is lvl 50.
![doegjgkjtgaaeu2dwjlnog](https://user-images.githubusercontent.com/20763516/31847365-f74d99b2-b5e8-11e7-9fed-69a8ab012fd4.png)

**Comment by QAkvastskaft** [comment]
Which server are you on?
This quest was added in patch 1.8 and is not available on Elysium yet 

http://wowwiki.wikia.com/wiki/Patch_1.8.0
