### ISSUE TITLE
Lokhtos Darkbargainer in Blackrock Depths does not sell all items

### ISSUE THREAD

**Issue by Ranto92** [LightsHope/server#848]
Hello, just like the titel states i've had some issues with the vendor in BRD. I got the rep to buy a recipe but it doesnt show when i go there, i deleted the WTF and WDB folder and disable all addons as i was told to do that after my first ticket. But it didnt work so was told to write about the issue here. The recipe in question is http://www.wowhead.com/item=20761/recipe-transmute-elemental-fire
Best Regards Ranto

**Comment by Cabro** [comment]
That NPC shows items in the vendor list based on your reputation with TB.

**Comment by brotalnia** [comment]
He does sell that item, but it is limited supply. Somebody has bought it before you. Notice it says Stock: 1 on Wowhead.

**Comment by Ranto92** [comment]
I ran in the front of my group, i had aspect of the cheatha on so i would be the first there, noone of my group even enterd the room. Is it possible that i need 1/6000 rep with them for it to count as friendly?

**Comment by druidish** [comment]
This recipe came out in 1.9 so if you're on the newer server it won't be there.

**Comment by Ranto92** [comment]
Oh im on Lightbringer.

**Comment by Cabro** [comment]
Not a bug then. :)

**Comment by Ranto92** [comment]
Wait so it isnt even out there yet? on what patch is Lightbringer on?

**Comment by Ranto92** [comment]
According to Wowhead, all the recipies came out "Added in patch 1.11.1.5462" things like 
Formula: Enchant Weapon - Mighty Intellect
That are already out on the server

**Comment by druidish** [comment]
From the 1.9 patch notes.

"An Alchemy recipe to Transmute Heart of Fire into three Elemental Fires has been added at the Friendly level of the Thorium Brotherhood."

**Comment by Ranto92** [comment]
okay thanks alot for all the info. if you want we can delete this now.
