### ISSUE TITLE
Divine Intervention does not kill the Paladin casting it

### ISSUE THREAD

**Issue by Aklol** [LightsHope/server#85]
As the title says, using DI does not kill the Paladin casting it.

I honestly can't believe this hasn't been reported yet.

**Comment by brotalnia** [comment]
It kills you on my local server.
![divineint](https://user-images.githubusercontent.com/6519171/31850519-ec9d4044-b65b-11e7-981c-b7601db19558.jpg)

**Comment by Aklol** [comment]
When is the last time you updated your server? It has been like this on Elysium for at least the past week or so. Has been tested multiple times.
