### ISSUE TITLE
Druid stealth bugged

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#850]
Druid stealth is bugged

**Comment by Cabro** [comment]
Best bug report :))

**Comment by brotalnia** [comment]
![wowscrnshot_112917_235915](https://user-images.githubusercontent.com/6519171/33401344-9b0beab2-d561-11e7-8540-c8a3c5b56bb9.jpg)

Doesn't look bugged to me.

**Comment by ohganot** [comment]
nice
