### ISSUE TITLE
[RESOLVED] - [Warlock] Improved Imp

### ISSUE THREAD

**Issue by Corruption4** [LightsHope/server#852]
# Blood Pact with Improved Imp bug:

**Default value** of the spell: 
Blood Pact rank 5: _Increases party members' Stamina by 42._

Demonology Talent 3/3 : _Improved Imp talent: Increase the effect of your Imp's Blood Pact spell by 30%._ 

Blood Pact rank 5 **new value**:  _Increases party members' Stamina by 54._

**Real buff value**: _Stamina 42._ 

IMAGE FROM THE GAME HERE:
https://image.noelshack.com/fichiers/2017/48/4/1511999399-bug-report-blood-pact.png

**Comment by kallith** [comment]
Dismiss your pet with your character pane open, you will notice that it actually decreases by 54. In general any buff tooltip will always show its untalented state.

**Comment by Corruption4** [comment]
That's right, sorry =)
