### ISSUE TITLE
Silverpine Forest zone not acting as a green safe zone for Horde

### ISSUE THREAD

**Issue by VladtheImaper** [LightsHope/server#854]
Lightbringer server version 1.12.1 5875 release

On 11\29\2017 a rogue and I were questing at Pyrewood Village in the Silverpine Forest zone (green safe zone). We were killed by red ?? Alliance players multiple times and corpse camped.

We had no chance to be flagged for pvp. I had just logged into the game and gone from The Sepulcher directly to Pyrewood Village. 

Normally, in a green zone, Alliance players are yellow and they can't attack an unflagged player. It seems like Silverpine Forest zone is not considered a green zone by the game.

**Comment by fgsfdss** [comment]
Did you buff or heal the Rogue or someone else who may have manually flagged for PvP?
Did you right-click the Alliance player?

**Comment by VladtheImaper** [comment]
I am a warlock. I didn't buff the rogue at all. It is possible that I buffed some random player with unending breath on the road to Pyrewood. I usually do that everyone I pass.

But that doesn't explain why the rogue would also be pvp flagged and killed. Rogues can't buff or heal so he wouldn't have been pvp flagged. We were ignoring the Alliance players because they usually run up the hill to Scarlet Monastery. 

There also was 3 other players that were questing in Pyrewood and they got killed and camped as well. 

I'll go in game and make sure pvp debuff is gone (I won't buff anyone and I'll wait 5 min for the timer to go off) with /pvp and I won't click on Alliance players at all. 

I'll come post again with the results

**Comment by VladtheImaper** [comment]
You are correct. I must have buffed someone that was pvp flagged. Sorry about that
