### ISSUE TITLE
Lunar wands are only rolling +13 or +23 X spell damage.

### ISSUE THREAD

**Issue by Aguilaa** [LightsHope/server#861]
Lunar Wands are currently only dropping as either +13 or +23. 
It should be between 13-23. 

This is pretty gamebreaking, as a +23 should be very hard to come by and as of this moment, it's becoming quite common,

**Comment by StadenElysium** [comment]
Can't find any evidence that suggests there were any rolls between 13 and 23.

https://web.archive.org/web/20060304235858/http://wow.allakhazam.com:80/db/item.html?witem=15283
