### ISSUE TITLE
(Local server)Remote attacks, ignoring obstacles?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#879]
Hello friend @brotalnia , thank you for helping me before! I have successfully compiled to run a local server. . .But I found .........
The new compiled development branch,
Remote attacks, ignoring obstacles.
Why is that? I am using the extraction tool provided in the wiki (https://github.com/elysium-project/server/files/852498/Elysium.Extractors.18.March.zip)
Is this related to the server data file?
![look](https://user-images.githubusercontent.com/21149808/33516816-fb538872-d7b3-11e7-8e20-9ed0da61c66a.png)

**Comment by dagochen** [comment]
every obstacle with the m2flag should not block los for projectiles or spells

**Comment by brotalnia** [comment]
Not everything is supposed to obstruct line of sight, there are many things you can attack through in vanilla.

**Comment by DarkmoonRabbit** [comment]
@brotalnia @dagochen
and so. . . This phenomenon is normal?

**Comment by DarkmoonRabbit** [comment]
@brotalnia 
There is no command in the server: .levelup / .die / or add gold .....

**Comment by brotalnia** [comment]
Make sure your account is rank 6. Type this in the mangosd console to promote your account:
account set gmlevel <name> 6

**Comment by DarkmoonRabbit** [comment]
@brotalnia 
oh my god...Always think that gmlevel 3 is the highest.
