### ISSUE TITLE
The Volatile Infection debuffs shouldn't target you, only the ones around you (read spell).

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#891]
http://vanillawowdb.com/?search=volatile+infection

ALL of them specify very clearly "Infects an enemy for X sec., causing it to inflict Y Nature damage to its nearby allies every Z sec."
Proof in the comments, such as http://www.wowhead.com/spell=3584/volatile-infection#comments:id=466592
Similar to how the Conflagration spells are also bugged on the server (targeting you also).
Also proof is in videos from Emeriss from vanilla. If needed i will dig through those also.

**Comment by GuybrushGit** [comment]
Hard to find videos where its not instantly dispelled.
In this one the tank has it and takes the damage: https://www.youtube.com/watch?v=Co9NSSentYQ
But its uploaded 2010.

**Comment by Cabro** [comment]
How do you know it's from his (tank's) own debuff? Like i said, Conflagration has the exact same description and it is not doing damage to the one with the debuff.
One spell that is doing damage to both the player and the others around it is Mother's Milk, but it has a description that tells that everyone will be affected by it.
