### ISSUE TITLE
Ashjre'Thul, Crossbow of Smiting attack speed bugged.

### ISSUE THREAD

**Issue by amd1044** [LightsHope/server#892]
I am deeply sorry if this is already on the issue tracker, I was searching **for the issue tracker** and couldn't find it. If you could provide a link to the issue tracker that'd be great.
This weapon clearly has a 3.4 attack speed.  In case you've not played hunter, it's the best bow (for now).  The reason it's the best is because it's attack speed is finally longer than the 3 second aimed shot cast.  Aimed shot skill clearly says 3 Second Cast.  
Auto shot, Aimed shot, .4s, auto shot.  Extra dps.  
When using this crossbow, my aimed shot carries over a full half second interrupting my next auto shot, defeating the purpose and what historically made this weapon amazing.

**Comment by druidish** [comment]
You know you have a quiver right, and possibly Imp Aspect of the Hawk proc?

**Comment by amd1044** [comment]
I'll try without quiver and if I'm having problems still I'll fraps

**Comment by GMNylth** [comment]
Hi there! <GM>Nylth here.

Ranged weapon attack speed is broken into two components for hunters: Cooldown and charge-up. Charge-up is always .5 seconds, and the cooldown is whatever's left over. For Ashjre'thul's 3.4 speed, Auto Shot takes .5 seconds to charge up, leaving 2.9 seconds for Auto Shot's cooldown.

No matter what weapon you have, you will always clip your Auto Shot a little bit. Hope that helps. :)

**Comment by amd1044** [comment]
Ok that makes a lot of sense thanks I wasn't considering the charge up
being apart of the 3.4.  that combined with my quiver makes 100% of the
difference.
