### ISSUE TITLE
Improved Chain Heal not benefiting from +heal

### ISSUE THREAD

**Issue by zelazrgn** [LightsHope/server#894]
Tested on Bropack v7

This time I only bothered testing the first bounce. In order to compare with the exact same gear, I manually learned and unlearned improved chain heal via the gm commands (.learn 21899).

I tested it with starting gear, with no +heal, and with gear giving +1088 heal.

I threw out chain heals that involved a critical.

T1 refers to heals applied to the first target, T2 second target.

| Test  | Trials | Avg Ratio (T2/T1) | Avg T1 | Avg T2 | Min T1 | Max T1 | Min T2 | Max T2 | highest possible ratio | 
| ------------- | ------------- | ------------- | ------------- |------------- |------------- |------------- |------------- |------------- |------------- |
| 0+Heal | 60 | 0.5027 | 607.7000 | 305.5000 | 567.0000 | 644.0000 |  283.0000 | 322.0000 | 0.5679 |
| ICH 0+Heal | 39 | 0.6505 | 606.1026 | 394.2821 | 568.0000 | 643.0000 | 369.0000 | 418.0000 | 0.7359 |
| 1088+Heal | 52 | 0.5007 | 1379.7885 | 690.8846 | 1344.0000 | 1422.0000 | 672.0000 | 710.0000 | 0.5283 |
| ICH 1088+Heal | 38 | 0.5686 | 1381.7632 | 785.7105 | 1347.0000 | 1422.0000 | 756.0000 | 807.0000 | 0.5991 |
 
Difference between Avg T2 for 0+heal = 88.78
For 1088+Heal = 94.83

highest possible ratio is taking the max t1 / min t1, you can see it doesn't even get close to 0.65 for +heal

combat logs:
https://gist.github.com/zelazrgn

Effectively with good +healing gear, Impoved Chain Heal is only giving a ~15% boost.

**Comment by GuybrushGit** [comment]
Improved Chain Heal is a TBC talent isn't it?

**Comment by chrisj** [comment]
It is the 3 set bonus from Ten Storms http://vanillawowdb.com/?spell=21899

I was able to manually learn it with GM commands which allowed me to avoid testing with different amounts of +heal.

**Comment by zelazrgn** [comment]
It is the 3 set bonus from Ten storms, I was able to manually learn it using the gm commands. http://vanillawowdb.com/?spell=21899

**Comment by GuybrushGit** [comment]
I see. Looking at the code it seems like every healing spell is set up to work like this.
It seems to be intentional, from the 1.12.1 TC addon:
>Some spells are hardcoded to not have talents applied on gear, this is from testing in game.  Eg curse of agony, drain life, every healing spell :).

**Comment by GuybrushGit** [comment]
From the wiki:
>http://wowwiki.wikia.com/wiki/Spell_power?oldid=317990
>Damage benefits are applied before any talents or buffs that may increase your damage by a flat percentile. Healing spells are opposite; all talents are added to the base first then healing benefits added.

**Comment by zelazrgn** [comment]
yeah that sounds correct, thanks for checking

**Comment by zelazrgn** [comment]
It appears it did benefit from +healing in TBC based on this post https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/107115-resto-shaman-healing-gear-guide.html

But there were spell/healing power changes in TBC. You are free to close it/tag it as not a bug.

**Comment by zelazrgn** [comment]
And a better source for the T2 Bonus (original source I posted is a copy)
https://web.archive.org/web/20080302191341/http://elitistjerks.com:80/f31/t19181-shaman_how_heal_like_pro/

"* Added a section on using Tier 2 (1/7/2008)"

**Comment by GuybrushGit** [comment]
That source is from 2008 and most likely is referring to the chain heal talents, which doesn't even exist in vanilla.
Actual Vanilla sources clearly state that modifiers dont apply to +heal from gear.

**Comment by zelazrgn** [comment]
That source has a section dedicated to Tier 2. It is very long. The improved chain heal talent behaves differently as it increases the original heal (and all bounces based on that). It is not a modification of the decay.

It is true that talents are calculated before +heal but it seems there is a pretty strong assumption that these auras for the chain decay is behaving differently. I feel the the expected behavior of such a bonus would be a consistent ratio between the bounces regardless of +healing gear.

"In a regular chain heal you have X + (0.50*X) + (0.50*0.50*X) where X is the base healing on the first target or 
X + 0.50X + 0.25X = 1.75X

With 3T2 you have X + (0.65*X) + (0.65*0.65*X) where 
or X + 0.65X + 0.4225X= 2.0725X" from source. the source also mentions improved chain heal.
