### ISSUE TITLE
Wrong Dire Maul instance zone-out point

### ISSUE THREAD

**Issue by b82a** [LightsHope/server#9]
Dire Maul zone-out point leads to the tunnel you leave DM:E with. That makes opposite faction camp and abuse it, because when you die, you can not spirit walk back. (If you don't remember, you are dropping down from that tunnel and you cant "fly" back in it).
The only way out of it is ressurection sickness, which leads to yet another abuse of people camping it and getting free kills. Proof: https://i.imgur.com/OCwE6Ne.jpg

Expected behaviour: Zone-out point is DM:W entrance, where you can ressurect on your corpse and don't have to res-sick.

Server: Elysium

**Comment by FireReaver** [comment]
Maraudon similar issue still not fixed
