### ISSUE TITLE
Amulet of the Darkmoon stats incorrect (post 1.7)

### ISSUE THREAD

**Issue by EdMao** [LightsHope/server#903]
The Amulet of the Darkmoon necklace has incorrect stats and quality level on the Lightbringer realm (now on patch 1.8).

The current stats on the necklace are (superior/blue quality): 
[Amulet of the Darkmoon]
Binds when picked up
Neck
+18 Agility
+7 Stamina
Requires Level 60

The stats of the necklace post 1.7 should be (epic/purple quality):
[Amulet of the Darkmoon]
Binds when picked up
Neck
+19 Agility
+10 Stamina
+10 Strength
Requires Level 60

The updated stats and patch notes (for 1.7) references can be found here:
https://www.engadget.com/2011/07/19/wow-archivist-patch-1-7-rise-of-the-blood-god/
http://wowwiki.wikia.com/wiki/Amulet_of_the_Darkmoon
http://db.vanillagaming.org/?item=19491

**Comment by QAkvastskaft** [comment]
Have you deleted your WDB folder?
