### ISSUE TITLE
Paladin BUG

### ISSUE THREAD

**Issue by shrinkwow** [LightsHope/server#906]
Hello,

i have a problem = paladin bug. I cant train ressurection. I read on the internet, when my first quest is sense undead, so ressurection quest jump to the bug. I know, my false, but i play paladin for first time. Can you give me the ressurection over the game database please? Sorry for the misstake.

Thanks for positive answer.
(gamename: Zlacernoska, Human Paladin 23lvl)

**Comment by GuybrushGit** [comment]
No
