### ISSUE TITLE
Lorgalis Manuscript is zone drop instead of only object drop.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#907]
http://vanillawowdb.com/?item=5359
http://wowwiki.wikia.com/wiki/Lorgalis_Manuscript?direction=next&oldid=285222
This shouldn't drop from any mob. It should only drop from object=13949, i see it drops from 2 objects atm, the 2nd being in Thousand Needles (?).

**Comment by QAkvastskaft** [comment]
https://web.archive.org/web/20050222232909/http://wow.allakhazam.com:80/db/item.html?witem=5359

Low percentages on the mobs are likely junk data from the addon used to gather the data
