### ISSUE TITLE
Starshards math tolerance error

### ISSUE THREAD

**Issue by RoxanneFlowers** [LightsHope/server#908]
Darrowshire patch 1.9 dated 3 Dec 2017

Original reporting: [Link](https://forum.lightshope.org/viewtopic.php?p=16925#p16925)
Character window screenshot: [Link](https://i.imgur.com/8n086zu.jpg)
Starshards spell tooltip: [Link](https://i.imgur.com/fiFSjAg.jpg)
Starshards use results: [Link](https://i.imgur.com/7z4hLYz.jpg), [Link](https://i.imgur.com/TvFjTOj.jpg)

So with **+86 spellpower**, my Starshards is dealing 54, 54, 81, 81, 108, 108 = 486 damage.
414+86 = 500 damage ... so somehow I'm "losing" 14 damage somewhere in the "drop fractions" math that's getting used to divide up the damage for the Starshards damage ticks. **Remember, the multipliers, per tick are 2, 2, 3, 3, 4, 4 (=18 total) for all 6 damage ticks.** What's probably happening is that 500 damage is getting divided by 18, yielding a value of 27.777. Drop the fraction to make an integer value and you get 27, which then perfectly multiplies out into 54, 54, 81, 81, 108, 108 for a total of 486 damage. I've got no definitive proof from looking at the game encoding telling me that's how it works under the hood, I'm just thinking I'm safe in assuming this to be the case (because lazy programming by Blizzard, I'm guessing).

So what that would mean is that for the purposes of Starshards, I'm looking at needing a full +18 spellpower per bump in damage applied by all 6 damage ticks. So once I can manage to get +90 spellpower, 414+90=504 ... divide that by 18 and get a value of 28 ... run the multipliers and get damage ticks of 56, 56, 84, 84, 112, 112 = 504 ... I'm theorizing.

Note that 414/18=23 ... producing a +0 spellpower result of 46, 46, 69, 69, 92, 92 = 414 after running through the 2, 2, 3, 3, 4, 4 multipliers for each damage tick.

So it looks like the 100% spellpower coefficient for Starshards is working "just fine" right up until pushing the damage through the sausage grinder that divides it up into the individual damage ticks to be dealt to the target, which can result in some "lossy" inefficiencies of throughput when the spellpower being added doesn't divide "neatly" by 18 into getting cleanly added into each damage tick via the limitations of integer math (brought to you by Premature Optimization™).

**Comment by QAkvastskaft** [comment]
Please see #216
