### ISSUE TITLE
Weapon Skill - Leveling Rate

### ISSUE THREAD

**Issue by Hackstylez** [LightsHope/server#911]
Leveling weapon skill feels prohibitively arduous compared to past experiences with Retail Vanilla 1.12.

**03 Dec 2017.**  Fighting level 60 non-elite mobs in Eastern Plagueland's Noxious Glade for two hours whilst equipping 203 Intellect worth of greens yielded zero weapon skill levels.  Attempt to progress 273 -> 274 Guns and 298 -> 300 Two-Handed Axes failed.

Bug or blizzlike?  Either way, would be interested to see the SQL powering this mechanic.

**Comment by Zarant** [comment]
I usually level my weapon skills on the servants in blasted lands, and from what I could tell, the chance of getting a skill up is the same regardless of the weapon speed, 2h weapons take a long ass time to level, like many weeks worth of grinding. With no intellect buffs it took me around 9500 swings, about 5 to 6 hours worth of auto attacking a servant while afk to level my one handed axe skill from 295 to 300 with a 2.3 speed 1h + shield. Not sure if that's blizzlike or not, but you can ask anyone who played a melee class back then, I can't recall having to grind mobs for 1 or 2 weeks straight to level my 2h weapon skill.
Unfortunately that is the kind of thing that you won't find any thoroughly documented sources from retail wow.

I found a wowhead post from TBC (patch 2.3):
http://www.wowhead.com/forums&topic=7234/fastest-way-to-level-weapon-skills#p66000
It says that it took him about 1 to 1.5 hours to level from 1 to 348 (maximum weapon skill was 350 at the time)
The only documented change regarding the weapon skill leveling rate dated from patch 2.4, I don't believe the formula was ever changed from vanilla to tbc.

Source:
Weapon Skill: Points will be gained faster in weapon skills for levels 1 through 59. (http://wowwiki.wikia.com/wiki/Patch_2.4.0)

**Comment by Zarant** [comment]
I did some more research and found out that ranged weapons and wands should have an increased chance of getting a skill up:
Skill-up rate improved for bows, crossbows, guns, thrown, and wands. (http://wowwiki.wikia.com/wiki/Patch_1.3.0)

Maybe I'm missing something but I can't find any special case to handle ranged weapon skill at
https://github.com/LightsHope/server/blob/6dfb67c785206410a4d3030fd28f3d1ced462e5e/src/game/Objects/Player.cpp#L5373
which may indicate that the behavior is not blizzlike.

**Comment by stesve** [comment]
> I did some more research and found out that ranged weapons and wands should have an increased chance of getting a skill up:
>  Skill-up rate improved for bows, crossbows, guns, thrown, and wands. 

They improved the skill uprate from a previous value. That doesn't necessarily mean that the skillup rate of ranged weapons is higher than melee weapons.
