### ISSUE TITLE
Chain Lightning Bonus not benefitting from Spell Power

### ISSUE THREAD

**Issue by zelazrgn** [LightsHope/server#915]
Similar to my Improved Chain Heal (ICH) (T2 3 set bonus report)

http://db.vanillagaming.org/?spell=26123 is the spell from the Gift of the Gathering Storm set.

Default decay of chain lightning is 0.7x, 0.49 for the second bounce. CLB is a 5% bonus (0.75 0.5625).

This may not be conclusive proof (harder to test with a small bonus) but I believe it is enough to warrant investigation into the code. I tested it similarly to ICH by manually adding the aura to character. Tested it on Bropack v7. This time I included criticals (divided by 1.5) and I used resists (added damage + resisted amount). I tested it on the imp packs in molten core.

T1, T2, T3 = damage to target 1, 2, 3

| Test  | Trials | Avg (T2/T1) | Avg (T3/T2) | Avg (T3/T1) | AVG T1 | AVG T2 | AVG T3 | 
| ------------- | ------------- | ------------- | ------------- |------------- |------------- |------------- |------------- |
| 0+Spell | 51 | 0.7079 | 0.6896 | 0.4882 | 529.3987 | 374.7647 |  258.4510 |
| CLB 0+Spell | 88 | 0.7317 | 0.7336 | 0.5368 | 535.9432 | 392.1667 | 287.7083 |
| 640+Spell | 72 | 0.7013 | 0.6994 | 0.4905 | 991.9398 | 695.6852 | 486.5370 |
| CLB 640+Spell | 65 | 0.7134 | 0.7207 | 0.5141 | 996.1077 | 710.5897 | 512.1026 |

Difference between AVG T3 for 0+Spell = 29.26, 640+spell = 25.56

combat logs are uploaded here: https://gist.github.com/zelazrgn

Side note: possible bug is that if you get a full resist on T1, the damage done on T2 and T3 is greatly increased. It seems that maybe T2 and T3 may get the bonus of T1 and T2 if the original target fully resists, I didn't purposely test this but it was a significant boost (+100 damge on T3).

I would also like to re-open https://github.com/LightsHope/server/issues/894 on the following grounds:

1. The earliest source on the benefits of the T2 set bonus indicates it does benefit from +healing. Nothing indicates that wasn't the case in 1.12.1.
2. These spells are very unique and behavior of more traditional talents cannot be assumed. It seems unreasonable that they would adjust it to benefit from +healing only to then nerf it from 30% down to 5% in 2.4.2.
3. Behavior makes more sense from end user, they maintain a consistent ratio from T1/T2/T3 as you add HP.
4. Both these spells (ICH, CLB) are nearly identical looking at QSW.
5. Chain Healing Wave (T1 bonus) does benefit from +healing in this code base.

Last 2 are suggesting that the behavior of these spells should probably be consistent.

**Comment by zelazrgn** [comment]
And a better source for the T2 Bonus (original source I posted is a copy)
https://web.archive.org/web/20080302191341/http://elitistjerks.com:80/f31/t19181-shaman_how_heal_like_pro/

"* Added a section on using Tier 2 (1/7/2008)"

**Comment by GuybrushGit** [comment]
In short, the spellpower portion of the chain light / heal spells is being affected by the chain modifiers here: https://github.com/LightsHope/server/blob/development/src/game/Spells/SpellMgr.cpp#L332
But its only the default modifiers from spellProto, these values should change with gear / talents.

**Comment by zelazrgn** [comment]
I was incorrect in saying this bonus results in a 0.75, 0.5625 multiplier. It is actually a (0.7 * 1.05) = 0.735, 0.540225 multiplier which explains the results I got above. Based on the TBC sources on the chain heal modifier, that is probably the correct interpretation of "Increases the chain target damage multiplier of your Chain Lightning spell by 5%".
