### ISSUE TITLE
Custom Change: Anvilrage Warden's Hooked Net in BRD

### ISSUE THREAD

**Issue by Belmontz** [LightsHope/server#925]
All the sudden Anvilrage Warden: http://db.vanillagaming.org/?npc=8890#abilities
got net from TBC version of WoW. As well as i can recall, there were no nets during all Nost progression patches, plus official Blizzard patches, plus, according to the link i posted above, they dont really have this spell. Maybe some database shift fucked up everything, or whatever.

**Comment by druidish** [comment]
https://imgur.com/a/SHmAu from page 57 of the dungeon guide for vanilla.

**Comment by Belmontz** [comment]
Well, i dont think that you can refer to this "dungeon guide" since A LOT of stuff that i see there, is not in game, like Officer's with healing spells and paladin immune thingy. But somehow, someone took random parts of "changes" and applied it to server, without development updates or any public info. And that's bad. Coz i was trying to learn how to farm random part's of BRD in AoE spec, and yesterday, there were no nets, and now, you actually dont stand a chance even vs a 2 mobs.

**Comment by stesve** [comment]
> Well, i dont think that you can refer to this "dungeon guide" since A LOT of stuff that i see there, is not in game, like Officer's with healing spells and paladin immune thingy. But somehow, someone took random parts of "changes" and applied it to server, without development updates or any public info. And that's bad. Coz i was trying to learn how to farm random part's of BRD in AoE spec, and yesterday, there were no nets, and now, you actually dont stand a chance even vs a 2 mobs.

Net, healing and bubble is ingame atm and was during vanilla retail.

**Comment by Belmontz** [comment]
Well yeah, according to this "guide" Officer's only have ranged attack, without anything above it. But IN GAME they have immune and Holy Light, AND ranged attack. So, ugh, you do it in 2 ways. Way number one, you take anything that is in the guide, and port it, just like that. Way number two, you dont take anything from it. I dont think that taking a random parts, ignoring others, is a good thing.

**Comment by druidish** [comment]
In the text description of their strats in the book they mention more of the officer's abilities. For whatever reason they only highlighted some abilities in their mob summary.

**Comment by Belmontz** [comment]
Looks like another Gordok tribute teleport thing. Elysium staff nerfed DM a lot, RIP Hunter-mage farm. Mages went to BRD after that. And now, we get BRD nerfs. Without returning previous changes to normal condition. Hey-hey-hey whitekidney shop uprising boys. Oh well. Let's do it "we cant just copy Nost version without ruining it with, oh so all-knowing hands" way. With gold farm spots heavy nerfs. So noone will be able to get gold themselves. So everyone will buy gold from admins. Cheers, i'm out.

**Comment by stesve** [comment]
> Looks like another Gordok tribute teleport thing. Elysium staff nerfed DM a lot, RIP Hunter-mage farm. Mages went to BRD after that. And now, we get BRD nerfs. Without returning previous changes to normal condition. Hey-hey-hey whitekidney shop uprising boys. Oh well. Let's do it "we cant just copy Nost version without ruining it with, oh so all-knowing hands" way. With gold farm spots heavy nerfs. So noone will be able to get gold themselves. So everyone will buy gold from admins. Cheers, i'm out.

This is just dumb. There is an upcoming change to Tribute and you should be aware of, that every change takes time.

I quite confident that the current state of BRD is blizzlike. 

You should spend more time investigating if you think there is an issue, and less time of wildly accusing everyone else.

**Comment by QAkvastskaft** [comment]
The World of Warcraft Master Guide is valid source.  http://db.vanillagaming.org is not. If there are other abilities of mobs that are missing or is incorrect please make a bugreport of it. 

The incorrect behavior of these mobs were brought up on the tracker a few weeks ago and a fix was submitted. Today that fix was put to live realms. 

The patch notes are posted here https://forum.lightshope.org/viewforum.php?f=5&sid=bb0a2026101da6d25cc37853e8fa014c
some time after the patching is done. This can take 1-2 days based on workload of the dev team and other factors.

**Comment by stesve** [comment]
Well.. i just got my copy... so 

Source: World of Warcraft: Dungeon Companion - Published July 11, 2006 

Page 57 confirms that wardens has a net ability.
Page 65 confirms that officers are paladins and cast divine shield.
