### ISSUE TITLE
Warriors can't hit Ragnaros with Whirlwind

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#934]
**Issue**
If you use Whirlwind vs Ragnaros while being in range of him, it doesn't hit him. I think this has something to do with his hitbox or how Whirlwind is coded.

This might also be an issue for Cleave, Sweeping Strikes and Blade Flurry, but I haven't tested those.

My theory is that for some reason Whirlwind and possibly other cleave abilities calculate the distance based on the center of the mob, rather than the hitbox.

**How it should be**
Whirlwind should hit up to 4 targets within 8 yards. Ragnaros' hitbox is huge, which means if you're within 8 yards of his hitbox, you should be able to hit him with whirlwind.

**Reasoning**
If you are auto-attacking Ragnaros, you're clearly within 8 yards, since auto-attack range is 5 yards.

**Comment by agrom1** [comment]
iirc this is blizzlike

**Comment by gotmilk0112** [comment]
Yes, for the longest time, certain abilities calculated distance based on the center of the mob's hitbox, instead of the outside. Priest's "Atonement" worked like this until late Cata. Really only got fixed because of Ragnaros and how the center of his hitbox was 30+ yards away from anyone, so Atonement would do nothing on that fight.

**Comment by n985950** [comment]
This is true I played in vanilla and I remember being able to use whirlwind, also ironfoe was 6%

**Comment by knasen88** [comment]
You can use it, you just have to jump into him, or walk to your left (if using usual melee spot)

**Comment by vindruvor** [comment]
The same thing happens on Kel'thuzad and Sapphiron, but ye idk what is blizzlike

**Comment by ohganot** [comment]
Well it's certainly a bug even if it wasn't fixed in Vanilla. I'm fairly sure it worked in Vanilla though.

**Comment by bigfgeg** [comment]
I tested this yesterday and it worked just fine on Lightbringer.

**Comment by ohganot** [comment]
No it doesn't. You can hit him, but only if you go very close to him. If you are within range to auto-attack which is 5 yd range but can't whirlwind which is 8 yd range, then it doesnt work.

**Comment by ohganot** [comment]
Looks like a blizzlike bug after all:
https://www.youtube.com/watch?v=VNbEcXikcvA Thaddius Fury Warrior PoV
