### ISSUE TITLE
Quest chain, 549, 566 wrong level requirement

### ISSUE THREAD

**Issue by obmit2** [LightsHope/server#939]
The quest 549, "WANTED: Syndicate Personnel", should allow to take and complete follow-up:

566, WANTED: Baron Vardus

The level requirement was 18 (correct on 549, but not on 566).

Sources:
https://www.wow-freakz.com/quest_helper.php?quest=566&name=deprecated-wanted-baron-vardus
http://wowwiki.wikia.com/wiki/Quest:WANTED:_Baron_Vardus

**Comment by obmit2** [comment]
Better source:
http://web.archive.org/web/20070716044035/http://www.thottbot.com:80/q566

**Comment by Cabro** [comment]
https://github.com/LightsHope/server/pull/843
From what i could find in vanilla, that quest was level 35. In the link you gave, the comments only started to say about being a level 19 quest sometime in TBC, until then it was level 37-ish that said they killed it.

**Comment by obmit2** [comment]
see thotbot link, states the level req:
http://web.archive.org/web/20070716044035/http://www.thottbot.com:80/q566

**Comment by Cabro** [comment]
2007 16 august - that is TBC date, man

**Comment by QAkvastskaft** [comment]
We use the value from the World of Warcraft Master Guide.
566, WANTED: Baron Vardus has a min level of 35
![image](https://user-images.githubusercontent.com/26366996/33782235-25537cec-dc58-11e7-813b-8c35b8d5c231.png)

**Comment by Cabro** [comment]
@QAkvastskaft any info on the quest levels pull? :) They've been ready 2 weeks ago or so.
