### ISSUE TITLE
Rogue talant - Riposte

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [LightsHope/server#940]
Why when a rogue in battle with mobs who do not have hands (or they do not have weapon in their hands) cast [Riposte](http://db.vanillagaming.org/?spell=14251) ? Or if it's right - why we have animation of disarm on those mobs that have no weapon or have no weapon in their hands ?
![wowscrnshot_120817_192253](https://user-images.githubusercontent.com/30354821/33770374-e0ec6e26-dc5f-11e7-99ec-7e15a460fa5b.jpg)

How Riposte working on Darrowshire:
![wowscrnshot_121017_005922](https://user-images.githubusercontent.com/30354821/33798515-6b88c11e-dd4c-11e7-8303-f1229eb5ef7f.jpg)
![wowscrnshot_121017_011259](https://user-images.githubusercontent.com/30354821/33798517-72d8261c-dd4c-11e7-8b2d-f599756bda46.jpg)
![wowscrnshot_121017_011643](https://user-images.githubusercontent.com/30354821/33798518-76cd925c-dd4c-11e7-8a04-b24ffbcfc9dd.jpg)
![wowscrnshot_121017_012351](https://user-images.githubusercontent.com/30354821/33798519-7bf4a2f2-dd4c-11e7-94ea-b4d8a4c40051.jpg)

**Comment by thepparker** [comment]
This is simply a client visual to the disarm aura. You can definitely use Riposte on creatures which do not necessarily have weapons.
