### ISSUE TITLE
Disenchanting The Lion Horn of Stormwind gives you a Large Brilliant Shard instead of Nexus Crystal(s)

### ISSUE THREAD

**Issue by steeve21** [LightsHope/server#945]
Disenchanting The Lion Horn of Stormwind gives you a Large Brilliant Shard instead of Nexus Crystal(s).
Posted here as requested by GM.

**Comment by QAkvastskaft** [comment]
Nexus Crystal(s) were not ingame until patch 1.9. http://wowwiki.wikia.com/wiki/Patch_1.9.0
