### ISSUE TITLE
[Lightbringer] Bonereaver's Edge armor pen buff not supposed to exist yet

### ISSUE THREAD

**Issue by bigfgeg** [LightsHope/server#965]
BRE isn't supposed to have that particular proc in this patch. Fairly gamebreaking to have 2100 armor pen proc on BRE. It was added as a catchup mechanic in 1.10 and buffed to stack to 3 in naxx patch or so (unsure), so it makes relatively little sense to have the weapon be in that "ultimate" stage right now.

For info as to what it's supposed to have in this patch view old allakhazam page. 
https://web.archive.org/web/20060215114712/http://wow.allakhazam.com:80/db/item.html?witem=17076
Feb 15, 2006. That's sometime after 1.9 and it still has the old proc then. 

https://web.archive.org/web/20060716021330/http://wow.allakhazam.com:80/db/item.html?witem=17076
July 2006, that's post-1.11 and stacks only once. 

Patch 1.10 mentions the change. 
http://wowwiki.wikia.com/wiki/Patch_1.10.0
>>The Bonereaver's Edge's triggered effect has been changed. Instead of lowering your victim's armor, it will cause you to ignore a portion of your victim's armor. Its triggering rate was substantially increased as well as the magnitude of the effect. In addition, the item now has 16 stamina. 

Since I've heard difficulties with adding the old proc previously (since the proc effect apparently does not exist in the client anymore) perhaps the buff should be disabled for now, or limited to 1 stack if possible as an inbetween solution. 
It's important to keep in mind that disabling the proc entirely is closer to the weapons blizzlike state than keeping it the way it is now. 

Thanks for your time

**Comment by Aklol** [comment]
#394 please close this

**Comment by bigfgeg** [comment]
Why? The problem persists and the discussion in that issue seems to not have reached any conclusion. 

If no conclusion can be reached from discussion, then in my opinion the best course of action is to make things blizzlike.

**Comment by Aklol** [comment]
so bump the other thread that has a lot of input, including developers. don't make a new thread

**Comment by bigfgeg** [comment]
There's no bumping on github issues.

**Comment by brotalnia** [comment]
Duplicate issue. If you are capable of figuring out packet structure for each patch so we can implement full client progression in order to fix this let me know. Otherwise it is pointless to keep opening additional issues for the same thing.
