### ISSUE TITLE
[Lightbringer] Mobs that shouldn't parry do parry

### ISSUE THREAD

**Issue by bigfgeg** [LightsHope/server#966]
Currently nearly every single enemy in the game parries. 

I know there was a change recently that enabled parrying for non humanoids, which is right and proper since there are some non humanoid enemies in the game (certain undead, certain beasts like crabs) that should parry. 

It seems however that something is missing still because now it looks like flat out every single enemy can parry. Fire eles, tigers, slimes, snakes, absolutely everything. Even CRITTERS! A rat critter parried me in EPL today. Jindos totems parry. Totems on nef parry. 

while it's sometimes funny, it's also a fairly big deal for leveling. 

Also, while this might just be a completely subjective feeling (potentially because most creatures did not parry at all previously), parry chance seems completely overtuned. I'm not sure if it's just bad RNG coupled with confirmation bias but it feels like certain mobs have like a 30% parry chance on me.

**Comment by Cabro** [comment]
Also from what i know, mobs shouldn't parry while casting. Or is that only for players?

**Comment by stesve** [comment]
These where linked before:
https://vanilla-twinhead.twinstar.cz/?issue=4987
https://vanilla-twinhead.twinstar.cz/?issue=3179

I can also provide evidence of a critter parrying, but its during tbc.

**Comment by ohganot** [comment]
It should probably be disabled for totems.

Most if not all mobs should be able to parry though.

**Comment by brotalnia** [comment]
I disabled parry for Totems. Makes sense that they wouldn't be able to parry.
https://github.com/LightsHope/server/commit/3eb5db1b7973201d12b14b4d2e197e90f591bb0d

If somebody has some evidence that they could actually parry please come forward.
