### ISSUE TITLE
Nature's Wisper quest item not aquired from mailbox.

### ISSUE THREAD

**Issue by Ambjoern** [LightsHope/server#971]
I want to report a bug regarding the quest item "Nature's Wisper" (http://db.vanillagaming.org/?item=20645) that should be sent via in-game mail after completion of the questline http://db.vanillagaming.org/?quest=8287

The quest item should be send roughly 24 hours prior to completing the questline - a week later I still haven't recieved anything via in-game mail.
I also did the questline http://db.vanillagaming.org/?quest=8320 which according to the interwebs had to be done to acctually get the quest item (Nature's Wisper). 
Nothing happened, and I got no necklace. 

I was sent forward to here after sending an in-game ticket. 

It would be awesome if you could look into this matter since I hear more people not getting their in-game mailbox reward.

Thanks in advance, 

Best regards,

Ambjoern

**Comment by thepparker** [comment]
I received the neck with no issue both on dev and the live servers.
