### ISSUE TITLE
How to get the title of [king beetle]?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#982]
How to get the title of [king beetle]?
Ahn'Qiraj event has been completed, but no...

**Comment by Phoosy** [comment]
There are no titles in Vanilla. Invalid issue.

**Comment by DarkmoonRabbit** [comment]
@Phoosy .....???
in TBC?

**Comment by Slicy** [comment]
There are titles in Vanilla. It's called your current PvP rank.

**Comment by thepparker** [comment]
Titles added in BC

**Comment by DarkmoonRabbit** [comment]
@thepparker BC? TBC?

**Comment by Sabre142** [comment]
@DarkmoonRabbit The Burning Crusade.
