### ISSUE TITLE
Empyrean Demolisher procc too high

### ISSUE THREAD

**Issue by Homiecup** [LightsHope/server#983]
With the recent buff of Empyrean Demolisher it has become incredibly powerfull of a weapon even beating r14 weapons and being better or pretty much on par with KT swords, i feel like this is a red flag already since it really shoulden't be that being a weapon from Kazzak.
https://xpoff.com/threads/weapon-proc-rates.60492/ - This is a source that was used for the buffing of the weapon, but as you can see alot of these procc chances are way too high, we can see this with Ironfoe being a whopping 2.5 which would've made it the best weapon in the game.
http://www.wowhead.com/spell=243994/empyrean-demolisher Empyrean demolishers procc 1.5
http://www.wowhead.com/spell=182395/thrash-blade - Ironfoe's procc 2.0
This was the retail source used  to change Empyrean Demolisher's procc rate, but why would Ironfoe get nerfed then when it was already under the retail procc chance? I think for Ironfoe a 4% procc chance is fair for being a dungeon item, it makes it good, but not game breaking and makes r14 grind worth it, and it is still pretty solid with wbuffs. 
Empyrean demolisher on the other hand is just broken for how easy Kazzak is as a boss, and i feel its even easier to get than Ironfoe - if your guild controls the world bosses, which would be easier on a blizzlike pop realm.
I belive that giving Empyrean Demolisher a 4% procc chance will not break the weapon as you can see with Ironfoe, so that it can still be viable but it wont be as broken as it is now.

The change of Ironfoe and Empyrean Demolisher was all bugreports by Ohganot 
http://realmplayers.com/CharacterViewer.aspx?realm=LB&player=Steppenwolf

These are the bugreports he made
https://github.com/LightsHope/server/issues/111 - Buffing Empyrean Demolisher 21. oct
https://github.com/LightsHope/server/issues/204 - Nerf Ironfoe 23. oct

Steppenwolf has beeen farming Ironfoe for quite a while before making the bug reports and after getting Empyrean Demolisher he made a bug report to buff his new weapon and nerf the Ironfoe he never got. 

Summary:
The retail procc chances on wowhead is definitly not the right way to decide the procc chances of weapons, making the 1.5 ppm of Empyrean Demolisher unrealistic and if not, then i would expect Ironfoe getting the same treatment getting it buffed to 2.0 ppm which would make it the best weapon in the game, even better than KT swords when buffed.

**Comment by ohganot** [comment]
I don't see any vanilla sources in this bug report, as opposed to my reports having vanilla sources amongst others.

Also, me benefiting from a higher proc chance has nothing to do with the question which proc rate is more blizzlike, which should be the main question that requires answering.

1.5 PPM has supporting sources from both Vanilla and TBC, whereas I haven't been able to find any sources to support 1 PPM. If you can find sources for this, you're very welcome to post them here.

**Comment by wuvluv** [comment]
There were no vanilla sources in your post

**Comment by Homiecup** [comment]
https://cdn.discordapp.com/attachments/323644704896057344/390548865998389269/unknown.png
https://cdn.discordapp.com/attachments/323644704896057344/390548801829470218/unknown.png
This is spreadsheet showing the power of the buffed Emphyrean

**Comment by YoshGit** [comment]
Clearly all those sources that point to a 1.5 ppm for Empyrian are bogus. There was clearly a double standard between these reports and this one slid under the radar and merged without having been thoroughly investigated first.

**Comment by Homiecup** [comment]
@ohganot 
- Increased the procrate of Empyrean Demolisher from 1ppm to 1.5ppm, based on evidence from retail
I provided the same source for Ironfoe as for Empyrean Demolisher, you diden't have any sources for your weapons buff other than comments saying that it has a high procc chance, which there is no evidence to back up

**Comment by omakaroni** [comment]
This will essentially mean rogue prio on Gressil for human warrs, thats not blizzlike. Gressil and Hungering Cold should be BiS for all warrs.

Im the dev of the fury spreadsheet and i strongly suggest some of you DEVs join the warrior Discord and see the discussion this buff have caused. https://discord.gg/Ds85MeR

Rigth now we only have Gemt here :)

**Comment by YoshGit** [comment]
Turns out changing the code is easier than farming BIS these days :(

**Comment by ohganot** [comment]
Spreadsheet doesn't change much, since the main reason to change this was PPM sources, not for balancing.

Besides, the spreadsheet has inaccuracies, especially for Empyrean Demolisher since it doesn't factor the fact that sometimes the proc isn't useful, for example if it procs during moving or if the mob dies when you get the proc.

Also, my own spreadsheet has different results, it seems ED is somehow too strong in your spreadsheet.
https://gyazo.com/4e3b50ac2945ace82ba7a77b36b911c8 ED + Hungering Cold 1137 DPS
https://gyazo.com/e40de5aba3565d4bd0aed1d9849a48ee Gressil + Hungering Cold 1152 DPS

**Comment by omakaroni** [comment]
You dont have naxx BiS on in your spreadsheet you run AQ gear, as gear progress ED/haste scales more aswell.

**Comment by Homiecup** [comment]
@ohganot There was no source to the ppm you provided, and if you consider retail the source then Ironfoe should be 2.0ppm. 
And i would trust Omaks sheet more as its the original that you stole and put your name on, and omak has naxx items and more experience with that

**Comment by ohganot** [comment]
https://web.archive.org/web/20060516095122/http://www.warriorguideswow.com/index2.php?option=com_content&do_pdf=1&id=13

Vanilla Warrior guide which was found on retail forums, saying that the proc rate is 1/15. Which is very close to 1.5 PPM.

**Comment by ohganot** [comment]
@Homiecup You mean the spreadsheet I have been making for a year now, based on the original Nost spreadsheet and which Omak started using it as the base for his spreadsheet, because he liked the design more? Please dont spread lies.

**Comment by Manlet** [comment]
> ohganot: Please dont spread lies.

😂

**Comment by YoshGit** [comment]
"ohganot: Please dont spread lies."
😂

**Comment by Homiecup** [comment]
> ohganot: Please dont spread lies. 

😂
