### ISSUE TITLE
Cloudkeeper Legplates shouldn't trigger trinket cooldowns

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#987]
**Issue**
Cloudkeeper Legplates active effect puts Diamond Flask, Earthstrike, Jom Gabbar and other similar trinkets on cooldown.

**How it should be** 
Cloudkeeper Legplates don't share cooldown with anything

**Proof**
https://www.youtube.com/watch?v=WJWZ8jcswj0

In this video you can see the Warrior using Cloudkeeper Legplates, Badge of the Swarmguard and Jom Gabbar all in conjunction.

**Comment by knasen88** [comment]
please fix

**Comment by Fiskehatt** [comment]
That behaviour could have been changed in [Patch 1.10](http://wowwiki.wikia.com/wiki/Patch_1.10.0) in which most trinket stacking was made impossible:

>  Many trinkets will now trigger a cooldown equal to the duration of their effects that will prevent simultaneous use of more than one of these trinkets. The Trinkets affected include the Zandalarian Hero Charm, Zandalarian Hero Badge, Zandalarian Hero Medallion, and most all the other Trinkets available from Zul'Gurub, Earthstrike, the Talisman of Ephemeral Power, and the level 50 class quest trinkets such as the Devilsaur Eye. 

To be sure it does not share a cooldown, we would need to ensure that video is taken after Patch 1.10 (the upload date is not enough) or find another video/proof.

**Comment by knasen88** [comment]
Not only is cloudkeeper not a trinket but a leg, nor is it from ZG and badge trinket is notorious for being unique with its double trinket activation. It is also not listed in the patch so I reckon the burden of proof is the other way around.

**Comment by ohganot** [comment]
Not only that, but the video was uploaded on 20th April of 2006, almost 1 month after patch 1.10 release.

**Comment by Fiskehatt** [comment]
I guess you are right: this seems to be a general mechanic for "Use" items. In this video a paladin pops a Manual Crowd Pummeler and Scrolls of Binding Light at the same time (even though his other trinket goes on CD).

https://youtu.be/9tQbfK7kImA

**Comment by ohganot** [comment]
Good find.
