### ISSUE TITLE
Gerenzo's Orders

### ISSUE THREAD

**Issue by cljnilsson** [LightsHope/server#99]
So me and my mate was using Questie and found a quest on the map which we went to do.
http://db.vanillagaming.org/?quest=1090 does not really matter if it is the wrong link, that is the name no matter which database you check.

We talked to the questgiver and the quest started, 10-ish kobolds came running and we had no way to kill those so we died. Somehow, my friend got the quest to complete even when dying.
I resurrected and tried again, hoping that I could get it to complete as well.
No luck.

So, it seems like all the kobolds spawn at the same time and not in waves that they are supposed to.

**Comment by GuybrushGit** [comment]
Waves are set at 5 / 10 / 20 seconds which is way too fast. But what should be the timers? Anyone got video is this quest?

**Comment by cljnilsson** [comment]
Well regardless of the spawn rate, my friend got the quest to complete without us killing the kobolds, and he only got it to complete I did not.

**Comment by GuybrushGit** [comment]
https://www.youtube.com/watch?v=PFNcwco8JZ0
