### ISSUE TITLE
I think Celestial Stave from mage level 40 Tabetha quest is bugged. Should give +8 int and +22 spell damage. Appears to give +8 int and 7 spell damage even though the tool tip says +2int +7spell damage. 

### ISSUE THREAD

**Issue by jojojo1234** [LightsHope/server#990]
I think Celestial Stave from mage level 40 Tabetha quest is bugged. Should give +8 int and +22 spell damage. Appears to give +8 int and 7 spell damage even though the tool tip says +2int +7spell damage.

**Comment by Nyatsuelysium** [comment]
u shud add sources

**Comment by jojojo1234** [comment]
![celsstave](https://user-images.githubusercontent.com/34529641/34008176-7bd55f80-e0d2-11e7-9bd2-59611c117b69.png)
![celsstave1](https://user-images.githubusercontent.com/34529641/34008195-872fa142-e0d2-11e7-82f0-e88d4100ac59.png)

**Comment by jojojo1234** [comment]
look at intellect on celestial staff tool tip (+2) but on my character sheet when  I equip it I get +9 (normally +8, but +9 cause I'm a gnome) 
http://wowwiki.wikia.com/wiki/Celestial_Stave

This seems to be the vanilla stats. I checked out all other webpages and couldn't find a green celestial staff in vanilla

**Comment by stesve** [comment]
Some items changes stats when the server progresses to a new patch. Celestial Stave is one of them.

If you are experiencing that the stats on an item doesn't equate to the stats you gain from equipping it, you should clear your WDB folder.

**Comment by QAkvastskaft** [comment]
Before 1.8: https://web.archive.org/web/20050219015619/http://wow.allakhazam.com:80/db/item.html?witem=9517
After 1.8: https://web.archive.org/web/20060527143806/http://wow.allakhazam.com:80/db/item.html?witem=9517
