### ISSUE TITLE
Battle Chicken damage is incorrect

### ISSUE THREAD

**Issue by BattleChickensRevenge** [LightsHope/server#992]
The Battle Chicken minion, which is spawned by the Engineering Battle Chicken trinket, is bugged with regard to the damage it gives.

Most of the time the Chicken, which for me as a level 47 eng is a level 60 minion, does 1 point of damage, with a crit for 2.

This is on *any* mob or player, regardless of level.

*Occasionally* it will do about 72 or 73 points of damage - what you would expect.

**Comment by Seberats** [comment]
"It hits for 1 damage every 2 seconds.
If it enrages (does so often) it deals 40-70 damage (against a lvl70 target) every 1 second, lasts 10 seconds per enrage.

Occassionally it Battle Squawks, the entire group has +5% attackspeed for 5 minutes." 
http://db.vanillagaming.org/?item=10725#wh-comments

**Comment by stesve** [comment]
https://www.youtube.com/watch?v=I4fqFTDbvHs
