### ISSUE TITLE
Fishing Bug (no loot) 

### ISSUE THREAD

**Issue by TrebledBass** [LightsHope/server#994]

**Comment by TrebledBass** [comment]
So I'm having an issue while fishing and I'm wondering if there's a fix or if it's a bug that's already been reported. I've noticed while fishing (seems to be frequent during the time where stonescale eel catch % is supposed to go up so 00:00-06:00 server time). I'm 300 fishing with +20 pole and bait in tanraris so I have 100% catch chance. So the problem is that on a successful catch at times I will catch nothing. Essentially an empty loot window. I'd even occasionally skill off of this, before I hit 300. This occurs frequently enough and I was curious if this has been a reported issue and if there's a potential fix on my end. I don't have enough time lately to fish in the other 3 fishing time zones so I'm unsure if it's related to increased/decreased fish drop chances and perhaps it's the game attempting to give a fish to the player that shouldn't be available during that time. I understand this is probably low priority but it's a huge time waster when seemingly 5%-15% of your successful catches give nothing. I'm unsure as to whether this is a universal issue or isolated to me as when I ask in chat others do not chime in. I believe this due to the relatively high unpopularity of fishing to player. Anyways thanks for taking the time to looks at this!

**Comment by TrebledBass** [comment]
Forgot to mention, this is on the Lightbringer server. Anyone else who's had this happen if you can chime in with specifics or if you did anything that fixed it, I'd appreciate the information here.

**Comment by TrebledBass** [comment]
Also to clarify on the occurrence. When the bug occurs and I catch the fish. It makes the loot sound but the loot window simply flashes quickly up then away (since there's nothing to loot). It's a very strange (and truly frustrating occurrence). It's probably closer to 3-5% of the time but over a long period of time fishing, that's quite a few fish.

**Comment by druidish** [comment]
This is the same issue as https://github.com/LightsHope/server/issues/761. 

Those empty catches you're getting between 12AM-6AM server time are catches that rolled sunscale which are setup with a condition to prevent them from dropping during those hours. A similar window of empty catches exist between 12PM-6PM server time which would be the time when nightfin isn't allowed to drop.

**Comment by TrebledBass** [comment]
Ah my apologies I missed that issue that was already opened. So it seems it's a known issue and just doesn't have an implementable solution yet. Thanks!
