### ISSUE TITLE
Drop tables incorrect for golemagg.

### ISSUE THREAD

**Issue by dcish** [LightsHope/server#996]
Looking at the imported database from lightshope we see that the loot tables have been altered.
http://vanillawowdb.com/?npc=11988 

They should probably look more like this: http://db.vanillagaming.org/?npc=11988

I'm not sure when the change occurred, but it's definitely not blizzlike to have the weapons dropping at that rate.

**Comment by stesve** [comment]
Looks like a bug on vanillawowdb, since the site doesn't show the weapons in a lootgroup.

**Comment by dcish** [comment]
Or maybe they were removed from a lootgroup by accident. Worth looking into.

**Comment by stesve** [comment]
I'm using the newest public world db in my own setup and the lootgroup is there.

**Comment by dcish** [comment]
Can you post the results from that lootgroup that you're seeing?

**Comment by thepparker** [comment]
To the contrary, the weapon drop rates being high is Blizzlike. https://web.archive.org/web/20060715155026/http://wow.allakhazam.com:80/db/mob.html?wmob=11988

VanillaGaming is never an accurate source for loot tables, nor rates. See
