### ISSUE TITLE
Bugged Quest: Redemption

### ISSUE THREAD

**Issue by sonpett** [LightsHope/server#997]
Hello, the quest "Redemption" from Tirion Fordring in Eastern plaguelands is currently bugged for me. I can not start the dialogue, that is the quest objective. I was able to do the other quests from him, but the dialogue wont show. I believe the Mob just needs to be respawned and the problem will be gone. Here is a screenshot of what it looks like for me: 

https://gyazo.com/edcf96d2799661ef173671487b2c60aa

The quests are there but the dialogue wont come up, and the mob is also facing a wierd direction when not targeted. ¨

Server: Lightbringer

**Comment by stesve** [comment]
The dialogue won't appear, until you do what he tells you in the quest.

**Comment by sonpett** [comment]
what

**Comment by Sabre142** [comment]
Type /sit

**Comment by QAkvastskaft** [comment]
See #910

**Comment by TheCruxDev** [comment]
This quest is not bugged on Anathema.
